### ISSUE TITLE
Deleting a wallet leads me to blank screen (Next)

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#1012]
I deleted one of my non-used testnet wallets and was sent to a blank screen.

See screencast here: https://streamable.com/d27ew

## Expected Behavior

I think Zap should go to some other wallet, even if it is random, I think that would be fine.

**Comment by mrfelton** [comment]
@JimmyMow we already had a screen to handle the case where no wallet is selected, so I have updated to code to ensure that is used. See #1015

I did originally have it set up to select the first wallet in the list on delete (if there was one) but I think the UX was bad - it's confusing to be taken directly to an unrelated wallet after deleting one of your wallets and it's not clear to the user exactly what happened. By showing the user the `NoWallets` component instead it's very clear that the wallet was deleted and that they should now either select one from their list or create a new one.

**Comment by mrfelton** [comment]
Fixed via #1015
