### ISSUE TITLE
Show loading state when opening/closing channel

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#103]
# **Problem**
Zap opens and closes channels [async](https://github.com/LN-Zap/zap-desktop/blob/master/app/lnd/push/openchannel.js#L4) and waits for updates from LND to [fetch](https://github.com/LN-Zap/zap-desktop/blob/master/app/reducers/channels.js#L123) the new channels list. 

The issue here is that the UX is poor. The form closes and the user is left not knowing what's happening for 5-30 seconds while LND is attempting to open/close the channel

# **Solution**
Zap should update some form of CHANNEL_IS_OPENING and CHANNEL_IS_CLOSING state inside the channel reducer. This way we can design some UI to show the user work is being done behind the scenes. 

# **Design**
Design should be consulted with myself and @brandnanthny in slack

**Comment by Empact** [comment]
@JimmyMow Looks like this is working:

<img width="1492" alt="screen shot 2018-01-05 at 14 30 00" src="https://user-images.githubusercontent.com/5470/34632304-7c2111ec-f229-11e7-84e4-3ca3f2e106df.png">

One issue I'm seeing is that clicking on the pending channel did not open the transaction in the chain explorer. I'm looking into that at the moment, could just be a local thing.

**Comment by Empact** [comment]
Nevermind re chain explorer - it started working after I restarted my browser, which was mid-auto-update.

**Comment by JimmyMow** [comment]
Cool. I also am merging an a giant update that removes channels/peers and replaces them with "contacts"

It will resolve this ticket
