### ISSUE TITLE
Can't send on invoice that has 0 amount

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#1046]
## Description

When I click on an invoice that has the amount set to 0 Zap doesn't allow me to send. With invoices set to 0 the sender can set what amount they'd like to send over. 

## Expected Behavior

When I click an invoice that has the amount set to 0 I would like to be able to set the amount and then attempt to send

## Actual Behavior

Zap errors out and doesn't let me send:

<img width="1020" alt="screen shot 2018-12-07 at 8 49 53 pm" src="https://user-images.githubusercontent.com/4040039/49681090-af9eed00-fa61-11e8-84c3-139bfbf71796.png">

## Proposed Solution

If the invoice amount is 0, add an additional step to the payment form to allow the user to enter a custom amount.

![image](https://user-images.githubusercontent.com/200251/49760860-c80f4180-fcc5-11e8-943f-b32c70855abc.png)

## Steps to Reproduce

You can test 0 amount invoices with https://tippin.me

## Your Environment

Zap Desktop Next branch

**Comment by mrfelton** [comment]
![image](https://user-images.githubusercontent.com/200251/49760803-a6ae5580-fcc5-11e8-87c9-20377b5eda0e.png)

**Comment by JimmyMow** [comment]
Closing due to #1069 being merged
