### ISSUE TITLE
Can't perform a React state update on an unmounted component

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#1072]
## Description

When on the `next` branch and clicking on a payment request I get the following console error:

<img width="1020" alt="screen shot 2018-12-11 at 10 01 14 pm" src="https://user-images.githubusercontent.com/4040039/49833153-94e5b480-fd90-11e8-8f50-0e8a8e5a133a.png">

This error _only_ shows the first time the pay form is mounted and attempted to be used. It also does not break any functionality.

## Steps to Reproduce

- 1. Checkout to the next branch
- 2. Click on a lightning link (aka yalls.org article)
- 3. Check your console and you should see the above error

## Your Environment

- Zap Desktop version: Next branch
- Operating System and version: MacOS Majove 10.14.1

**Comment by mrfelton** [comment]
@JimmyMow this was an issue in `react-spring`:

https://github.com/drcmda/react-spring/issues/348

I have updated to the most recent version (https://github.com/LN-Zap/zap-desktop/commit/84ca90571f65b0ea901fc1589af1d6f28d62669d) which has resolved the issue.

I've rebased the `next` branch from master so it also has the fix.
