### ISSUE TITLE
Opening lightning channel should never create small or dust outputs

### ISSUE THREAD

**Issue by bg002h** [LN-Zap/zap-desktop#1082]
Most users usually don’t care about the _exact_ size of a new channel. Opening a lightning channel should **absolutely never** create a dust output as change. UTXOs included in opening a channel should be selected in such a way that minimizes number of inputs needed to get reasonably close to desired channel size. If opening a channel at exactly a desired size would cause a change output of a small amount (say <5% of channel capacity for example), UI should offer to increase channel capacity or miner fee to avoid creating change output. 

Often opening a channel with slightly less than the target size is acceptable (although being able to specify minimum channel capacity would be useful).  

The UTXO set is a network resource and care should be taken to decrease number of UTXOs whenever it is reasonably achievable.

**Comment by mrfelton** [comment]
All wallet and channel channel related functionality is handled directly in lnd and is therefore outside of the scope of Zap, which is really just a UI on top of lnd.

@bg002h I'd suggest that you create an issue over in the [lnd issue queue](https://github.com/lightningnetwork/lnd/issues)
