### ISSUE TITLE
Support multiple sass-themes

### ISSUE THREAD

**Issue by jackmallers** [LN-Zap/zap-desktop#11]
The application support Litecoin and can/will support others as well but defaults to BTC colors for now. Curious what the best way is to accomplish dynamic color-way themes

**Comment by lsdafjklsd** [comment]
Do you want help on this? I was learning the codebase and assessing level of effort, also playing around with litecoin color combos (if that's on the table). The litecoin grey is a bit drab and I think a blue (compliment to bitcoin orange) with white and grey would look nice.

**Comment by jackmallers** [comment]
yo! sup haywood, I recognize you on the dev chat. I would love help. before we dive into the hex color schemes how do you think we should go about supporting multiple color schemes?

**Comment by jackmallers** [comment]
keep in mind we also wanna design for a future where you can switch between chains while in the application. i've though about this for a little and am not set on any solution, would love to hear your opinion

**Comment by auldsyababua** [comment]
@jackmallers why would switching between chains affect color schemes? Wouldn't the theme just change once a user switched to a different chain? Just trying to understand the enhancement wanted here so maybe I can help. Is this still something you are looking to do?

**Comment by JimmyMow** [comment]
@auldsyababua yeah so this was back when litecoin devs were working on LN stuff. The idea was that we could have a theme for each LN supported coin. this isn't high priority anymore and I may close it. no other coins have neutrino support and we are focused on BTC atm

**Comment by pajasevi** [comment]
Best way to do this in css is using [CSS custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/--*). Very easy to switch to different theme then.

**Comment by kaloudis** [comment]
It would be nice to have a light theme. Perhaps we should build out a settings view that we can put the onboarding settings on as well as a toggle for a theme. @pajasevi's proposed approach is the way to go

**Comment by JimmyMow** [comment]
Ok I'm gonna see if I can make some progress on this one today. I'd love to have multiple themes

**Comment by JimmyMow** [comment]
![2018-09-05 15 20 20](https://user-images.githubusercontent.com/4040039/45119440-1938f380-b121-11e8-83f0-da5191f905bd.gif)

**Comment by JimmyMow** [comment]
@kaloudis @pajasevi I just submitted #761 to address this as a start. Can you guys test it and give me feedback?

**Comment by mrfelton** [comment]
Closed via #761
