### ISSUE TITLE
Application displaying blank screen when restarting 

### ISSUE THREAD

**Issue by lieteau2** [LN-Zap/zap-desktop#1108]
After quitting desktop application and reopening it, the application screen is blank and I cannot proceed to use Zap 

I am testing version 0.3.0 prerelease 
<img width="1280" alt="screen shot 2018-12-17 at 1 31 53 pm" src="https://user-images.githubusercontent.com/45567325/50110566-342b0180-0200-11e9-8c66-0527949843ce.png">

**Comment by JimmyMow** [comment]
@mrfelton I am getting this as well. For some more context, I found this in my logs: 

`zap:main [ERR]  Unable to start lnd: transition is invalid while previous transition is still in progress +5ms`
