### ISSUE TITLE
"across" misspelled as "accross"

### ISSUE THREAD

**Issue by thejourneydude** [LN-Zap/zap-desktop#111]
On the Lnd Syncing page, the word "across" is misspelled as "accross." To fix this, one can edit the text on the following [line](https://github.com/LN-Zap/zap-desktop/blob/37959368619cc895f99b96f5561f9439e042956e/app/components/LndSyncing/LndSyncing.js#L20).

**Comment by joaodealmeida** [comment]
nice catch 👍
