### ISSUE TITLE
Zap 0.3.0 Windows Importing Wallet Feature 

### ISSUE THREAD

**Issue by lieteau2** [LN-Zap/zap-desktop#1117]
when importing an existing wallet to the windows desktop application (version 0.3.0) A bug presents itself. The UI presents an infinitely looped "importing wallet" screen (without ever successfully importing the wallet). When X'ing out of this screen, the Zap home screen presents iterations of the wallets that users arent able to log into, or delete. Please see the screenshots attached below and let me know if you have any questions. 

![zap desktop recovery wallet](https://user-images.githubusercontent.com/45567325/50172599-0fe02b00-02bb-11e9-83a2-87e16961ce01.PNG)
![zap desktop recover wallet delete error](https://user-images.githubusercontent.com/45567325/50172600-0fe02b00-02bb-11e9-9f23-8b195111a904.PNG)

**Comment by lieteau2** [comment]
@mrfelton issue reconstructs for mac as well

**Comment by RiskyFire** [comment]
I have the same problem when importing from a recovery seed. The wallet gets stuck on importing wallet, if you close using X the wallet shows several un-usable wallets.
![image](https://user-images.githubusercontent.com/28758929/52379696-1ee58d00-2a63-11e9-97e5-ad3565b61805.png)
![image](https://user-images.githubusercontent.com/28758929/52379792-5eac7480-2a63-11e9-8351-ee9fad5dd21b.png)

**Comment by yukairex** [comment]
> I have the same problem when importing from a recovery seed. The wallet gets stuck on importing wallet, if you close using X the wallet shows several un-usable wallets.
> ![image](https://user-images.githubusercontent.com/28758929/52379696-1ee58d00-2a63-11e9-97e5-ad3565b61805.png)
> ![image](https://user-images.githubusercontent.com/28758929/52379792-5eac7480-2a63-11e9-8351-ee9fad5dd21b.png)

same here

**Comment by mrfelton** [comment]
Sounds related to https://github.com/LN-Zap/zap-desktop/issues/2071

Is your seed encrypted with a passphrase?

**Comment by yukairex** [comment]
> Sounds related to #2071
> 
> Is your seed encrypted with a passphrase?

yes..i have a passphrase..get the issue
