### ISSUE TITLE
Zap JavaScript Error

### ISSUE THREAD

**Issue by Ootsg** [LN-Zap/zap-desktop#1119]
I got this error multiple times with a time distance of 5-10 minutes.

![vystrizek](https://user-images.githubusercontent.com/45978353/50177000-29a46100-0301-11e9-9a16-75241471f61b.JPG)

I think it happened when i tried to open a channel with somebody and while connecting i tried to switch from BTC to Sats, but not sure if that was the issue. Now it is running correctly. First time it happened  - it made Zap crash, other times i just clicked OK and it kept going. 

Like I wanted to switch the BTC->Sats, instantly error window, zap crashed. Reloaded, started working, afte couple minutes - error again, kept running and this happened 1 more time

W10, latest update. ZAP not sure, version is nowhere written, but downloaded recently according to Pierre Rochard

**Comment by tooraj-enayati** [comment]
Thanks, I am downloading 0.3.0.  But I just realised that I have opened a channel to Satoshi's Place and was in pending while I was getting all these errors and restarting. Now, 0.2.2 comes up with no open channel at all. What will happen t that channel? Will the funding return to me? What do I have to do to recover the funds?

**Comment by tooraj-enayati** [comment]
I cannot reproduce the error on 0.3.0.

**Comment by mrfelton** [comment]
Great! Thanks for letting us know @tooraj-enayati
