### ISSUE TITLE
additional t added to bitcoin denominations when wallet is logged into multiple times / date partitioning

### ISSUE THREAD

**Issue by lieteau2** [LN-Zap/zap-desktop#1120]
an additional t is added to the btc denominations every time a user logs in. 

in order to reconstruct this issue simply log in and out of the same wallet multiple times and you will see the additional t get added. 

3x login = tttBTC 
4x login = ttttBTC 

additionally after logging into the wallet for the second time an instance of the desktop application is opened the transactions are partitioned by date with the last transaction being classified under to correct date (Dec 18,2018) however all other previous transactions are classified under the date "undefined NaN, NaN" 

please see screenshot below. 

![zapttt](https://user-images.githubusercontent.com/45567325/50177184-f04eff80-02c6-11e9-82e9-08c5072027b7.PNG)

**Comment by mrfelton** [comment]
@lieteau2 whilst I wasn't able to replicate the issue, I did detect a couple of places where we were mutating the redux state which could quite easily have lead to the issue with the additional `t` being added.

There are now 2 commits in this branch. One which fixes the date issue, and another which I believe should fix the duplicate `t` issue.
