### ISSUE TITLE
Generate LNDConnect QR code for remote nodes that want to use Zap iOS

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#1145]
Right now the process for getting Zap iOS up and running is a bit difficult. An improvement on the current user story would be:

1. User runs Node Launcher
2. User LNDConnects to Zap Desktop from Node Launcher
3. User then scans LNDConnect QR code from Zap Desktop to connect to Zap iOS

**Comment by mrfelton** [comment]
Closed via #1313

**Comment by codenamecoder** [comment]
I cannot determine how to generate a QR code from my Windows desktop app so I can connect my iOS - I'm using Pierre's node launcher and though I have zap running with a wallet open, the node launcher dialog does not show the Open Zap Desktop and Show QR code - it's probably very simple but I'm unable to get it done.
