### ISSUE TITLE
Zap displays incorrect balance after importing seed

### ISSUE THREAD

**Issue by bg002h** [LN-Zap/zap-desktop#1175]
In trouble shooting a bug I’m having with LND, I made a new user and imported my seed into LND. When synced, Zap doesn’t see all transactions from that seed and reports an incorrect balance (too high). Using 0.3.1 on Mac OS X Mojave. Reports error 25 (inputs not found) when trying to send from wallet.

**Comment by mrfelton** [comment]
@bg002h Zap does not currently support importing balances from channels. The recovery process only covers recovery of onchain funds.

Simple recovery of channel balances has been added in lnd 0.6. Support for this will be added in a future release of Zap.

See https://github.com/LN-Zap/zap-desktop/issues/1971 and https://github.com/LN-Zap/zap-desktop/issues/2082
