### ISSUE TITLE
More helpful loading screen

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#1178]
Sometimes the app gives the user our animated loading screen for 20 seconds or so. Sometimes as a user I am confused whether something went wrong, and am often left checking logs, to see the app is acting totally fine and processing some data.

It would be nice if the Loading component was able to take some strings as an argument to be displayed. So for example the loading screen while the app is trying to connect to the last remote node used on start the Loading component can be streaming updates like:

`Loading - Connecting to custom lnd instance`
`Loading - Establishing connection to Lightning gRPC interface...`
`Loading - Connecting to Lightning gRPC service`

I think this would be much more helpful and improve the UX

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/1605
