### ISSUE TITLE
Yarn dependency installation: flow-typed exits out with code 0

### ISSUE THREAD

**Issue by DenisMir** [LN-Zap/zap-desktop#118]
I have tried to follow the documentation for installing zap-desktop on a OSX 10.13.2. I'm using `node@9.3.0`, `npm@5.5.1` installed by `nvm` and `yarn` installed by `brew` @ version 1.3.2. When executing `yarn` the dependency installation exits out with: 

```
[0] !! No flow@v0.48.0-compatible libdefs found in flow-typed for the above untyped dependencies !!
[0]
[0] I've generated `any`-typed stubs for these packages, but consider submitting
[0] libdefs for them to https://github.com/flowtype/flow-typed/
[0]
[0] npm run flow-typed exited with code 0
```
Do you have any idea of what is going wrong?

**Comment by Empact** [comment]
When I run the install, it shows the error you mention, which is non-fatal, processes for a while, then eventually outputs:
`✨  Done in 301.11s.`

Are you sure the install is failing? Have you tried running `npm run dev`?

**Comment by DenisMir** [comment]
@Empact Trying it out right now. I will give feedback when done.

**Comment by DenisMir** [comment]
You were right. It does succeed after some time of waiting. `npm run dev` does run fine now!

**Comment by JimmyMow** [comment]
Cool. Closing this
