### ISSUE TITLE
Activity list empty after connecting to and unlocking remote lnd node

### ISSUE THREAD

**Issue by mrfelton** [LN-Zap/zap-desktop#1193]
## Description

If you connect to a remote lnd node that is locked, you are prompted to enter the wallet password to unlock the wallet prior to connecting. Once the wallet has been unlocked and you are taken to the wallet screen with the correct balance showing, the correct channel list showing, but an empty activity list.

This is only an issue of the node is locked prior to connecting to it. If the node is already unlocked, the activity list is correctly populated when you connect to it.

## Expected Behavior

The activity list should be populated when the wallet first shows.

## Actual Behavior

It requires a manual click of the refresh button before the activity list shows correctly.

## Possible Fix

Review how/when fetchTransactions etc is called and ensure it is called after unlocking remote wallet.

## Steps to Reproduce

1. Start up remote lnd node but DO NOT unlock it/
2. Connect to the node using Zap
3. Unlock the node from Zap
4. Note that the activity list is blank
5. Hit the refresh button and note that the activity list is now correctly populated

## Context

Connecting to remote lnd node that is locked.

## Your Environment

- Zap Desktop version: 0.3.2
- Operating System and version: Mac, latest

**Comment by korhaliv** [comment]
Currently investigating this issue
