### ISSUE TITLE
Running e2e tests task locally fails

### ISSUE THREAD

**Issue by bolatovumar** [LN-Zap/zap-desktop#1209]
When I attempt to run e2e tests with the `npm run test-e2e` command I get the following error:
![screen shot 2018-12-31 at 5 55 25 pm](https://user-images.githubusercontent.com/1934678/50569830-7470a080-0d25-11e9-9768-ffcf8550cbae.png)

The task times out and fails after a while.

## Expected Behavior

Expect e2e tests to run.

## Actual Behavior

e2e tests don't run.

## Steps to Reproduce

Run `npm run test-e2e` command.

## Your Environment

- Zap Desktop version: 0.3.2-beta (0.3.2-beta.5107)
- Operating System and version: Mac OS X Mojave
- Node.js version: 10.15.0
- npm version: 6.5.0
- yarn version: 1.12.3

**Comment by mrfelton** [comment]
@bolatovumar you must build the app prior to running the e2e tests as they run against the fully built version of the app.

```
yarn test-e2e
```
