### ISSUE TITLE
Wallet hangs when connecting to a remote LND node with incorrect auth

### ISSUE THREAD

**Issue by korhaliv** [LN-Zap/zap-desktop#1223]
## Description
Wallet hangs when trying to connect to a remote LND node (Connect to your own node item during onboarding). This happens when there is an auth error. In my case invalid macaroons\tls.cert

## Expected Behavior
You should be able to connect to your node

## Actual Behavior
Wallet hangs
![image](https://user-images.githubusercontent.com/14069193/50599240-263ed700-0eb6-11e9-850e-cd26d10fe715.png)

## Possible Fix
Possibly need to handle this response from LND
`Unable to connect to Lightning gRPC interface: { Error: verification failed: signature mismatch after caveat verification at Http2CallStream.call.`

## Steps to Reproduce
1. Start wallet
2. Choose "Connect to your own node"
3. Enter details. Either admin.macaroon or tls.cert must be incorrect
4. Input password and hit Next
5. Wallet hangs

## Your Environment

- Zap Desktop version:  built from source, dev mode (npm run dev)
- Operating System and version:Windows 10

**Comment by mrfelton** [comment]
Based on the log output from the screenshot, this issue should be addressed by #1235 as there was actually no problem connecting to your node and the connection was fully established.

I tested and verified that errors with the host, cert, or macaroon are properly handled.
