### ISSUE TITLE
Wallet hangs when connecting to a remote LND node 

### ISSUE THREAD

**Issue by korhaliv** [LN-Zap/zap-desktop#1224]
## Description
Wallet hangs when trying to connect to a remote LND node (Connect to your own node item during onboarding). Happened to me when creating a new connection and there was no saved last active node. After reloading the wallet it works as expected with previously saved credentials

## Expected Behavior
You should be able to connect to your node

## Actual Behavior
Wallet hangs

![image](https://user-images.githubusercontent.com/14069193/50599740-99951880-0eb7-11e9-9dd5-b4ab8c44b303.png)

## Possible Fix
Could be related to [#1223](https://github.com/LN-Zap/zap-desktop/issues/1223)

## Steps to Reproduce

1. Start wallet
2. Choose "Connect to your own node"
3. Enter details. Either admin.macaroon or tls.cert must be incorrect
4. Input password and hit Next
5. Wallet hangs

## Your Environment

- Zap Desktop version: built from source, dev mode (npm run dev)
- Operating System and version: Win10

**Comment by korhaliv** [comment]
Might have been fixed by [#1235](https://github.com/LN-Zap/zap-desktop/pull/1235)

**Comment by mrfelton** [comment]
Based on the log output from the screenshot, this issue should be addressed by #1235.
