### ISSUE TITLE
When opening a channel sometimes duplicate appears in the list

### ISSUE THREAD

**Issue by korhaliv** [LN-Zap/zap-desktop#1244]
## Description
Duplicate entries appear in the list when user open a channel

![image](https://user-images.githubusercontent.com/14069193/50707834-e5d48a00-106a-11e9-96c2-3d87b28b8a04.png)

## Expected Behavior
Only one channel item must be added

## Actual Behavior
Multiple items sometimes appear

**Comment by mrfelton** [comment]
Closed via #1521
