### ISSUE TITLE
react-intl messages defined incorrectly?

### ISSUE THREAD

**Issue by bolatovumar** [LN-Zap/zap-desktop#1251]
I stumbled upon this issue after having run the project code through the TypeScript compiler.

In any file that uses the `defineMessages` function of the `react-intl` library you will see something like this:

```javascript
export default defineMessages({
  copy: 'Copy Request',
  invoice_copied_notification_title: 'Payment Request copied',
  invoice_copied_notification_description: 'Payment Request has been copied to your clipboard',
  pay_req: 'Payment Request',
  memo: 'Memo',
  request: 'Request',
  save: 'Save as image',
  not_paid: 'Not Paid',
  paid: 'Paid'
})
```

However, the type definitions and the documentation for `react-intl v2.7.2` (used in this project) show this API: [https://github.com/yahoo/react-intl/wiki/API#definemessages](https://github.com/yahoo/react-intl/wiki/API#definemessages)

It seems to me that the data is not being passed into `defineMessages` in the shape it expects it?

**Comment by mrfelton** [comment]
Hey @bolatovumar .

This is actually handled by a babel plugin [`react-intl-auto`](https://github.com/akameco/babel-plugin-react-intl-auto). See https://github.com/LN-Zap/zap-desktop/blob/master/babel.config.js#L17-L23

**Comment by mrfelton** [comment]
@bolatovumar Also worth noting - `yarn extract-messages` will extract all translation strings from the source code and upsert into the files in `/app/translations`

See https://github.com/LN-Zap/zap-desktop/blob/master/package.json#L15

**Comment by bolatovumar** [comment]
Ok, so there is nothing wrong then.

So, when using TypeScript there would be several options here:
1. Ignore compiler error. This is perfectly fine if you are not using the `.ts` file extension and only using the `.js` file extension and using TS for some IDE niceties.
2. Insert the `@ts-ignore` flag in each file that has this issue. This way TS will just ignore everything. `@ts-ignore` can also be configured to ignore only specific types of errors.
3. Rewrite the code to not depend on the Babel plug-in. This is probably the most "TS" way to do this but would require the most work. It's probably the way to go long-term if the goal is to use all of TS features at some point in the future.

I don't think there is anything that needs to be done now so the issue can be closed but it's good to have this to refer to in the future.
