### ISSUE TITLE
Remove unused react-router-redux dependency?

### ISSUE THREAD

**Issue by bolatovumar** [LN-Zap/zap-desktop#1257]
I ran into this while adding type definitions for dependencies specified in package.json.

Dependency `"react-router-redux": "5.0.0-alpha.9"` doesn't seem to be imported anywhere in the project (I searched for this string and didn't find any references to it outside of package.json).

Is it being used somewhere or is this a stray dependency?

**Comment by mrfelton** [comment]
Fixed via #1269
