### ISSUE TITLE
Missing curly braces around React prop

### ISSUE THREAD

**Issue by bolatovumar** [LN-Zap/zap-desktop#1259]
I ran into this issue while working on adding TypeScript support.

In `RequestSummary.js` on line 169 there is this `right=` prop but the value passed into it doesn't have curly braces around it. Looks like someone just forgot to add them?
![screen shot 2019-01-05 at 10 20 28 pm](https://user-images.githubusercontent.com/1934678/50732901-23531900-1138-11e9-80e0-c6b246e6312d.png)

**Comment by mrfelton** [comment]
Interesting, yet it works as expected. 

I read through the docs at https://reactjs.org/docs/jsx-in-depth.html and I'm a little unclear on the requirement here. It seems this is more a matter of preference, no? Is there a type specific requirement to have these surrounded by curly braces?

I also took a look at https://github.com/yannickcr/eslint-plugin-react/blob/HEAD/docs/rules/jsx-curly-brace-presence.md and played around with the settings...

```
'react/jsx-curly-brace-presence': [2, { props: 'always', children: 'never' }],
```
After running `yarn lint-fix` with the above, it resolves the issue, but also results in a huge changeset across the codebase and tends to make the code a littler more dense and cumbersome in general, with curly braces surrounding things where they really aren't needed.

```
'react/jsx-curly-brace-presence': [2, { props: 'never', children: 'never' }],
```
This seems to be how it's configured by default and running `yarn lint-fix` results in no change to the code.

Probably this instance should be adjusted regardless, for the sake of consistency. It's a shame that the eslint rules can't get a little more granular on this.

**Comment by bolatovumar** [comment]
I think the general rule is that everything but string literals should have curly braces around them. String literals may or may not have curly braces surrounding them.

I might be worth it to set the ESLint rule to `always` just so this kind of stuff can be fixed easily in the future. I think this will result in all the string literals used as props to have curly braces around them.

**Comment by mrfelton** [comment]
Problem with setting `always` for that rule is that it results in a *huge* changeset that touches most of the codebase - which would be quite disruptive.

The current setting is the "recommended" default, and personally I don't like the look of the code so much when there are curly braces surrounding basic string props that could be written more cleanly as a pure string literal (just my 2c).

However, If we were going to make a change like this,it would probably also be a good idea to roll in other sweeping changes to lint rules that have been discussed, such as enforcing trailing commas in lists and get more bang for our buck.

For this story though, I think we should just add the missing curly brace around this specific node for the sake of consistency.

**Comment by bolatovumar** [comment]
Yeah, that's fine by me. My only motivation for adding the `always` option would be the consistency aspect and that it's easy to enforce through the fix command provided by the linter. I don't particularly like the curly braces around strings myself.
