### ISSUE TITLE
Add wallet name when connecting remote node

### ISSUE THREAD

**Issue by JSRossiter** [LN-Zap/zap-desktop#1262]
It took me a while to realize I could add a wallet name after connecting a remote node, I think it could just be on the form with host/tls/macaroon

**Comment by mrfelton** [comment]
In the future there will be other options that can set for remote nodes in addition to the wallet name (autopilot settings, node alias etc) and we want to keep the onboarding screen as simple and clutter free as possible to avoid distraction.

Perhaps we could add an `Additional options` area which is not visible by default but that can be expanded to show additional options such as this.

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/3690
