### ISSUE TITLE
Invoice QR too small

### ISSUE THREAD

**Issue by JSRossiter** [LN-Zap/zap-desktop#1263]
I'm having a lot of trouble scanning invoice QR codes (node pubkey/btc address seem better), perhaps an option to click/hover and enlarge it?

(I'm renaming an issue because I missed that it was a duplicate)

**Comment by bolatovumar** [comment]
Would making it somewhat larger suffice? Adding the "click to enlarge" functionality wouldn't be needed if the QR code was large enough.

**Comment by JSRossiter** [comment]
Possibly, would need to know how common this issue is to determine best fix.

I noticed there is a save image button when you view a pending invoice, adding that to the post-create screen could work too.
