### ISSUE TITLE
Upper case bech32 not recognized

### ISSUE THREAD

**Issue by FelixWeis** [LN-Zap/zap-desktop#1266]
According to the bech32 spec, there is no distinction between upper/lower case. some QR codes use a special mode where they only use UPPER case to encode the data more efficiently.

**Comment by mrfelton** [comment]
@FelixWeis could you give an example of one of these QR codes?

**Comment by mrfelton** [comment]
Here is the relevant part of the spec:

https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki#specification

> The lowercase form is used when determining a character's value for checksum purposes.

> Encoders MUST always output an all lowercase Bech32 string. If an uppercase version of the encoding result is desired, (e.g.- for presentation purposes, or QR code use), then an uppercasing procedure can be performed external to the encoding process.

> Decoders MUST NOT accept strings where some characters are uppercase and some are lowercase (such strings are referred to as mixed case strings).

> For presentation, lowercase is usually preferable, but inside QR codes uppercase SHOULD be used, as those permit the use of alphanumeric mode, which is 45% more compact than the normal byte mode.
