### ISSUE TITLE
Add contextual help to form fields to help users understand how to fill out forms

### ISSUE THREAD

**Issue by mrfelton** [LN-Zap/zap-desktop#1291]
## Detailed Description

Add additional help text to form fields where more information would be useful, such as the fields in the onboarding forms and and the request/pay forms.

## Context

There are many parts of the app where we need to collect data from users. Sometimes it is not always obvious what we are asking for or where the user should get the data or what format they should provide it in.

## Possible Implementation

- Add tooltip icon next to fields where additional help is available
- Show additional help on hover

![image](https://user-images.githubusercontent.com/200251/50822475-1c8ff600-1332-11e9-8fe1-31792dbe35eb.png)

![image](https://user-images.githubusercontent.com/200251/50822506-2d406c00-1332-11e9-983e-34ff0975d16a.png)

**Comment by bolatovumar** [comment]
@mrfelton would a simple first step be to add the "title" attribute to form fields so you get the built-in tooltip when you hover over the input field?

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/1737
