### ISSUE TITLE
Payment that timed out remains in sending state until app is restarted

### ISSUE THREAD

**Issue by NicolasDorier** [LN-Zap/zap-desktop#1292]
![image](https://user-images.githubusercontent.com/3020646/50828900-090e7a80-1386-11e9-9aad-cee302b53d06.png)

Expecting the payment to fail after 1 minutes.

Actual: Keep spinning.

**Comment by NicolasDorier** [comment]
More info: After I restarted Zap, the payment disappeared

**Comment by mrfelton** [comment]
@NicolasDorier do you have a reliable way to trigger this issue by any chance? Do you know what the condition was that was causing the payment to timeout?

**Comment by mrfelton** [comment]
These lnd issues seem relevant:

 - https://github.com/lightningnetwork/lnd/issues/2286
 - https://github.com/lightningnetwork/lnd/issues/1867

Might be worth migrating from `sendPaymentSync` to `sendPayment`

**Comment by NicolasDorier** [comment]
No reliable way to reproduce.

I can just say that to the same person I made 4 payments, the third one failed and the fourth one got this problem.

My destination was a c-lightning node which seem to be problematic these days (it often crashes since 1 week ago)
