### ISSUE TITLE
After moving tls.cert and admin.macaroon to another dir, Zap stopped working

### ISSUE THREAD

**Issue by otaviobps** [LN-Zap/zap-desktop#1310]
## Description

I first launched and connected to my node without problems via remote. After it, I closed the Zap Wallet app on Mac and moved the tls.cert and admin.macaroon files to another dir. I opened Zap again and it shows the loading screen and then goes to a blank screen.

## Expected Behavior

Zap should ask where is the new location of the files

## Actual Behavior

Zap goes to a blank screen after loading. Trying to reinstall Zap doesn't work

## Possible Fix

Ask the user where the files are

## Steps to Reproduce

- 1. Connect Zap to a remote node
- 2. Close Zap
- 3. Move tls.cert and admin.macaroon to another dir
- 4. Launch Zap

## Context

I'm not able to launch Zap anymore, even deleting all config files and reinstalling it

## Your Environment

- Zap Desktop version: Version 0.3.2-beta (0.3.2-beta.5107)
- Operating System and version: Mac OSX 10.14.2

**Comment by mrfelton** [comment]
@otaviobps this has been addressed in https://github.com/LN-Zap/zap-desktop/pull/1261

This fix be included in forthcoming release.

We'll also be implementing https://github.com/LN-Zap/zap-desktop/issues/1182 to allow you to reconfigure the settings

**Comment by mrfelton** [comment]
Until then,. you can fix manually by following the steps in https://github.com/LN-Zap/zap-desktop/issues/1173#issuecomment-449775755

**Comment by otaviobps** [comment]
Thanks, it worked
