### ISSUE TITLE
Stuck on loading after connecting to local node (incompatible with latest lnd master branch) 

### ISSUE THREAD

**Issue by cherijs** [LN-Zap/zap-desktop#1320]
Stuck on loading after connecting to local testnet node (localhost:10009)

> checkPropTypes.js:19 Warning: Failed prop type: The prop `network` is marked as required in `Network`, but its value is `undefined`.

![image](https://user-images.githubusercontent.com/2779993/51080647-612be080-16e8-11e9-8b03-f42dfb39f4fd.png)

`stateProps.info.network` is empty object

**Comment by mrfelton** [comment]
@cherijs can you provide exact steps to replicate please? Thanks.

**Comment by mrfelton** [comment]
This sounds like a case of https://github.com/LN-Zap/zap-desktop/issues/1310 or https://github.com/LN-Zap/zap-desktop/issues/1173

These issues are resolved in master and will be fixed in the next release, but you can resolve manually by following the steps here:

https://github.com/LN-Zap/zap-desktop/issues/1173#issuecomment-449775755

**Comment by cherijs** [comment]
> This sounds like a case of #1310 or #1173
> 
> These issues are resolved in master and will be fixed in the next release, but you can resolve manually by following the steps here:
> 
> [#1173 (comment)](https://github.com/LN-Zap/zap-desktop/issues/1173#issuecomment-449775755)

![image](https://user-images.githubusercontent.com/2779993/51101780-ca911980-17e4-11e9-8860-cf6e509309b3.png)

Ok, after " Launch Now" same loading screen

**Comment by Jfigs101** [comment]
That worked! Thank you.

**Comment by mrfelton** [comment]
@cherijs could you explain your setup a little please? You have your own instance of LND running on your local machine that you are trying to connect to using the "Connect to your own node" option?

Can you provide exact steps to reproduce please? Thanks

**Comment by Jfigs101** [comment]
@mrfelton After the fix, as @cherijs stated. The loading screen comes up again. To answer the question you posed. I am running bitcoind, and my own LND on my local machine and I am attempting to "connect my your own node". Also, @mrfelton should I start my own issue? I don't want to hijack this thread, just thought it was prudent to show that > 1 user was having this issue.

**Comment by cherijs** [comment]
> @cherijs could you explain your setup a little please? You have your own instance of LND running on your local machine that you are trying to connect to using the "Connect to your own node" option?
> 
> Can you provide exact steps to reproduce please? Thanks

Exactly, LND running on local machine - and i'm trying to connect through  "Connect to your own node"

![image](https://user-images.githubusercontent.com/2779993/51101994-d3361f80-17e5-11e9-8358-511b216db9f7.png)

Alter opening app, LND console prints 

![image](https://user-images.githubusercontent.com/2779993/51102051-0ed0e980-17e6-11e9-8a88-647d19292a4c.png)

**Comment by cherijs** [comment]
same :( 

![Image](http://up.pixels.lv/Screen-Shot-2019-01-14-10-34-52-1547454892.png)

**Comment by cherijs** [comment]
lnd version 0.5.1-beta commit=v0.5.1-beta-343-g55b580f2b80d2e62af4067d3ddf8688614bf0914
Bitcoin Core Daemon version v0.17.99.0-3ec4cc0a9

**Comment by mrfelton** [comment]
@cherijs - could you join our slack and ping me there? Might be easier to walk through this with you in real time than going back and forth on this issue.

**Comment by mrfelton** [comment]
@cherijs the issue here appears to be an incompatibility with the latest development version of lnd. Amongst other things, the result from `lncli getinfo` has changed as per https://github.com/lightningnetwork/lnd/pull/2399

You will need to install lnd 0.5.1 to use Zap currently as we are not tracking lnd HEAD  right now.

**Comment by mrfelton** [comment]
> lnd version 0.5.1-beta commit=v0.5.1-beta-343-g55b580f2b80d2e62af4067d3ddf8688614bf0914

This is 343 additional commits on top of 0.5.1

**Comment by mariodian** [comment]
Have the same issue on the latest `lnd`.

**Comment by mrfelton** [comment]
@mariodian you can try the patch in https://github.com/LN-Zap/zap-desktop/pull/1431 if you like, which should resolve the issue. Alternatively, we will be making a new release soon that will include the fix.

**Comment by mariodian** [comment]
@mrfelton does it work with a remote lnd too?

**Comment by mrfelton** [comment]
Yes @mariodian

**Comment by stevedekorte** [comment]
I'm seeing this on Zap Version 0.3.1-beta (0.3.1-beta.5049).

**Comment by bolatovumar** [comment]
@stevedekorte the latest version 0.6.2-beta. You should upgrade as 0.3.1-beta is very old.
