### ISSUE TITLE
Singular input for Node URI

### ISSUE THREAD

**Issue by pajasevi** [LN-Zap/zap-desktop#133]
It would be better to have single text input for Node URI (Peer connecting) in `public_key@ip_address:port` format rather than having two inputs.

Other LN clients support it this way and LN explorers (like https://explorer.acinq.co) will provide URI this way too.

I can do a PR if you agree.

**Comment by thinkjanis** [comment]
What about having one input field at first and if it detects that only the peer is inserted, it can generate an IP address field below?

**Comment by pajasevi** [comment]
The component is now stateless and I would like to avoid changing that. This would make the component a little too complex with a little new advantages. Proper error message (which is there now) should be enough.

**Comment by JimmyMow** [comment]
Closing this as the new contacts feature seems to address this
