### ISSUE TITLE
Convertation from satoshis to millisatoshis incorrect?

### ISSUE THREAD

**Issue by bolatovumar** [LN-Zap/zap-desktop#1332]
I'm trying to write unit tests for btc.js and running into this issue:
![screen shot 2019-01-13 at 3 04 21 pm](https://user-images.githubusercontent.com/1934678/51091827-f78def80-1744-11e9-9d4b-857976c9f3b5.png)

I expect 0.001 satoshis to equal to 1 millisatoshi (as per the [spec](https://github.com/lightningnetwork/lightning-rfc/blob/master/11-payment-encoding.md#human-readable-part)) but get 0.01 instead. It looks like the code thinks there are 10 millisatoshis per 1 satoshi when there are a 1000. Am I misunderstanding something here?

![screen shot 2019-01-13 at 3 17 50 pm](https://user-images.githubusercontent.com/1934678/51091933-73d50280-1746-11e9-8a39-5cd6f1fd7407.png)

Additional links: 
* [https://bitcoin.stackexchange.com/questions/69700/what-is-a-millisatoshi-i-thought-satoshi-is-the-smallest-unit](https://bitcoin.stackexchange.com/questions/69700/what-is-a-millisatoshi-i-thought-satoshi-is-the-smallest-unit)
* [https://en.bitcoin.it/wiki/Units#cite_note-4](https://en.bitcoin.it/wiki/Units#cite_note-4)

**Comment by mrfelton** [comment]
@bolatovumar I've pushed up a fix for that issue in #1337.

Could you submit a PR with these unit tests please?

**Comment by bolatovumar** [comment]
@mrfelton yeah, I will submit the PR with unit tests later.
