### ISSUE TITLE
btc to fiat conversion isn't handled well for non-round values

### ISSUE THREAD

**Issue by bolatovumar** [LN-Zap/zap-desktop#1334]
I'm writing unit tests for btc.js and getting this result when testing the `bitsToFiat` function:
![screen shot 2019-01-13 at 3 47 23 pm](https://user-images.githubusercontent.com/1934678/51092329-cadcd680-174a-11e9-99fa-2ead92e56430.png)

I would expect to see 1.58 as this makes sense for a fiat values. The issue is in the btcToFiat function on [line 32 ](https://github.com/LN-Zap/zap-desktop/blob/master/app/lib/utils/btc.js#L32). Some rounding to the nearest second decimal place should be done there.

**Comment by mrfelton** [comment]
Probably should add `.toFixed(2)` or something like that, and this should probably apply to all of the `*ToFiat` methods.

**Comment by bolatovumar** [comment]
Just using `.toFixed(2)` doesn't actually work. Instead of 1.58 you would get something like 1.5700000000 or something like that, You have to do something like this to get it working correctly: [https://stackoverflow.com/questions/11832914/round-to-at-most-2-decimal-places-only-if-necessary](https://stackoverflow.com/questions/11832914/round-to-at-most-2-decimal-places-only-if-necessary)

I can submit a PR with a fix.
