### ISSUE TITLE
UI Feature: Add an app icon

### ISSUE THREAD

**Issue by thinkjanis** [LN-Zap/zap-desktop#135]
For a fast implementation, these would look good in my opinion.

![screenshot from 2017-12-28 18 47 05](https://user-images.githubusercontent.com/31632325/34417451-5d508654-ec01-11e7-9ace-9f90ed63e6ce.png)

![screenshot from 2017-12-28 18 55 09](https://user-images.githubusercontent.com/31632325/34417452-5d9ec8be-ec01-11e7-983d-980d55905563.png)

**Comment by FrimJo** [comment]
Nice work, I like them. I'm up to the task of implement them. And, I have also created som alternative ones, would be cool if even more proposals dropped in, then maybe we could have a vote later on?

<img width="429" alt="skarmavbild 2018-01-15 kl 14 07 17" src="https://user-images.githubusercontent.com/4533443/34943783-69c464f0-f9fd-11e7-8eee-44ce740b680c.png">

**Comment by thinkjanis** [comment]
I took them from the existing designs. Nice work @FrimJo! You should bring this up on Slack.

**Comment by JimmyMow** [comment]
<img width="544" alt="screen shot 2018-01-19 at 9 46 19 pm" src="https://user-images.githubusercontent.com/4040039/35179569-6ce6410e-fd62-11e7-9c2d-57000ccf122c.png">

right now i am using this app icon on builds. i think it looks solid for now. thoughts?

**Comment by FrimJo** [comment]
I think its a good icon, but I believe that a icon also should communicate the use of the application, that it some how should communicate wallet, what’s your take on that? I do like the cloud an lightning symbol though, I really get the feeling that it is “Zapping” something :)

**Comment by thinkjanis** [comment]
For now sure, better than nothing.
Personally, I really like icons with background gradients like the App store and Discord in the screenshot. Atom editor icon as well. Could you try creating a circle icon with a frame, 2 color gradient with the variants you presented and the existing lightning cloud @FrimJo?

**Comment by JimmyMow** [comment]
yeah I just went to one of the top results for "create an icon" in google search lol, didn't wanna spend too much time on it. i'm open to all suggestions, i'm sure we can come up with something cool

**Comment by thinkjanis** [comment]
Jup, I think designers here are pretty talented, so won't be a big undertaking.

**Comment by FrimJo** [comment]
@thinkjanis, definitely, I'll give it a go :)

**Comment by FrimJo** [comment]
![image](https://user-images.githubusercontent.com/4533443/35219814-603804d8-ff74-11e7-8fe8-bbdc743049f6.png)

**Comment by Empact** [comment]
FYI, an icon was added in f535e2322c91fc2a93352ffa61a4b85c25f391fd

It looks like this:
<img width="512" alt="screen shot 2018-03-12 at 9 12 11 pm" src="https://user-images.githubusercontent.com/5470/37322344-2debecc8-263a-11e8-9694-449ff3cb1c87.png">
