### ISSUE TITLE
Zap causes LND to spam channel DB

### ISSUE THREAD

**Issue by ZapUser77** [LN-Zap/zap-desktop#1358]
Running slow due to infinite loop

## Actual Behavior
Several times a second Zap is causing LND to "list channels" 
And it is "building nursery report for channel <omitted> 
It just keeps checking the same channel over and over again.

## Steps to Reproduce

NPM START
[That's it... absolutely nothing else]

## Your Environment

- Zap Desktop version: Latest Git Pull
- Operating System and version: Raspberry PI

**Comment by ZapUser77** [comment]
It gets stuck in an infinite loop on a pending "force closed" channel that's at -24000 blocks till maturity.

**Comment by ZapUser77** [comment]
Still having the same issue.  
One important note, I have mods to the dependencies (which are required to function on R-Pi)

npm install electron@3.0.10 (From within the zap-desktop directory)

And changed the dependency in package.json of Electron-updater to 3.2.3.

**Comment by JimmyMow** [comment]
@ZapUser77 how may channels do you have?

**Comment by JimmyMow** [comment]
I have a node with a similar channel count with no issue. What LND version (commit) are you using? I suspect this has to do with LND master having a breaking API change which caused Zap to have users that were using LND master. We have merged a fix recently but our latest release won't work with LNDs master API

**Comment by ZapUser77** [comment]
0.5.1 LND

**Comment by JimmyMow** [comment]
The release? Or is there a specific commit?

**Comment by ZapUser77** [comment]
Specifically: v0.5.1-beta-424-g4537c63dbd1cd96c1d4e73e8fa1e47a12314f418

**Comment by ZapUser77** [comment]
I very recently (within the last 5 days) did a git pull of Zap.
(What's the command to get the specific commit number?)

**Comment by JimmyMow** [comment]
Ah, I recommend doing another `git pull` -> `yarn clean` -> `yarn` and then restart Zap. Just today we merged in a fix to dynamically adjust to whatever LND API the user wants to use

**Comment by ZapUser77** [comment]
Now the interface is screwy.

<img width="1843" alt="ick" src="https://user-images.githubusercontent.com/40261754/52166067-38bd6200-273b-11e9-8946-8849e862331f.png">

Nothing is clickable other than "Launch"... which gives error "e.isDirectory is not a function"
None of the settings are editable.  No place to select macroons, etc.

**Comment by mrfelton** [comment]
> Nothing is clickable other than "Launch".

We don't currently support editing the wallet settings after the wallet has been created. This is being worked on for a future release.

> which gives error "e.isDirectory is not a function"

I think you said you have downgraded electron? This would also downgrade node, most likely to 
an old version that we don't support. We require the latest node version that is bundled with electron 4.x

**Comment by ZapUser77** [comment]
"electron 4.x"
Does *not* work on Raspberry PI, and *can not* work on Raspberry PI, currently.

I don't know what you mean by "node version", but if it's a dependency, please provide instructions on how to install the latest node version.

**Comment by ZapUser77** [comment]
"We don't currently support editing the wallet settings after the wallet has been created"
The wallet was created before I downloaded zap.  I don't want to create a new one, I don't want to delete my existing one... I just want to access my existing LND wallet... which I could do before.

**Comment by ZapUser77** [comment]
I've installed node 11.8.0 through "NVM".  Node --version -> 11.8.0
Still exact same error message when clicking launch.

**Comment by mrfelton** [comment]
Electron provides a Chromium environment which embeds a subset of Nodejs within it, in which our application runs.

You can not just download Election to an earlier version that the one we are building for and expect things to work. That’s a bit like downgrading Windows 10 to Windows 95 and expecting windows programs to still function.

Unfortunately, until Electron properly supports cross compiling for ARM, running Zap on a Raspberry Pi is just not liket to be possible without some serious tinkering.

**Comment by ZapUser77** [comment]
Unfortunately, that may permanently preclude Zap from running on the most prominent type of LN full node... Raspberry Pi.  

https://github.com/electron/electron/issues/16205

**Comment by mrfelton** [comment]
The Raspberry PI is indeed a very popular bit of hardware for a fullnode. However you probably shouldn't be trying to run desktop wallet software on a machine that is serving as a fullnode. This is bad for security reasons, aside from the fact that Zap Desktop is designed to be used as desktop software where as your fullnode is really a server application and a Raspberry PI is usually vastly under powered to run something like Zap Desktop efficiently.

A more normal thing to do would be to run Zap Desktop on your desktop machine, and connect it to your full node remotely (just copy your `tls.cert` and `admin.macaroon` file over to your desktop machine and provide paths to these files in Zap when setting up the remote connection). Many of our users - including myself - connect to full nodes running on Raspberry PI's this way.

**Comment by ZapUser77** [comment]
Running a completely standalone machine is drastically more secure than adding another attack surface (actively used desktop.)
If a windows machine is compromised and someone has full access to the machine, what's to prevent them from using the ZAP wallet right there on the desktop to drain the entire wallet?  

Whereas, a RPI with no remote access, at all, would still be secure.

[And I've yet to get the windows ZAP to connect to my RPI node.  No error, no nothing.  I'll open a separate ticket.]

**Comment by mrfelton** [comment]
> Running a completely standalone machine is drastically more secure than adding another attack surface (actively used desktop.)

Running nodejs code on your fullnode is asking for trouble if you ask me.

> If a windows machine is compromised and someone has full access to the machine, what's to prevent them from using the ZAP wallet right there on the desktop to drain the entire wallet?

Currently, nothing - you have to copy the `admin.macaroon` from your node to your desktop, and whoever gets access to the macaroon has the ability to control your now - But, this is a problem space that we are working on improving. We have some updates in the pipelines that aim to make this more secure.

**Comment by mrfelton** [comment]
To be clear - it may be ok to take a pre-compiled version of Zap Desktop, that was built specifically for ARM and run that directly on your Pi, if we were able to provide such a thing.

But what you are doing is installing our entire toolchain and all of the development tools and libraries needed to compile the app, and then building and compiling the app directly on that box. So you are running all kinds of code that you really don't need to be running on that machine, just to build and compile the app.

I appreciate that it would be nice if you could just download a pre-compiled Zap Desktop build for ARM, and install and run it on your Pi - that would be great, and I'd love for us to be able to support that in the future. But unfortunately Electron just isn't ready for that yet and Electron is our most core dependency.

**Comment by mrfelton** [comment]
@ZapUser77 I have just made an update to I believe will make the app run under an older version of Electron once more. I can't promise this will work, or that we will continue to support this in the future - but if you would like to try compiling again from the master branch and confirm wether or not it works that would be great:

```
git checkout master
git fetch --all
git reset --hard origin/master
[apply your patch to downgrade electron etc]
yarn clean
yarn
yarn package --linux
```

I'm going to close this issue since the actual cause of the original issue that you reported was that you were connecting to a newer version of lnd than we supported, and this has been addressed in the master branch such that we now support the most recent versions of lnd.

> And I've yet to get the windows ZAP to connect to my RPI node. No error, no nothing. I'll open a separate ticket.

Please do open another ticket if you would like help connecting to your lnd node from your desktop machine.

**Comment by ZapUser77** [comment]
"yarn package --linux"
Yielded a ton of errors, but I don't have time to play with it at the moment.

**Comment by mrfelton** [comment]
Ok - well try whatever set of commands you were using previously to build/run the app after downgrading electron. I'm not sure exactly what you were doing. Maybe you were using `yarn dev`? or `yarn start`?

**Comment by ZapUser77** [comment]
Since there's no actual instructions on how to run the program... anywhere... I had to figure out something on my own... 
I've been using npm run start.

**Comment by ZapUser77** [comment]
Hey hey!  It worked.  NPM run start worked like a champ with the rest of your instructions.
For anyone else that needs to do the same:
git checkout master
git fetch --all
git reset --hard origin/master
yarn clean
npm install electron@3.0.10 (From within the zap-desktop directory)
change the dependency in package.json of Electron-updater to 3.2.3.
yarn
npm start run

**Comment by mrfelton** [comment]
Awesome. Thanks for letting me know.

**Comment by ZapUser77** [comment]
Thanks for taking the time to get it to work!  ^_^

**Comment by ZapUser77** [comment]
Though, it still spams "Fetched 42 channels from DB".  As long as zap is open, I see it 3-4 times a second, then nothing for 10 seconds, then another burst spam.
Working as intended?

**Comment by mrfelton** [comment]
@ZapUser77 yes - we subscribe to a feed from lnd that tells us when there have been changes to nodes or channels on the network. If we detect that the change is relevant to your node or one of your channels we call out to lnd to fetch the latest channel data to ensure that what we have is as up to date as possible.

This can result in relatively frequent attempts to fetch channel data from lnd, although we do take some measures to ensure that we don't call it more than once per second so I'm unsure how you would be seeing this 3-4 times per second.

Which log are you looking at? Where are you seeing this message?

**Comment by mrfelton** [comment]
Also - worth noting - you will probably see this more when you first start up a wallet. If the wallet has been open for some time this should become less frequent.

**Comment by ZapUser77** [comment]
o_0
When you say "wallet" are you talking about the actual wallet... or Zap?  Because the wallet has been open for over a week.  And the spam only starts while zap is running.

**Comment by ZapUser77** [comment]
"Which log are you looking at? Where are you seeing this message?"
I ran LND within a console window... and that's where I see all the logs.
As you can see below, there are several times it pegs twice within under 1s of the previous.  And there's no way *my* channels are changing this frequently.

2019-02-05 07:57:05.961 [INF] RPCS: [listchannels] fetched 42 channels from DB
2019-02-05 07:57:06.875 [INF] RPCS: [listchannels] fetched 42 channels from DB
2019-02-05 07:57:20.035 [INF] RPCS: [listchannels] fetched 42 channels from DB
2019-02-05 07:57:26.417 [INF] RPCS: [listchannels] fetched 42 channels from DB
2019-02-05 07:57:29.465 [INF] DISC: Broadcasting batch of 11 new announcements
2019-02-05 07:57:32.973 [INF] RPCS: [listchannels] fetched 42 channels from DB
2019-02-05 07:57:54.391 [INF] RPCS: [listchannels] fetched 42 channels from DB
2019-02-05 07:57:59.465 [INF] DISC: Broadcasting batch of 10 new announcements
2019-02-05 07:58:07.310 [INF] RPCS: [listchannels] fetched 42 channels from DB
2019-02-05 07:58:08.288 [INF] RPCS: [listchannels] fetched 42 channels from DB
2019-02-05 07:58:10.440 [INF] RPCS: [listchannels] fetched 42 channels from DB
2019-02-05 07:58:11.512 [INF] RPCS: [listchannels] fetched 42 channels from DB
2019-02-05 07:58:12.695 [INF] RPCS: [listchannels] fetched 42 channels from DB
2019-02-05 07:58:20.103 [INF] RPCS: [listchannels] fetched 42 channels from DB
2019-02-05 07:58:21.025 [INF] RPCS: [listchannels] fetched 42 channels from DB
2019-02-05 07:58:21.720 [INF] RPCS: [listchannels] fetched 42 channels from DB
2019-02-05 07:58:24.914 [INF] RPCS: [listchannels] fetched 42 channels from DB
2019-02-05 07:58:25.881 [INF] RPCS: [listchannels] fetched 42 channels from DB
2019-02-05 07:58:27.004 [INF] RPCS: [listchannels] fetched 42 channels from DB
2019-02-05 07:58:29.465 [INF] DISC: Broadcasting batch of 59 new announcements
2019-02-05 07:58:36.421 [INF] RPCS: [listchannels] fetched 42 channels from DB
2019-02-05 07:58:40.981 [INF] RPCS: [listchannels] fetched 42 channels from DB
2019-02-05 07:58:41.962 [INF] RPCS: [listchannels] fetched 42 channels from DB
2019-02-05 07:58:54.416 [INF] RPCS: [listchannels] fetched 42 channels from DB
2019-02-05 07:58:59.465 [INF] DISC: Broadcasting batch of 24 new announcements
2019-02-05 07:58:59.751 [INF] RPCS: [listchannels] fetched 42 channels from DB
2019-02-05 07:59:00.697 [INF] RPCS: [listchannels] fetched 42 channels from DB
2019-02-05 07:59:06.509 [INF] RPCS: [listchannels] fetched 42 channels from DB
2019-02-05 07:59:07.527 [INF] RPCS: [listchannels] fetched 42 channels from DB
2019-02-05 07:59:12.494 [INF] RPCS: [listchannels] fetched 42 channels from DB
2019-02-05 07:59:13.495 [INF] RPCS: [listchannels] fetched 42 channels from DB
2019-02-05 07:59:26.373 [INF] RPCS: [listchannels] fetched 42 channels from DB
2019-02-05 07:59:29.465 [INF] DISC: Broadcasting batch of 23 new announcements
2019-02-05 07:59:40.792 [INF] RPCS: [listchannels] fetched 42 channels from DB
2019-02-05 07:59:41.734 [INF] RPCS: [listchannels] fetched 42 channels from DB
2019-02-05 07:59:51.121 [INF] RPCS: [listchannels] fetched 42 channels from DB
2019-02-05 07:59:52.144 [INF] RPCS: [listchannels] fetched 42 channels from DB
