### ISSUE TITLE
UI Bug: Make error message close button (X) noticeable with long messages

### ISSUE THREAD

**Issue by thinkjanis** [LN-Zap/zap-desktop#136]
![screenshot from 2017-12-26 20 47 18](https://user-images.githubusercontent.com/31632325/34417889-9cd89594-ec03-11e7-9211-23e6f26235c5.png)

**Comment by NahomAgidew** [comment]
@thinkjanis  I was thinking of removing the close button and make the error message auto-disappear after a few seconds.

**Comment by thinkjanis** [comment]
Solved by #140
