### ISSUE TITLE
Initial sync screen sometimes does not present an address or QRCode

### ISSUE THREAD

**Issue by brandoncurtis** [LN-Zap/zap-desktop#1367]
## Description

Zap does not offer a deposit address while syncing.

## Expected Behavior

As described in the PR that closed #105, Zap should offer a deposit address while syncing.

## Actual Behavior

The wallet invites you to fund your wallet but does not provide an address:

![screenshot from 2019-01-16 13-41-53](https://user-images.githubusercontent.com/2591290/51277753-b7717b80-1995-11e9-98a0-8fdb7e4d3c13.png)

## Steps to Reproduce

Create a new wallet in Zap.  Attempt to sync.

## Your Environment

- Zap Desktop version: v0.3.3 built locally from source
- Operating System and version: Linux Mint 19.1

I haven't tried the prebuilt binaries yet, so I'm not sure if this issue is present there.  Will test that momentarily.

**UPDATE**

I installed the prebuilt binaries, and here  I *do* get a funding address.

There were no errors in the local build, so I'm not sure what the issue is.

![screenshot from 2019-01-16 15-02-07](https://user-images.githubusercontent.com/2591290/51281698-6ca93100-19a0-11e9-9486-8d69b9b87d16.png)

Things I've tried:
- building with npm versus with yarn.  outcome: broken with both.
- running with `npm run dev` instead of building and install.  outcome: it *does* display an address.

Updating the title to reflect this.

**Comment by mrfelton** [comment]
@brandoncurtis I tested this and can not reproduce the issue (tried with a build built from `yarn package --linux` as well as running in dev mode `yarn dev`).

There are a couple of gotchas, however:

1) It can take a little time (usually no more than a few seconds) for the QR code to appear once the syncing has started.

2) We have on a number of occasions experienced issues with our BTCD nodes. If you got unlucky and try to sync at such a time, this could have caused an issue with the sync process that may have resulted in the issue you say.

Could you try against with a fresh checkout on the master branch please and let me know if you experience the issue again?

**Comment by brandoncurtis** [comment]
I tried again and it worked fine.  Looks like it was the BTCD node sync issue!

**Comment by mrfelton** [comment]
I'm going to re-open this issue, because there does indeed seem to be a scenario in which the QR code does not display when it should do.

Need more investigation to understand exactly what the conditions for this are.
