### ISSUE TITLE
UX Enhancement: Remove error popup message after an action

### ISSUE THREAD

**Issue by thinkjanis** [LN-Zap/zap-desktop#138]
The top red popup doesn't disappear after an error. When modifying input fields (performing an action) or switching to a new view, it should disappear.

**Comment by pajasevi** [comment]
What about timeout on error message? 10 seconds maybe? Could be easy to implement.

**Comment by thinkjanis** [comment]
Yes, good point @pajasevi. I was about to add it but the timeout may prevent the user from reading it, gets distracted etc. What if a user sends a transaction, the error is displayed, and the app is minimized? 

I am thinking the timeout should apply when the app window is active. Every time the app is minimized with the message, the timeout stops, and when maximized, resets or has 5 seconds remaining.

**Comment by pajasevi** [comment]
Maybe we should rethink how the global error UI works. Right now it can only show one error, so more errors happening at the same time are a problem.

Solution would be adding errors to the list and displaying them to the user in more compact but still visible way (top of the UI, not fixed to the top of the app). This would allow displaying more errors without hurting the view and there would be no need for timeout.

I can take a look at.

Enhancement: propagate errors to system notifications maybe?

**Comment by JimmyMow** [comment]
Gonna close this issue since #140 is merged. 

@pajasevi if you wanna open a new ticket to enhance global errors feel free. Probably a good idea

**Comment by pajasevi** [comment]
Will do! Thanks :zap:
