### ISSUE TITLE
Getting error message: There was a problem sending your payment. Error: Getting metadata from plugin failed with error: New streams cannot be created after receiving a GOAWAY

### ISSUE THREAD

**Issue by ad2003** [LN-Zap/zap-desktop#1385]
Itried to pay an invoice on yalls.org

like I did before, with the same version, I wanted to read postings by paying invoices.

invoice gets paid in no time...

## Actual Behavior

"There was a problem sending your payment. Error: Getting metadata from plugin failed with error: New streams cannot be created after receiving a GOAWAY" in red letters.

## Possible Fix

restarting ZAP desktop fixed it

## Steps to Reproduce

- 1. go on yalls.org - pay invoice to read message
- 2. invoice opens in ZAP Desktop
- 3. click Pay
- 4. Error 

## Context

I was unable to pay invoices - no matter which post I tried

## Your Environment

- Zap Desktop version: 0.3.3 Beta
- Operating System and version: windows 7

**Comment by mrfelton** [comment]
@ad2003 could you provide a little more information about your setup please?

Are you connected to your own node or using our internal one?

Mainnet or testnet?

If you restart the app does the problem persist?

**Comment by ad2003** [comment]
restarting ZAP desktop fixed it. 
Using my own node.
all on mainnet.
Didn't have had the problem since the last time it happened.

**Comment by mrfelton** [comment]
Did you restart your lnd node or otherwise disconnect from it whilst zap was still open?

**Comment by ad2003** [comment]
I am not sure, I cannot remember - but maybe I updated btcpay - therefore the lightning node would have been restarted while ZAP might have been open.

**Comment by mrfelton** [comment]
Closing as issue is almost a year old with no further updates. Problem relates to a much older version of node-grpc.
