### ISSUE TITLE
copy and paste amount into boxes not working

### ISSUE THREAD

**Issue by ad2003** [LN-Zap/zap-desktop#1389]
It's not possible to paste a specific number in to the request amount box.

Let's say I want to paste 0.001 into the amount box - I can't.
It's saysing "A number is required.

Also "," should be automatically converted to "." - so it makes using the numpad easier. 

when pasting, both versions should work: 0,001 and 0.001.

## Your Environment

- Zap Desktop version:
- Operating System and version: windows 7

**Comment by mrfelton** [comment]
> Also "," should be automatically converted to "." - so it makes using the numpad easier.

I don't really understand this. comma and period mean distinctly different things. Why would you convert one to another?

**Comment by ad2003** [comment]
while in US and other countries you use $10.25 you would use €10,25 in europe for instance. 

Europe (except the UK):

    100.000 or 100 000 means one hundred thousand
    €100.000,33 or €100 000,33 means one hundred thousand euros and thirty-three cents

US, UK, Australia

    100,000 means one hundred thousand
    €100,000.33 means one hundred thousand euros and thirty-three cents

Also programs like unity 3d or even ledger live lets you put in numbers with comma or period - and it is converted to period or comma where needed.

**Comment by mrfelton** [comment]
That would mean that we need to consider the user's locale before converting. We can't just blindly convert `,` to `.`

**Comment by ad2003** [comment]
I am talking about the amount of currency for instance: 0,125 => 0.125 or 10,25btc => 10.25btc..... 
It's just from my user experience point of view as I am often using the numpad for typing in numbers. Or copying an amount from other programs / wallets to pay with zap - and they are sometimes in comma, sometimes with period. If this is not possible, I can live with that.

**Comment by mrfelton** [comment]
@ad2003 I have pushed up a fix that handles the copy/paste issue anyway (will be in the next release)

Regarding the comma/period issue - It's definitely possible, just a question of what is the right way to handle it as it's actually not as simple as it sounds when you start to get into the details. If you want to discuss this some more, please create a new issue for that so that we are not trying to tackle two distinctly different issues in this thread. Thanks
