### ISSUE TITLE
UX Enhancement: Include unconfirmed incoming and outgoing onchain transactions

### ISSUE THREAD

**Issue by thinkjanis** [LN-Zap/zap-desktop#139]
Should appear in the transaction list either greyed out or with a message that indicates the status.

**Comment by bitgosh** [comment]
Should also appear in the wallet header as pending 
-> right now the btc amount used to open a channel is deducted from your total (it should still be part of the total) and doesn't show up as either  btc available or btc in channels. It think the header needs a new row, something like: 
_0.0997 pending_
Also, the **available btc** line in the header drops to 0.0 while a transfer is pending (screenshot attached)
![screen shot 2018-01-28 at 6 49 48 pm](https://user-images.githubusercontent.com/35896605/35484772-5fae5312-045d-11e8-965c-e285a946b969.png)

**Comment by thinkjanis** [comment]
That seems like an LND bug @bitgosh. I experience the same. 

The pending channel suggestion should be discussed on Slack in #desktop-design.

**Comment by mrfelton** [comment]
This is now supported in lnd and zap.
