### ISSUE TITLE
UX Enhancement: Add "Send All Funds" button in pay view for on-chain transactions

### ISSUE THREAD

**Issue by thinkjanis** [LN-Zap/zap-desktop#142]
## Detailed Description

Add option to send all on-chain funds shows up when pasting in a BTC address in pay view.

## Context

Improve usability of Pay form

## Possible Implementation

- Add a Toggle switch to the bottom of the amount section of the Pay form
- When selected, the populate the amount fields with the full on-chain balance and disable the amount fields
- When deselected, re-enable the amount fields
- When sending, pass the `send_all` flag to `sendCoins - see https://api.lightning.community/#sendcoins

![image](https://user-images.githubusercontent.com/200251/50820945-40e9d380-132e-11e9-9144-1ec07d14e8f0.png)

![image](https://user-images.githubusercontent.com/200251/50821090-9625e500-132e-11e9-94bd-91b404a62d4e.png)

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/1952
