### ISSUE TITLE
Infinite loading screen when connecting to remote node without rpclisten flag

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#1446]
When trying to connect to a node that does not have the `rpclisten` flag enabled, Zap does not timeout and gets stuck in an infinite loading screen. Restarting does not fix the issue because Zap will try and connect to the last node it was connected to in its prior session, so a user is left permanently stuck.

Reproduction steps:

1. Start a new LND with the following commands:
(It is important to _not_ add the rpclisten flag)
```
lnd --bitcoin.active --bitcoin.testnet --debuglevel=debug --bitcoin.node=neutrino --neutrino.connect=faucet.lightning.community
```

2. Connect to this node via Zap Remote Node setup
3. You get an infinite loading screen

Expected behavior is that Zap times out after 20 seconds and returns an error to the user, refusing to connect

**Comment by mrfelton** [comment]
I'm going to close this as we discovered that this was actually an issue with the patch in #1320 which has now been corrected.
