### ISSUE TITLE
New create channel form UI

### ISSUE THREAD

**Issue by lieteau2** [LN-Zap/zap-desktop#1448]
Implement the new channel form UI.

Screen designs can be found here:

https://app.zeplin.io/project/5bacdbad33af886d419f1b34/screen/5c519c6d1dfb92353b503ef9
https://app.zeplin.io/project/5bacdbad33af886d419f1b34/screen/5c519c6e0ddfba308d08c95e

**Comment by mrfelton** [comment]
Closed via #1568. Follow up stories created for additional bells and whistles for the forms.
