### ISSUE TITLE
Implement force close modal warning

### ISSUE THREAD

**Issue by lieteau2** [LN-Zap/zap-desktop#1449]
When a user force closes a channel, they should first be prompted to verify, as their funds will be time locked.

Use the existing warning modal within the code base that we use for deleting wallets, but just changed copy.

Design can be found here: https://app.zeplin.io/project/5bacdbad33af886d419f1b34/screen/5c3c88e822be21beb3e8c99e

**Comment by mrfelton** [comment]
Closed via #1576
