### ISSUE TITLE
UI blank after sending a successful payment

### ISSUE THREAD

**Issue by danielemiliogarcia** [LN-Zap/zap-desktop#1451]
UI blank after sending a successful payment

## Description

UI blank after sending a successful payment

## Expected Behavior

return to main menu

## Actual Behavior

window is blanc

## Steps to Reproduce

send a payment

## Context

sending a payment from zap desktop to my Lightning mobile wallet in android

## Your Environment

ZAP DESKTOP version 0.3.3-beta-5477

System:    Host: machinename Kernel: 4.4.0-141-generic x86_64 (64 bit gcc: 5.4.0)
           Desktop: Cinnamon 3.4.4 (Gtk 3.18.9) Distro: Linux Mint 18 Sarah
Machine:   System: Alienware product: Alienware 15 R2 v: 1.2.14
           Mobo: Alienware model: Alienware 15 R2 v: A00 Bios: Alienware v: 1.2.14 date: 06/02/2016
CPU:       Quad core Intel Core i7-6700HQ (-HT-MCP-) cache: 6144 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 20737
           clock speeds: max: 3500 MHz 1: 899 MHz 2: 899 MHz 3: 899 MHz 4: 900 MHz 5: 899 MHz 6: 899 MHz
           7: 900 MHz 8: 899 MHz
Graphics:  Card-1: Intel Skylake Integrated Graphics bus-ID: 00:02.0
           Card-2: NVIDIA GM204M [GeForce GTX 970M] bus-ID: 01:00.0
           Display Server: X.Org 1.18.4 drivers: intel (unloaded: fbdev,vesa) FAILED: nouveau
           Resolution: 1920x1080@60.02hz
           GLX Renderer: Mesa DRI Intel HD Graphics 530 (Skylake GT2)
           GLX Version: 3.0 Mesa 18.0.5 Direct Rendering: Yes
Audio:     Card Intel Sunrise Point-H HD Audio driver: snd_hda_intel bus-ID: 00:1f.3
           Sound: Advanced Linux Sound Architecture v: k4.4.0-141-generic
Network:   Card-1: Qualcomm Atheros Killer E2400 Gigabit Ethernet Controller
           driver: alx port: d000 bus-ID: 3b:00.0
           IF: enp59s0 state: down mac: <filter>
           Card-2: Intel Wireless 8260 driver: iwlwifi bus-ID: 3c:00.0
           IF: wlp60s0 state: up mac: <filter>
Drives:    HDD Total Size: 1000.2GB (18.6% used) ID-1: /dev/nvme0n1 model: N/A size: 256.1GB
           ID-2: /dev/nvme1n1 model: N/A size: 256.1GB ID-3: /dev/sda model: ST1000LM044_HN size: 1000.2GB
Partition: ID-1: / size: 172G used: 113G (70%) fs: ext4 dev: /dev/nvme0n1p3
           ID-2: swap-1 size: 68.72GB used: 0.00GB (0%) fs: swap dev: /dev/nvme0n1p2
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 62.0C mobo: N/A
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 321 Uptime: 9:27 Memory: 6144.7/32042.5MB Init: systemd runlevel: 5 Gcc sys: 5.4.0
           Client: Shell (bash 4.3.481) inxi: 2.2.35 
![image](https://user-images.githubusercontent.com/45073251/51946841-9da64e80-2401-11e9-9687-ce85ad507da3.png)

**Comment by mrfelton** [comment]
Hi @danielemiliogarcia could you provide a little more context about this issue please? If you could provide a copy of the invoice that you were trying to pay it would be a big help for us to diagnose the issue.

**Comment by danielemiliogarcia** [comment]
lntb13718930p1pw9yz22rzjq2ngydad6gzxyvpp6zdsxdxynykpxt4ne8w0ew8ne799wwr8w4fcu93fcqqqqzqqqyqqqqlgj5p0jqqqjqrzjqwyx8nu2hygyvgc02cwdtvuxe0lcxz06qt3lpsldzcdr46my5epmj93fhqqqq8gqqyqqqqlgqqqqqqgqjqfppqrthf80cq2z79r30rs3p5jxrtvtaklrzhdq2w3jhxcn4vuxqy9gcqpp5l8h6jrryem6j0ccc7c3h2f8vytxhfn6puezpd93x3n3egc6vf6eqfta48mypurgc6938vdyljr6c3hwxg5ktrs29j6ycasrqrjj5zj04dz28vzmvgv2gxm28wj2ukaf4fazlr50em5sg4xpy6sh6qd9rm6sp2ccv4d

recently, it pays ok (i recieve in the other node the payment), but the UI is blanck again
![image](https://user-images.githubusercontent.com/45073251/52010722-fbe03980-24b4-11e9-9fc6-20f295a7ceae.png)

the payment was generated by lightning wallet testnet for Android, last version

**Comment by mrfelton** [comment]
Thanks @danielemiliogarcia .

I believe the issue here is that this invoice is denoted in millisatoshis. There is a bug in Zap 0.3.3 that causes issues like this when paying millisatoshi denominated invoices.

This was fixed in https://github.com/LN-Zap/zap-desktop/issues/1372 via https://github.com/LN-Zap/zap-desktop/issues/1372 which has been merged into the master branch.

So - you can either compile a version of the app from the `master` branch  yourself, or you can wait for Zap 0.3.4 which is due to be releases soon.

**Comment by danielemiliogarcia** [comment]
Great! i hope the report was useful, Great project!

**Comment by Jfigs101** [comment]
Hi @mrfelton This is still an issue in Zap 0.3.4. I just paid for this invoice denoted in millisatoshi and received a blank screen: 

lnbc1336679810p1pwx5kefpp5nz4su9aezl8k77yakmpnvlg2fr3mg4y39a9cjyf72w4yxeum4jusdr2gfkx7cmtwd68yetpd5s9xar0wfjn5gp59cunjgz42dzzqen0wgszy3r0dcnhggz5wf6hxapwyptx2unfveujug3q2d6xjcmtv4ezq7pqxycqp2rzjqthv88m958rhnzyscgwuqay3dg7tsmvqp02cm62wzjy65tsu7q65kzyk3cqq20gqqyqqqqlgqqqqqqgqjqxuga2vz6ycmttj82cka76hdtj5682ahca2cxm9ezly6tzdrnd0jxyvzzelemgt67a6vrygt2tq5l2lup6a4syknmcs8klrgrchsxuhspndzpf5

**Comment by mrfelton** [comment]
@Jfigs101 thanks for reporting this. Was a slightly different, though related issue. This has been resolved in `master` via https://github.com/LN-Zap/zap-desktop/pull/1596. This fix will be included in our next release.
