### ISSUE TITLE
Lnd Syncing page fact descriptions don't have periods at the end

### ISSUE THREAD

**Issue by thejourneydude** [LN-Zap/zap-desktop#146]
On the Lnd Syncing page, there are four facts: `The Lightning Network`, `Payment Channel`, `HTLC `, and `Onion Routing`. Each fact has an description. Only one fact, `Onion Routing` has a period at the end of the description. There should be some consistency in either having or not having periods at the end of the description. My suggestion is to have a period at the end of each description. 

To fix this, one can edit the text in the following [file](https://github.com/LN-Zap/zap-desktop/blob/master/app/components/LndSyncing/LndSyncing.js#L9).

**Comment by pajasevi** [comment]
@thejourneydude Well, why don't you open a pull request then?

**Comment by JimmyMow** [comment]
Good catch @thejourneydude. I am actually redesigning the syncing page.

The new syncing page will have the ability to set your node `alias` and show you a deposit address so you can deposit coins while syncing. I already mocked it out on a branch:

<img width="1440" alt="screen shot 2017-12-29 at 2 22 05 pm" src="https://user-images.githubusercontent.com/4040039/34463465-7ccd0444-ee22-11e7-99de-d4f13f776b0b.png">

**Comment by JimmyMow** [comment]
Closing this. Syncing page will be redone soon, don't want people picking up this issue and submitting PRs
