### ISSUE TITLE
Wallet name Deleted

### ISSUE THREAD

**Issue by lieteau2** [LN-Zap/zap-desktop#1492]
When a user logs into a saved wallet, then logs out of that same wallet, the users saved wallet name is deleted and reverted back to `Wallet #X`

## Expected Behavior

Users wallet name should remain the same logging in and out of wallet. 

Users wallet name is reverted back to `Wallet #X`

## Steps to Reproduce

Log into a saved wallet and log out of that same wallet.

**Comment by mrfelton** [comment]
This issue was introduced in https://github.com/LN-Zap/zap-desktop/pull/1454 and has been corrected in that branch.
