### ISSUE TITLE
Channel funding dialog should prevent user from requesting a channel size that exceeds available wallet balance

### ISSUE THREAD

**Issue by brandoncurtis** [LN-Zap/zap-desktop#1494]
## Expected Behavior

If wallet balance is 0.001 tBTC, Zap should constrain the balance in the channel-open dialog such that the channel balance + TX fees ≤ 0.001 tBTC.

## Actual Behavior

In this wallet with 0.001 tBTC, the dialog box still turns green when 0.005 tBTC is entered as the proposed channel amount:

![image](https://user-images.githubusercontent.com/2591290/52249112-46432b00-28a6-11e9-8e19-384f136d2b32.png)

Upon submission, Zap then displays the user-unfriendly error message `Error: not enough witness outputs to create funding transaction`:

![image](https://user-images.githubusercontent.com/2591290/52249156-6f63bb80-28a6-11e9-865f-762d1c49676b.png)

## Possible Fix

Constrain the balance in the channel-open dialog such that the channel balance + TX fees ≤ confirmed wallet balance.  Confirmed wallet balance is readily available via https://api.lightning.community/#walletbalance

It doesn't look like there is a way to ask https://api.lightning.community/#openchannel to craft a transaction without actually _sending_ the transaction.  Is that the problem?  If so, I'll open something against LND.

## Steps to Reproduce

1. fund Zap Wallet
2. attempt to open channel
3. specify channel size equal or greater to the amount of available funds

## Context

This is especially confusing to new users when they attempt to create a channel with their entire balance, it fails because TX fees are not considered, and the error message isn't enlightening.

## Your Environment

- Zap Desktop version: v0.3.3-beta
- Operating System and version: Ubuntu Linux 18.04

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/1665
