### ISSUE TITLE
Use unconfirmed change outputs as inputs to channel funding transactions

### ISSUE THREAD

**Issue by brandoncurtis** [LN-Zap/zap-desktop#1495]
## Description

During typical use, Zap will be funded with a single UTXO in a funding transaction.  The user will then attempt to use Zap to open multiple channels.  Only the first channel funding attempt will successfully create a transaction, because the change from this channel funding transaction will not yet have confirmed and Zap will refuse to use it as an input in additional channel funding transactions.

## Expected Behavior

Zap will use unconfirmed channel funding change outputs as inputs in subsequent channel funding transactions.

## Actual Behavior

Subsequent channel funding requests fail:

![screenshot from 2019-02-04 18-25-24](https://user-images.githubusercontent.com/2591290/52249997-adfb7500-28aa-11e9-95a7-8530f1126648.png)

Even though there is enough unconfirmed change to fund the channel:

![screenshot from 2019-02-04 18-27-27](https://user-images.githubusercontent.com/2591290/52249971-93c19700-28aa-11e9-8e2e-2c091715c556.png)

## Possible Fix

Use the `spend_unconfirmed` flag: https://api.lightning.community/#openchannelrequest

## Steps to Reproduce

1. fund Zap with 0.001 tBTC
2. open a channel for 0.0003 tBTC
3. attempt to open another channel for 0.0003 tBC

## Your Environment

- Zap Desktop version: v0.3.3-beta
- Operating System and version: Ubuntu Linux 18.04

**Comment by mrfelton** [comment]
Fixed via https://github.com/LN-Zap/zap-desktop/pull/1780
