### ISSUE TITLE
Wrong Bitcoin Address Showing

### ISSUE THREAD

**Issue by corypchajek** [LN-Zap/zap-desktop#1496]
Wrong Bitcoin Address Showing in Zap Wallet

## Description

Sent btc to the Bitcoin Address shown in my Zap Wallet. Balance is still 0 despite many confirmations.

## Expected Behavior

Balance in Zap wallet should be updated.

## Actual Behavior

Balance is not updated. Does this mean my Zap wallet is not showing the correct address?

## Your Environment

- Zap Desktop version: 0.3.3
- Operating System and version:
Windows 10 Home Build 17134
LN Wallet created through Node Launcher

**Comment by brandoncurtis** [comment]
Not likely that an incorrect address is shown, as all that Zap does is provide a graphical interface for the underlying LND node.  More likely that there was some communication failure between Zap and the node.  Is this mainnet or testnet?  If you shut down Zap and the node and bring them back up again, does Zap show the correct balance?

**Comment by corypchajek** [comment]
No. Shuttting down and restarting doesn’t do anything. I’m pretty sure it’s mainnet. I was in mainnet tab when I created the node through Node Launcher app.

**Comment by mrfelton** [comment]
@corypchajek did you figure this out in the end?

**Comment by corypchajek** [comment]
Whatever was wrong magically righted itself and funds eventually appeared in the correct wallet address. So no I didn’t really figure out exactly what went wrong but all is ok now.

Hey I could really use some incoming channels. Please feel free to connect to Running Perogy.

Cheers!

Cory

**Comment by mrfelton** [comment]
Glad it's working for you now. Thanks for the update.
