### ISSUE TITLE
Pre-release testing (0.3.4)

### ISSUE THREAD

**Issue by lieteau2** [LN-Zap/zap-desktop#1499]
- [x] user logs into wallet 
- [x] User opens zap by clicking on a ln payment link (yalls)
- [x] User can see fiat amount when creating payment request
- [x] User can buy a yalls article
- [x] Double paying same invoice leads to payment failure
- [x] User can create a payment request
- [x] User can change between tbtc, tbits, tsats in payment request 
- [x] User can change fiat denomination when creating a payment request
- [x] User can change fiat denomination home screen
- [x] User can select mini QR code on home screen and see node pub key and bitcoin address 
- [x] User can change QR code between node pub key and bitcoin address 
- [x] User can change btc denomination in home screen
- [x] User can see information on requested payments requests
- [x] User can see information on pending payment requests
- [x] User can display / hide expired requests
- [x] Failed Payments remain on home screen UI until user logs out 
- [x] User can change language denomination in home screen
- [x] User can switch between light and dark themes
- [x] Several error messages can populate at once
- [x] User can scroll through launchpad modal
- [x] On sync screen user can select zap tutorials and be brought to https://ln-zap.github.io/zap-tutorials/zap-desktop-getting-started
- [x] On sync screen user can select zap tutorials and be brought to https://ln-zap.github.io/zap-tutorials/zap-desktop-getting-started
- [ ] User names their wallet a short name and wallet settings UI is uninterrupted (looks same as wallet with a long name) 
- [x] Settings menu closes when user clicks out of it 
- [x] User selects copy invoice payment request and can paste the payment request
- [x] Column text left aligned for channel portion of home screen
- [x] Loading screen doesnt flicker after user selects launch button on wallet settings page for local wallet 
- [x] Pay modal is scrollable
- [x] Request modal is scrollable 
- [x] User can delete a wallet 
- [x] User can create a wallet 
- [x] User can open a channel
- [x] User can close a channel
- [x] User can confirm channel transactions on blockstream
- [x] User can search for a specific channel they have opened 
- [x] USD values are rounded to two decimals 
- [x] Add intl support to 'importing wallet...' message which appears during Wallet Recover state
- [x] Add internal (inside GUI) notification when copying payment request
- [x] avoid jumping when scroll bar appears
- [x] ensure copy/paste works in amount fields
- [x]  highlight border of selected inputs
- [x]  add cross platform about menu

## Issues found in testing

- [x] https://github.com/LN-Zap/zap-desktop/issues/1509
- [x] https://github.com/LN-Zap/zap-desktop/issues/1510
- [x] https://github.com/LN-Zap/zap-desktop/issues/1512
- [x] https://github.com/LN-Zap/zap-desktop/issues/1515
- [x] https://github.com/LN-Zap/zap-desktop/pull/1519
- [x] https://github.com/LN-Zap/zap-desktop/pull/1524
- [x] https://github.com/LN-Zap/zap-desktop/pull/1521
- [x] https://github.com/LN-Zap/zap-desktop/pull/1518
- [x] https://github.com/LN-Zap/zap-desktop/pull/1527

**Comment by JimmyMow** [comment]
@lieteau2 can you change this from a checklist screenshot to github checkboxes?

You can use `[x]` for a completed check and `[]` for an uncompleted check

Example:

[x] Comment on issue #1499
[] Become a billionaire

**Comment by JimmyMow** [comment]
@lieteau2 can you change this from a checklist screenshot to github checkboxes?

You can use `- [x] the_completed_task_goes_here` for a completed check and `- [ ] the_uncompleted_task_goes_here` for an uncompleted check

Example:

- [x] Comment on issue #1499
- [ ] Become a billionaire

**Comment by lieteau2** [comment]
@JimmyMow see changes above

**Comment by JimmyMow** [comment]
Closing due to the release
