### ISSUE TITLE
Slack invite is no longer valid

### ISSUE THREAD

**Issue by coolpick** [LN-Zap/zap-desktop#150]
The Slack URL is a dead link.  Please update with an active URL.  Current (dead) is: https://join.slack.com/t/zaphq/shared_invite/enQtMjc5Njg3NjU5MzMzLWE1M2RiNjYxNWEyMTRjMzhmZDIyNTQ0YTRjNDg4MWNiMzI1ODNlODhhMzE5ZWVmMGVkOWVkMTVmNzBhNDhiZjQ

**Comment by JimmyMow** [comment]
fixed #152

**Comment by sairion** [comment]
It is not working again.
