### ISSUE TITLE
"Not a valid bitcoin/lightning request." when pasting a valid bitcoin or lightning address into pay form

### ISSUE THREAD

**Issue by mrfelton** [LN-Zap/zap-desktop#1510]
## Description

Getting the following error when trying to make a payment to a valid onchain or offchain address

![image](https://user-images.githubusercontent.com/200251/52398543-b2e24380-2ab9-11e9-80b0-3023614e609c.png)

## Expected Behavior

Should detect the address as valid.

## Actual Behavior

Shows error "Not a valid bitcoin/lightning request." and does not let me proceed.

## Possible Fix

Debug Pay form validation

## Steps to Reproduce

Paste valid LN/Bitcoin address into the pay form

## Your Environment

- Zap Desktop version: master
- Operating System and version: Mac

**Comment by oh-kurrrrt** [comment]
Tom, 
Windows version is doing the same thing.  It won't allow me to pay a tippin.me lightning address.  
Thanks, I'm running Zap 0.6.2 Beta on Win 10

**Comment by robbie2121** [comment]
> Tom,
> Windows version is doing the same thing. It won't allow me to pay a tippin.me lightning address.
> Thanks, I'm running Zap 0.6.2 Beta on Win 10

I'm getting the same message, also trying to tip with tippin.me lightning address. I downloaded the latest zap wallet version for windows 10. (0.6.2-beta)

**Comment by bolatovumar** [comment]
I can take a deeper look. @oh-kurrrrt @robbie2121 could you provide an example of the toppin.me payment request that fails for you? I can try my own account but in case that doesn't fail and the payment goes through I will need an example of a failing payment request.

**Comment by robbie2121** [comment]
> I can take a deeper look. @oh-kurrrrt @robbie2121 could you provide an example of the toppin.me payment request that fails for you? I can try my own account but in case that doesn't fail and the payment goes through I will need an example of a failing payment request.

Hi,

This is an example of one that wasn't working: lnbc1p0x2wtwpp5qf36ferg5ereu9nurpud93g4gx7vq5ukaq9jka0ujfuamdxy6x9qdpu235hqurfdcs8xam9v3jhgmmndp5jq2r5d9c8q6tw9ekk22fgw5cnjvfexu5scqzpgxqyz5vqsp5th6wqw0354lnds9nv6hqtdfqueux9vhgxxmsayluanppa7upfg8q9qy9qsqkg2x58ave6jpwl0jvqmgdh5j69f5skzq0najfe3px0umalknkq4rzpcampv47hpt5dkct80qqnnm92xw4ntvq2w0wm3xn8z77qv0ndgqdj6kle

Not sure if these expire, so here is a fresh one:

lnbc1p0xtj6epp5rd0aqa39xft9tfrl048rf5sfpckjzagkhrwcjt05rhpfp8m0hhcsdpu235hqurfdcs8xam9v3jhgmmndp5jq2r5d9c8q6tw9ekk22fgw5cnjvfexu5scqzpgxqyz5vqsp5mwzdutnewqauhun5hm9rfct7gpv0cl8h96a4uzs37kfdgen8ej8s9qy9qsqzp00aqdv96ddunmzqpl4u3c06e7k4akv8q9y49qj93v9d97je7v4k2yad4mxprtzy0njm70sffxmrqumvhnxjy4pmyyuhg3sdhyaangqnvq62v

**Comment by mrfelton** [comment]
Tippin.me produces zero amount invoices - we don’t support paying these in zap because there are security concerns with them.

**Comment by bolatovumar** [comment]
@mrfelton i'm wondering if we can show a warning to the user saying these are not supported instead of a generic error message?

**Comment by mrfelton** [comment]
Probably a good idea @bolatovumar .

**Comment by robbie2121** [comment]
> Tippin.me produces zero amount invoices - we don’t support paying these in zap because there are security concerns with them.

Ah, thank you for letting me know.

**Comment by bolatovumar** [comment]
@mrfelton ok, i will take a look into doing that.

**Comment by mrfelton** [comment]
Closing as this is expected behaviour for zero value invoices and we have improved the error message in of https://github.com/LN-Zap/zap-desktop/pull/3385
