### ISSUE TITLE
Check if remote node is synced 

### ISSUE THREAD

**Issue by korhaliv** [LN-Zap/zap-desktop#1520]
## Detailed Description
Check if remote node is synced by comparing its sync height to some external source

## Context
Currently Zap checks sync status for local nodes only. It would be good to have some checks for the remote nodes too

## Possible Implementation
Compare remote node sync height to an external source like block explorers and\or zap hq feed

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/2390
