### ISSUE TITLE
Better handling for extremely long wallet names

### ISSUE THREAD

**Issue by lieteau2** [LN-Zap/zap-desktop#1529]
add a character limit to the wallet names so as if to minimize UI/UX disruptions

## Possible Fix

introduce a character limit to the wallet name

## Steps to Reproduce

use an extremely long wallet name 

- Zap Desktop version: 0.3.4-beta
- Operating System and version: mac osX

**Comment by bolatovumar** [comment]
Some screenshots of the UI when the wallet name is really long:

![Screen Shot 2019-03-12 at 8 07 40 PM](https://user-images.githubusercontent.com/1934678/54251310-081fd380-4504-11e9-9b1f-57d2c20b0fa8.png)
![Screen Shot 2019-03-12 at 8 14 40 PM](https://user-images.githubusercontent.com/1934678/54251311-08b86a00-4504-11e9-804b-ec941d353083.png)
![Screen Shot 2019-03-12 at 8 17 52 PM](https://user-images.githubusercontent.com/1934678/54251312-08b86a00-4504-11e9-8202-1b7f6bf85fc6.png)

It seems like a 30 character limit would be work well.

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/2116
