### ISSUE TITLE
Combine the Need Help? Sync Screen Options

### ISSUE THREAD

**Issue by lieteau2** [LN-Zap/zap-desktop#1530]
I think the two separate functions / sentences can be combined

Change to 

Need help?  While waiting you could have a look at our Tutorials and learn how things are working.

## Your Environment

- Zap Desktop version:0.3.4-beta
- Operating System and version: mac osX

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/1798
