### ISSUE TITLE
Standalone settings screen

### ISSUE THREAD

**Issue by korhaliv** [LN-Zap/zap-desktop#1535]
## Detailed Description
Add a standalone settings screen which would allow to edit settings without launching a wallet.

Settings such as:
- Theme
- Language
- Autoupdate Settings
- Default denominations
- Block explorer
- Address format (native/wrapped bech32)
- Ports (rpc/rest/p2p)
- Neutrino backends
- Invoice expire time
- Preferred target confs (slow/medium/fast()
- Channel routing fees

## Context
Currently settings are scattered across the app and some of theme require a wallet to be open (such as theme). It would be convenient to have them in one place at a higher level in UI.

https://app.zeplin.io/project/5bacdbad33af886d419f1b34/screen/5c5d94cd9a750e351a730321
https://app.zeplin.io/project/5bacdbad33af886d419f1b34/screen/5c5d94ce2e7593353865585e

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/2200
