### ISSUE TITLE
Add ability to toggle autoupdate

### ISSUE THREAD

**Issue by korhaliv** [LN-Zap/zap-desktop#1536]
## Detailed Description
Add a setting that would allow to enable/disable autoupdate feature.

## Context
Currently autoupdate is enabled by default, which has certain security concerns and may be undesirable by some users. There is no way to disable this behavior currently.

## Possible Implementation
Add an option to a global settings screen (is addressed in #1535 )

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/2200
