### ISSUE TITLE
Stuck in Testnet?

### ISSUE THREAD

**Issue by robbie2121** [LN-Zap/zap-desktop#1548]
I downloaded the latest zap wallet today (0.3.4-beta) and I create a new wallet, and select "create new wallet" and then it gives me the seed, asks me to make a password then it finishes "synching the blockchain" after that, my wallet says it is in testnet only (not mainnet). I made a second wallet with the same result! I don't see any option to switch to mainnet.
## Description

I am in testnet mode and cannot switch to mainnet
## Expected Behavior
install wallet, make a wallet, be on mainnet

make a wallet on mainnet
## Actual Behavior
makes wallets on testnet

## Steps to Reproduce

- 1. install wallet
- 2. create new wallet "Let Zap create a new bitcoin wallet and lightning node for you."
- 3. Let zap blockchain synch
- 4. open wallet and see that it is in testnet

## Context

wanted to test mainnet lightning
## Your Environment
windows 10 enterprise 64bit

Works on a VM i setup using Pierre's Node Launcher guide
- Zap Desktop version: 0.3.4-beta
- Operating System and version: windows 10 enterprise 64bit

**Comment by JimmyMow** [comment]
Hey @robbie2121. Great to hear you downloaded Zap and got on-boarded with no issues!

Bad news is mainnet is not yet supported out of the box. It involves a new light client designed specifically with LN clients in mind, and it is not quite ready for mainnet yet.

You can however use Zap on mainnet by setting up a remote mainnet LND node paired with a Bitcoin full node and connect Zap to it. That is how all of our mainnet users including myself are using it today. 

It looks like you have done this with Pierre's Node Launcher, which is fantastic. When creating a new Zap wallet, click "Connect to your own node". Pierre has written a guide on this here: 

https://medium.com/lightning-power-users/easy-lightning-with-node-launcher-zap-488133edfbd

**Comment by JimmyMow** [comment]
@PierreRochard does NodeLauncher currently support an `lndconnect` button in the UI? If so @robbie2121 you should be able to just click that which will launch Zap and connect the applications

**Comment by robbie2121** [comment]
Thanks for clarifying Jimmy! I'm making a lightning page on my website so I just wanted to check. You guys are amazing, thank you so much to all the developers in the space!!

**Comment by PierreRochard** [comment]
Yes, guide is here https://medium.com/lightning-power-users/easy-lightning-with-node-launcher-zap-488133edfbd
