### ISSUE TITLE
Allow custom invoice expiration and/or increase the default

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#1550]
Right now when you create an LN invoice it expires in 10 minutes. We should either let the user customize this, increase the default, or both. I'm not totally sure it's worth it to allow users to customize it. I think the short term answer here is to just increase the default a tad. But idk curious to hear thoughts

**Comment by mrfelton** [comment]
@JimmyMow I created a story for this a while back and had some designs mocked up already. See #876. Let's carry the on discussion over there.

Closing this as a duplicate.
