### ISSUE TITLE
Better "Getting Started UI"

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#1553]
The `How do you want to connect to the Lightning Network?` screen is not as inviting and intuitive as it could be. Considering this is how users first interact with Zap, I think we should simplify the copy, add some helpful icons and maybe re-design the layout if need be.

Below is the current screen in `next`:

<img width="1022" alt="screen shot 2019-02-10 at 12 37 46 pm" src="https://user-images.githubusercontent.com/4040039/52537876-38235d80-2d31-11e9-96a4-9b1f939d8ec0.png">

I think the title of the options should be one word: `Create`, `Connect` and `Recover`. Simpler UX. I also think each should have it's own icon maybe and we could play around with new layout ideas and see if any feel good

Each title option has its own icon and below is the layout design. 

<img width="666" alt="screen shot 2019-03-05 at 1 20 45 pm" src="https://user-images.githubusercontent.com/45567325/53835772-e3e85380-3f53-11e9-9ec5-194586ac2bc1.png">
<img width="668" alt="screen shot 2019-03-05 at 1 21 13 pm" src="https://user-images.githubusercontent.com/45567325/53835758-dd59dc00-3f53-11e9-90ef-1e44d1052de1.png">
<img width="666" alt="screen shot 2019-03-05 at 2 33 50 pm" src="https://user-images.githubusercontent.com/45567325/53835719-ca470c00-3f53-11e9-9843-fba8fcf65c6e.png">

https://app.zeplin.io/project/5bacdbad33af886d419f1b34/screen/5c7ea7efbc2e8abcea0eb7a5

https://app.zeplin.io/project/5bacdbad33af886d419f1b34/screen/5c7ea7edbf0d81bce4546b39

https://app.zeplin.io/project/5bacdbad33af886d419f1b34/screen/5c7ea7eed693e3bc7283dc38

**Comment by KayBeSee** [comment]
New designs look 🔥!!

I would say though that the "Next" button on the bottom right is a little unnecessary. I'd just direct the user to the next page when they click one of the three options to reduce the number of clicks they need to do.

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/1742
