### ISSUE TITLE
Change product name from "ZapDesktop"

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#1554]
Right now our product name is `ZapDesktop`. It feels like complicated legacy software with that copy lol. Maybe we should add a space so it's Zap Desktop? Or I kinda like cutting the desktop (because no duh it's desktop if you're downloading it) and just go with `Zap`

**Comment by mrfelton** [comment]
I agree. I would cut `Desktop` completely and just name it Zap. The product is Zap, wether you are on Mac, Linux, Windows, iOS or Android when we get to that, you are just using the Zap app.
