### ISSUE TITLE
Pay and request do not execute

### ISSUE THREAD

**Issue by emplexity** [LN-Zap/zap-desktop#157]
I run lnd 0.3 with the following lnd.conf on my ubuntu 14.04:
debuglevel=info
bitcoin.active=1
bitcoin.testnet=1
neutrino.active=1
neutrino.connect=btcd.jackmallers.com:18333
autopilot.active=1
noencryptwallet=1

I then launch zap w/ the 'mpn run dev' cmd. (installed from github on the 03.01.18)
I did set up 6 channels successfully and they are all showing up as active, all all related bitcoin transaction shown paid in the zap wallet.
When a submit a payment eg on starblocks, yalls or bitrefill, zap fills the screen with the "Loading" logo for ever, until I shut down zap. When I restart it, there is no trace of the previous pay attempts.
For receive, I use eclair on my android to capture the invoice (which goes ok!) and send the funds but they never arrive, while I can pay to starblocks, yalls and bitrefill with no problem from eclair.
So it looks like that while I have 6 open active channels each with between 10 to 100 connections, no lightning transaction is possible with the zap + lnd + lnd.conf set up.

By the way I experience the same with the lightning app. Is there anything I should change in the lnd.conf file to get it working or any other advise?

Thanks for any support.

**Comment by JimmyMow** [comment]
Can you paste your `lnd.conf`?

Also, what do your logs look like? We should do a better job of displaying errors for sure, but for now the truth lives in the logs. If you can capture the logs when trying to submit a payment that would be great

**Comment by emplexity** [comment]
Thanks.
Was not able to locate much logs beyond lightdm.log in /var/log. So you will find in the gz attached:

-  the traces for lnd and zap-desktop from their respective terminal windows, generated from their respective launches till I tried to pay a starbocks invoice and after few minutes forced closed zap by hitting file close on its window menu and nicely shutdown lnd with lncli stop;

- the starbocks invoice paste to pay in ZAP;

- lnd.conf;

- lightdm.log in the .gz attached.

Hope it helps. Available for further info

[ZAP_trace+log+conf.tar.gz](https://github.com/LN-Zap/zap-desktop/files/1608904/ZAP_trace.log.conf.tar.gz)

**Comment by mrfelton** [comment]
This issue relates to a very old version of zap and lnd that is no longer supported. @emplexity please feel free to reopen this issue persists with the latest codebase/lnd.
