### ISSUE TITLE
Stuck at 99%

### ISSUE THREAD

**Issue by Sorikal** [LN-Zap/zap-desktop#1577]
When I try to sync with the blockchain I get stuck at 99%

**Comment by GiovanniBordiga** [comment]
Same issue here on the linux x86_64 .AppImage `v0.3.4`.

**Comment by JimmyMow** [comment]
After some investigation, it seems one of our BTCD nodes that is serving the filters to the clients stalled out. We just restarted the node. Can you try again? The problem should be solved now.

**Comment by GiovanniBordiga** [comment]
@JimmyMow sync is working now! Keep up the good work! :sunglasses:

**Comment by Sorikal** [comment]
Thanks I will check if the issue has been resolved.

**Comment by lieteau2** [comment]
@Sorikal any updated here?

**Comment by JimmyMow** [comment]
@Sorikal I am going to close this due to inactivity and reports that it has been resolved. Feel free to re-open if you encounter the issue again
