### ISSUE TITLE
Inconsistent icons in pay and request forms

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#1610]
Currently, the `Request` form has our new icon but the `Pay` form has an older icon. The Pay form should get an updated icon to keep consistent. We can't use our LN or on-chain ones because the Pay form encompasses both, I assume that's why we've kept the old one. We should design a Pay icon and replace the old one.

See screenshots below:

`Request form with new Icon`:
<img width="900" alt="screen shot 2019-02-20 at 8 30 35 am" src="https://user-images.githubusercontent.com/4040039/53099134-c1cdea80-34ea-11e9-81ad-9f24174a5e33.png">

`Pay form with old icon`:
<img width="902" alt="screen shot 2019-02-20 at 8 30 28 am" src="https://user-images.githubusercontent.com/4040039/53099151-cabebc00-34ea-11e9-8f71-3a3412a8418d.png">

**Comment by mrfelton** [comment]
We might need a new icon then. Because the icons that we use on the second page differ depending on wether we detect that you are trying to send on-chain vs via lightning.

**Comment by JimmyMow** [comment]
Agreed. Will at it to the design prios

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/1713
