### ISSUE TITLE
Address modal bug (next branch)

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#1614]
In the next branch when clicking on the `qrcode` to access my address, URI and lndconnect QRCode I see the following UI:

<img width="902" alt="screen shot 2019-02-20 at 6 50 44 pm" src="https://user-images.githubusercontent.com/4040039/53135367-9a097180-3540-11e9-9cd3-f051b8cef154.png">

Also, clicking on `Node URI` makes the screen go blank

**Comment by korhaliv** [comment]
Closed via #1616
