### ISSUE TITLE
UX Improvement: PAY checks clipboard for copied transaction requests

### ISSUE THREAD

**Issue by DannyJAAM** [LN-Zap/zap-desktop#162]
If I've copied a payment request to my clipboard, when I hit the PAY button the payment request field should be pre-populated to save me pasting.

**Comment by Empact** [comment]
Hey @DannyJAAM, in most web cases, payment is made easy by hosting a "lightning:" protocol link that will open Zap and pre-fill with the payment request. See the video here: https://twitter.com/ln_zap/status/949160105865633792

**Comment by JimmyMow** [comment]
Agree with @Empact here. I'm going to close this
