### ISSUE TITLE
Add ability to edit remote connection settings that use lndconnect 

### ISSUE THREAD

**Issue by korhaliv** [LN-Zap/zap-desktop#1624]
## Detailed Description
Currently you are only allowed (#1620) to edit host, cert and macaroon if you've used paths to setup your node as opposed to lndconnect uri

## Possible Implementation
Allow to paste/edit the entire lndconnect uri but also introduce some way to make it hidden by default for security reasons.

![image](https://user-images.githubusercontent.com/200251/53815835-beaf1180-3f62-11e9-8cb4-b99162b21698.png)

**Comment by korhaliv** [comment]
@mrfelton I think `TextArea` should not be editable in hidden mode, otherwise it doesn't really make sense because `lndconnectUri` will be overridden with some garbage

**Comment by mrfelton** [comment]
makes sense @korhaliv

**Comment by mrfelton** [comment]
Fixed via https://github.com/LN-Zap/zap-desktop/pull/1718
