### ISSUE TITLE
Inaccurate on-chain balance in Next branch

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#1648]
When opening a channel, the channel form is showing me my `channel` balance as my on `on-chain`. I was getting a not enough funds error and didn't know what was happening until I realized I actually had barely any funds on-chain.

You can see the pay form here is accurate:

<img width="902" alt="screen shot 2019-02-27 at 6 00 48 am" src="https://user-images.githubusercontent.com/4040039/53449876-df083900-3a55-11e9-96e0-444dbcc13a6a.png">

And how it's different here:

<img width="901" alt="screen shot 2019-02-27 at 6 00 38 am" src="https://user-images.githubusercontent.com/4040039/53449886-e6c7dd80-3a55-11e9-8527-79e502782cf8.png">

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/1653
