### ISSUE TITLE
`Pending Open` breaks line in Next branch

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#1649]
`Pending Open` breaks into two lines in the next branch. If possible we should fix it so there is no line break

<img width="427" alt="screen shot 2019-02-27 at 6 04 58 am" src="https://user-images.githubusercontent.com/4040039/53449937-05c66f80-3a56-11e9-93de-a6aba137fd52.png">

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/1658
