### ISSUE TITLE
Currency selector is unusable for non-active channels in the channel summary view

### ISSUE THREAD

**Issue by mrfelton** [LN-Zap/zap-desktop#1672]
## Description

The currency selector is unusable for non-active channels in the channel summary view. It displays at a very low opacity and is cut off by lower items in the list.

## Expected Behavior

Currency selector should be easy to see and use.

## Actual Behavior

Dropdown is hard to read due to low opacity, and it gets cut off by lower items in the list.

![image](https://user-images.githubusercontent.com/200251/53624199-b58b1100-3bff-11e9-98d5-f528c440b793.png)

## Possible Fix

Adjust opacity, z-index etc.

## Steps to Reproduce

Try to use the currency selector from a channel summary view item on a non-active channel.

## Your Environment

- Zap version: 0.x.4
- Operating System and version: Mac

**Comment by korhaliv** [comment]
@mrfelton Similar issue in card list too

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/1675
