### ISSUE TITLE
Transaction modal showing unconfirmed when there are confirmations

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#1683]
I have a transaction that has 4 confs but is showing `Status: Unconfirmed`. Screenshots below:

<img width="902" alt="screen shot 2019-03-02 at 12 30 21 pm" src="https://user-images.githubusercontent.com/4040039/53677193-16d9df80-3ce7-11e9-8910-40c23d95adb6.png">

<img width="1063" alt="screen shot 2019-03-02 at 12 32 20 pm" src="https://user-images.githubusercontent.com/4040039/53677198-3f61d980-3ce7-11e9-85c5-8fa042733f78.png">

**Comment by mrfelton** [comment]
I don't think there is currently there is no way to receive updates to transactions from lnd directly.

In the `master` branch of lnd, there is a new `ChainNotifier` RPC service that can allow clients to subscribe to receive updates relating to transactions, and to the blockchain more generally.

See https://github.com/lightningnetwork/lnd/blob/master/lnrpc/chainrpc/chainnotifier.proto

This RPC api is currently only enabled in development builds with a special build tag enabled, so it's not something that is currently widely available to build against.

The only reliable way for us to get these updates currently would be to periodically fetch the list of all transactions using `GetTransactions`, and use the result to update our dataset. This is less than ideal as it would introduce yet more spamming of the lnd node.

Note, you can force an update by clicking the `refresh` button in the activity list.

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/1711
