### ISSUE TITLE
I should be able to see the closing transaction id for channels that are in the process of closing

### ISSUE THREAD

**Issue by mrfelton** [LN-Zap/zap-desktop#1687]
## Detailed Description

When waiting for a channel to close, you want to be able to access at the details of the closing transaction so that you can track it's progress more easily.

Currently we show the funding transaction id, but not the closing transaction id.

## Context

Channel UI

## Possible Implementation

Show the closing transaction id on the channel detail page for transactions that are in the process of closing.

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/1695

**Comment by dorothy617** [comment]
so what is the solution transaction is in closing but shows no closing transaction just stuck in limbo any way to refresh it ?

channels closing but no on chain payment is made how to resolve this?
