### ISSUE TITLE
Support bitcoin URI scheme (BIP 21)

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#1692]
We should support the Bitcoin URI scheme specified in BIP 21 (https://github.com/bitcoin/bips/blob/master/bip-0021.mediawiki) so you can click to pay an LN invoice or click to pay an on-chain invoice (most current merchants offer these now). I paid for my flight today with Zap on-chain and I had to copy the address and amount manually, couldn't click the "Open in wallet" link

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/1724
