### ISSUE TITLE
Add additional suggested nodes for testnet

### ISSUE THREAD

**Issue by mrfelton** [LN-Zap/zap-desktop#1702]
## Detailed Description

Ensure there are 6 suggested testnet nodes and ensure that each one has a valid image hosted on www.zap.jackmallers.com (same as mainnet)

## Context

The feed at http://zap.jackmallers.com/api/v1/suggested-peers only has 1 node for testnet, and the image is broken.

**Comment by JimmyMow** [comment]
Updated: http://zap.jackmallers.com/api/v1/suggested-peers

HTLC.me and ZigZag don't have downloadable logos, so I used a black gradient placeholder for now:

<img width="900" alt="Screen Shot 2019-03-11 at 5 06 27 PM" src="https://user-images.githubusercontent.com/4040039/54158048-0a106680-4420-11e9-8f65-45050324d550.png">

**Comment by brandoncurtis** [comment]
@JimmyMow is there a place to PR directly into this suggested list?

For the Testnet version of https://ion.radar.tech we host this node: `03d5e17a3c213fe490e1b0c389f8cfcfcea08a29717d50a9f453735e0ab2a7c003@tbtc.ion.radar.tech:9735`

Text can be `Radar ION`, icon can be cut from this: https://ion.radar.tech/images/image-hero.png

**Comment by JimmyMow** [comment]
@brandoncurtis currently there is not. Ideally, we have a web interface for this. I will manually add `Radar ION` to the testnet list. Feel free to create an issue if you'd like

**Comment by brandoncurtis** [comment]
Thanks @JimmyMow!  We also have a Mainnet node at `0318070901e08df311cdc6cdb8a0b4a43a3690c5b32d1fb9d8e99d1a625a65e5f2@btc.ion.radar.tech:9735`.

I'll create an issue re:venue for self-service addition to this list.
