### ISSUE TITLE
Remove "pinwheel" that shows in the amount field of the pay/request form

### ISSUE THREAD

**Issue by mkehlmann** [LN-Zap/zap-desktop#171]
Get rid of the pinwheel arrows that show next to the amount field in the pay/request form.  Seen on Windows/Ubuntu for me.  This was reported by a couple other users as well.

![pinwheel](https://user-images.githubusercontent.com/4022410/34756168-c560510e-f57d-11e7-833d-07926b5a91e1.png)

**Comment by mkehlmann** [comment]
Should be an easy css fix as noted by Austin Pearce in slack.  I should have a pull request ready in a bit.

**Comment by FrimJo** [comment]
I'm on it, added a fix using [Can I hide the HTML5 number input’s spin box?](https://stackoverflow.com/a/4298216)
<img width="381" alt="skarmavbild 2018-01-10 kl 10 45 05" src="https://user-images.githubusercontent.com/4533443/34766016-61b01c72-f5f3-11e7-9679-c5939aba8113.png">
