### ISSUE TITLE
[typo]2 non-critical & non-breaking component name typos

### ISSUE THREAD

**Issue by thedon-chris** [LN-Zap/zap-desktop#1720]
## Description
During my translation work of Spanish JSON I discovered 2 small typos on the component names. These class titles are not breaking anything because the typo persists across all use of the app. 

Although these are such a petty typo, I thought I should bring it up incase it creates issues in the future :)

`components.Contacts.SubmitChannelForm.duplicate_warnig` should be `components.Contacts.SubmitChannelForm.duplicate_warning`

`components.Home.create_wallet_promot` should be `components.Home.create_wallet_prompt`

https://github.com/LN-Zap/zap-desktop/blob/master/app/translations/es-ES.json#L88
https://github.com/LN-Zap/zap-desktop/blob/master/app/translations/es-ES.json#L96

## Possible Fix

Rename component name and correct down to use of component.

If this is worth correcting, I can take this issue.

**Comment by thedon-chris** [comment]
These are different in `next` branch, but 1 typo still remains.

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/1782
