### ISSUE TITLE
Delete wallet is not working in next

### ISSUE THREAD

**Issue by korhaliv** [LN-Zap/zap-desktop#1721]
## Description
Delete wallet button does nothing when pressed

## Expected Behavior
Should delete wallet

## Actual Behavior
Delete button does nothing

## Possible Fix
Issue is caused by 
https://github.com/LN-Zap/zap-desktop/blob/next/app/reducers/wallet.js#L66
state entry which was recently moved to `settings` reducer

## Steps to Reproduce

- 1. Open wallet settings
- 2. Press delete wallet
- 3. Press delete button

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/1722
