### ISSUE TITLE
Active wallet settings don't show up after logout in next

### ISSUE THREAD

**Issue by korhaliv** [LN-Zap/zap-desktop#1723]
## Description
Active wallet settings don't show up after logout. 

## Expected Behavior
After logging out user should see active wallet settings screen

## Actual Behavior
User sees `you have no wallets` screen

## Possible Fix
This is probably caused by 
https://github.com/LN-Zap/zap-desktop/commit/c0979d614777f80a977b2139f84de38bcee13ef2#diff-e0aed3f347d566cf3db9f244ae5ed5c3L47

More specifically - corresponding state entry has moved to `settings reducer`

## Steps to Reproduce

- 1. Login into a wallet
- 2. Logout

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/1727
