### ISSUE TITLE
Unable to select theme or language in next

### ISSUE THREAD

**Issue by korhaliv** [LN-Zap/zap-desktop#1744]
## Description
Second level drop down menu in activity page is not showing up, preventing from selecting theme or language

## Expected Behavior
Should be able to select theme/language from drop down menu

## Actual Behavior
Can't select theme/language from drop down menu

**Comment by mrfelton** [comment]
Thanks for reporting - we are aware of this issue and there is a PR pending review here: https://github.com/LN-Zap/zap-desktop/pull/1738

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/1738
