### ISSUE TITLE
Improve Connection Details copy

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#1762]
I think we can improve the `Custom` option copy in the Connection Details screen found below:

![dsbhld](https://user-images.githubusercontent.com/4040039/54132514-bc2d3b80-43ea-11e9-861d-d01468d367fb.png)

It is not clear what `Custom` is and it is not the first option by default so it is presented with no context. Open to suggestions on what it should be changed to, my first proposition is `Add files` as that seems to be the standard copy when uploading files on various web services

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/1766
