### ISSUE TITLE
Update processing payment copy

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#1763]
The more I use Zap the less I feel like the second half of `Zap is processing your payment. This can take up to 01:00 min.` is helpful. This is the message we show for both on-chain and LN payments. It is true that Zap manually times out after 1 minute but I don't think it's relevant to the user tbh (especially because we aren't counting down) and for on-chain it is inaccurate. I think simply removing the `This can take up to 01:00 min.` leaving us with `Zap is processing your payment.` is fine and much cleaner. Maybe even `Processing your payment...` is even better, so the app isn't referring to itself in 3rd person.

<img width="1440" alt="Screen Shot 2019-03-11 at 10 42 45 AM" src="https://user-images.githubusercontent.com/4040039/54132787-378eed00-43eb-11e9-82e5-6da31b91d794.png">

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/1764
