### ISSUE TITLE
Support mainnet neutrino

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#1767]
Mainnet neutrino has begun public testing phase, and we should support it in my opinion. It is still extremely experimental and by definition very risky as you can still not back up your channels and there are no watchtowers or services watching the chain while clients go offline. It should be only for experimental users and people that don't mind risking funds to test the software.

I propose we duplicate the Autopilot config onboarding screen for the selection of the wallet's `Network`. See screenshot below:

<img width="900" alt="Screen Shot 2019-03-11 at 1 26 14 PM" src="https://user-images.githubusercontent.com/4040039/54145623-bcd2cb80-4404-11e9-8d5a-266e8417c96a.png">

Suggested copy is as follows:

Title: `Network`
Desc: `Select the network your wallet will be connected to.`
Warning (when a user selects mainnet): `This is experimental and not recommended. There are known issues such as lack of channel backups, lack of watchtower support, and lack of thorough testing. Losing funds is a risk and we advise users to use testnet for the time being.`

Testnet should also be the default selected option on top

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/1769
