### ISSUE TITLE
Add pending open balance to main balance

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#1770]
Right now the pending open channel balance is not factored into a users balance, resulting in money seemingly disappearing when a channel is opened. This is magnified recently when channel transactions aren't in the main activity list anymore (they now live in the `Internal` tab). See example screenshot below of the issue as I deposited 0.1BTC and my balance is half that (because I opened a channel for 0.05BTC):

<img width="903" alt="Screen Shot 2019-03-12 at 4 03 28 AM" src="https://user-images.githubusercontent.com/4040039/54184655-8b4a1680-447d-11e9-8f84-5907d0fab2d9.png">

To fix this, I propose we just add `ChannelBalance.pending_open_balance` in our total balance

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/1772
