### ISSUE TITLE
Change Node URI copy

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#1771]
Right now `LndConnect` inside of Zap Desktop is under `Node URI` tab. This copy is inaccurate as Node URI would be `pubkey@host`. People seem to be fairly familiar with LndConnect now as many LN wallets and services use it. I propose we switch the tab copy to `LndConnect`

<img width="902" alt="Screen Shot 2019-03-12 at 4 21 57 AM" src="https://user-images.githubusercontent.com/4040039/54185112-9cdfee00-447e-11e9-91a2-0631565b6a24.png">

**Comment by mrfelton** [comment]
Fixed via https://github.com/LN-Zap/zap-desktop/pull/1773
