### ISSUE TITLE
I should be able to see all of my existing autopay merchants grouped together on the autopay screen

### ISSUE THREAD

**Issue by mrfelton** [LN-Zap/zap-desktop#1778]
## Detailed Description

I should be able to see all of my existing autopay merchants grouped together on the autopay screen

Merchant cards should display in a carousel, Netflix style.

Cards should show the autopay limit that has been configured for the merchant.

## Context

Autopay

## Possible Implementation

https://zpl.io/bAZdRrq

![image](https://user-images.githubusercontent.com/200251/54194774-4d6ce280-44bd-11e9-85b9-cd1298f7137f.png)

**Comment by korhaliv** [comment]
@mrfelton @JimmyMow How do we display this pretty if autopay limit is set in `sats` while displayed in `USD` according to the mockup? Dynamic + rounding to a dollar?

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/1894
