### ISSUE TITLE
Channel form bitcoin amount too small

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#1786]
When building a `next` production build and opening a channel, the channel amount in the final summary UI is extremely small. See screenshot below:

<img width="561" alt="Screen Shot 2019-03-12 at 1 14 48 PM" src="https://user-images.githubusercontent.com/4040039/54221062-16043300-44c9-11e9-81ac-022f65e71b1d.png">

**Comment by JimmyMow** [comment]
Seems to be the same in the pay form as well:

<img width="523" alt="Screen Shot 2019-03-12 at 1 28 37 PM" src="https://user-images.githubusercontent.com/4040039/54221931-c7579880-44ca-11e9-8686-adb62998c460.png">

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/1787
