### ISSUE TITLE
Add total_limbo_balance to balance total

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#1792]
We recently added the pending open channel balance to the balance total so the users balance doesn't go down when moving funds onto LN. The same should be for limbo balance on force close. For example, if the user has one channel open and force closes it, their balance will go to zero. That would be a scary experience if they weren't clued into what's going on.

We should add the total_limbo_balance to the total balance (this data can be found in the pending channels call, see screenshot below)

<img width="883" alt="Screen Shot 2019-03-13 at 7 16 44 AM" src="https://user-images.githubusercontent.com/4040039/54275026-fbc96400-455f-11e9-8a6d-631662549e88.png">

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/1793
