### ISSUE TITLE
Network "Loading" spinner showing on pay/request form

### ISSUE THREAD

**Issue by mkehlmann** [LN-Zap/zap-desktop#180]
Steps to reproduce:

1. Open the network tab
2. While the network is being loaded, click the "Pay" or "Request" buttons.

You will see the loading spinner even though the form modal should cover it up.

![networkspinneronpayform](https://user-images.githubusercontent.com/4022410/34844799-86f65cec-f6c7-11e7-9f8f-25a1ff836ce1.png)

**Comment by JimmyMow** [comment]
fixed in #183
