### ISSUE TITLE
Manually bootstrap local nodes graph on fresh sync

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#1815]
Through recent testing, local neutrino nodes have a hard time bootstrapping the network graph at first. Not many peers and unable to find edges.

I suggest we make a `connectPeer` call to some well known/connected nodes to help get these new nodes off the ground. Only on fresh sync for local wallets, as LND will try to reconnect and keep a connection with previously established peers after a first connection, so no need to do it every single time a user launches the app.

We can use our existing suggested nodes list for the time being that we use for the suggested channels list.

**Comment by mrfelton** [comment]
@JimmyMow I created a PR to do this, but in my testing I found that it isn't needed. With latest version of lnd (which we now bundle) the bootstrapping happens automatically as soon as the sync has completed. Within a minute, the node graph already knows about over 150 nodes, and this continues to grow very quickly so it's possible to start creating channels very soon after opening the app already.

**Comment by JimmyMow** [comment]
Ok cool. I will close this for now then @mrfelton
