### ISSUE TITLE
Handle if LND process exits

### ISSUE THREAD

**Issue by brandoncurtis** [LN-Zap/zap-desktop#1824]
## Description

Zap takes no action if LND crashes.

## Expected Behavior

Zap should take one of these actions when LND crashes:

1. restart LND (newest versions of LND can continue to sync the channel graph if the wallet is locked)
2. alert the user (I believe there is an alert, but I believe it disappears after only a few seconds. the alert should persist until it is dismissed)
3. send the user back to the wallet selection/login screen

## Actual Behavior

LND crashes.  The app is now totally broken, but there is no indication that LND has crashed.

## Steps to Reproduce

Leave Zap open and wait for LND to spontaneously crash, or `kill` it.

## Your Environment

- Zap version: v0.4.0 58188fb184621d23bd25f912da62360c1b33a1f5 (running self-packaged build)
- Operating System: Ubuntu Linux

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/1849
