### ISSUE TITLE
Unit choice mistakenly changes "Bitcoin Address" on node info screen

### ISSUE THREAD

**Issue by brandoncurtis** [LN-Zap/zap-desktop#1843]
Zap v0.4.4 prerelease

On e.g. Bitcoin testnet with satoshis selected:

![image](https://user-images.githubusercontent.com/2591290/54547019-2e110200-4962-11e9-8457-2895789e0c82.png)

(assuming it should read "tBTC address")

Same thing with Litecoin.

**Comment by mrfelton** [comment]
Fixed via feat/lnd-crash-dialog

**Comment by mrfelton** [comment]
Fixed via https://github.com/LN-Zap/zap-desktop/pull/1850
