### ISSUE TITLE
Zap hangs on loading screen if gRPC version is unknown

### ISSUE THREAD

**Issue by tehelsper** [LN-Zap/zap-desktop#1848]
Zap will hang on the loading screen if it cannot determine the gRPC version. Unfortunately, this appears to occur whenever LND has been build from source.

## Description

See above.

## Expected Behavior

See possible fixes.

## Actual Behavior

The loading screen hung and I could not interact with Zap. Closing and re-opening Zap immediately put me back in this state.

## Possible Fix

Two possible solutions:
- Prevent the stuck loading screen and display an error to the user.
- Attempt to guess at the gRPC version and display errors when RPC calls fail.

## Steps to Reproduce

1. Open Zap
2. Connect to custom LND node that was built from source
3. Zap will now hang

Error message:
Unable to determine exact gRPC version: Error: Could not get version from version string "0.5.2-99-beta commit=queue/v1.0.1-76-gec62104accc08d22f967b03a31ca564055624886"

## Context

This bug completely prevented connecting to the LND node and then made zap unresponsive.

## Your Environment

I saw this in Zap version 0.3.4 on OSX and versions 0.3.4 and 0.4.0 beta.

**Comment by otaviobps** [comment]
Same bug here.

Updated LND to latest version: 0.5.2-99-beta commit=queue/v1.0.1-109-g9f6a1403e9773ba97ec0e9fdee3b654789970d3a

Launched Zap, entered my LND address, tls.cert and admin.macaroon. Zap hangs on loading screen.

Log shows: `Unable to determine exact gRPC version: Error: Could not get version from version string "0.5.2-99-beta commit=queue/v1.0.1-109-g9f6a1403e9773ba97ec0e9fdee3b654789970d3a"`

**Comment by mrfelton** [comment]
This issue will be resolved in our next upcoming release (due any day now). Until then, you can build that app yourself from the master branch to get a version of the app with the relevant fixes. Ping me in Slack if you need a hand with that.

**Comment by mrfelton** [comment]
@otaviobps please can you confirm wether this issue is resolved for you in version `0.4.0`? Thanks.

**Comment by otaviobps** [comment]
Yes @mrfelton, it's working fine!

**Comment by mrfelton** [comment]
Awesome - thanks for confirming
