### ISSUE TITLE
Zap crashes only when sending to blockstream

### ISSUE THREAD

**Issue by th3geek** [LN-Zap/zap-desktop#1875]
Using zap wallet on windows to interface with an lnd instance running on ubuntu. Sending payments are normally fine, but whenever I pay an invoice from blockstream zap just goes blank. The blue window is still there, but the program must be stop and re-started to get working again. This last time, I can't even get zap to load again. This has happened several times now (only with broadcasting a message from blockstream). Interesting thing is, everytime this has happened, the payment still seems to go through and it shows up on my transaction list after reloading the program. I'm going to reboot and see if I can even get the program to re-load again.

**Comment by th3geek** [comment]
Alright, so I just rebooted and figured out why I couldn't get zap to reload at all (my lnd machine wasn't connected) BUT, the original problem still stands. After reloading zap, I sent another test payment to blockstream and again, the zap client hung and I had to close it out (which happened no problem). On re-load the transaction was shown as being sent in the history, so the payment is going through, it's likely some UI issue. No idea why it only does it for blockstream and nowhere else.

**Comment by JimmyMow** [comment]
@th3geek what version of Zap are you using?

**Comment by th3geek** [comment]
0.3.4-beta   ... And here's where I'm trying to send (only costs a few sats to test)  https://blockstream.com/satellite-queue/

**Comment by mrfelton** [comment]
@th3geek are you able to test this with the latest code in the master branch?

**Comment by mrfelton** [comment]
Please can you upgrade to Zap 0.4.0 and let us know if the issue persists. Thanks.

**Comment by th3geek** [comment]
That fixed it. Thank you very much!
