### ISSUE TITLE
Closing the app window when on full screen will leave a black screen

### ISSUE THREAD

**Issue by otaviobps** [LN-Zap/zap-desktop#1893]
## Description

When the app is running on full screen mode, on OSX, exiting the app will bring a black screen and the app will continue to run.

## Expected Behavior

The app should close.

## Actual Behavior

The app won't close, instead a black screen is shown

## Possible Fix
I'm not a JS dev, so I really don't know how it's possible to fix it.

## Steps to Reproduce

- 1. Open the app
- 2. Switch to full screen
- 3. Exit the app

## Your Environment

- Zap version: v.0.4
- Operating System and version: Mac OSX Mojave 10.14.3

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/28715087/54949996-15cf5300-4f1f-11e9-9e18-a8b355de3e09.png">

**Comment by mrfelton** [comment]
Hi @otaviobps - I've been unable to reproduce this issue. Does it reliably reproduce for you?

If so, please can you provide exact steps to reproduce (have you created a wallet? are you connecting to your own node or using the built in neutrino client? are you logged into a wallet when you quit? is the app in the middle of syncing when you quit? etc etc). I want to understand exactly what state your app is in when this happens.

Perhaps you could provide a video that shows exactly what you do to make this happen?

Thanks!

**Comment by otaviobps** [comment]
Hi @mrfelton, I've noticed this bug is not exclusively to your app, a few others have the same behavior. It doesn't mind the state the app is, if maximize it and close it, the bug happens.

I'm attaching the video

![ZapBug](https://user-images.githubusercontent.com/28715087/54967967-c3f6ef00-4f57-11e9-8a70-5fea0fb35f66.gif)

**Comment by mrfelton** [comment]
Thanks @otaviobps . I can reproduce this and will look into it. I guess it's probably an Electron issue rather than anything Zap specific.

One thing to note is that clicking the red close button does not exit the app, it only closes the window. The app in only minimised and continues to run. It will still be in your dock, and can be maximised again by clicking on the app in the dock.

To actually exit the app you should choose `Quit` from the `Zap` menu, or press `cmd+q`

**Comment by otaviobps** [comment]
> To actually exit the app you should choose `Quit` from the `Zap` menu, or press `cmd+q`

Yes, I noticed this. However the behavior of the app is strange when you click on the red close button if it's maximized. When you open again the app, it looks very small, like it's in the video. Yes, probably is something with Electron
