### ISSUE TITLE
UI: Manual Add Contact Submit Button doesn't respond if the format is incorrect

### ISSUE THREAD

**Issue by waseem999** [LN-Zap/zap-desktop#191]
As a first time user this was a bit confusing to me, and I assumed my connection was broken because there was no feedback when I was trying to add a NodeID without an "@ip:port."  I'd like to add a simple error message under the form input.

**Comment by JimmyMow** [comment]
Awesome. I'll assign this to you then. We can talk in slack about design details 😃
