### ISSUE TITLE
Only able to open 1 channel without re-starting program

### ISSUE THREAD

**Issue by th3geek** [LN-Zap/zap-desktop#1912]
Can open a new channel just fine (slick new interface, btw), but when trying to open ANOTHER channel, the "next" button at the bottom of the "open a channel" window is greyed out. After exiting the program and re-starting, it works fine and is able to establish another channel, but again, only 1.

- Zap version: 0.4.0-beta
- Operating System and version: up to date windows 10, connecting to an LND instance running on ubuntu 12

**Comment by korhaliv** [comment]
Thanks for reporting. I was able to reproduce this one too.
