### ISSUE TITLE
UI Bug: Dropdown menus visible over modal overlay

### ISSUE THREAD

**Issue by dfattlar** [LN-Zap/zap-desktop#193]
Steps to reproduce:

1. Open Wallet or Contact Tab
2. Open Filter Dropdown
3. Activate Modal (Contact -> Add Contact, Wallet -> Receive Payment)
4. Observe the Filter Dropdown elements are still visible and clickable over the modal overlay and sometimes over the modal itself.

<img width="486" alt="screen shot 2018-01-15 at 4 17 56 pm" src="https://user-images.githubusercontent.com/4843270/34966686-4f791a54-fa12-11e7-8348-a249ff0185fe.png">
<img width="594" alt="screen shot 2018-01-15 at 4 24 17 pm" src="https://user-images.githubusercontent.com/4843270/34966691-51d758e2-fa12-11e7-85dc-3e813f5d170d.png">
<img width="540" alt="screen shot 2018-01-15 at 4 31 04 pm" src="https://user-images.githubusercontent.com/4843270/34966695-555b1ac6-fa12-11e7-80a2-055792b60ba2.png">

**Comment by JimmyMow** [comment]
#194 

closing
