### ISSUE TITLE
Zap mobile from public IP and RTL 

### ISSUE THREAD

**Issue by walterkok** [LN-Zap/zap-desktop#1945]
Hi I built the bitcoin/ lnd node on raspberry PI (I am Stadicus compliant :-)) and also use the RTL user interface (saubyk)

Got the. Zap IOS app to work on my local network at home, with the following setting in lnd.conf

restlisten=0.0.0.0:8080 # for RTL
rpclisten=0.0.0.0:10009
tlsextraip=0.0.0.0

I used to be able to access with Zap IOS my pi remotely ( with tlsextraip=publicipaddress ) and portforward of 10009 to my Pi, but than RTL does not work

Let me know of a route to a solution you can see, Also tries to open two tlsextraip but that did not fly

**Comment by feitsau** [comment]
I had a similar problem trying to get Joule and Zap iOS to both work. I think the problem was similar to yours that if I added both tlsextraip=0.0.0.0 and =externalipaddress then only one of them would work. What I found is that when looking at my tls.cert file in a viewer it did not contain both ipaddresses. No idea why this happens but as soon as I removed one of the two lines in lnd.conf it would work.

**Comment by mrfelton** [comment]
`tlsextraip=0.0.0.0` is incorrect. You should add a `tlsextraip` entry for every IP address that you want to be able to connect with. Eg, if you want to conenect to youer node using `1.2.3.4' and '192.168.0.100` then you should add the following entries:

```
tlsextraip=1.2.3.4
tlsextraip=192.168.0.100
```

After making the changes, you should delete your `tls.key` and `tls.cert` files and restart the node. Then, you must update your connections params to use the new tls cert.

**Comment by walterkok** [comment]
hi, I followed your suggestion but it still does not work from externally accessing (wallet does not connect, have port 10009 forwarded on my router

tlsextraip=external_ip
tlsextraip=internal_ip
rpclisten=0.0.0.0:10009
restlisten=0.0.0.0:8080
# tlsextraip=0.0.0.0
Wallet does connect from within WIFI but not from public internet

**Comment by mrfelton** [comment]
@walterkok please hop into Slack and ping me there. Will be far easier to debug that way.
