### ISSUE TITLE
UI: Additional Input Validation on Bitcoin Amounts

### ISSUE THREAD

**Issue by helgabutters** [LN-Zap/zap-desktop#196]
Additional input validation on bitcoin amounts should be done in the UI to prevent invalid input. Some notable examples that should not be allowed are:

- `-`
- `+`
- `e`
- multiple periods

Two pages are affected:

[RequestForm.js]( https://github.com/LN-Zap/zap-desktop/blob/master/app/components/Form/RequestForm.js)  - Input type is "text"

[PayForm.js](https://github.com/LN-Zap/zap-desktop/blob/master/app/components/Form/PayForm.js) - Input type is "numbers"

**Comment by helgabutters** [comment]
[ContactsForm.js](https://github.com/LN-Zap/zap-desktop/blob/65a71dd173c510f39cd67e25b4357c7992aa2f76/app/components/Contacts/ContactsForm.js#L196) as well

![text](https://user-images.githubusercontent.com/8001978/35035816-71a02742-fb40-11e7-9a31-f403d0248e5e.png)

**Comment by mrfelton** [comment]
This was addressed in https://github.com/LN-Zap/zap-desktop/pull/705
