### ISSUE TITLE
UI Wallet: Consistent Sorting

### ISSUE THREAD

**Issue by helgabutters** [LN-Zap/zap-desktop#197]
In the wallet, the sorting of transactions in each of the sub-menus is not consistent:

- All Activity: Newest First
- LN Activity: Newest First
- LN Payments: Oldest First
- LN Invoices: Oldest First
- On-Chain Activity: Oldest First

I think newest first makes the most sense as the default sort so the bottom three in the above list would need to be changed.

**Comment by JimmyMow** [comment]
Nice find. I'll assign this to myself

**Comment by Empact** [comment]
This is fixed in master.
