### ISSUE TITLE
I should be able to enable automated backups of channel state data

### ISSUE THREAD

**Issue by mrfelton** [LN-Zap/zap-desktop#1971]
## Detailed Description

I should be able to enable automated backups of channel state data to Dropbox so that I can more easily recover channel state data in the event of needing to restore.

## Context

Static Channel Backups (new lnd feature)

## Possible Implementation

Build out Dropbox integration and provide an easy way for users to enable automated, realtime backups of channel state data to a designated Dropbox account.

**Comment by jrosco** [comment]
Backing up to your local file system would be a better choice. You can just dump the backup into the Dropbox folder, this way you could also dump into other cloud syncing apps like google drive etc. Since 0.6.0 now support backup/restore it shouldn't be to trivial. Encryption would be nice.

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/2233
