### ISSUE TITLE
Improve fee estimation

### ISSUE THREAD

**Issue by mrfelton** [LN-Zap/zap-desktop#1972]
## Detailed Description

Current fee estimations come form https://bitcoinfees.earn.com/api/v1/fees/recommended which provides fee estimates on the high end in order to guarantee settlement within the specified time.

We'd like to use something the provides lower rates / lower probability.

## Possible Implementation

Consider using https://api.lightning.community/#estimatefee (new in lnd 0.6) and falling back to earn.com if that api isn't available.

**Comment by ossel** [comment]
I wanted to open a channel and even the slow option was 150 sats/Byte. (According to blockstream explorer still overpaying by 450%) with Zap-win32-v0.4.1-beta.
I actually did not care if the channel was funded now or in a week.
A possibility to enter a custom fee would be really nice. A custom radio button would do the job and it would be nice if the resulting fee costs would be displayed in dollar. 
It´s nice to see how you impove the product release by release. 
How can I send you a tip via lightning?

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/2098
