### ISSUE TITLE
New Channel Metric: Activity

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#1973]
It would be cool to have a number metric for the best channels. This can get complex, but for starters, I propose [`(sent + received)/capacity`](https://lightninglayer.com/channels)

Would be nice if this was shown in the channel preview, detail page, and if I can organize my channels by the most active

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/2331
