### ISSUE TITLE
Ability to cancel wallet connection attempt

### ISSUE THREAD

**Issue by P0u1us** [LN-Zap/zap-desktop#1989]
When ZAP wallet is setup and connecting (or with wrong settings: not connecting); then there is no ability to change the connections settings; the only solution is to fully uninstall and manually remove data folders (which are left after uninstall).

## Detailed Description
Would be great to have a simple ability to change the connection settings on an already installed ZAP wallet.

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/2062
