### ISSUE TITLE
UI: Multiple Notifications on Contact Add

### ISSUE THREAD

**Issue by helgabutters** [LN-Zap/zap-desktop#199]
When adding a new contact through "Contacts" > "+ Add" after successfully sending the funding transaction you get two on-chain transaction notifications instead of just one.

![twonotifications](https://user-images.githubusercontent.com/8001978/35034209-65395aa0-fb3b-11e7-9a45-cf6de8ab0bda.png)

**Comment by JimmyMow** [comment]
Hmm, another one I have to reproduce locally. I think our overall notification system is really poor and needs to be re-thought. Let's also discuss in slack as this has a lot to do with UX/UI

**Comment by mrfelton** [comment]
This issue was resolved a while through of https://github.com/LN-Zap/zap-desktop/pull/575.
