### ISSUE TITLE
ZAP channel open to Eclair; mainnet;  0 remote balance

### ISSUE THREAD

**Issue by wdey** [LN-Zap/zap-desktop#1991]
Open channel between ZAP and Eclair; mainnet; capacity 1mBTC; ZAP and Eclair (and BTC core node) on same node.
I see the channel online with 0 remote and 1 mBTC balance.
Sending outgoing works ok; is there a feature, that lets me configure non zero remote balance in the channel creation menue ?

**Comment by JimmyMow** [comment]
@wdey right now we don't allow channel opens pushing a balance to the remote side. To solve this you can open another channel the other way, or use the command line to push a remote balance
