### ISSUE TITLE
Missing host string after creating new wallet connection with Node Launcher

### ISSUE THREAD

**Issue by mrfelton** [LN-Zap/zap-desktop#1997]
## Description

Missing host string after creating new wallet connection with Node Launcher

## Expected Behavior

Host should be set properly in the wallet config.

## Actual Behavior

Host value is empty.

## Steps to Reproduce

1. Launch the node launcher bitcoin and lnd nodes
2. Click the `Configure Zap Desktop` button to launch Zap
3. Confirm host as `127.0.0.1`
4. Log out of the wallet
5. Notice that the Host is blank.
6. Attempt to enter a host value and save
7. App crashes with `Uncaught TypeError: Cannot read property 'split' of undefined at split (webpack:/renderer/components/Util/WalletName.js:11)`

![image](https://user-images.githubusercontent.com/200251/55892782-410ca000-5bb7-11e9-9306-76370167e0f3.png)

## Context

lndconnect

## Your Environment

- Zap version: 0.4.0
- Operating System and version: Mac / Windows

**Comment by mrfelton** [comment]
This looks to be because Node Launcher are using old style lndconnect links, eg:

```
lndconnect:?cert=~/.lnd/tls.cert&macaroon=~/.lnd/admin.macaroon&host=example.com:10009
```

New style links work correctly:

```
lndconnect://example.com:10009?cert=~/.lnd/tls.cert&macaroon=~/.lnd/admin.macaroon
```

**Comment by JimmyMow** [comment]
@mrfelton let's create an issue within the Node Launcher repo and close this?

**Comment by mrfelton** [comment]
@JimmyMow I put a fix in place for this: https://github.com/LN-Zap/zap-desktop/pull/2000

Also created issue for Node Launcher to update their link format: https://github.com/lightning-power-users/node-launcher/issues/272

Once other thing we should probably do is a migration script to delete any wallet configs with missing host info. I'll do another PR for that.
