### ISSUE TITLE
Javascript error when running `npm run dev`

### ISSUE THREAD

**Issue by fresheneesz** [LN-Zap/zap-desktop#2]
I get the following error when I try to run the dev client with `npm run dev`:

![zap js error](https://user-images.githubusercontent.com/149531/29401821-8bc0ca9a-82e7-11e7-9e4f-3b4d4b625071.png)

Running on windows 8.1 node v7.10.0

**Comment by jackmallers** [comment]
`app.doc` seems to be undefined. 

Did you run `yarn` after cloning the repo and did you have any trouble with that?

**Comment by fresheneesz** [comment]
I did run `yarn` - seemed to go through fine. I first ran npm install for about 20 seconds before I realized that wasn't the thing to do. So I killed it midway - might that have caused a problem?

**Comment by fresheneesz** [comment]
Bleh, I'm sure this is because I don't have btcd and lnd up. But I ran into issues running them, so I'll just wait until this installation process is a bit easier.

**Comment by jackmallers** [comment]
Ah! So you should only use one of the two, so pick either `yarn` or `npm` to manage your dependencies @fresheneesz

**Comment by funyug** [comment]
Seems like that app.dock.setIcon() is only available for macOS. This needs to be fixed @jackmallers

**Comment by jackmallers** [comment]
Reopened, I will look into this now. Thanks @funyug

**Comment by callmekurisu** [comment]
confirm the app.dock.setIcon() is not available on Ubuntu 16.04. Commenting out allows the wallet to be launced.

**Comment by jackmallers** [comment]
commented out for now, will revisit later. not that important atm

**Comment by jackmallers** [comment]
Gonna close this for now since it is no longer an issue
