### ISSUE TITLE
[Feature] BOLT #11: Add 'lightning:' and fallback 'bitcoin:' URI schemes

### ISSUE THREAD

**Issue by helgabutters** [LN-Zap/zap-desktop#200]
[BOLT #11 - Encoding Overview](https://github.com/lightningnetwork/lightning-rfc/blob/master/11-payment-encoding.md#encoding-overview) details that the lightning invoice URI schemes should be 'lightning:' and fallback to 'bitcoin:'

These URI schemes should be added as valid in the [PayForm](https://github.com/LN-Zap/zap-desktop/blob/65a71dd173c510f39cd67e25b4357c7992aa2f76/app/components/Form/PayForm.js#L97)

**Comment by JimmyMow** [comment]
Nice, will assign this to myself

**Comment by mrfelton** [comment]
Close via https://github.com/LN-Zap/zap-desktop/pull/3131
