### ISSUE TITLE
Wallet Refresh for Lightning Transactions

### ISSUE THREAD

**Issue by helgabutters** [LN-Zap/zap-desktop#201]
There is currently no way for the "Wallet" to be refreshed/automatically check for invoices that may have been paid by the underlying `lnd` server (if the payment was not initiated in the Zap UI). The example below shows that nothing is seen in the wallet after the payment in the console has been successfully sent.

![pre-walletrefresh](https://user-images.githubusercontent.com/8001978/35038741-ae3116b8-fb49-11e7-96b7-0d6adb425fe1.png)

At this point the sub-menus "LN Activity", "LN Payments", etc do not refresh the information and the only way to update is click "Contacts",  "Network", etc. and then back to "Wallet"

**Comment by JimmyMow** [comment]
Hmm really? I'll try and reproduce this locally but it should update automatically.

**Comment by mrfelton** [comment]
I tried to reproduce this issue but it seems to work as expected, at least in the current version of the app. @helgabutters is this issue reproducible for you? From your screenshot it looks like you are using an older version of the app. Can you test with the latest version of the app from the mater branch please?

**Comment by mrfelton** [comment]
The latest release includes the ability to manually refresh your activity list (transactions, invoices, etc).
