### ISSUE TITLE
"Please select" on dropdowns

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#2017]
When on the next branch and first launching the app, my dropdowns show "Please select", even though they are already selected to "All"

<img width="856" alt="Screen Shot 2019-04-12 at 5 49 20 PM" src="https://user-images.githubusercontent.com/4040039/56070039-7cd86e80-5d4b-11e9-87a0-f0735dbefedb.png">
<img width="147" alt="Screen Shot 2019-04-12 at 5 50 25 PM" src="https://user-images.githubusercontent.com/4040039/56070040-7f3ac880-5d4b-11e9-909a-3baa140f2962.png">

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/2044
