### ISSUE TITLE
Add fallback address to LN invoices

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#2021]
Our LN invoices don't include a fallback address. The future UX for LN is to opt to pay on-chain if there are capacity issues with paying over Lightning. We should support this ourselves and encourage others to do the same. For starters, we should pass a fallback address to our newly generated LN invoices for users.

This can be accomplished by passing `fallback_addr` to the `addinvoice` API call: https://api.lightning.community/#addinvoice

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/2697
