### ISSUE TITLE
Utilize new --neutrino.feeurl config for neutrino clients

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#2022]
You can now pass a `feeurl` config argument to neutrino that will be used to do fee estimates. The URL is expected to have a specific format, that can be seen by Lightning Labs URLs here:

https://nodes.lightning.computer/fees/v1/btc-fee-estimates.json

https://nodes.lightning.computer/fees/v1/btctestnet-fee-estimates.json

**Comment by bolatovumar** [comment]
@JimmyMow @mrfelton can someone explain what this actually does if this argument is passed in? Seems like it would be really easy to add this but I don't understand what it will do. I googled around and only found this:

https://github.com/lightninglabs/lightning-app/issues/1043

https://github.com/lightninglabs/lightning-app/blob/master/public/lnd-child-process.js#L92

**Comment by mrfelton** [comment]
feeurl is used in the latest version, so closing this.

https://github.com/LN-Zap/zap-desktop/blob/33fc554d37c0aa5a748c95cd8936412c82061600/services/neutrino/neutrino.js#L374-L379
