### ISSUE TITLE
Folder Icon misaligned

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#2024]
It seems that there is a style bug that results in the folder icon being vertically misaligned in the `Files` form of `Connection Details`

<img width="531" alt="Screen Shot 2019-04-13 at 12 35 09 AM" src="https://user-images.githubusercontent.com/4040039/56075194-2cc9ce00-5d84-11e9-8b4b-4f1adf13c2c7.png">

**Comment by korhaliv** [comment]
@JimmyMow Hey! Is this in `master` ? I believe I've already fixed that in next a couple of days ago.

**Comment by JimmyMow** [comment]
@korhaliv oh ok. this is in `0.4.1`. If a fix is in, I'll close this
