### ISSUE TITLE
Easy and accesible way to see on chain vs LN vs total balance.

### ISSUE THREAD

**Issue by pedromvpg** [LN-Zap/zap-desktop#2031]
## Context

Cloud confuse some users but I think its important as it would save some hassle in going back to the dashboard, pulling the address, sending some Bitcoin, and then go back to creating the channel.
Users would always be aware of their balance in more detail. On chain vs LN Bitcoin.

## Possible Implementation

![Frame 2](https://user-images.githubusercontent.com/807505/56082751-7fd66c00-5dea-11e9-8294-f3d99e50d73b.png)

- Zap version: 0.4.1
- Operating System and version: Mac OSX

**Comment by xultima** [comment]
Maybe (pending: xxx sats) beside?

**Comment by JimmyMow** [comment]
This has been addressed in the `next` branch and will be available in the next major release.

In the new navigation, when clicking on the channels section you can a summary overview:

![channel_nav_menu](https://user-images.githubusercontent.com/4040039/56096346-9e9d3700-5eac-11e9-97e8-5d5c4e622c27.png)

**Comment by JimmyMow** [comment]
There are improvements currently in our `next` branch that will be included in our next major release. New navigation, and when clicking on the `Channels` section you are displayed with a summary of funds and total channels (pending balance shows if there is a pending balance):

<img width="901" alt="Screen Shot 2019-04-14 at 2 09 41 PM" src="https://user-images.githubusercontent.com/4040039/56097825-f80e6180-5ebe-11e9-973c-c43c2d9a6560.png">

**Comment by JimmyMow** [comment]
Going to close this as it's already merged into the code base
