### ISSUE TITLE
Problem sending request

### ISSUE THREAD

**Issue by wdey** [LN-Zap/zap-desktop#2036]
I have a open channel between ZAP und <wdey> (Eclair); local and remote balance are ok. Neverthess I get the following very complex error message:

There was a problem sending your payment. Unable to route payment to destination: TemporaryChannelFailure(update=(*lnwire.ChannelUpdate)(0xc00b98cd10)({ Signature: (lnwire.Sig) (len=64 cap=64) { 00000000 f1 3e f7 11 4a 3e 19 ad 61 78 37 11 be 56 c6 51 |.>..J>..ax7..V.Q| 00000010 f5 4d 9e 71 a6 32 e8 ce 5b 52 fc bd 1b 4f 37 d0 |.M.q.2..[R...O7.| 00000020 7c c4 42 a6 db 2f 44 82 d3 82 49 65 e9 28 0c 63 ||.B../D...Ie.(.c| 00000030 ce a5 a2 e3 22 0b 52 62 23 5d d0 0c 19 ef d3 4b |....".Rb#].....K| }, ChainHash: (chainhash.Hash) (len=32 cap=32) 000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f, ShortChannelID: (lnwire.ShortChannelID) 570632:1579:1, Timestamp: (uint32) 1555228351, MessageFlags: (lnwire.ChanUpdateMsgFlags) 00000001, ChannelFlags: (lnwire.ChanUpdateChanFlags) 00000000, TimeLockDelta: (uint16) 144, HtlcMinimumMsat: (lnwire.MilliSatoshi) 1 mSAT, BaseFee: (uint32) 1000, FeeRate: (uint32) 1, HtlcMaximumMsat: (lnwire.MilliSatoshi) 376753000 mSAT, ExtraOpaqueData: ([]uint8) <nil> }) )

**Comment by wdey** [comment]
I shut and then started ZAP again: and everything is working ! Any explanation ?

**Comment by korhaliv** [comment]
Are you using a remote or a local node with Zap? Local is when you create a wallet within Zap, write down a seed, etc. Remote is when you connect to your own LND. One reason for the failure could be that LND was still catching up with network graph sync when you were sending a request.

**Comment by wdey** [comment]
I use a local node with ZAP; I created a channel from Eclair full node to ZAP, which is properly up and running, and has local / remote balance, seen from both sides.

**Comment by wdey** [comment]
Btw. Had exactly the same issue, sending 16 sat from ZAP to Bluewallet. Again, shut / unshut ZAP and everything works

**Comment by JimmyMow** [comment]
Seems related: https://github.com/lightningnetwork/lnd/issues/2272

**Comment by mrfelton** [comment]
I believe this issue will be resolved by https://github.com/LN-Zap/zap-desktop/pull/2575. Fix to be included in soon to be released 0.5.1 update
