### ISSUE TITLE
Autopilot turned on automatically on mainnet neutrino node

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#2041]
## Description

When testing mainnet neutrino on the `next` branch I deposited BTC into my wallet and it started opening channels even though I never enabled autopilot

## Expected Behavior

Autopilot disabled

## Steps to Reproduce

- 1. Create mainnet neutrino wallet
- 2. Get an address and log out
- 3. Deposit BTC to address and log back in

- Zap version: `next` branch 
- Operating System and version: Mac OS X

**Comment by korhaliv** [comment]
@JimmyMow Hey! Could you please check if `autopilot` is turned on in the wallet settings for this wallet?

**Comment by JimmyMow** [comment]
@korhal it was but I never toggled it on. It was a freshly created wallet

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/2045
