### ISSUE TITLE
Zero value invoices don't display the amount paid after settled

### ISSUE THREAD

**Issue by Fi3** [LN-Zap/zap-desktop#2047]
## Description

Any amounts invoices are showing an incorrect amount.

## Expected Behavior

The invoice amount should be correct.

## Actual Behavior

Any amounts invoices always show 0 for the amount.

## Steps to Reproduce

- 1. Create an invoice with 0 sat
- 2. Pay it with n sat with n > 0
- 3. You balance is not updated, in the tx list you see a payment of 0 sat, the channel balances are not updated 

## Your Environment

- Zap Desktop version: master

**Comment by JimmyMow** [comment]
Hey @Fi3, thanks for filing an issue.

I'm having trouble understanding the problem your facing. What exactly is the issue? I've tried to reproduce what you've described above and all my invoices are showing correct amounts.

**Comment by Fi3** [comment]
1. I create an invoice and I put 0 satoshis as amount, so an invoice that start with `lntb1p` (tried only in testnet).
2. From another client I pay the invoice and with an amount that is not 0 (ex 50000 sat)
3. In the tx list I can see a received payment for that invoice but the amount is 0 instead of 50000.

**Comment by JimmyMow** [comment]
Ah, understood. 0 value invoices don't display the amount that is paid after they are settled

**Comment by mrfelton** [comment]
@Fi3 I'm unable to reproduce this issue.

What I tried:

1) Got the QR code on https://tippin.me/@mrfelton
2) Opened in Zap
3) Entered a custom payment amount of 1000 Satoshis and paid the invoice

Lightning payment of 1000 sats shows up in the activity list
Clicking on the payment to see the details showed the amount as 1000 sats
Balance decreased by 1000 sats

Please note that 0 value on-chain transactions do sometimes show in the transaction list which are a bi-product of some lnd internals. I wonder if it's one of these that you are seeing?

**Comment by Fi3** [comment]
@mrfelton 

I think that you are trying the other way around. I create the 0 value invoice from Zap, and then I pay it from another wallet. 

In the tx list I have:
```
Received payment                                        + 0 tsatoshis
1:29 PM                                                       $0.00
````

If I click on the tx I get the right tx values:
```
                           Received
                      Lightning Payment
------------------------------------------------------------
Amount                                             tsatoshis
                                                         500
------------------------------------------------------------
Current value                                            USD
                                                        0.03
------------------------------------------------------------
.....
```
Also the wallet amount and the channel balances shows a value that is not updated.

**Comment by mrfelton** [comment]
@Fi3 Are you using Zap's built in lnd node, or are you connected to your own lnd node? If so, what lnd version are you running?

**Comment by mrfelton** [comment]
@Fi3 I was able to reproduce and have a fix in https://github.com/LN-Zap/zap-desktop/pull/2053

In my testing though, the wallet balances are updated correctly (with lnd 0.6). What version of lnd are you using?

**Comment by Fi3** [comment]
@mrfelton ty
Im using Zap's built in lnd node, the Zap vesrion is 0.4.1.
