### ISSUE TITLE
Bug: Frozen UI on lnd Unavailability

### ISSUE THREAD

**Issue by helgabutters** [LN-Zap/zap-desktop#205]
I've identified some example scenarios where you can freeze the Zap UI. To recreate these have everything setup correctly and then at certain points you will kill the connected `lnd` daemon.

These are complete freezes and you need restart Zap.

## Scenerio 1:

- Start Zap
- Click "Pay"
- Kill `lnd`
- Insert lightning invoice into payment request field

## Scenerio 2:

- Start Zap
- Click "Contacts"
- Kill `lnd`
- Click "Wallet"
- Click "Requests"

### Example Screenshot:
![crashlight](https://user-images.githubusercontent.com/8001978/35137748-ea5b01ce-fcb8-11e7-9c52-91a808bc188d.png)

**Comment by Empact** [comment]
This looks to be fixed - the current behavior is that the action is attempted, then when it fails, an error header is shown:

<img width="858" alt="screen shot 2018-03-12 at 9 38 37 pm" src="https://user-images.githubusercontent.com/5470/37322930-cb74b756-263d-11e8-9dc5-40b1e8117312.png">
