### ISSUE TITLE
I should be able to sort channels

### ISSUE THREAD

**Issue by korhaliv** [LN-Zap/zap-desktop#2058]
## Detailed Description
Introduce channel sorting capability.
There could be a following list options:
1. sort by open date
2. sort by remote balance
3. sort by local balance
4. sort by activity metric #1973 
5. sort by  name
6. capacity

## Possible Implementation
![image](https://user-images.githubusercontent.com/14069193/56347449-f13c6300-61cc-11e9-8073-75a39e775f17.png)

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/2331
