### ISSUE TITLE
Bug: Contacts Online Status Incorrect on lnd Unavailability

### ISSUE THREAD

**Issue by helgabutters** [LN-Zap/zap-desktop#206]
If the "Contacts" page has been navigated to and you kill `lnd`, any online contacts will continue to show "Online" even if `lnd` is not available/timing out.

Clicking "Refresh" on the "Contacts" page or any other section of the wallet does not seem change the status.

- Start Zap
- Click "Contacts"
- Kill `lnd`
- Click "Refresh"

**Comment by mrfelton** [comment]
The current behaviour is to exit the app if lnd exists. We will however be improving this behaviour through https://github.com/LN-Zap/zap-desktop/issues/620
