### ISSUE TITLE
Wallet duplicates can appear during creation process

### ISSUE THREAD

**Issue by korhaliv** [LN-Zap/zap-desktop#2087]
## Description
`Next` button is not disabled while Zap creates new wallet.
Clicking on it creates wallet dupes
![image](https://user-images.githubusercontent.com/14069193/56568735-46f37f80-65c0-11e9-8d3e-a8431cc4086b.png)

## Possible Fix
1. Disable button while creation process is running (ui level)
2. Don't allow to create a wallet with the same settings while creation process is running (app logic level)

## Steps to Reproduce

1. Press `create new wallet`
2. Generate seed
3. Enter seed
4. While the wallet is in the process of creation - press `Next`

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/2101
