### ISSUE TITLE
unable to find a path to destination

### ISSUE THREAD

**Issue by pavoltravnik** [LN-Zap/zap-desktop#210]
This error occurs to me, when I try to pay in lightening channel. Am I supposed to create lightening channel first by using pubkey and connecting to specific HOST IP first or am I missing anything else?
![screen shot 2018-01-21 at 11 32 58](https://user-images.githubusercontent.com/21983609/35193153-1fa1db54-fe9f-11e7-97cb-672aafa720ce.png)

**Comment by JimmyMow** [comment]
Yup. You either need a channel with the party you're trying to send to or have a mutual channel with enough liquidity to route the payment.

Going to close this as it is not an issue with the application
