### ISSUE TITLE
Routing hints for private channel invoice 

### ISSUE THREAD

**Issue by MaxHillebrand** [LN-Zap/zap-desktop#2165]
## Problem

The creation of private channels is already possible in Zap, thanks!
When running private channels, the public network does not know about the possible routes for sending payments to the private node.

## Solution

The receiver can include routing hints within the invoice he provides to the sender. 
`lncli addinvoice --private --amt <sat>`
Feature request to include a check box with Include routing hint in the invoices tab.

## Context

Muh privacy.

## Possible Implementation

@JimmyMow and @mrfelton have [already discussed this many blocks ago](https://github.com/LN-Zap/zap-desktop/pull/726), I'm not sure if this is implemented already, but I don't see the option in the GUI.

- Zap version: 0.4.1-beta
- Operating System and version: Debian 9

**Comment by mrfelton** [comment]
Hi Max,

We do already support this to some degree. When running as a neutrino light client we always default to private channels and we include the routing hints in invoices that we create.

When connecting to a a remote node we make the assumption that your node is probably an always on node, more suitable as a routing candidate and that your channels are public. So in this instance we do not include the routing hints.

I think a good enhancement to this would be to give owners of remote nodes the ability to make this choice for themselves and override our assumptions about wether or not routing hints should be included when creating invoices.

**Comment by MaxHillebrand** [comment]
Very nice, thanks Tom!

Yes, for BIP158 SPV nodes it probably makes sense to have private channels.
And I agree that it would be nice to have a optional checkbox for remote node users. At least when there is one private channel opened.

**Comment by mrfelton** [comment]
@MaxHillebrand I've done an implementation of this in #2191

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/2191

**Comment by fjdone** [comment]
The option to mark routing hits was included in previous versions, but now in 0.5.3 beta it has been removed again, I can't received payments from nodes that I am not connected to because those nodes don't know my node since my node and channels are private.
Could you please   tell me how to add routing hints in zap wallet 0.5.3 invoices?
