### ISSUE TITLE
I sent BTC to an address generated in ZAP but it is not showing up.

### ISSUE THREAD

**Issue by spookiestevie** [LN-Zap/zap-desktop#2182]
## Description
I sent btc to an address that zap generated under the qr code section -> BTC address.
![here](https://i.gyazo.com/39e647d5679bbc170389157d8de994a1.png)

https://www.smartbit.com.au/address/37pdy3hSiSA9LLynmmJxELuehHnp3LLDf1

The funds have definitely been sent to the address, it is confirmed above. Yet doesn't show in zap wallet.
when doing `lncli walletbalance`, it doesn't show the funds

I am connecting to my own node using lndconnect.

How can i gain access to these funds?

## Your Environment

- Zap version: 4.1 beta (latest)
- Operating System and version: windows 10

**Comment by mrfelton** [comment]
Is your node synced?

**Comment by spookiestevie** [comment]
![yes](https://i.gyazo.com/068d99fd451976ac878ca7bb300b1b6b.png)

**Comment by mrfelton** [comment]
Can you share the output of `lncli getinfo`?

**Comment by spookiestevie** [comment]
![sure](https://i.gyazo.com/9fdb2cfb17303eaed6440b1522f1b29a.png)

**Comment by mrfelton** [comment]
What about `lncli listunspent` which will list all of your wallet's unspent outputs? Or ` lncli listchaintxns` that will show all the transactions from your wallet. The combination of those 2 commands should show you all addresses created/used by your wallet.

**Comment by spookiestevie** [comment]
yep, still cannot see that 37pdy3hSiSA9LLynmmJxELuehHnp3LLDf1 address :(

**Comment by spookiestevie** [comment]
does zap have its own wallet file which can be recovered?

**Comment by mrfelton** [comment]
Is the first/only wallet that you have created in Zap Desktop?

**Comment by mrfelton** [comment]
No, Zap doesn’t have a wallet file. Zap doesn’t have a wallet at all. You are connected to your own node - Zap is essentially just a remote control to your node. It’s just a gui on top of your own lnd node.

**Comment by spookiestevie** [comment]
yes, it is the only wallet i have with zap. I wonder why zap gave me an address which my node says it doesn't know.

**Comment by spookiestevie** [comment]
My fault for not using `lncli newaddress`

**Comment by mrfelton** [comment]
The address that zap shows is literally generated by calling lncli newaddress via your nodes grpc interface

**Comment by mrfelton** [comment]
How is your lnd node connected to the blockchain? Bitcoind? Btcd? Neutrino?

Maybe you should try to force a resync of your lnd chain data

**Comment by spookiestevie** [comment]
bitcoind, i will do some more investigating.

**Comment by spookiestevie** [comment]
Ok thank you @mrfelton for your time. Turns out that address was linked to a second lightning node that i had running a while back.

**Comment by mrfelton** [comment]
So, to be clear - you connected zap to a different node and sent bitcoin to that instead of the one that you thought you did?

**Comment by spookiestevie** [comment]
ngl, i don't really know what happened either but essentially i have a lightning/bitcoin node running on a rpi and a windows computer (not simultaneosly). I only access the rpi using zap on a laptop. I had problems with the rpi (data corruption, but thats now fixed) so i used the windows computer to start bitcoind and lnd with and old channels.db to recover my funds (this was successful). So i can only guess somewhere in this mess i managed to find an address to an old wallet. So in short, yes. 😃 🤦‍♂

**Comment by mrfelton** [comment]
Lol, ok cool. Glad you got it sorted. I would be worried if Zap was somehow showing random addressees that don’t belong to your node. I much prefer user error to fatal bug 🤪
