### ISSUE TITLE
Add transaction ID copy functionality

### ISSUE THREAD

**Issue by maraph** [LN-Zap/zap-desktop#2186]
The transaction view doesn't allow to copy the transaction ID.

## Detailed Description

When going to the detail view of a transaction, one is presented with a link to https://blockstream.info when clicking on the transaction ID.
There should be an easy and convenient possibility to copy the presented ID.

![2019-05-10 14_13_53-Window](https://user-images.githubusercontent.com/11649986/57526982-243ac800-732f-11e9-9c8a-ce5927be81c8.png)

## Context

- Not everyone wants to track his or her transaction through https://blockstream.info.
- Not everyone wants to use his default browser to open the transaction info, as this could lead to privacy issues, if the default browser is not private/secure.

## Possible Implementation

1.  Add a small copy symbol near the link
2. Show the full transaction ID and make it easy to copy (like in a code block)

## Your Environment

- Zap version: 0.4.1-beta
- Operating System and version: Windows 10

**Comment by maraph** [comment]
On a sidenote, the link to the contributing guidelines is invalid: https://github.com/LN-Zap/zap-desktop/blob/master/CONTRIBUTING.md

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/2420
