### ISSUE TITLE
ZAP LN wallet home page design

### ISSUE THREAD

**Issue by wdey** [LN-Zap/zap-desktop#2187]
Please arrange the LN wallet home page, such it does fit one screen; I searched for the delete wallet option for quite some time. with the dark background, the slider can hardly be seen.

**Comment by mrfelton** [comment]
I'm not sure that we can really make all of the wallet settings always fit above the fold. However, in the `next` branch we have already adjusted the scrollbar to make it more visible which will make this less of an issue.

See https://github.com/LN-Zap/zap-desktop/pull/2049
