### ISSUE TITLE
Zap Wallet Stuck on "Fetching tickers" status

### ISSUE THREAD

**Issue by hubiktomas** [LN-Zap/zap-desktop#2190]
## Description

Zap Wallet Stuck on "Fetching tickers" status after startup. Probably related to issue #1966 

## Expected Behavior

Open Zap wallet successfully and see channels and funds

## Actual Behavior

Gets stuck on "Fetching tickers" status / loading page

## Steps to Reproduce

- 1. Setup BTCPayServer with LND 0.6.0
- 2. Install Zap 0.4.1
- 3. Open Zap app
- 4. Wait

## Context

Cannot fund wallet and see channels.

## Your Environment

- Zap version: 0.4.1
- Operating System and version: Windows 10 Pro 64-bit with all updates
- BTCPayServer 1.0.3.97 with LND 0.6.0

**Comment by sicksubroutine** [comment]
Same issue for me for a remote BTCPay server using LND 0.6.0-beta and Zap 0.4.1-beta.

**Comment by mrfelton** [comment]
This is a known issue with the version of lnd that BTC pay server bundles. - will be fixed in our next release.

Using one of the official lnd releases will resolve the issue for you until we make our next release.

**Comment by mrfelton** [comment]
Hi. Please update to Zap 0.5.0 and let us know if the issue persists. Thanks.

**Comment by mrfelton** [comment]
I'm going to close this due to lack of activity. This was a known issue with BTCPay server in order versions of Zap & BTCPay Server. Updating Zap and BTCPay Server to the latest versions should resolve the issue.
