### ISSUE TITLE
ZAP and port 9735

### ISSUE THREAD

**Issue by wdey** [LN-Zap/zap-desktop#2194]
I have a lab, running btcd (0.18.0), Eclair, LN desktop and ZAP on the same server.
This seems problematic, as everybody uses port 9735.
Q. Is ZAP using 9735 Incoming / outgoing
Q. is this port configurable in ZAP

**Comment by mrfelton** [comment]
Yes, we are using port 9735.

This is configurable, but currently only via our config file and not via the UI so you would need to make your own build with adjusted config. We are working on a settings page for the app from where this will be more easily configurable.
