### ISSUE TITLE
On-chain Balance ?

### ISSUE THREAD

**Issue by wdey** [LN-Zap/zap-desktop#2197]
I have a total of 442'377 sat , where 263'458 are allocated in two channels.
When I want to open a new channel, before even entering a value for the balance, I receive a message: on-chain balance is 72'695.
And I cannot even a channel with 50'000 sat ? Is there a min of 100'000 by ZAP ?

Sorry; after refreshing the channel screen, everything seems to be ok.

**Comment by mrfelton** [comment]
When you go to open a channel the balance that we show is your confirmed onchain balance (so, excluding unconfirmed funds)

The minimum channel size is set by the node you are opening a channel to so will vary depending on who you are connecting to.

**Comment by wdey** [comment]
confirmed funds means >= 3 confirmations

**Comment by mrfelton** [comment]
Just 1 confirmation.
