### ISSUE TITLE
Zap yarn error

### ISSUE THREAD

**Issue by Freefromchainz** [LN-Zap/zap-desktop#223]
After running yarn building Fresh Packages Gets stuck I left it for about an hour and nothing happens. Hope this is an easy fix.
![zap yarn error](https://user-images.githubusercontent.com/8317700/35414870-05d42458-01e1-11e8-9781-f0baf63720f9.PNG)

**Comment by jakezeal** [comment]
Can you try `yarn cache clean` & `yarn install` again?
Also, what version of node.js are you running?

**Comment by Empact** [comment]
Closing as stale and probably yarn rather than zap-related. Feel free to re-open if the issue is ongoing!
