### ISSUE TITLE
Connection type radio cards do not display correctly in the Light theme

### ISSUE THREAD

**Issue by lieteau2** [LN-Zap/zap-desktop#2259]
When creating a new wallet in Zap using light theme, the tiles dont display the proper graphics. You can see how it should look below and how it currently does look. 

<img width="901" alt="Screen Shot 2019-05-22 at 12 12 08 PM" src="https://user-images.githubusercontent.com/45567325/58194547-6f3bd000-7c8b-11e9-8e17-73781656c28a.png">

<img width="901" alt="Screen Shot 2019-05-22 at 12 15 19 PM" src="https://user-images.githubusercontent.com/45567325/58194552-75ca4780-7c8b-11e9-8dff-81df62a2adab.png">

**Comment by mrfelton** [comment]
Fixed via https://github.com/LN-Zap/zap-desktop/pull/2267
