### ISSUE TITLE
Allow using ipv6 host in manual connection mode

### ISSUE THREAD

**Issue by korhaliv** [LN-Zap/zap-desktop#2270]
## Description
Currently, it is impossible to create a connection using ipv6 host in manual mode

![image](https://user-images.githubusercontent.com/14069193/58344670-ff7e3e80-7e5e-11e9-967e-6dfafd7cb399.png)

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/2287
