### ISSUE TITLE
Update default channels with Tippin and Yalls?

### ISSUE THREAD

**Issue by marsrobertson** [LN-Zap/zap-desktop#2273]
Tried opening other predefined channels with Tippin and Yalls (well known LN services):

![image](https://user-images.githubusercontent.com/44369284/58359146-e20a9e00-7e79-11e9-8000-a2f4c7a35d0c.png)

![image](https://user-images.githubusercontent.com/44369284/58359154-e9ca4280-7e79-11e9-8878-c53a0a8865f2.png)

In fact I want to open a channel with Radar: https://github.com/LN-Zap/zap-desktop/issues/2271#issuecomment-495769664

But I'm getting this error: https://github.com/LN-Zap/zap-desktop/issues/723#issuecomment-495780286

**Comment by mrfelton** [comment]
This has been fixed in #2577 and will be included in 0.5.1
