### ISSUE TITLE
Unexpected on-chain transactions after restarting Zap? (general newbie question)

### ISSUE THREAD

**Issue by marsrobertson** [LN-Zap/zap-desktop#2280]
### Day 1

My first experience with Zap desktop `0.4.1-beta` on Mac.

> Unable to open channel: Error: not enough witness outputs to create funding transaction

https://zaphq.slack.com/archives/C6P5UNJMV/p1558865433013900

This is my theory:

> My funding transaction had approx `35k sat` transaction fee.
> I’ve sent small amount `0.0005 BTC`… `20k sat` is minimal channel size.
> Is it possible that minimal channel size + transaction fee to open channel is less than my on-chain balance?
> `20k sat` + `35k sat` > `0.0005 BTC`

Then tried opening pre-configured to Tipping and Yalls, this time encountering: https://github.com/LN-Zap/zap-desktop/issues/2273

I went to sleep, it was late.

### Day 2

I open my laptop, start Zap, instantly I'm getting this:

<img src="https://user-images.githubusercontent.com/44369284/58380387-66f3d580-7fa8-11e9-9841-b683158919e3.png" width="300">

I thought maybe some of the transaction got unstuck, maybe a channel was opened.

Then I was able to send some transactions back and forth, it small relatively smooth. First I needed to send to someone `1000 sat` _(another me on BlueWallet iOS)_ and back `10 sat`, also `32 sat` tip to @wbobeirne

![image](https://user-images.githubusercontent.com/44369284/58384847-8c500600-7fdf-11e9-91e9-9c6f268327eb.png)

So far so good, then I started rollin like a [Bitcoin millionaire](https://www.youtube.com/watch?v=UG7zLhEWanc), `150 sat` to Yalls article, some micro tip via Tippin... But both of these got stuck, pending, decided to restart Zap.

Just like previously, when starting Zap, I got the on-chain notification:

<img src="https://user-images.githubusercontent.com/44369284/58380387-66f3d580-7fa8-11e9-9841-b683158919e3.png" width="300">

* I did not send an on-chain transaction.
* I did not close the channel.

I'm trying to figure out what is happening. 

**EDIT / UPDATE:** ⚠️⚠️⚠️AUTOPILOT !== default settings ⚠️⚠️⚠️

**EDIT / UPDATE:** think that me ticking "autopilot" automatically opened the channel, subsequently unticking it closed the channel.

### `Closing` vs `Pending force close`
I took screenshots at various phases:

<img width="1012" alt="Screenshot 2019-05-25 at 22 09 29" src="https://user-images.githubusercontent.com/44369284/58386099-d0003b00-7ff2-11e9-8e09-203628c1478e.png">

<img width="1012" alt="Screenshot 2019-05-26 at 18 06 32" src="https://user-images.githubusercontent.com/44369284/58386100-d098d180-7ff2-11e9-9211-57c544d9012f.png">

### What is the meaning / significance / reason of a timelock?

<img width="516" alt="Screenshot 2019-05-26 at 17 53 35" src="https://user-images.githubusercontent.com/44369284/58386192-dc38c800-7ff3-11e9-9337-41fd8b9dd686.png">

How to know the timelock looking at the raw transaction?

* https://blockstream.info/tx/19838eb547fe1427ee813dd62d1487244563aadc757d159ba98c5a8eae72d751?expand
* https://www.blockchain.com/btc/tx/19838eb547fe1427ee813dd62d1487244563aadc757d159ba98c5a8eae72d751

### Yet another on-chain transaction

Check this out: https://blockstream.info/tx/19838eb547fe1427ee813dd62d1487244563aadc757d159ba98c5a8eae72d751

I'm totally confused.

It's sending all the balance to an address I control, minus the miner fees.

I have no idea what is happening.

I did not initiate this transaction. 

Most likely (not 100% sure) it happened again upon restarting Zap...

<img src="https://user-images.githubusercontent.com/44369284/58386293-5d448f00-7ff5-11e9-8413-1974790d116d.png" width="300">

### Summary

We are here now, such early days.

![image](https://user-images.githubusercontent.com/44369284/58380441-fb5e3800-7fa8-11e9-8a08-c48c0ae7d970.png)

https://twitter.com/francispouliot_/status/1131650888110624768

I should be using `testnet` right from the start. I thought I can afford `1000 sat` back and forth, but every on-chain transaction feels like pain 😇

**Comment by marsrobertson** [comment]
# ⚠️⚠️⚠️AUTOPILOT !== default settings ⚠️⚠️⚠️

Silly me, I thought that ticking autopilot means _"use default settings, route my payment through most cost-effective route"_

I did not know that it means automatically opening and funding channels.

The behaviour consistent with hacking:

![image](https://user-images.githubusercontent.com/44369284/58558741-847ba600-8219-11e9-9d25-2e001f4ddcb0.png)

![image](https://user-images.githubusercontent.com/44369284/58558760-8cd3e100-8219-11e9-893f-fce59c30d43a.png)

To receive on-chain transaction just to see the next second the funds are being transferred away...

# 🤔

Autopilot: https://github.com/LN-Zap/zap-desktop/issues/609

https://github.com/lightningnetwork/lnd/blob/0c1b619e53ac88ad53f3a88e5d1129c25ddeaf13/sample-lnd.conf#L251-L265

```
[autopilot]

; If the autopilot agent should be active or not. The autopilot agent will
; attempt to automatically open up channels to put your node in an advantageous
; position within the network graph.
; autopilot.active=1

; The maximum number of channels that should be created.
; autopilot.maxchannels=5

; The fraction of total funds that should be committed to automatic channel
; establishment. For example 0.6 means that 60% of the total funds available
; within the wallet should be used to automatically establish channels. The total
; amount of attempted channels will still respect the maxchannels param.
; autopilot.allocation=0.6
```

**Comment by marsrobertson** [comment]
I would like to know how are these numbers calculated. Commit Fee?  Node's Fee Base?
* Red - `sats`
* Green - it is the same transaction
* https://blockstream.info/tx/278f49934d1a4554324295ca96ecd4c65d1da9a1ecefa71197708fce20ba9dc9

![image](https://user-images.githubusercontent.com/44369284/58565328-6d8f8080-8226-11e9-8910-dbeefdd3f790.png)

----

# I've just opened a channel with it and it is already offline?

https://1ml.com/node/02388d70afa6a8bceeee633386ad2bc67c1ac5eef0ae75b6d4f25fff5b425a417e

![image](https://user-images.githubusercontent.com/44369284/58565730-235acf00-8227-11e9-8ff0-1549b17d2ef6.png)

**Comment by mrfelton** [comment]
I'm going to close this issue since I think we got to the bottom of the problem which was that you had enabled autopilot.

In 0.5.x we have removed the ability to enable autopilot when creating your wallet. We are rethinking the approach to autopilot for a future release.
