### ISSUE TITLE
Change Zap Logo to bolt only

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#2315]
I think we should change this logo to remove the copy `zap` so it is just a bolt:

<img width="124" alt="Screen Shot 2019-05-30 at 8 47 58 AM" src="https://user-images.githubusercontent.com/4040039/58637240-b3e0f000-82b7-11e9-987e-8f0f6058f36d.png">

My reasoning for this is because as I test and work on iOS/Android, draw mocks for our website, tweet, etc. the `bolt` only is the logo that is used across everything. I think unifying across all platforms as a logo without copy is smart and a small but useful change

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/2323
