### ISSUE TITLE
New Profile Modal

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#2317]
Right now for a user to access their `public key (and host)`, `lndconnect` info, and on-chain address they click this QR code to the left of the balance:

<img width="353" alt="Screen Shot 2019-05-30 at 10 13 50 AM" src="https://user-images.githubusercontent.com/4040039/58642860-c19c7280-82c3-11e9-87ca-a67fc31d672c.png">

There are a few UX issues here. One of them is the fact that node information (Profile information) shouldn't live where the current on-chain address lives, and it is confusing to a user on how to find such information.

<img width="668" alt="Screen Shot 2019-05-30 at 10 13 56 AM" src="https://user-images.githubusercontent.com/4040039/58642937-e2fd5e80-82c3-11e9-8c51-e22f08f5de9c.png">

I propose we create a `Profile` link under `Settings` in our new navigation.

<img width="323" alt="Screen Shot 2019-05-30 at 10 16 13 AM" src="https://user-images.githubusercontent.com/4040039/58642985-ff010000-82c3-11e9-93c2-d1a9c609356f.png">

When clicking on this new `Profile` link, we will open a modal similar to the Settings modal:

<img width="897" alt="Screen Shot 2019-05-30 at 10 17 05 AM" src="https://user-images.githubusercontent.com/4040039/58643028-193ade00-82c4-11e9-939e-d0a5f5bc576e.png">

The left nav will contain items like `Node information (Pubkey)` and `lndconnect`.

This allows all the profile type node info to live in its own area within the application, and moves us closer to removing that weird QRCode next to the balance 😄

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/2392
