### ISSUE TITLE
Pending Channel Card height misaligned

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#2327]
I think we should make the height of these cards a minimum px number so that there are no cards shorter than others. What do you think @ole1220 @mrfelton @korhaliv?

<img width="900" alt="Screen Shot 2019-05-31 at 2 04 50 PM" src="https://user-images.githubusercontent.com/4040039/58728764-34cde380-83ad-11e9-928e-b63c5a8a95ba.png">

**Comment by ole1220** [comment]
@JimmyMow yes let's do that. we should set the max. height as the standard size for all cards.

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/2348
