### ISSUE TITLE
Undefined string in channels sub-menu

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#2339]
<img width="282" alt="Screen Shot 2019-06-04 at 12 50 40 PM" src="https://user-images.githubusercontent.com/4040039/58901758-6bff0600-86c7-11e9-9117-d1fcb1b6b3d8.png">

When opening a local wallet that hs no balance, I see my channels sub menu has `0 undefined`

**Comment by korhaliv** [comment]
@JimmyMow any additional details that you could share? I've tried with multiple empty local wallets (testnet and mainnet) and couldn't seem to reproduce the issue

**Comment by JimmyMow** [comment]
<img width="899" alt="Screen Shot 2019-06-06 at 8 31 53 PM" src="https://user-images.githubusercontent.com/4040039/59076141-28a8c100-889a-11e9-9769-016a31aa89d9.png">

@korhaliv I am now seeing this in `next` (`commit 2ff9a56b86faf5f46fa1bad238d2f8f0ab2abd34`)

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/2374
