### ISSUE TITLE
No bottom padding in Launchpad

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#2340]
Running `next`, my Lanchpad doesn't seem to have any bottom padding, resulting in the `Delete Wallet` button hugging against the bottom of the screen. I assume this is a small bug, and I think adding some padding here would give the UI some needed breathing room.

<img width="673" alt="Screen Shot 2019-06-04 at 12 53 00 PM" src="https://user-images.githubusercontent.com/4040039/58901975-ddd74f80-86c7-11e9-9ad4-57bff70ff1b3.png">

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/2344
