### ISSUE TITLE
Performance issues due to UPDATE_NODE_DATA

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#2341]
When on the next branch (`commit 5999b60b1f0c57ec16260351480f55b37614da80`) and logging into a local node, my wallet performance is extremely laggy and almost unusable. When looking in the console logs, it looks like `UPDATE_NODE_DATA` is being called multiple times a second and is causing the performance issues

**Comment by mrfelton** [comment]
Yes, this is a known issue @JimmyMow . See https://github.com/LN-Zap/zap-desktop/issues/2225

**Comment by JimmyMow** [comment]
Ah ok. Closing due to duplicates
