### ISSUE TITLE
Processing your payment loop

### ISSUE THREAD

**Issue by wdey** [LN-Zap/zap-desktop#2365]
Running the latest version 0.4.1.beta 
2 channels are open by means of autopilot.
I try to do a payment to yalls.org (mainnet), and the end up
in a processing your payment loop, which already hangs since hours.
How can/should I troubleshoot ?

**Comment by mrfelton** [comment]
Hi, please can you confirm if this is still an issue for you with 0.5.0? Thanks

**Comment by wdey** [comment]
I upgraded to 0.5.0 and have not seen any issue since (with the exception of
