### ISSUE TITLE
Shoot, we're having troubles sending your payment

### ISSUE THREAD

**Issue by AdriaanVanNuffel** [LN-Zap/zap-desktop#239]
So far I haven't been able to do any payments, neither to Yalls or to Starblocks. To Yalls I have an open channel, which is found by the Network explorer. There Zap gives me "Shoot, we're having problems sending your payment".

I think I also have an open channel to Starblocks but Zap doesn't find a route for payment.

![schermafbeelding 2018-01-27 om 23 15 10](https://user-images.githubusercontent.com/35861589/35476868-123f98de-03b8-11e8-9546-894a742f34fd.png)

**Comment by PlanBit** [comment]
Same issues. 4 channels open but can't make any payments.

**Comment by bitcoinuser** [comment]
Same here. I have open channel with yalls and when i try to make a payment I see this message: Shoot, we're having troubles sending your payment.

I can't make any payment.

**Comment by larspohlmann** [comment]
Same problem. I have 6 open channels (4 online). A pretty large network with 461 nodes. But no payment has been successful so far (yarn or starblocks).

I always get following error: "unable to find a path to destination". 

It should be able for at least a few receipients...

**Comment by floundies** [comment]
Same issue.  MacOS. Can't seem to make any payments either, even with two channels open.  The network graph shows the route to the node I am trying to pay (yalls.org article). But when actually paying the payment request, I get the same error.

<img width="1435" alt="screen shot 2018-01-29 at 12 35 16 am" src="https://user-images.githubusercontent.com/3433553/35494995-80cd12f2-048c-11e8-85c2-b7dd591893d1.png">

**Comment by JimmyMow** [comment]
it takes 6 confs for channels to be announced to the network, so it's possible you had an active channel that hadn't been announced yet. 

Were you all able to eventually send payments? This is a normal error. The UX will be improved (better errors) but I wouldn't classify this as a bug, more poor UX which is being there is already a todo for, so I'm going to close thise.

**Comment by AdriaanVanNuffel** [comment]
No, I'm still not able to do payments. I'm either getting "No route found", or the "Shoot, we're having touble!". Could this be some security setting?

Also, when running Zap, my MacBook's ventilation really starts to whir louder & louder - looks like it's doing a lot of work there.
