### ISSUE TITLE
Zap windows: blank screen on resize

### ISSUE THREAD

**Issue by rationalflaneur** [LN-Zap/zap-desktop#2393]
Whenever I resize my Zap window, the UI disappears. Restarting often fixes the problem.

## Description

![blank](https://user-images.githubusercontent.com/48932639/59235093-c31c4380-8bbd-11e9-907f-9e0c6a0a9234.png)

## Expected Behavior

Screen shows UI.

## Actual Behavior

Screen goes blank.

## Steps to Reproduce

- 1. Start Zap from start menu
- 2. Resize
- 3. ???
- 4. Sadness :(

## Your Environment

- Zap version: 0.41-beta
- Operating System and version: Windows 10 64 bit

**Comment by korhaliv** [comment]
Tested  a678706a63c1d67d4a08ec4e7f05a715d0c8ae84 (HEAD, tag: v0.4.1-beta) on win10 64 and wansn't able to reproduce this

**Comment by korhaliv** [comment]
Closing for now. Can be reopened if the issue re-appears.
