### ISSUE TITLE
Funding ZAP from faucet and GUI difference from youtube video tutorials

### ISSUE THREAD

**Issue by Gribor** [LN-Zap/zap-desktop#240]
Hi. 
First of all, great work man, i hope that you keep working to make ligthning network a reality.

Zap Wallet running in windows 10 doesn't update the btcs sent from faucet. Problem with the server?

i sent two times bitcoins from faucet and the tx does not appear in the wallet. 
maybe the problem is my pc?

another thing is that the gui is different of the interface you show in the tutorials videos of youtube. I cna't see the found direction while the wallet was syncs. windows version different from mac

Thanks for the help ;) 

EDIT: the TX already appeared.

Question, the TX will not appear in activity until they get 1 confirmation?

**Comment by JimmyMow** [comment]
It takes 1 confirmation to have the on-chain transactions show up in your wallet. The funding address in the sync page actually got removed before release, sorry about the confusion.

Things seem to actually be working, no bug here. I'm going to close this
