### ISSUE TITLE
Style bug in next

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#2403]
It seems there are some broken styles in `next`.

When syncing new local nodes, the QR code styles are broken it seems:

<img width="613" alt="Screen Shot 2019-06-11 at 7 20 31 PM" src="https://user-images.githubusercontent.com/4040039/59316621-fa095c80-8c84-11e9-8ef3-33aa1d4f5735.png">

`Commit: 34abbe77069eeb4f31bd4ec3c0caa4a4c6de4a1c`

**Comment by mrfelton** [comment]
I noticed and fixed this in 2392 so should be resolved when that is merged

**Comment by JimmyMow** [comment]
#2392 seems to have fixed it @mrfelton. closing
