### ISSUE TITLE
Implement pagination for the activity list to prevent items being dropped from the activity list.

### ISSUE THREAD

**Issue by BitcoinAcolyte** [LN-Zap/zap-desktop#2404]
## Description
When my lnd node creates a new requested payment I see it on the activity list but after hitting the refresh button the transaction disappears. I get the same behavior with received payments. If I filter by received payments only the last payments in the log are from about a month ago but there have definitely been some since then. 

## Expected Behavior
Received payments should be shown in the activity list.

## Actual Behavior
Received payments show up at first but then disappear after refreshing the activity list.

## Your Environment
Windows 10
LND 6.1
Zap 4.1

- Zap version:
- Operating System and version:

**Comment by mrfelton** [comment]
As discussed via Slack, it seems that the most likely reason for this is that you have several thousand nodes and we only fetch up to 1000.

As a quick fix I have increased this to 2500, which is really just kicking the can down the road until we implement proper pagination.

**Comment by bolatovumar** [comment]
@mrfelton I'm looking at the LND API for this and it says this:

> By default, the first 100 invoices created will be returned.

By changing `num_max_invoices` to 2500 LND returns the first 2500 invoices now as far as I understand it. LND also supports the `reversed` flag when `listinvoices` is called which as far as I understand it would return 2500 invoices started from the end (i.e., latest) which is what we want, no?

I don't have anywhere enough transactions on my node to be able to test this lol.

**Comment by mrfelton** [comment]
@bolatovumar I think there is an issue which is that lnd currently only supports pagination for invoices, which means we wouldn't be able to add support for the full activity list. Also, we were probably going to do this with infinite scroll rather than pagination.

This issue is assigned to @korhaliv though since he already started on it, so you should probably connect with him before diving further into this.

**Comment by bolatovumar** [comment]
@mrfelton I'm probably not going to dive further into this as I don't really have anywhere near enough in transactions on my node lol. But I was also thinking that infinite scroll would make a lot of sense here.

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/2911
