### ISSUE TITLE
Zap Desktop does not like LightningLabs' Loop

### ISSUE THREAD

**Issue by 05nelsonm** [LN-Zap/zap-desktop#2408]
## Description
Issue 1:
Installing Lightning Lab's Loop, and then with lnd already running in a terminal in the background, starting Zap yeilds a blank screen. I must execute `lncli stop`, open Zap Desktop, execute `lnd` in a terminal, and then unlock my wallet via Zap for it to work. This is without loop running. Also, any refreshing of wallet transaction history will cause Zap to post a blank screen and require a restart of lnd and Zap.

Issue 2:
Installed Lightning Lab's loop, upon restarting Zap-Desktop and refreshing channels, the names disappeared and I was left with letter/number ID's

LightningPowerUsers now shows --> 0331f80652
and Zap Technologies now shows --> 03634bda49

## Expected Behavior
Screen should not go blank and should update appropriately (like the Zap Android App does)
Channels should retain their given names

## Actual Behavior
Zap goes blank and requires a restart of lnd and Zap Desktop in a particular order to get it "working"
Channels do not retain their given names

## Steps to Reproduce

- 1. Update lnd in accordance with (IAW) https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md , but instead of executing `make clean && make && make install`, execute `make clean && make && make install tags="signrpc walletrpc chainrpc invoicesrpc routerrpc"` IAW https://github.com/lightninglabs/loop instructions and my issue ticket https://github.com/lightningnetwork/lnd/issues/3193
- 2. Proceed with the rest of lightning loop install IAW https://github.com/lightninglabs/loop
- 3. In terminal, start lnd
- 4. Start Zap-Desktop
- 5. Unlock Wallet and wait for Zap-Desktop to load (before starting lnd, you may have to start Zap-Desktop and delete your current wallet because Zap kept giving me a blank screen. Then start lnd and unlock wallet in terminal, then open and re-connect Zap)
- 6. In Zap, go to `manage channels` and click refresh
- 7. In Zap, refresh transaction history.
- 8. Try opening Zap with lnd already running in the background.

## Context
I've gotta remember what channels are what now, instead of just seeing it and knowing

## Your Environment
+lnd version 0.6.1-beta commit=v0.6.1-beta-256-g00a86696a8e737d2b3a621f72d2926c6b79cc4fe
+go1.12.3.linux-amd64.tar.gz was installed
+bitcoind v0.18.0 running on Samourai Dojo v1.0 Docker
+Running the machine VirtualBox 6.0.8

- Zap version: Zap-linux-amd64-v0.4.1-beta.deb
- Operating System and version: Linux ubuntu-desktop-vm 4.18.0-21-generic #22~18.04.1-Ubuntu SMP Thu May 16 15:07:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mrfelton** [comment]
@05nelsonm `Zap 0.4.1` supports up to `lnd 0.6.1-beta` release.  If you want to run a later version of lnd (you are running a recent build from their master branch) then you should build your own pre-release version of Zap from our `next` branch.

**Comment by 05nelsonm** [comment]
Ah OK. I'll give it a go right now then.

**Comment by 05nelsonm** [comment]
That worked... most difficult part was making a damn desktop file to launch it (because I'm lazy like that)... for anyone else wondering...

```
[Desktop Entry]
Encoding=UTF-8
Type=Application
Version=1.0
Terminal=false
Exec=gnome-terminal --title="Zap Desktop" --geometry=80x25 --zoom=0.8 -- bash -c 'cd /home/$USER/zap-desktop; PATH="/home/$USER/.nvm/versions/node/v10.16.0/bin:$PATH"; npm run dev; $SHELL'
Name=Zap Desktop
Icon=/home/matthew/zap-desktop/resources/icon.png
Name[en_US]=Zap Desktop
```
