### ISSUE TITLE
Initial sync could have better UX

### ISSUE THREAD

**Issue by mattbourke** [LN-Zap/zap-desktop#243]
I think this line https://github.com/LN-Zap/zap-desktop/blob/998722cf7b6fc2a4393face510f3aa7b664da9d3/app/components/LndSyncing/LndSyncing.js#L15  could be more user friendly, it could be appended to include something like "The initial setup may take up to x time to sync your Lightning Network node to the Blockchain"  
  
Although there is a % counter in the top right that when moused over explains this, it's a little confusing for new users at first, as it just looks like a % very slowly increasing and no information saying what it is doing.  
I'd be willing to do a pull request for this if others agree.

**Comment by ericomurtez** [comment]
Agree the UX could be improved here.

Setting expectation is important since it takes a long time. Also did not see the loading spinner immediately as it is so dark, so I had no idea what was going on for a little while.

**Comment by CryptoChronicus** [comment]
I agree, maybe do a smaller box with just a status on the percent complete? Much the same way a lot of apps like Photoshop etc will do a splash loading status screen while you wait. I think that may set the expectation a little more conservatively for a few impatient users :)

**Comment by Empact** [comment]
Now it simply says "Syncing to the blockchain..." with a loading bar, similar to your suggestion @CryptoChronicus. Feel free to open new issues against the current interface!
