### ISSUE TITLE
UI gets stuck when connecting to remote nodes in some cases

### ISSUE THREAD

**Issue by korhaliv** [LN-Zap/zap-desktop#2430]
## Description
If remote LND has no connection to bitcoind, Zap UI gets stuck forever after unlocking the wallet, because of the unhandled exception in the `lnd-grpc`
https://github.com/LN-Zap/node-lnd-grpc/pull/30

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/2510
