### ISSUE TITLE
Zap app and lightning labs app show same testnet btc and transaction history

### ISSUE THREAD

**Issue by chippsmith** [LN-Zap/zap-desktop#245]
I downloaded the lightning labs app a few weeks ago and played around with some testnet btc.  When I downloaded the zap app today all the channels and transaction history from the lightning app showed up on the zap app.

**Comment by mattbourke** [comment]
@chippsmith (I'm not a Zap dev, but just looking through these tickets)  
I'd assume this is because they're using the same lightning node account, I doubt it's a bug, but I'm sure a dev will chime in

**Comment by JimmyMow** [comment]
Yep, this is not a bug. Zap is just a simple UI layer on top of LND, this is intentional, at least for the time being.
