### ISSUE TITLE
Can't make unchain payment "Insufficient Funds"

### ISSUE THREAD

**Issue by themickeyc** [LN-Zap/zap-desktop#2495]
## Description

I have about 1M satoshis not in channels, unchain in my wallet. I want to send a transaction.

I am trying to make an onchain payment and even though I have enough funds, I keep getting an error message

There was a problem sending your transaction. Error: insufficient funds available to construct transaction

## Expected Behavior

I should be able to make an unchain transaction

## Actual Behavior

I get the following error message

There was a problem sending your transaction. Error: insufficient funds available to construct transaction

## Your Environment

- Zap version:

0.4.1
- Operating System and version:

Mac 0S 10.14

**Comment by JimmyMow** [comment]
@themickeyc were you accounting for fees as well? What you have on-chain isn't exactly what you can send, as there must be room for fees. Also, it could be possible that you were trying to spend unconfirmed change.

Are you still experiencing this issue?

**Comment by themickeyc** [comment]
Yes, I am accounting for fees.

No, I am not trying to spend unconfirmed change.

I have about 1M sats that have been confirmed for over a month, and I can't spend any amount on chain without getting this error

There was a problem sending your transaction. Error: insufficient funds available to construct transaction

I am pretty sure there is a bug of some sort.

I can wait, if a new update is coming up soon. I really need a "sweep wallet" function.

**Comment by mrfelton** [comment]
Sweep wallet feature is in 0.5.0 - coming soon

**Comment by mrfelton** [comment]
@themickeyc the latest release of Zap (0.5.0) includes support for wallet sweeping. On the send form you will now find a `send all` toggle which will use lnd's underlaying sweep functionality to sent your full confirmed on-chain balance. So you no longer have to try to guess the amount minus the fee rate that you can send.
