### ISSUE TITLE
Needs a warning / notification before allowing you to open a double channel

### ISSUE THREAD

**Issue by bitgosh** [LN-Zap/zap-desktop#252]
When opening a new channel, the app should check the peer or alias of the new node against the list of nodes you already have opened channels with and notify you before opening a double channel (idiot-proof is good, right?)

Also maybe check if the channel is still funded -> so the notification window can remind the user of the funds they already have available in that channel or alternatively, check to see if there's a path available for a payment to that node from another already funded lightning channel -> so the notification window could show all this payment options before allowing the user to open a new channel (especially a double channel).

Could be very useful for users who might think they need to open a new channel to pay each merchant, more so as the network is still growing and paths will be harder to find in the beginning.

**Comment by jamaljsr** [comment]
There are a few features lumped into one here. After a discussion with @JimmyMow & @mrfelton, we've decided to implement the following functionality.

1. display a warning when the user attempts to open a channel to node that already has an active channel open. It would make sense that the user may want to open another channel with a node where the previous one is closing.
2. display the funding amount of the existing channel in the warning message

Checking for an existing path to the node is out of scope for this PR and may be addressed later.
