### ISSUE TITLE
Info pages during setup too high on screen

### ISSUE THREAD

**Issue by coolpick** [LN-Zap/zap-desktop#253]
Looks like it just needs to be dragged down a bit, but the dots you use to change pages is stuck in the middle.  

I should also note the application defaults in Windows 10 to that vertical "mobile" sized screen.  Could be my computer, or it could be the code.  Not too familiar with default window sizing in applications.

When moving to full screen, the dots stay in the same place, but the text is more spread out, and thus shows in the intended format.

Screenshot below.

![zap](https://user-images.githubusercontent.com/1341176/35485183-af91771c-0429-11e8-8e34-acb866c5d752.JPG)

**Comment by JimmyMow** [comment]
Yup. We've redeisgned the loading screen and it's merged into master. Closing
