### ISSUE TITLE
After Update to 0.5-beta error message appears

### ISSUE THREAD

**Issue by ad2003** [LN-Zap/zap-desktop#2535]
After updating the client to 0.5-beta this message appears:  

"Unable to connect to host: Not enough responses received"

Wallet runs with btcpayserver on windows 7

## Expected Behavior

should connect to node

## Actual Behavior
error pops up

## Possible Fix

none yet

## Steps to Reproduce

- 1. Start zap
- 2. Click Launch now
- 3. error appears
 

## Context

Zap is not starting at all.

## Your Environment

- Zap version: 0.5-beta
- Operating System and version: Windows 7

**Comment by djmelik** [comment]
I can confirm I see this same issue as well with my btcpayserver as well.  I tried enabling debug logging, but I am not seeing error outputs on my console.

**Comment by mrfelton** [comment]
@djmelik The debugging setup has changed slightly in this release. Messages no longer go to the terminal and instead everything goes to the browser console. To enable it, start the app like so:

```
DEBUG_PROD=1 /path/to/zap
```

The following options are available:

`DEBUG_PROD`: enable chrome devtools
`DEBUG_LEVEL`: set debug level (defaults to `info`)
`DEBUG`: set debuggers (default zap:main,zap:updater,zap:grpc,lnrpc*)

**Comment by sicksubroutine** [comment]
Same issue on my end. This happened on Windows 10. Uninstalled, deleted Zap directory from AppData, rebooted, and reinstalled. Same issue remains.

**Comment by mrfelton** [comment]
Hi,

Can you provide any more info about your environment?

What version of lnd are you trying to connect to?

Can you connect to any other lnd nodes?

Can you try running with debugging enabled (as per my previous post) and share anything interesting from the logs.

Thanks

**Comment by NicolasDorier** [comment]
I merged @mrfelton fix to the nginx config, and Zap is opening now.

**Comment by mrfelton** [comment]
This issue should now be resolved. Please update BTCPay Server to the latest version. Thanks

**Comment by ad2003** [comment]
thanks for fixing it!

**Comment by NicolasDorier** [comment]
@ad2003 can you try and report here? Somebody said it did not on twitter (but that might come from some unrelated issue)

**Comment by ad2003** [comment]
@NicolasDorier I updated BTCPayServer and it works perfectly fine. For me the problem is fixed! 

What I additionally did: I delted all files inside \AppData\Roaming\Zap and Reconnected the node.
