### ISSUE TITLE
Invoice expire time displays incorrectly for invoices with distant expiry

### ISSUE THREAD

**Issue by Relaxo143** [LN-Zap/zap-desktop#2547]
![Screenshot_124](https://user-images.githubusercontent.com/42069389/60771015-3c8a5180-a0ea-11e9-9613-1620fd0a79f0.png)

It should say "expires" and not "expired", right?

**Comment by mrfelton** [comment]
Hi,
Can you provide steps to reproduce this issue please? Thanks.

**Comment by Relaxo143** [comment]
> Hi,
> Can you provide steps to reproduce this issue please? Thanks.

Open the windows desktop Zap wallet
create an invoice for any amount
done

**Comment by mrfelton** [comment]
Got it. Thanks. Looks like this is only an issue if you have set your invoice expire time to 1 month.
