### ISSUE TITLE
Add PGP signatures of builds

### ISSUE THREAD

**Issue by MaxHillebrand** [LN-Zap/zap-desktop#2548]
## Description

Currently, there is no way to verify if the downloaded build is actually the one compiled by the devs. Man in the middle attacks are not at all defended.

## Expected Behavior

Especially for high security software such as Bitcoin wallets, PGP signatures are the bear minimum.

## Fix

Get @jackmallers a PGP key & sign released builds.

**Comment by mrfelton** [comment]
For reference:

https://github.com/electron-userland/electron-builder/issues/3116
https://github.com/electron-userland/electron-builder/issues/3132

**Comment by mrfelton** [comment]
@MaxHillebrand we can look to add PGP signing, however FYI all of the builds are already signed by Jack and your OS would check this for you upon install (this is why when you try to run the app after downloading on Mac for example, it doesn't warn you that it's unsigned or published by an unknown author)

Also, you can verify that the checksum of the file you download matches the checksum that was generated at the time of publishing:

For example, run the following and compare with the checksum shown in `latest-mac.yml`

```
openssl dgst -sha512 -binary ZapDesktop-darwin-v0.2.2-beta.dmg | base64
```

**Comment by MaxHillebrand** [comment]
Good to know that there are some sigs :) 
I'm not sure if this applies to how Zap is distributed, but afaik, some OS [I am quite sure about Ubuntu] have disabled the check of developer signatures, and they only check the sigs of the dpkg maintainers. [See the details here in the chapter on Current Mitigation Attempts](https://frankbraun.org/essay/fighting-targeted-backdoors/)
Thus I would like to see a separate .asc file of the builds or hash sums of the builds that I can check manually myself.

I tried to verify the sigs as you have recommended, but I can't find the latest.yaml that contains the `Zap-linux-amd64-v0.5.0-beta.deb`... And I'm not sure where exactly I see a valid signature in the `latest.yml`.

**Comment by MrPaz** [comment]
> @MaxHillebrand we can look to add PGP signing, however FYI all of the builds are already signed by Jack and your OS would check this for you upon install (this is why when you try to run the app after downloading on Mac for example, it doesn't warn you that it's unsigned or published by an unknown author)

FYI, on Windows I get a warning telling me not to install.  

Also, what format is the checksum in the yml?  It does not match my checksum:
```
PS C:\Users\mrpaz\Downloads> Get-FileHash .\Zap-win-v0.5.2-beta.exe -Algorithm SHA512 | Format-List

Algorithm : SHA512
Hash      : 1992C8E160F5C7125D7B8D67C0479F8A011BF96CC65EACB892F570213301F544DF9660D13A1C7DE98CF5C55D0FFCC1DF5CC1215F4B1A8783DF3B5761B50B567
            E
Path      : C:\Users\mrpaz\Downloads\Zap-win-v0.5.2-beta.exe
```

vs.

```
path: Zap-win-v0.5.2-beta.exe
sha512: GZLI4WD1xxJde41nwEefigEb+WzGXqy4kvVwITMB9UTflmDROhx96Yz1xV0P/MHfXMEhX0sah4PfO1dhtQtWfg==
releaseDate: '2019-07-31T21:12:50.814Z'
```

I would also very much like to verify via gpg.  Signing builds or publishing signed checksums should be low hanging fruit, and par for the course... cypherpunk ethos, y'all!

**Comment by mrfelton** [comment]
Could you provide a screenshot of that warning that you see on windows please?

**Comment by mrfelton** [comment]
I will be looking to pgp sign our builds... just looking to find a suitable way that fits nicely with our release process

**Comment by mrfelton** [comment]
@MrPaz you can verify the checksum with the following:

```
openssl dgst -sha512 -binary Zap-win-v0.5.2-beta.exe | base64
```

**Comment by MrPaz** [comment]
> Could you provide a screenshot of that warning that you see on windows please?

Here is the message that appears.  I have to click 'More info' then it warns further that it may be a malicious program, then I have to click 'Run anyway' to install:

![Capture](https://user-images.githubusercontent.com/35268901/63166585-7a856a00-bff4-11e9-83f3-0b66b8a3153a.PNG)




> @MrPaz you can verify the checksum with the following:
> 
> ```
> openssl dgst -sha512 -binary Zap-win-v0.5.2-beta.exe | base64
> ```

That command doesn't work in Windows PowerShell or cmd, however I do have WSL on my Windows machine, so was able to run it, and the checksum was indeed OK:
`paz@MrPaz:/mnt/c/Users/mrpaz/Downloads$ openssl dgst -sha512 -binary Zap-win-v0.5.2-beta.exe | base64
GZLI4WD1xxJde41nwEefigEb+WzGXqy4kvVwITMB9UTflmDROhx96Yz1xV0P/MHfXMEhX0sah4Pf
O1dhtQtWfg==`

**Comment by mrfelton** [comment]
Thanks @MrPaz . We actually have a new Microsoft signing cert on the way, so the next release should be signed by that as well, which should clear up that warning.

**Comment by MrPaz** [comment]
Also, last night when originally trying to verify, I thought it looked like base64, so I put the hash strings in this online decoder https://www.base64encode.net , but couldn't decode properly.  Kind of off topic but was just wondering why that didn't work.

**Comment by mrfelton** [comment]
All releases in the 0.5.x series are now signed and moving forwards all new releases will be signed in the same way. I have added some documentation to [our release process](https://github.com/LN-Zap/zap-desktop/blob/master/docs/RELEASING.md) as well as documentation on [how to verify the release](https://github.com/LN-Zap/zap-desktop/blob/master/docs/SIGNATURES.md).

The Windows installation warning should be resolved with the upcoming 0.3.5 release.

**Comment by MrPaz** [comment]
Absolutely outstanding.  Great work @mrfelton and team!

**Comment by MrPaz** [comment]
![checksum](https://user-images.githubusercontent.com/35268901/63225147-fc12fe80-c192-11e9-8de4-44813bc4d58c.png)

![checksum1](https://user-images.githubusercontent.com/35268901/63225149-ffa68580-c192-11e9-80f8-287ebfd02ec9.PNG)

![checksum2](https://user-images.githubusercontent.com/35268901/63225152-046b3980-c193-11e9-82f0-aa69ecfd3c4a.PNG)

👍
