### ISSUE TITLE
Contacts still in "Removing" state after 100+ confirmations

### ISSUE THREAD

**Issue by lra** [LN-Zap/zap-desktop#257]
See:
![screen shot 2018-01-29 at 1 14 49 am](https://user-images.githubusercontent.com/122286/35502421-d3ae4e00-0491-11e8-8424-7c6fc0a5f800.png)

- 1st one: https://testnet.smartbit.com.au/tx/e4c4cf5ea9cc11fd84c7b0bfc59ca11326b11696f4f5547637433ddf5b333e66
- 2nd one: https://testnet.smartbit.com.au/tx/9eeece0c1cfd9cd24212608e6c159af9a4bbf4a766c197a00e27743e4e568f19

163 confirmations each, both stuck in the "Removing" state.

**Comment by bitgosh** [comment]
Same issue here, 718 confirmations thus far and the channel is till marked with "removing", the locked funds have not been made available:

tx: 

https://testnet.smartbit.com.au/tx/a601f1f7230018588c3ca632c7a1cca1a94553d55829fccf81894483e2ff166d

screenshot:

![screen shot 2018-01-31 at 3 12 19 pm](https://user-images.githubusercontent.com/35896605/35624932-2a65319c-0699-11e8-80a4-acac6cd79aaf.png)

**Comment by CryptoChronicus** [comment]
same here 
243 confirmations
Still says Removing

https://testnet.smartbit.com.au/tx/c99f2bca7ea0833a2974b164d5e9eea3fbe263cd9d1889cf4841a3eaa022772e

**Comment by JHPSoft** [comment]
Same issue.
In my case,
all of successfully removed channel's transaction was
>     input : witness_v0_scripthash 
>     output : witness_v0_keyhash

And on "removing" state channel's transaction is
>     input : witness_v0_scripthash 
>     output : witness_v0_scripthash

**Comment by mrfelton** [comment]
The whole channels functionality has had an overhaul both in Zap and in Lnd itself since this issue was created over a year ago. I'm going to close this issue as no longer relevant but please feel free to open a new issue if you experience this problem with recent versions of lnd/zap.
