### ISSUE TITLE
Prompted to unlock wallet when connecting to an already unlocked wallet

### ISSUE THREAD

**Issue by dannybitgo** [LN-Zap/zap-desktop#2576]
## Detailed Description
My node is running on a cloud server 24/7. It is already unlocked, and I have a script on that keeps it unlocked at all times. I want to be able to control my node from Zap Desktop. Connecting to it works great, using the hostname, TLS cert, and macaroon. However, once it connects, I am forced to type in my wallet password to unlock the wallet. This blocks me because 1) my wallet is already unlocked (its running 24/7). and 2) My password is stored secretly on the server and backed up to a backup disk. I'd rather not have to take my password off that disk.

Ideally Zap would recognize that my wallet is already unlocked, possibly with a simple "getinfo" rpc call. If the getinfo provides the "needs unlock" error, then send me to the wallet password page. If the getinfo call succeeds, just take me straight to my node's page in Zap.

## Context

It seems that Zap makes the assumption that my node is down until Zap starts and launches it. This assumption does not work with my node. My node is containerized in a cloud cluster and is designed to auto-restart and have as close to 24-7 uptime as possible, regardless of what my Zap controller is doing.

## Your Environment

- Lnd version 0.7.0-beta
- Zap version: 0.5.0-beta
- Operating System and version: Mac 10.13.6

**Comment by JimmyMow** [comment]
@dannybitgo this is strange. I have the same setup, and Zap detects when my node is locked or unlocked, and the UI is smart enough to take me to the wallet or allow me to authenticate.

Your ideal scenario is how Zap is supposed to behave. I know this is crazy, but are you sure the wallet is unlocked when launching Zap? Is there a way to verify by making `lncli` command line calls to LND and then cross-testing with launching Zap?

**Comment by dannybitgo** [comment]
> @dannybitgo this is strange. I have the same setup, and Zap detects when my node is locked or unlocked, and the UI is smart enough to take me to the wallet or allow me to authenticate.
> 
> Your ideal scenario is how Zap is supposed to behave. I know this is crazy, but are you sure the wallet is unlocked when launching Zap? Is there a way to verify by making `lncli` command line calls to LND and then cross-testing with launching Zap?

Yeah, i can connect to it from my local command line `lncli` with the same credentials just fine and server logs show that the node is unlocked and running. 

I recently configured a Testnet node with my same Zap Desktop and didn't need a password either. I wonder if maybe Zap thinks my Mainnet node is a testnet node, which could would make it think its locked

**Comment by dannybitgo** [comment]
Maybe the network (testnet/mainnet) is a global variable somewhere and doesn't get cleared before trying to connect to a new node

**Comment by mrfelton** [comment]
@dannybitgo did you start your lnd node with any special flags, like `--noseedbackup`?

Can you try running the app in debug mode and share the log output with us from where it tries to connect?

```
DEBUG_PROD=1 DEBUG_LEVEL=debug /path/to/zap
```

See https://github.com/LN-Zap/zap-desktop/blob/master/docs/DEBUGGING.md

**Comment by dannybitgo** [comment]
Thanks @JimmyMow and @mrfelton for the responses - after looking into this further, I'm pretty sure it's an issue on the authentication proxy server that I have set up as a grpc wrapper around my lnd node, and its not an issue with Zap. 

It appears that Zap sends an `unlockWallet` grpc call to the node and examines the response to check if it is unlocked or not. My proxy server is wrongfully expecting the `unlockWallet` to have a macaroon header, but the grpc spec does not require it, and Zap correctly does not provide one. 

I will fix my proxy server accordingly. Looks like Zap is all good here.

**Comment by dannybitgo** [comment]
Apologies, I should have mentioned my grpc proxy wrapper in the original post -_-
