### ISSUE TITLE
Error when zap application is closed

### ISSUE THREAD

**Issue by mntetai** [LN-Zap/zap-desktop#258]
![image](https://user-images.githubusercontent.com/1884392/35503394-ac6a37d0-04e8-11e8-8022-faf5ab6cad13.png)

**Comment by mrfelton** [comment]
@mntetai I believe this issue to be resolved in the master branch. Please can you try to reproduce and verify? Thanks

**Comment by mntetai** [comment]
I have not encountered it again since march.

**Comment by mntetai** [comment]
Closing issue.
