### ISSUE TITLE
Crazy LND error when sending a payment

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#2580]
I tried sending a payment and got a crazy LND error. I think from a UX point of view this is not great, and we should maybe default to `Error sending payment` if the error is too crazy. I can see this really scaring users

<img width="921" alt="Screen Shot 2019-07-14 at 11 34 14 AM" src="https://user-images.githubusercontent.com/4040039/61186480-81067780-a62b-11e9-86d1-d756062a104c.png">

**Comment by korhaliv** [comment]
@JimmyMow Perhaps we could show truncated or generic version and have some kind of `more` or `details` button. These extended error messages are very helpful when users create corresponding GH issues.

**Comment by korhaliv** [comment]
See #2584

**Comment by korhaliv** [comment]
Closed via #2584
