### ISSUE TITLE
Closing channel card shows funding transaction

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#2581]
After closing a channel this is the card view I'm shown:

<img width="921" alt="Screen Shot 2019-07-14 at 11 36 44 AM" src="https://user-images.githubusercontent.com/4040039/61186496-bad77e00-a62b-11e9-997b-82f9ea71a293.png">

As a user, I am personally more interested in the newly broadcasted closing transaction. I think Zap should show the closing transaction instead

**Comment by korhaliv** [comment]
@JimmyMow the same logic should probably apply to a card itself 
![image](https://user-images.githubusercontent.com/14069193/61189175-1b95a380-a68a-11e9-8419-f3ef29ce723a.png)

**Comment by korhaliv** [comment]
@JimmyMow I've checked the code and am fairly sure we are displaying both funding and closing tx in that popup. For instance 
![image](https://user-images.githubusercontent.com/14069193/61202344-8a551a00-a6e7-11e9-8027-7b5c9e5d18ac.png)

The only reason why you are not seeing that must that either closing tx wasn't broadcasted at that point by the LND or somehow we didn't get that update. Could you please keep an eye on that? I'm trying to repro it too. Also, in the card view we indeed were always showing only funding tx. See #2583  that addresses that
