### ISSUE TITLE
Adding USD price equivalent 

### ISSUE THREAD

**Issue by kondev85** [LN-Zap/zap-desktop#259]
In Request page, you can add what is the equivalent USD of the amount you request in BTC. In that way, when you are requesting funds, you are double checking if you are not making mistake and feel more secure. Such design have Nano ledger wallet and it is quite easy to use.

-Also adding USD equivalent will be very beneficiary when you compare by the time of requesting how much was worth btc when you look at past transactions

- if you are adding such feature, please do it with mind additional improvements to be made easily, and people to choose alternative currency like euro

- please add it as well for balance screen and request screen

**Comment by Empact** [comment]
The USD is shown on the request page as of #323. Not on the transactions list yet, neither do we have multiple fiat currencies supported. Feel free to open separate issues for those if you like!
