### ISSUE TITLE
Failed to open zap on Ubuntu 18.04 (/opt/zap not found)

### ISSUE THREAD

**Issue by dannypaz** [LN-Zap/zap-desktop#2590]
Installing zap w/ `Zap-linux-amd64-v0.5.1-beta.deb` on Ubuntu 18.04.2 LTS. Deb is loaded/installed through `Ubuntu Software`.

When I try to open the application using search, I get the error `Failed to open zap /opt/zap not found` which makes sense because the app is actually at `/opt/Zap` on the system.

**Comment by mrfelton** [comment]
Thanks for the report @dannypaz . We will however be dropping support for the `.deb` build. Moving forwards, please use the `AppImage` instead.
