### ISSUE TITLE
Pending Open Channel - Stuck for Weeks

### ISSUE THREAD

**Issue by squatz1** [LN-Zap/zap-desktop#2591]
So I had had my Zap-Desktop on AutoPilot, and due to this it has opened some channels. One of them had been pending, and it is still pending for weeks. I'm unable to close / force close it as it is still open.

Also -- The TX that it has provided to show that it's opening can't be found, which is why this is still stuck.

Channel should open and then allow me to close it.

## Steps to Reproduce

- 1.
- 2.
- 3.
- 4.

## Context

I'm trying to withdraw my funds, though I'm stuck on pending.

## Your Environment

- Zap version: Newest verison
- Operating System and version: Windows 10

**Comment by squatz1** [comment]
This is still an issue, I still have $ stuck here. 

Please do let me know if the pending is ever going to go away.

**Comment by grubeli** [comment]
DONE.
Okay. I found a way to return our funds.
if your funds are stuck like mine, I mean you send them from Zap (on-chain) wallet to Zap Lightening and is stuck on Pending.
What you need is to copy your recovery words, download new app on a different PC and recover (!) your wallet from the seed numbers you copied before. if you don't have a different PC you can use virtualization software like virtualbox (https://www.virtualbox.org) to create a virtual PC and install Zap on it.

After that, when you open your Zap on that new PC you will see all your coins on On-Chain, it means you can send it back to your original account/address or any other address
