### ISSUE TITLE
Channel closure not represented in Zap, despite closing transaction confirmed

### ISSUE THREAD

**Issue by bitgosh** [LN-Zap/zap-desktop#260]
I closed a channel about 20 hours ago, the transaction has 180 confirmations, but the contacts tab still shows the channel as pending - _removing_ is written in red. Also, the locked funds have not become available again. 
Tx link: https://testnet.smartbit.com.au/tx/a601f1f7230018588c3ca632c7a1cca1a94553d55829fccf81894483e2ff166d

Tx hash: 82fabe4870d15a86012c87f316f9c46d4c04fe4f02be5965ba2d09ce7ff611fa

Screenshot: 
![screen shot 2018-01-29 at 6 26 09 pm](https://user-images.githubusercontent.com/35896605/35521440-69c88140-0522-11e8-87e5-0de241aef096.png)

**Comment by Empact** [comment]
Closing as dup of #257
