### ISSUE TITLE
USD amount not populated on send all

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#2602]
When toggling the `Send all of your funds` toggle in the pay form, the USD amount is not populated:

<img width="633" alt="Screen Shot 2019-07-23 at 10 22 34 AM" src="https://user-images.githubusercontent.com/4040039/61724722-227c8000-ad34-11e9-9545-cb2fe99ed563.png">

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/2624
