### ISSUE TITLE
On-chain fee doesn't change when toggling between slow, medium, fast

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#2615]
I'm using Zap Desktop 0.5.1-beta local wallet (neutrino). When attempting to send an on-chain transaction, toggling my fee between `slow`, `medium` and `fast` didn't do anything. I checked my preferences and my confirmation targets were 1, 10 and 60.

<img width="936" alt="Screen Shot 2019-07-25 at 11 28 39 AM" src="https://user-images.githubusercontent.com/4040039/61891717-e847e580-aecf-11e9-92ae-bac269a27e69.png">
<img width="930" alt="Screen Shot 2019-07-25 at 11 28 35 AM" src="https://user-images.githubusercontent.com/4040039/61891718-e847e580-aecf-11e9-9665-adfeddb6d4ba.png">
<img width="936" alt="Screen Shot 2019-07-25 at 11 28 30 AM" src="https://user-images.githubusercontent.com/4040039/61891719-e847e580-aecf-11e9-9f12-97cf46076ccb.png">

**Comment by korhaliv** [comment]
@JimmyMow I've done some testing and for me, it was working as expected. I also have the same settings as you do, and LND fee estimator was returning the following values:
```
{fast: 1, medium: 6, slow: 60} 
{fee_sat: 13550, feerate_sat_per_byte: 96} 
{fee_sat: 12847, feerate_sat_per_byte: 91} 
{fee_sat: 12847, feerate_sat_per_byte: 91}
```
So they are very close and I can imagine that sometimes they can be the same. This is not to say that I'm 100% sure there is no bug in our code. So let's keep this issue open for some time and test some more.

**Comment by JimmyMow** [comment]
Yeah, I am comfortable closing this. I'm not seeing this issue anymore
