### ISSUE TITLE
Cannot right-click to paste Payment Shortcut, must CTRL+V

### ISSUE THREAD

**Issue by CryptoChronicus** [LN-Zap/zap-desktop#263]
I am running Windows 10 Pro, and I am unable to paste the Payment Invoice url/shortcut into place, I have to use CTRL+V. RIght-clicking the appropriate place does nothing.
![screenshot_4](https://user-images.githubusercontent.com/34789878/35536289-12657324-050c-11e8-8bd4-1d7a037ae832.png)

**Comment by MilosoBit** [comment]
Same issue with Ubuntu 16.04.

**Comment by CryptoChronicus** [comment]
Milo, can you still paste using CTRL+V (GUI) or SHIFT+CTRL+V (in command line) and get it to paste the URI into place?

**Comment by MilosoBit** [comment]
Forgot to write it down, but yes, copy/paste is fine, it’s the same issue you described.

**Comment by JimmyMow** [comment]
fixed in #270
