### ISSUE TITLE
UI overall window default dimensions is very tall & narrow

### ISSUE THREAD

**Issue by CryptoChronicus** [LN-Zap/zap-desktop#265]
just look at the the screenshot. Every time I open a new instance of ln-zap it looks like that.

![screenshot_2](https://user-images.githubusercontent.com/34789878/35591106-79d0d928-05ce-11e8-8099-2a14d6331b69.png)

Once I move the window any amount at all, it snaps to a less-tall&narrow... more square, normal-looking window
![screenshot_3](https://user-images.githubusercontent.com/34789878/35591122-8ad101a8-05ce-11e8-8637-0bd564010f9c.png)

Windows 10 Pro, 1600x900.

Not a big deal, but a little bothersome.

**Comment by mrfelton** [comment]
I'm going to close out this issue as I'm unable to reproduce with the current version of Zap, and this issue was created 9 months ago. Please feel free to reopen if this is still a problem for you @CryptoChronicus
