### ISSUE TITLE
Implement Skeleton Loading Screens

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#2654]
Right now, when Zap is loading for whatever reason, we have this gradient animation with our bolt. I actually think it looks pretty cool but there are much bigger UX wins to be had.

An obvious one is skeleton loading screens. Through various studies that have proven to be much more effective at reducing the cognitive load for users, keeping users engaged and reducing the rate at which users leave the application.

To implement them for starters, here are the below images:

![skeleton_loading_wallet_02](https://user-images.githubusercontent.com/4040039/62175060-d6b47280-b301-11e9-813d-5ab9a459f0ca.png)
![skeleton_loading_wallet_01](https://user-images.githubusercontent.com/4040039/62175061-d6b47280-b301-11e9-89d6-b193abf9b9fc.png)

The screens should be animated as if it's going from light to dark. Also, I'd like to use this issue to highlight the other Zap UIs that will need skeleton loading screen designs. Channel UI? Anything else?

**Comment by mrfelton** [comment]
Some work was done on this a while back in https://github.com/LN-Zap/zap-desktop/pull/2413 although the approach there was to show the skeleton items when the activity list is empty (ie, after new wallet creation) where as I think the intention here is to show it whilst the app is in a loading state.

**Comment by bolatovumar** [comment]
Skeleton screens are very useful when the app takes a while to load resources or fetch data. In my experience Zap is pretty zappy and I never have to wait for stuff to load. I'm wondering what areas of the UI would benefit the most from this.

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/2879

**Comment by bolatovumar** [comment]
Weird thing is that this change made me perceive the loading process to be slower than it previously did even though it's not actually slower. It could be that it's just me though.
