### ISSUE TITLE
Switching to the testnet

### ISSUE THREAD

**Issue by Imadlekal** [LN-Zap/zap-desktop#2657]
I've managed to set Zap wallet (Desktop) without issues  (Zap 0.5.1 Beta) but from what I can see, by default, the wallet created is set to the mainnet network.

Is it possible to switch or create another wallet in the testnet? If not through the UI, how can I build it from the source?

**Comment by mrfelton** [comment]
Hi, yes it's possible. I've just written up some docs for how you can edit the config:

Please see https://github.com/mrfelton/zap-desktop/blob/docs/config/docs/CONFIG.md

Also see https://github.com/LN-Zap/zap-desktop/blob/master/docs/ADVANCED.md

After changing the config values you can create your own build by running `yarn package --mac` (or `--win` for windows / `--linux` for linux)

**Comment by Imadlekal** [comment]
The first link is no longer functional?

**Comment by mrfelton** [comment]
Hi. Sorry about that - it was just merged into master. Please see https://github.com/LN-Zap/zap-desktop/blob/master/docs/CONFIG.md

**Comment by Talkless** [comment]
@mrfelton 
>After changing the config values you can create your own build....

To make sure I've got it right - in order to run Zap on testnet one needs to build it from source, i.e. it's not possible to make `.AppImage` executable to work on testnet?

**Comment by mrfelton** [comment]
Currently yes, that’s correct for neutrino nodes. If you have you own testnet node then you can connect to that directly without any changes.

**Comment by Talkless** [comment]
Oh, so I need to run testnet `lnd` node and then I will be able to choose it?

**Comment by mrfelton** [comment]
That is one option yes. Other option is to edit the config, build the app yourself and then you can create testnet neutrino nodes yourself directly in Zap without needing to run a node externally
