### ISSUE TITLE
PAY window BTC amount text box needs more room. Some clipping occuring.

### ISSUE THREAD

**Issue by CryptoChronicus** [LN-Zap/zap-desktop#266]
can't see the whole amount

![screenshot_5](https://user-images.githubusercontent.com/34789878/35592356-593ee99e-05d2-11e8-8134-c0b85aaf4929.png)

Maybe make the text box bigger, and the font smaller? See if it still clips off some of the amount?

**Comment by mrfelton** [comment]
This issue refers to an older version of the UI. Closing this issue as it is no longer relevant.
