### ISSUE TITLE
Transaction popup window should be large like pay or request window.

### ISSUE THREAD

**Issue by bitcoinuser** [LN-Zap/zap-desktop#267]
Hi,

I think the transaction popup window, like this one:

![captura de tela de 2018-01-30 19-13-25](https://user-images.githubusercontent.com/1178856/35592874-7d335ef2-05f5-11e8-9b6c-56a1a607f456.png)

Should be large like Pay or Request window, but, of course, with transaction information.

![captura de tela de 2018-01-30 19-12-56](https://user-images.githubusercontent.com/1178856/35592893-8e1cb61e-05f5-11e8-9f0e-97bd74336036.png)

**Comment by JimmyMow** [comment]
Going to close this as this is a design request. To chime in on design details please join our slack
