### ISSUE TITLE
Add explanation for why the fee is unknown when sending a LN payment

### ISSUE THREAD

**Issue by bolatovumar** [LN-Zap/zap-desktop#2676]
I wonder if it would be useful to add an explanation for why the fee is unknown when sending an LN payment.

![Screen Shot 2019-08-02 at 3 45 13 PM](https://user-images.githubusercontent.com/1934678/62371319-3a76af80-b53d-11e9-9644-c14a3943a00b.png)

## Context

Seeing an "unknown" fee could confuse some people and make them wonder if they are going to overpay in fees.

## Possible Implementation

Use the tooltip component with an explanation like in the "Receive Bitcoin" screen (see screenshot below)
![Screen Shot 2019-08-02 at 3 47 19 PM](https://user-images.githubusercontent.com/1934678/62371268-0d2a0180-b53d-11e9-915b-29e61846afb1.png)

## Your Environment

- Zap version: 0.5.2-beta

**Comment by JimmyMow** [comment]
@bolatovumar hmmm, the only reason you would see this is because you don't have enough funds I think? Maybe the error in the bottom should be more apparent to the user? Either way, nice suggestion this makes sense to me

**Comment by bolatovumar** [comment]
@JimmyMow I mean specifically about the "Fee unknown" row in the "Send Bitcoins" table. As I understand we do not know the exact fee ahead of time because your payment may be routed through nodes which can have different routing fees, right? In any case the fee is probably going to be very small. This type of explanation in a tooltip could help those new to Lightning. Else it feels weird to send a payment with an "unknown" fee.

**Comment by mrfelton** [comment]
`Unknown` will show if `queryRoutes` failed to return a potential route for any reason. This often indicates that the payment is likely to fail since there are no known routes, although this may not always be the case.
