### ISSUE TITLE
Allow closing error message modals with Escape key

### ISSUE THREAD

**Issue by bolatovumar** [LN-Zap/zap-desktop#2677]
I would like to be able to close these types of error message modals with Escape key just like all other modals:
![Screen Shot 2019-08-02 at 5 34 25 PM](https://user-images.githubusercontent.com/1934678/62377819-2edeb500-b54c-11e9-996c-cfe25a7c503e.png)

**Comment by JimmyMow** [comment]
Nice feature request @bolatovumar.

Concept ACK

**Comment by bolatovumar** [comment]
@JimmyMow this already works for other types of modals so I expected it to work for the error ones as well.

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/2687
