### ISSUE TITLE
[Win 10 pro] issue on installation

### ISSUE THREAD

**Issue by crive69** [LN-Zap/zap-desktop#268]
On installing the windows version (win-release-v0.1.0-beta.zip by using 'zap Setup 0.1.0.exe') i got this issue. After this issue the program is trieing to open and load zapp, but without success (it keeps stuck at 'loading')

this is the popup message:

A javascript error occured in the main process

uncaught exception:
Error: 'wmic' is not recognized as an internal or external command,
operable program or batch file.

at
C:\Users\myuser\Appdata\local\programs\zap-desktop\resources\app.asar\webpack:\app....:11
at
C:\Users\myuser\Appdata\local\programs\zap-desktop\resources\app.asar\node_module.....:14
at ChildProcess.<anonymous>
(C:\Users\myuser\Appdata\local\programs\zap-desktop\resources\app.asar\node_module.....:7)
at emitTwo (events.js:106:13)
at Childprocess.emit (event.js:191:7)
at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by JimmyMow** [comment]
weird, is `wmic` not in your PATH?

**Comment by jtayrone** [comment]
I believe this is related to LND if you have it installed on your computer. To troubleshoot remove LND or run first then run ZAP.

**Comment by JimmyMow** [comment]
Feel free to reopen this but I'm going to close for now, seems like an old LND issue
