### ISSUE TITLE
Add pin/password protection

### ISSUE THREAD

**Issue by Relaxo143** [LN-Zap/zap-desktop#2693]
On the android wallet app, there is a pin prompt every time I start the app. On the windows desktop app there is no such security. Anyone can just start Zap and send away one's entire balance.

**Comment by mrfelton** [comment]
Hi @Relaxo143 thanks for your suggestion. We already have an issue tracking this at https://github.com/LN-Zap/zap-desktop/issues/1387 so I'm going to close this as a duplicate.
