### ISSUE TITLE
List on-chain + LN payments in payments list ordered by timestamp

### ISSUE THREAD

**Issue by jackmallers** [LN-Zap/zap-desktop#27]
The payments list should include on-chain + LN payments ordered by timestamp. Check with @brandnanthny and @jackmallers for design wireframes

**Comment by jackmallers** [comment]
https://github.com/LN-Zap/zap-desktop/pull/32

**Comment by fresheneesz** [comment]
Does this mean the todo item "List on-chain transactions" in the readme can be checked off?
