### ISSUE TITLE
Show corresponding invoice memo for completed payment

### ISSUE THREAD

**Issue by lexis-t** [LN-Zap/zap-desktop#2715]
## Detailed Description

When some adds invoice to lightning node it is possible to set memo field for it.
![invoice](https://user-images.githubusercontent.com/694511/62720957-cd1ebf00-ba13-11e9-9d78-b23530eeb764.png)

Unfortunately when the invoice is paid Zap does not show this memo at payment details.
![payment](https://user-images.githubusercontent.com/694511/62721004-efb0d800-ba13-11e9-93d6-f25d6b76b8b8.png)

## Context

It is really messy when you do not know what was a purpose of previous payments. Especially in case a shop was provided the info with invoice.  

## Possible Implementation

Starting from one of latest lnd beta (0.7.1?) ListPaymentResponse contains optional PaymentRequest field for every payment.

## Your Environment

- Zap version: 0.5.1-beta
- LND version: 0.7.1
- Operating System and version: Ubuntu 18.04.3 LTS

**Comment by korhaliv** [comment]
Closed via #2722
