### ISSUE TITLE
Add a symbol for satoshis

### ISSUE THREAD

**Issue by kek-coin** [LN-Zap/zap-desktop#2725]
## Detailed Description

Currently no symbol is in use for the satoshi denomination, however it would be nice to use one. 

## Context

This would help to reduce the amount of screen real estate taken up by text, making it easier to get an overview of what is going on on the screen at a glance.

## Possible Implementation

https://github.com/bitficus/theSat/ is a very nice concept.

**Comment by bolatovumar** [comment]
I like the idea in principle but I think there are a couple of issue that need to be resolved first before we can start using the "sats" symbol:

1. Zap allows switching between units (BTC, bits and satoshis). Would we show the sats symbol for satoshis and have text for BTC and bits? This could end up looking very weird.
2. I don't think there is really a consensus around how the "sats" symbol should look like yet which might confuse those users who are outside of the crypto-twittersphere.

I do think wallets will probably switch to some sort of symbol at some point but we might not be there yet.

**Comment by mrfelton** [comment]
Perhaps we could consider shortening satoshis to sats, which could be considered to be more inline with the other units we use, but personally I don’t we should use the symbol. It’s just not well recognised enough. Even the abbreviation sats instead of satoshis may end up only raising more questions from new users.

**Comment by mrfelton** [comment]
We could also consider adding an option to the preferences page to enable users choose between symbol or text display for the currency units, though I’m not sure if it’s really too much value.

**Comment by bolatovumar** [comment]
@mrfelton if we were to do that we have a symbol for BTC which is pretty well known, a symbol for sats which is not well known (and may still change) and no symbol for bits as far as I'm aware.

It's probably not worth it at the moment.

**Comment by kek-coin** [comment]
@mrfelton why would you think the abbreviation of "sats" would end up raising questions? Seems imho very likely to become the common way to refer to the base unit. And it seems like a good way to bring the length of the denomination more in line with "bits" and "BTC".

Fair point that it wouldn't make sense to use symbols unless every denomination had one.

**Comment by mrfelton** [comment]
> why would you think the abbreviation of "sats" would end up raising questions

@kek-coin just because the unit is more commonly known as satoshi. sats is a relatively new abbreviation that I suspect less people would be aware of. Could be wrong though.

> It's probably not worth it at the moment.

@bolatovumar that's my general feeling as well.

**Comment by bolatovumar** [comment]
Blockstream Green now has this sats symbol in the latest release:
https://www.reddit.com/r/Bitcoin/comments/ctoyyn/sats_denomination_in_blockstream_green_wallet_by/

**Comment by mrfelton** [comment]
I'm going to close this issue as I don't think it's something that adds much value right now. Perhaps we can reassess in the future.
