### ISSUE TITLE
Do not see on-chain bitcoin balance after cooperative close

### ISSUE THREAD

**Issue by richuurd** [LN-Zap/zap-desktop#2729]
Do not see on-chain balance in wallet after cooperative closing of 2 channels. Has been over 1 week (1545 blocks). 

Closing of channels confirmed in block explorer, but don't see anything in wallet.

I can only see the +4xx,xxx satoshis and +89,xxx satoshis under the "internal" dropdown menu. Nothing under "all."

I expected to see on-chain balance updated

- Zap version: 0.6.0
- Operating System and version: Windows 10 Pro x64

**Comment by bolatovumar** [comment]
@richuurd See issue #2278. It seems related to your issue.

**Comment by richuurd** [comment]
> @richuurd See issue #2278. It seems related to your issue.

Thanks for the reply. Went through the thread, but there was no mention of ability/inability to access funds.

The issue I have is that I can't move any of it because it doesn't show up in the balance.

![Zap](https://user-images.githubusercontent.com/33888496/63005831-29c61380-be32-11e9-8325-fa7d50c51333.png)

**Comment by bolatovumar** [comment]
@richuurd what does the "Pay" screen show? I'm interested in the bottom section. Does it show 0 for everything?

![Screen Shot 2019-08-15 at 10 41 39 AM](https://user-images.githubusercontent.com/1934678/63080342-6cc6da80-bf49-11e9-9bee-4f4e4123df54.png)

**Comment by richuurd** [comment]
![Zap2](https://user-images.githubusercontent.com/33888496/63123736-86bee800-bf5e-11e9-821b-c2206b530f54.png)

Yessir, indeed. I recently got a Casa node, so I closed all my channels on Aug 2/19 in an attempt to transfer them on-chain to the device.

**Comment by bolatovumar** [comment]
This is weird. Well, if all of your channels are closed (you can confirm this by going to the "Channels" menu item) you can safely restore your wallet with the seed you got when setting it up.

Also make sure Autopilot isn't activated and it's not trying to open new channels.

**Comment by richuurd** [comment]
> This is weird. Well, if all of your channels are closed (you can confirm this by going to the "Channels" menu item) you can safely restore your wallet with the seed you got when setting it up.
> 
> Also make sure Autopilot isn't activated and it's not trying to open new channels.

Yes, all the channels are closed. I actually don't see an option for Autopilot on any of the menus on 0.6.0 anymore. 

Also, can you point me in the right direction for restoring my wallet? I have my seed, but I don't see any option for deleting and restoring wallet on the interface. Should I uninstall and reinstall Zap?

Thanks again

**Comment by bolatovumar** [comment]
![Screen Shot 2019-08-22 at 11 17 37 AM](https://user-images.githubusercontent.com/1934678/63498445-95f9e480-c4ce-11e9-90b2-27ea83cb74b9.png)
Autopilot settings are on the "Settings" screen for your wallet.

You can restore your wallet from a seed from the same screen by clicking on "Create new wallet" button on the bottom left. Click on "Recover" after clicking on "Create new wallet".

**Comment by richuurd** [comment]
Ok, this is really strange. I don't even see a Settings menu. Just Preferences, Profile, Disconnect, then Currency, Language, and Theme

**Comment by mrfelton** [comment]
If you disconnect from the wallet then you will be taken to the launchpad area where you can configure your wallets.

However it sounds like you are connected to an external lnd node, and we only support configuring autopilot for the internal neutrino node:

**Comment by richuurd** [comment]
You know what, I'm just dumb. I'm checking 'listchaintxns' and realised that I had already transferred it out. Please ignore -_-
