### ISSUE TITLE
Center content in "Retype your seed" screen for better visual appearance

### ISSUE THREAD

**Issue by bolatovumar** [LN-Zap/zap-desktop#2730]
Currently you see this in the "Retype your seed" screen:
![Screen Shot 2019-08-13 at 9 25 20 AM](https://user-images.githubusercontent.com/1934678/62920003-0d33c800-bdad-11e9-93f3-95123d75702d.png)
Notice how the input fields throw the layout off-balance to the left. I propose centering content like this:
![Screen Shot 2019-08-13 at 9 24 03 AM](https://user-images.githubusercontent.com/1934678/62920070-4a985580-bdad-11e9-9dd7-f922f2e7cbc6.png)
Notice the improved visual appearance (imo).

**Comment by mrfelton** [comment]
I also think I prefer that. Thoughts @JimmyMow ?

**Comment by bolatovumar** [comment]
Another option could be to show them in a single row instead of a column but I think the centered column layout works fine.

**Comment by bolatovumar** [comment]
Closing the issue as PR was merged.
