### ISSUE TITLE
Allow seeing the password when setting it

### ISSUE THREAD

**Issue by bolatovumar** [LN-Zap/zap-desktop#2731]
I was looking at https://github.com/lightninglabs/lightning-app and they allow you to click on this little icon which allows you to see your password when you set it before you proceed further.

![Screen Shot 2019-08-12 at 9 49 16 PM](https://user-images.githubusercontent.com/1934678/62920422-65b79500-bdae-11e9-91dd-fe485b897f11.png)

Zap doesn't let you see your password when you set it:

![Screen Shot 2019-08-13 at 9 26 03 AM](https://user-images.githubusercontent.com/1934678/62920510-a9120380-bdae-11e9-8a7a-d01e68c780f5.png)

## Context

I get nervous when creating wallets because I might mistype the password. I imagine others feel the same. The Lightning Labs lightning app allows you to see your password once you typed it for ease of mind. It also makes you confirm it on the next screen so you can see it twice before you are totally set. I feel like having to confirm it is a bit of an overkill if you allow users to see their password on the first step.

## Possible Implementation

Allow clicking on an icon which would show the password to the user when they set it.

## Your Environment

- Zap version: 0.6.0-alpha

**Comment by bolatovumar** [comment]
Luckily enough there is already an [eye.svg](https://github.com/LN-Zap/zap-desktop/blob/master/icons/eye.svg) icon which would work quite well here.

**Comment by mrfelton** [comment]
Good suggestion @bolatovumar . This is a pretty common UX pattern that we should probably look to adopt.

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/2736
