### ISSUE TITLE
Remove unused icon SVG files and React components

### ISSUE THREAD

**Issue by bolatovumar** [LN-Zap/zap-desktop#2740]
From the Slack discussion earlier:

> jimmymow 6:09 PM
> sup friends
> i think the feather stuff was from a design contributor like two years ago, i don't think those are used anymore

> mrfelton 6:11 PM
> Probably a good maintenance chore to do a review of the icons that we have in the codebase and remove any unused ones. I suspect about 30% of them can go

There are a bunch SVG icons and corresponding React components under `renderer/components/Icon/` many of which are unused. Probably a good idea to do some clean-up and remove the unused ones.

**Comment by korhaliv** [comment]
Closed via #2797
