### ISSUE TITLE
Add an e2e test for importing an encrypted seed

### ISSUE THREAD

**Issue by bolatovumar** [LN-Zap/zap-desktop#2756]
There was a bug when importing an encrypted seed where you would either get an error modal or Zap would hang (see #2751). There should be an e2e test which tests importing an encrypted seed. 

There is currently an e2e test which tests importing a regular seed. Existing test could be updated to test an encrypted seed or a new test could be created to test importing an encrypted seed.

**Comment by bolatovumar** [comment]
An example encrypted seed if needed:
abandon naive angry envelope execute great iron fee obtain allow path position forum monkey invite canal paper crouch pilot knee tiger best pigeon believe

Passphrase: lol

**Comment by bolatovumar** [comment]
I was pretty sure I opened a PR for this but I guess I never did. I can open a PR.

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/2971
