### ISSUE TITLE
How do I receive on-chain payments?

### ISSUE THREAD

**Issue by Deekee62** [LN-Zap/zap-desktop#2760]
## Description

It seems that I'm unable or simply don't know on how to receive on-chain payments with the zap-desktop on a MacBook, using the iOS App it just works fine.

## Expected Behavior

On my iPhone I'm able to receive on-chain payments when I click "Receive":

![UNADJUSTEDNONRAW_thumb_1efc](https://user-images.githubusercontent.com/33904339/63110568-08793a80-bf8c-11e9-9d2b-c868447d4e86.jpg)

..and then "On-chain":

![UNADJUSTEDNONRAW_thumb_1efb](https://user-images.githubusercontent.com/33904339/63110465-cb14ad00-bf8b-11e9-8187-5c118fdf6818.jpg)

## Actual Behavior

But on my MacBook this option doesn't seem to exist, when clicking on "Receive":

![UNADJUSTEDNONRAW_thumb_1efd](https://user-images.githubusercontent.com/33904339/63111903-14b2c700-bf8f-11e9-8ae8-d24b3b73327b.jpg)

I don't have this option!

![UNADJUSTEDNONRAW_thumb_1efa](https://user-images.githubusercontent.com/33904339/63110661-46765e80-bf8c-11e9-9958-be9ddc248717.jpg)

## Steps to Reproduce

Use zap-desktop instead of zap-ios

## Context

Unable to make On-chain payment using zap-desktop

## Your Environment

iPhone 
- Zap version: 0.4.0 (48)
- Operating System and version: iOS 12.4

Macbook
- Zap version: 0.4.0 (48)
- Operating System and version: macOS Mojave 10.14.5

**Comment by bolatovumar** [comment]
@Deekee62 it's not very obvious but you can click on that little QR code on the top left where you will be able to generate an on-chain Bitcoin address. The "Receive" modal is for Lightning Network payments only at the moment.
