### ISSUE TITLE
0.1.1 on MacOS shows 0.1.0

### ISSUE THREAD

**Issue by lra** [LN-Zap/zap-desktop#278]
Downloaded from https://github.com/LN-Zap/zap-desktop/releases/download/v0.1.1-beta/zap-mac-release-v0.1.1-beta.zip

It shows 0.1.0 everywhere:
![screen shot 2018-02-02 at 10 36 39 am](https://user-images.githubusercontent.com/122286/35749029-03fdf31e-0805-11e8-898c-b53f7b375d6f.png)
![screen shot 2018-02-02 at 10 36 54 am](https://user-images.githubusercontent.com/122286/35749030-04175890-0805-11e8-9e9e-2fb2a7bd0ee4.png)

**Comment by JimmyMow** [comment]
👍

**Comment by Empact** [comment]
Fixed in 67f09ef02649b5baf853cacd987e33aa51a91811
