### ISSUE TITLE
Connect string can't be hidden in Launchpad

### ISSUE THREAD

**Issue by mrfelton** [LN-Zap/zap-desktop#2785]
## Description

The lndconnect string can't be hidden in the Launchpad.

![image](https://user-images.githubusercontent.com/200251/63449749-fe01e980-c440-11e9-94ea-af0a5e967079.png)

## Expected Behavior

Toggle should show/hide connection string

## Actual Behavior

Toggle has no effect

**Comment by bolatovumar** [comment]
Lol I noticed this as well but assumed this was just some glitch on my end. I can take a look.

**Comment by korhaliv** [comment]
Closed via #2791
