### ISSUE TITLE
Slack invite link is outdated

### ISSUE THREAD

**Issue by nopara73** [LN-Zap/zap-desktop#279]
In the readme:  "Join us on slack to discuss development, design and product."  

You get an error: "This invite link is no longer active."

**Comment by JimmyMow** [comment]
ah, sorry about that. fixed

**Comment by DataCourier** [comment]
Website slack link still outdated, it says "This invite link is no longer active.".
Reproduce using anonymous window, when logged in it goes into the channel so it may be misleading.

There are at least two links - one on homepage, one in top right menu.
