### ISSUE TITLE
Package neutrino within application

### ISSUE THREAD

**Issue by jackmallers** [LN-Zap/zap-desktop#28]
`LND Neutrino` light client should be packaged  with the app and running in the background, the user should not be responsible for running `LND` themselves unless they want to.

**Comment by fresheneesz** [comment]
Would love to see this. I gave up trying to test this because it was too hard to set up. I've been testing this one cause its dead simple (just download and run [and wait for sync]) https://github.com/lightninglabs/lightning-app

**Comment by joaodealmeida** [comment]
@fresheneesz We got it working for macOS. We are just waiting to finish the linux and windows implementations before distributing any binaries.

**Comment by JimmyMow** [comment]
Apologies @fresheneesz, I've been a bit busy with other things. I have this working for Mac, should be trivial to get it working for Linux and Windows.

**Comment by fresheneesz** [comment]
@joaodealmeida Sounds great! @JimmyMow No need to apologize. I wish I had time to help, myself. Excited to try it out with a friend when its ready!

**Comment by joaodealmeida** [comment]
This has been achieved with PR #59 .
