### ISSUE TITLE
Outdated `lnd` linked in README

### ISSUE THREAD

**Issue by lepipele** [LN-Zap/zap-desktop#281]
Just wasted few hours on this... README links to: https://github.com/lightninglabs/lightning-app/tree/master/apps/desktop/bin ... I was getting `lnd shutting down 1` error.

And latest codebase requires updated `lnd` -> https://github.com/LN-Zap/zap-desktop/releases

Reference: https://zaphq.slack.com/archives/C6P5UNJMV/p1517725708000035

I've created pull request that deals with this and includes few other fixes: https://github.com/LN-Zap/zap-desktop/pull/280

**Comment by DataCourier** [comment]
Thanks, I was getting `Uncaught Error: spawn EACCES` and replacing LND with the release one did the trick!

**Comment by JimmyMow** [comment]
fixed
