### ISSUE TITLE
Console error when clicking on the confirmation checkbox when deleting a wallet

### ISSUE THREAD

**Issue by bolatovumar** [LN-Zap/zap-desktop#2828]
See error:
![Screen Shot 2019-09-01 at 12 15 03 PM](https://user-images.githubusercontent.com/1934678/64081173-44adda00-ccb2-11e9-9eff-0cb4fceb92e8.png)

Steps to reproduce:
1. Create a new wallet
2. Click on "Delete wallet" in wallet settings
3. Click "I understand this is an irreversible action" checkbox
4. Notice the error in the console

![Screen Shot 2019-09-01 at 12 23 03 PM](https://user-images.githubusercontent.com/1934678/64081271-7f644200-ccb3-11e9-9cc2-9500daddaf7f.png)

Probably not a big deal but that error looks kind of scary.

**Comment by korhaliv** [comment]
Closed via #2847
