### ISSUE TITLE
Disable text selection in menu with css

### ISSUE THREAD

**Issue by DataCourier** [LN-Zap/zap-desktop#283]
It looks weird to be able to select text in menu and UI where you shouldn't be able to.

Example:
![screenshot 2018-02-04 15 57 43](https://user-images.githubusercontent.com/35670446/35778836-338f8136-09c4-11e8-8b50-16e84695011b.png)

solution:
https://stackoverflow.com/questions/826782/how-to-disable-text-selection-highlighting#4407335

**Comment by JimmyMow** [comment]
@DataCourier Want to submit a PR?

**Comment by JimmyMow** [comment]
Or else I can do it. Seems fairly simple thought 😄

**Comment by DataCourier** [comment]
I'll be getting familiar with the app over the weekends. I'll try to make some PRs, but if anyone wants to grab it go ahead.

**Comment by DataCourier** [comment]
Fixed by https://github.com/LN-Zap/zap-desktop/pull/296
