### ISSUE TITLE
Connect dialog remains open when request payment link (from web) is clicked

### ISSUE THREAD

**Issue by DataCourier** [LN-Zap/zap-desktop#284]
![screenshot 2018-02-04 16 05 48](https://user-images.githubusercontent.com/35670446/35778917-5f777a3c-09c5-11e8-9862-d63afc40af8b.png)

It should hide itself when that happens, or stay open but invisible and once payment is done, it can go back again.

For case like this I would use a popup stack and the payment would be just another popup that would be removed form the stack once completed, not messing with whatever was opened before.

**Comment by JimmyMow** [comment]
👍
