### ISSUE TITLE
Set minimum amount of precision when entering amount

### ISSUE THREAD

**Issue by DataCourier** [LN-Zap/zap-desktop#285]
It looks like I can set any amount of zeroes here:
![screenshot 2018-02-04 16 12 32](https://user-images.githubusercontent.com/35670446/35778976-428adeb8-09c6-11e8-8944-96148a93e7b7.png)

I wanted to know how many zeros a satoshi is so I typed a whole bunch of them and it turns out the field isn't limited.

I'd much more prefer being able to use bits/satoshis than 0.00...x

**Comment by JimmyMow** [comment]
👍

**Comment by DataCourier** [comment]
Playing with this right now, making an AmountInput component that:
- limits the precision to satoshis
- uses number input so non-numbers can't be put in
- supports up/down buttons to change the amount
- does not allow negative numbers

**Comment by Empact** [comment]
FYI the native precision of lightning is milisatoshis, so we will need different precisions for on vs off-chain.

**Comment by DataCourier** [comment]
Addressed in https://github.com/LN-Zap/zap-desktop/pull/322

**Comment by mrfelton** [comment]
@DataCourier could you rebase this off master please?

**Comment by mrfelton** [comment]
This has been fixed in the current master branch.
