### ISSUE TITLE
How to get unstuck on testnet?

### ISSUE THREAD

**Issue by DataCourier** [LN-Zap/zap-desktop#286]
So I've:
- received some testnet coins,
- tried opening some channels, but only one actually opened, other say EOF, timeour or are private
- tried paying for articles using Yalls but it fails to display the peer
- tried buying coffee, but they don't show the peer so I googled it, connected but still can't buy coffee (probably old / wrong peer, was pasted somewhere)
- tried connecting to some peers using https://htlc.me/ (including Jacks) but none were successful

Also, the LND seems to be consuming 3/4 of my cores on regular basis (on i7 chip).

What can I do now?

**Comment by JimmyMow** [comment]
Continue to find peers to open channels with? I'm not sure this is a Zap issue. If you were unsuccessful connecting with peers that suggests they were offline, behind firewall, etc. 

If you'd like to join the slack and talk about how to connect to some online testnet shops you're more than welcome but I'm going to close this issue
