### ISSUE TITLE
Documentation - Step by step install process

### ISSUE THREAD

**Issue by silver-moose** [LN-Zap/zap-desktop#288]
It will be nice to have step by step install 
-Cleanup process or implementation /directory
-Stop process background i.e. lnd
-Download nitrino, btcd, lnd, etc. 
-git, npm, or nothing

It could be beneficial, and one day included into the install process (Zap setup)
That will save time for newbies. like me

**Comment by zachgoll** [comment]
@silver-moose Are you referring to a step by step install for developers or for normal users of the wallet?

**Comment by silver-moose** [comment]
@zachgoll I think it's more important for End User - Normal users.
JD/

**Comment by mrfelton** [comment]
From an end user perspective installation steps are provided in the main readme:
https://github.com/LN-Zap/zap-desktop/blob/master/README.md 

From a developer perspective installation steps are detailed in here:
https://github.com/LN-Zap/zap-desktop/blob/master/ADVANCED.md

Additionally, we have a number of more detailed tutorials available here:
https://ln-zap.github.io/zap-tutorials/

I'm going to close this issue as I think we have this fairly well covered now but if there anything specific that you are not clear of or would like to see in addition to the existing material please feel free to reopen this issue. Thanks.
