### ISSUE TITLE
Waiting for peers... loop

### ISSUE THREAD

**Issue by arcbtc** [LN-Zap/zap-desktop#2880]
Are the btcd servers down? I'm getting a "Waiting for peers..." loop on startup?

Been working fine for weeks

**Comment by mrfelton** [comment]
mainnet or testnet?

**Comment by arcbtc** [comment]
Mainnet

**Comment by mrfelton** [comment]
All of our btcd nodes appear to be ok. I also just tested syncing a new mainnet node and it completed without issue.

**Comment by arcbtc** [comment]
Damn, must be my end
Any files I can delete/refresh? I am running the latest app image on ubuntu. I tried downloading another app image, but it's just using the same config files, so the problem persists

**Comment by mrfelton** [comment]
If you delete the `.bin` files in your chain data dir and restart the node it will cause a full resync. It could be worth trying incase your sync got buggered somehow.

e.g.
```
rm ~/Library/Application\ Support/Zap/lnd/bitcoin/mainnet/wallet-1/data/chain/bitcoin/mainnet/*.bin
```

(above command is for mac).

**Comment by arcbtc** [comment]
that makes sense,
So am I removing block_headers.bin, reg_filter_headers.bin?

**Comment by mrfelton** [comment]
Yes, those are the ones

**Comment by arcbtc** [comment]
Sweet! That totally worked, cheers!

**Comment by mrfelton** [comment]
kewl

**Comment by arcbtc** [comment]
Problems back. Deleted files. It creates new ones but the problem persists, with the "Waiting for peers" loop?

**Comment by arcbtc** [comment]
![giphy (3)](https://user-images.githubusercontent.com/33088785/65966611-4822b580-e458-11e9-863e-76790d4911ac.gif)

**Comment by mrfelton** [comment]
Was a temporary issue with one of our nodes. Should be back online now. Thanks

**Comment by tiero** [comment]
I have teh same issue, but in testnet. I have a btcd running online, can I provide to the zap desktop?
