### ISSUE TITLE
Transaction history is omitting received payments

### ISSUE THREAD

**Issue by ohenrik** [LN-Zap/zap-desktop#2881]
Zap Desktop is not showing incoming transactions (received). Not sure what is causing this. Transactions are correctly displayed on zap-ios.

It looks like new received payments show up for a few seconds before they are removed. They are however correctly recorded  

## Expected Behavior

Zap desktop should show both Sent and Received payments.

## Actual Behavior

Zap desktop has stopped showing Received payments from 13. September.

## Possible Fix

Might be a bug with how Zap downloads/requests data from lnd. But i honestly have  no idea.

## Steps to Reproduce

I have no idea how i can reproduce this error. This only happens on one of my nodes.

## Environment

- LND version: 0.7.1

- Zap version: 0.5.1and 0.5.2

- Operating System and version: Ubuntu 19.04.

**Comment by bolatovumar** [comment]
@ohenrik how many transactions do you have? This issue seems similar to #2404. If you have more than 2500 transactions then new ones won't show up I believe.

**Comment by ohenrik** [comment]
I'll need to check that on Monday, but i believe this might be the cause. Maybe there should be some warning or an alert about recommended configurations for lnd to prevent this

**Comment by bolatovumar** [comment]
@ohenrik i don't think this is an LND configuration issue. The maximum number of transactions to request is hardcoded into Zap.

**Comment by JimmyMow** [comment]
I believe this is fixed in master? (cc @korhaliv @mrfelton) 

We are looking to get a minor release out soon (0.5.3)

**Comment by korhaliv** [comment]
@ohenrik are we talking about paid LN invoices (e,g somebody has paid your invoice) or on-chain transactions?

**Comment by mrfelton** [comment]
Zap 0.5.x branch has a hard coded limit of 2500 invoices that it will fetch so if you have any more that they they will not be fetched.

This has been addressed in the `next` branch which now features infinite scrolling to ensure that all invoices can be displayed. This feature will be included in the upcoming `0.6.x` releases.

@ohenrik if you could test with a build from the `next` branch and verify if this resolves your issue it would be greatly appreciated.

Please see https://github.com/LN-Zap/zap-desktop/blob/master/docs/ADVANCED.md for details of how to build from source.
