### ISSUE TITLE
Question - Advance Installation Options

### ISSUE THREAD

**Issue by muhepd** [LN-Zap/zap-desktop#2884]
Hello, I have a question regarding the following statement in the Advance Usage.md

Option 1: default:
Zap installs lnd for you as part of the installation process. Zap will automatically start the internal lnd daemon for you when you select the default connection type during the on-boarding process. In this mode we run lnd as a light client called neutrino (BIP 157 & BIP 158) which allows us to run lnd without requiring a Bitcoin full node on your system - Instead, Zap will connect to one Zap's hosted BTC full nodes.

Question: After creating the wallet, is it possible to access the LND implementation that Zap just installed through LND's REST interface, invoice macaroon and tls.cert? 

I want to use Zap to control the wallet and LND and Bitcoin backend through Neutrino, but I want to be able to create invoices through a website connection to LNDs using Zap's wallet.

Thanks.

M.

**Comment by mrfelton** [comment]
It is possible.

See https://twitter.com/btcsocialist/status/1167861605721227264?s=21

I’ll do a more detailed write up and add to our documentation.

**Comment by mrfelton** [comment]
I put together a brief tutorial here https://docs.zaphq.io/docs-desktop-neutrino-connect
