### ISSUE TITLE
Question : what is the derivation path of wallet?

### ISSUE THREAD

**Issue by panagiotos** [LN-Zap/zap-desktop#2897]
I would like to restore wallet in another client. what is the derivation path of wallet?

**Comment by bolatovumar** [comment]
ZAP uses LND to generate the seed. LND wallets can only be recovered in LND itself as far as I'm aware. Trying to recover your wallet in Electrum, for example, won't work.

Correct me if I'm wrong @mrfelton

**Comment by JimmyMow** [comment]
This is correct. More can be read here: https://github.com/lightningnetwork/lnd/tree/master/aezeed

LND plans on writing a BIP for their new `aezeed cipher seed scheme`
