### ISSUE TITLE
Show channel reserve amount per channel in UI

### ISSUE THREAD

**Issue by muhepd** [LN-Zap/zap-desktop#2910]
Hello,

Would it be possible, when clicking on "more", on the channel detail section, to show also the channel reserved amount? I think this will be valuable for some users that would like to understand why they cannot spend their entire local balance or why the initial channel balance does not match the satoshis assigned during the initial channel creation.

A short explanation of what a channel reserve is and how it varies would be nice too.

Thanks!

Muhepd.

**Comment by bolatovumar** [comment]
This should be possible. Currently 1% of channel balance is reserved I believe. @mrfelton @JimmyMow do you think it would be worth it to surface up this info in the UI?

**Comment by bolatovumar** [comment]
@muhepd I added the requested field to the channel detail view. I used the descriptions from LND's  source code https://github.com/lightningnetwork/lnd/blob/master/lnrpc/rpc.proto#L1233

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/2937
