### ISSUE TITLE
Use Mission Control and loosen up fee limit

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#2952]
Currently, Zap uses `queryRoutes` for a few reasons.

One, we want to give users a fee estimate. Blindly sending the payment over the network could be dangerous if someone has routes cornered and is charging disgustingly high fees.

Two, we want to get a fee estimate and limit the fee a user will pay so they don't think they're paying 1 sat but end up paying 10.

However, there are a few issues with this now that LND has changed a little bit.

One, LND only returns one result from `queryRoutes` now. Because of this, using the fee as the feeLimit when sending the payment might not be best. If that route fails for some reason, the feeLimit may not allow us to try any other routes, failing the payment when there is in fact a route. (This would explain users saying it doesn't work on Zap Desktop but does on Zap iOS, etc.)

Also, when we use `queryRoutes`, we need to set `use_mission_control: true`. Within LND, `MissionControl` contains state which summarizes the past attempts of HTLC. If we queryRoutes without it, we are essentially getting bad guesses and routes that potentially don't work, then using that potential bad route to set a feeLimit, and then trying the payment resulting in more fails than needed. I don't know why `use_mission_control` defaults to false int he LND API, but we should be setting it to true.

Zap iOS doesn't use the feeLimit at all anymore, which we could do. We also use this `retryCount`. If a payment fails the first time, before retrying, we can back off the feeLimit a little bit, then if it fails again, back off once more. However, at that point why are we using the feeLimit at all maybe? Not sure.

Lastly, I'd like to see this go into master. I think it is worthy of a minor release in my opinion.

**Comment by mrfelton** [comment]
@JimmyMow we now set the `use_mission_control` bit in our call to `queryRoutes` as per https://github.com/LN-Zap/zap-desktop/pull/2956. This has been merged into master.

In terms of the limit itself we could do some kind of exponential backoff on the fee limit after each retry attempt. 

For example:

```js
const exponent = 1.2
let $feeLimit = queryRoutes() // e.g. gives result of 2100 msat

// first attempt, use quoted fee fee estimate as fee limit
const res = await sendPayment({..., feeLimit})

// second attempt, increase the limit a bit
if (!res) {
  feeLimit = feeLimit * exponent // 2100 * 1.2 = 2520
  await sendPayment({..., feeLimit})
}

// third attempt, increase a little more
if (!res) {
  feeLimit = feeLimit * exponent // 2520 * 1.2 = 3024
  await sendPayment({..., feeLimit})
}

```

In terms of how we present it to users, we currently show the fee as an approximate amount using one of the following templates depending on the estimates that we got back from `queryRoutes`

```
  fee_less_than_1: 'less than 1 satoshi',
  fee_range: 'between {minFee} and {maxFee} satoshis',
  fee_upto: 'up to {maxFee} satoshi',
```

I think we can just adjust which numbers we use to determine which message to display to factor in the highest possible attempt (eg, `queryRoutes estimate * 1.2 * 1.2`)

**Comment by JimmyMow** [comment]
@mrfelton this can be closed now yeah?

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/3024 and https://github.com/LN-Zap/zap-desktop/pull/2956
