### ISSUE TITLE
Add password confirmation input to set password dialog

### ISSUE THREAD

**Issue by korhaliv** [LN-Zap/zap-desktop#2969]
## Detailed Description
Ensure user confirms the password when setting it up

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/3006

**Comment by shawnyeager** [comment]
I came to enter a feature request for the same thing and found this issue. I see [#3006](https://github.com/LN-Zap/zap-desktop/pull/3006), but that appears to be in Preferences, not on setup?

**Comment by mrfelton** [comment]
Hi @shawnyeager - I created a PR to add password confirmation to the wallet create process here - https://github.com/LN-Zap/zap-desktop/pull/3057 - it's currently going through the review process.
