### ISSUE TITLE
Fix misleading information on recover wallet page

### ISSUE THREAD

**Issue by korhaliv** [LN-Zap/zap-desktop#2978]
## Detailed Description
![image](https://user-images.githubusercontent.com/14069193/66648742-fc7cc280-ec34-11e9-8662-aca28692fd0d.png)
This password is not to be confused with app-password introduced in 2940. Info on this page is misleading and needs to be presented more accurately

**Comment by bolatovumar** [comment]
The difference between this password and the one from #2940 is that this password is specific to a wallet while the one in #2940 is for the whole app?

**Comment by mrfelton** [comment]
That's correct @bolatovumar . Eventually we we be updating so that the global app password is the only password that you need, but for now the global password sit's on top of everything else. So individual wallets still have their own unlock passwords.

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/3114
