### ISSUE TITLE
Minor: CSS Layout. Walkthrough window pagination bullets need a margin above them.

### ISSUE THREAD

**Issue by FintanK** [LN-Zap/zap-desktop#298]
![image](https://user-images.githubusercontent.com/2451523/36066349-9e54ef7c-0ef3-11e8-9fe0-4b8b8c01b2ac.png)

**Comment by FintanK** [comment]
Another solution would be ensuring that the window is full screen when it is initially loaded.

**Comment by JimmyMow** [comment]
we have a new sync screen since #303, going to close this
