### ISSUE TITLE
Store fonts locally to remove outbound web requests

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#2984]
We should download/buy the fonts we use so we aren't making web requests to fetch them. Improves privacy and likely some small performance enhancements.

https://twitter.com/nvk/status/1182671014909698048

**Comment by bolatovumar** [comment]
I have a commit that does this but I couldn't get font file import path to not be relative. I know we try not to use relative urls but my ability to configure webpack is not good enough to get this to work.

See commit here: https://github.com/bolatovumar/zap-desktop/commit/327e61ec43554f58ff914a0fe81bb40810f0da1f

**Comment by korhaliv** [comment]
@bolatovumar try `@zap/fonts`

**Comment by bolatovumar** [comment]
@korhaliv will attempt this

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/3018
