### ISSUE TITLE
UI Bug - Channel backups error state

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#2987]
When getting an error setting the local location of my channel backup, the UI broke a little bit:

<img width="983" alt="Screen Shot 2019-10-14 at 9 37 42 AM" src="https://user-images.githubusercontent.com/4040039/66735382-7cd63a00-ee66-11e9-9c84-dad451e6b044.png">

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/3009
