### ISSUE TITLE
Use satoshis instead of floats to store amounts

### ISSUE THREAD

**Issue by DataCourier** [LN-Zap/zap-desktop#299]
Usually when dealing with money, you store the cents instead of storing a float value.

For instance, $1.22 is stored as 122. 
That ensures precision is not lost at any point in the application.

The other approach would be to use a big decimal datatype, but thats significantly more work to change your datatypes to.

https://stackoverflow.com/questions/1458633/how-to-deal-with-floating-point-number-precision-in-javascript

**Comment by DataCourier** [comment]
As someone pointed out, the unit should be mili -
satoshis as thats what Lighning Network supports.
https://github.com/lightningnetwork/lnd/blob/master/lnwire/msat.go

**Comment by JimmyMow** [comment]
Hm, I'm not sure about this.  Yes, LN does support mili-satoshis but only internally. The API only exposes satoshis I believe, I would see not benefit in converting to mili-satoshis and then converting back to satoshis when talking to and from the API

**Comment by Empact** [comment]
Good point, looking into the code sendpayment and payinvoice take satoshis. MSat and MilliMSat are used internally to accommodate lower relay fees.

**Comment by JimmyMow** [comment]
yeah, I do think we can take a much cleaner approach to how we handle the satoshi value (also allowing conversion to bits/USD/etc), but that should be handled in a separate issues, so I'm going to close this
