### ISSUE TITLE
Confusing description of available balance in open channel / send on-chain form

### ISSUE THREAD

**Issue by mrfelton** [LN-Zap/zap-desktop#2990]
## Detailed Description

Confusing description of available balance in open channel / send on-chain form

> Your current on-chain balance: 4,084,293 tsatoshis

This states that my current on-chain balance is X, which is not true. This is my current confirmed on-chain balance.

This can be quite confusing because, for example if I make a on-chain transaction my confirmed balance can go to `0` even though I do still have a balance.

## Context

UX

## Possible Implementation

We should clarify that this is confirmed balance and excludes unconfirmed and/or change outputs

**Comment by bolatovumar** [comment]
@mrfelton do you think it would be enough to change wording from
>Your current on-chain balance: 4,084,293 tsatoshis

to

>Your confirmed on-chain balance: 4,084,293 tsatoshis

or do you think we would need additional explainer text below clarifying it below.

**Comment by mrfelton** [comment]
I think this is probably ok @bolatovumar  as it provides the needed clarification. We don't want to overload the page with additional explainer text.

**Comment by mrfelton** [comment]
I'd perhaps say `current confirmed` instead of just `confirmed`

**Comment by bolatovumar** [comment]
@mrfelton I agree about not wanting to overload the page with additional text. 

I guess the only scenario in which someone could still be confused by this text is if that person didn't know what **confirmed** means. Not sure if anything can or should be done about this.
