### ISSUE TITLE
routing hints needed for private channels

### ISSUE THREAD

**Issue by fjdone** [LN-Zap/zap-desktop#3004]
I am able to send fund but I can only receive fund from the node that already knows my channel, I need to enable routing hints because my node is private.
I am running zap wallet 0.5.3 out of the box nothing change.
example I have a channel open to zapread, I can send payments from that cahnnel to anyone but if I want to received I have to send fund first to the wallet inside zapread so that from there I can send back to my channel/node.
Same with wallet of satoshi channel, I can't send fund directly from let say cobo wallet because the invoice doesn't have any routing hints.

I NEED TO KNOW HOW CAN I ADD ROUTING HINTS TO ZAP WALLET 0.5.3 WINDOWS.

When creating invoice there is no checkbox for routing hints

**Comment by mrfelton** [comment]
@fjdone please see my comment on https://github.com/LN-Zap/zap-desktop/issues/2409#issuecomment-542519107

**Comment by JimmyMow** [comment]
@fjdone if you don't see the routing hints option, that means you created a wallet with Zap (using neutrino) and we add routing hints to every invoice for you.

It's possible the reason you are only experiencing successful receives only after making payments is that those payments are giving you the necessary receive capacity. Without sending first, maybe you don't have enough receive capacity. Is that a possibility?

**Comment by JimmyMow** [comment]
@fjdone were you able to understand what the issue was? Is it safe to close this issue for now?

**Comment by mrfelton** [comment]
As per #2409, routing hints are included in the invoices so I'm going to close this one. Feel free to reopen this issue or hit us up in slack if you still have an issue here
