### ISSUE TITLE
Fund your ZAP wallet

### ISSUE THREAD

**Issue by wdey** [LN-Zap/zap-desktop#301]
I don't see "Fund your ZAP wallet" on the main page ? can I send my faucet tBTC to the "Deposit address" which I tried, but didn't work. Although I see many confirmation on the faucet site.

**Comment by JimmyMow** [comment]
Where did you get the address from? Are your funds still not there?

**Comment by wdey** [comment]
Hi

I closed ZAP and the did a restart, and finally could my faucet tBTC’s.

Von: JimmyMow [mailto:notifications@github.com]
Gesendet: Montag, 12. Februar 2018 18:45
An: LN-Zap/zap-desktop <zap-desktop@noreply.github.com>
Cc: wdey <wdey@bluewin.ch>; Author <author@noreply.github.com>
Betreff: Re: [LN-Zap/zap-desktop] Fund your ZAP wallet (#301)


Where did you get the address from? Are your funds still not there?

**Comment by JimmyMow** [comment]
ok, closing
