### ISSUE TITLE
Pay form error state shows up on modal close

### ISSUE THREAD

**Issue by bolatovumar** [LN-Zap/zap-desktop#3016]
This is super minor.

Pay form show error state momentarily when you close the pay form modal by clicking on the "close" icon. This is not an issue when you close the modal by "escape" key. See video here: https://youtu.be/-CX7MQ4b30I

## Expected Behavior

Closing the pay modal doesn't trigger pay form input error state

## Actual Behavior

Closing the pay modal triggers pay form field error state

## Steps to Reproduce

- 1. Click on "Pay" button
- 2. Click on the "x" close icon in the top right corner
- 3. Notice the red "failed" state shows up momentarily before the modal is closed

## Your Environment

- Zap version: 0.5.3

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/3067
