### ISSUE TITLE
Funds sent to qr-address in zap won't show up.

### ISSUE THREAD

**Issue by The34Goon** [LN-Zap/zap-desktop#3028]
**I sent BTC to the address shown below the QR Code in ZAP Desktop but the funds won't show up.**

![address](https://user-images.githubusercontent.com/56816899/67187353-49f1f000-f3ea-11e9-83dc-72dbccd961dc.PNG)

## Description
The node pubkey is correct.
![getinfo](https://user-images.githubusercontent.com/56816899/67187311-36df2000-f3ea-11e9-82be-d760f95e8d3c.PNG)
![node_pubkey_zap](https://user-images.githubusercontent.com/56816899/67187408-6a21af00-f3ea-11e9-9dfa-5888db1695c5.PNG)

The LN wallet is working i can send LN and OC funds.
The transaction has over 200 confirmations.
https://blockstream.info/address/33ziLLkEJxjNeDrHiAVfcA5eAeNMv2xePm

## Expected Behavior
address in zap desktop should link to my wallet

## Actual Behavior

the address won't show when calling 
lncli listchaintxns
lncli listunspent

## Your Environment
ZAP Desktop 0.4.1-beta
bitcoind / LND 0.8.0

my ZAP iOS 0.4.1 connects fine but with the same result regarding the funds sent to the address provided by zap desktop.

**Comment by mrfelton** [comment]
Hi. 0.4.1 is a very old release and likely to have issues working with such a recent release of land. Please can you update to the latest release of Zap Desktop and let me know if the issue persists. Thanks.

**Comment by The34Goon** [comment]
Hey
updated to 0.5.3
funds still not there.

**Comment by mrfelton** [comment]
If the funds don’t show up when using the lncli commands then this sounds like a possible issue with lnd - Zap literally calls lnd’s Api to get its data so if the data isn’t in lnd then there is no way it could be in zap.

When/where/how did you create the wallet? Is this a seed that you have restored or something like like that?

**Comment by mrfelton** [comment]
Could you tell me a bit about your lnd setup too? Where is it getting it’s data from? Bitcoind? Btcd? Neutrino?

**Comment by The34Goon** [comment]
sure
LND 0.8.0 / bitcoind
i did restore a seed in the past but in my mind this shouldn't be a prob since the wallet is functional and i can receive/send oc and lnd funds just fine.
i was in a hurry to receive some funds to my zap wallet and quickly took the address from the qr code.
however, with the latest update the address has changed in that section.
im aware i should have created lncli newaddress

**Comment by mrfelton** [comment]
When did you create the seed/wallet originally? When did you restore it?

Also, is it possible that this wallet would have had a large number of addresses?

When you do a restore from seed it has to scan forwards to find possible used addresses. Depending on how you did the restore and what parameters you used for this it’s possible that it didn’t scan forwards enough to final all of your used addresses.

**Comment by The34Goon** [comment]
cant remember when exactly i created/restored the wallet. :-/
50 addresses max. nowhere close to 2500
i recall using the --recovery_window=10000 when restoring.

maybe best to restore from seed again with that option?

**Comment by mrfelton** [comment]
If my memory serves me correctly I believe there was a bug in Zap 4.x that caused new addresses to be created every time the app was restarted, so you may have generated more addresses that you think.

You don't need to restore again in order to do a rescan - you can restart lnd and then run `lncli unlock --recovery_window=x`

> --recovery_window value  address lookahead to resume recovery rescan, value should be non-zero --  To recover all funds, this should be greater than the maximum number of consecutive, unused addresses ever generated by the wallet. (default: 0)

**Comment by The34Goon** [comment]
so i set the outlook to 100k, still no funds.

is it possible that the QR section shows a address from a previous LND wallet even if the ui shows all the info to the live one..? 
bizarre stuff..
thank you for looking in to this, appreciate it!

**Comment by mrfelton** [comment]
> is it possible that the QR section shows a address from a previous LND wallet even if the ui shows all the info to the live one ?

It's not something that has ever been reported before.

Have you created multiple wallets within Zap? Have you deleted wallets from within Zap? How many wallets do you / have you had inside Zap? Do you have local wallets in addition to remote wallet connections?

**Comment by The34Goon** [comment]
> Have you created multiple wallets within Zap? Have you deleted wallets from within Zap? How many wallets do you / have you had inside Zap? Do you have local wallets in addition to remote wallet connections?

Yes, 
Yes, 
3 from seed. atm i have 1 wallet. 
My wallet connects locally to Zap-Desk and remotely to iOS through TOR. 
Both methods worked fine when i took the address from QR.

**Comment by The34Goon** [comment]
restored the seed, found the funds.
but its still a mystery since i wanted to send the found funds from the old to the new wallet, so sent a probe of 20k sats. the 20k sats didnt make it but the change showed up in the **new** wallet...o0 

tbh. im going to whipe the whole damn thing and start from scratch.  
**Thank you so much for all the help.**
