### ISSUE TITLE
Closing "Open a Channel" modal opens channel management modal

### ISSUE THREAD

**Issue by bolatovumar** [LN-Zap/zap-desktop#3035]
This issue is on the `next` branch.

## Description

When you open "Open a Channel" modal and then try to close it you see the channel management modal. See video here: https://youtu.be/Cf7fG7Dl9M8

## Expected Behavior

See main wallet window when closing the "Open a channel" modal.

## Actual Behavior

See channel management UI instead.

## Possible Fix

Not sure but I think how modal are handle changed recently? @korhaliv probably knows.

## Your Environment

- Zap version: 0.6.0-alpha

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/3036
