### ISSUE TITLE
Unlocalizable strings

### ISSUE THREAD

**Issue by sohomang** [LN-Zap/zap-desktop#3045]
## Description

The following strings do not exist in `translations/en.json`, so they're not showing up in Crowdin:

- "Channels" menu's label on the main screen
- "onchain" and "in channels" on the `Pay` screen
- "or" on the `Connect` screen during the onboarding
- Some error message that shows up when trying to unlock a remote node

Bonus:
- Shouldn't the `open` status label next to each channel say `online` instead? In contrast to the `offline` status.

## Screenshots

Respectively:
<img width="284" alt="Channels" src="https://user-images.githubusercontent.com/28465517/67442893-e1319000-f602-11e9-843f-8606c270f3e7.png">
<img width="196" alt="On-chain:In channels" src="https://user-images.githubusercontent.com/28465517/67442898-e68eda80-f602-11e9-85e3-0f9b3e29e757.png">
<img width="560" alt="Or" src="https://user-images.githubusercontent.com/28465517/67442907-ec84bb80-f602-11e9-94e5-745ea83bef0c.png">
<img width="1193" alt="Screen Shot 2019-10-24 at 02 33 42" src="https://user-images.githubusercontent.com/28465517/67443826-c06b3980-f606-11e9-9a44-e0038ec923c2.png">
<img width="179" alt="Screen Shot 2019-10-24 at 02 36 35" src="https://user-images.githubusercontent.com/28465517/67443917-1f30b300-f607-11e9-9f95-bbd81f1e4585.png">

**Comment by bolatovumar** [comment]
I can take a look and include missing strings if they are hardcoded.

**Comment by bolatovumar** [comment]
@sohomang I addressed all issues except for the last one and the "bonus" one. I didn't address the last one 
> Some error message that shows up when trying to unlock a remote node

As these are error messages, do we wanna have them localizable @mrfelton?

As for the bonus one
>Shouldn't the open status label next to each channel say online instead? In contrast to the offline status.

This makes sense to me. Is there a reason why we would want to keep it as "open" instead of "online" @mrfelton?

**Comment by bolatovumar** [comment]
> Shouldn't the open status label next to each channel say online instead? In contrast to the offline status.

According @sohomang, there was a consensus that we want to change the wording to "online" here. Should we go ahead with it @mrfelton?

**Comment by bolatovumar** [comment]
Also, I'm wondering if we should have a lint rule to disallow hardcoded strings in JSX to avoid this sort of bug in the future. I found this rule: https://github.com/Shopify/eslint-plugin-shopify/blob/master/docs/rules/jsx-no-hardcoded-content.md

There might be rules in other packages that do the same thing.

Thoughts, @mrfelton?

**Comment by mrfelton** [comment]
> According @sohomang, there was a consensus that we want to change the wording to "online" here. Should we go ahead with it @mrfelton?

I think that makes sense - what we call `open` in this case actually means `open+online`, so `online` would be a more accurate description since a channel can be `open+offline`.

So, we'd have:

`online` (open and online)
`offline` (open but offline)

> Also, I'm wondering if we should have a lint rule to disallow hardcoded strings in JSX to avoid this sort of bug in the future. I found this rule: https://github.com/Shopify/eslint-plugin-shopify/blob/master/docs/rules/jsx-no-hardcoded-content.md

I don't know of other lint rules to do this @bolatovumar . I'd definitely be interested to see if this package works well as this is a common problem and one thats too easy to overlook.

**Comment by bolatovumar** [comment]
@mrfelton ok, i tried out that rule and it found 26 errors. I'm thinking it's worth it to create a separate issue for this and have a PR that enables this rule?

**Comment by mrfelton** [comment]
> ok, i tried out that rule and it found 26 errors. I'm thinking it's worth it to create a separate issue for this and have a PR that enables this rule?

Yes, please do @bolatovumar

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/3050
