### ISSUE TITLE
and normal zap open channels automatically?

### ISSUE THREAD

**Issue by joaoviniciussr** [LN-Zap/zap-desktop#305]
every time I open, has one or two channels open, which I did not ask for the manual open, and normal wallet zap add contacts automatically? thankful 
![contatozap](https://user-images.githubusercontent.com/33408963/36233662-36141dc4-11ce-11e8-99de-fa8697852f19.png)

**Comment by joaodealmeida** [comment]
Hello João,
Zap has autopilot enabled as default. If you don't know what autopilot is you can see more [here](https://github.com/lightningnetwork/lnd/tree/master/autopilot)

**Comment by joaoviniciussr** [comment]
I bugged rsr 
I saw, but I did not understand anything. but OK

**Comment by JimmyMow** [comment]
yeah that's autopilot. you'll be able to configure it soon. closing
