### ISSUE TITLE
Enable jsx-no-hardcoded-content lint rule

### ISSUE THREAD

**Issue by bolatovumar** [LN-Zap/zap-desktop#3065]
We should have a lint rule which detects hardcoded strings. We don't want them to end up in the UI since they are non-localizable. `eslint-plugin-shopify` package has a `jsx-no-hardcoded-content` rule which helps wit this.

See discussion here: https://github.com/LN-Zap/zap-desktop/issues/3045

We decided to enable this rule: https://github.com/LN-Zap/zap-desktop/issues/3045#issuecomment-546742395

**Comment by bolatovumar** [comment]
I will follow this up with a PR.

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/3066
