### ISSUE TITLE
Slack link is not working

### ISSUE THREAD

**Issue by yashbhutwala** [LN-Zap/zap-desktop#308]
Can someone update the link?

<img width="604" alt="image" src="https://user-images.githubusercontent.com/5788514/36331061-5ac91850-133a-11e8-818f-afd528934c72.png">

**Comment by happykids33** [comment]
https://join.slack.com/t/zaphq/shared_invite/enQtMzA4OTgxNTQ4NzUzLTQwYjkzZGM0ZWMwYmYyZTE2Y2E1YjM5NTIwOTU0M2I1Zjc2YWY1NTc4NjdhZWQxNTM1YzEzOGM2YTVlNWIwODc

**Comment by yashbhutwala** [comment]
Thanks @happykids33. Since the link expires every 16 days, I'll close this.
