### ISSUE TITLE
Slack invite link on README.md is no longer active

### ISSUE THREAD

**Issue by jakezeal** [LN-Zap/zap-desktop#309]
The [Slack invite link](https://join.slack.com/t/zaphq/shared_invite/enQtMjkyNTAxNDA3MjE2LWE3NGZjZGE5ZmI1NGQ5YTk3MGQzMTdmNDAwYjNhZTJkMWU0ZWZlNzA0MjJiNDBjMzcxYjcyMDMxNWY3OGNhYWQ) is no longer active:

<img width="1226" alt="screen shot 2018-02-17 at 9 28 05 pm" src="https://user-images.githubusercontent.com/13857938/36348647-93c1d984-146c-11e8-8c87-3613c8e08d9c.png">

**Comment by JimmyMow** [comment]
sorry about that. should be fixed now.

**Comment by darko-mijic** [comment]
@JimmyMow Slack invite link is not working again.
