### ISSUE TITLE
Handle buttons "focus" style correctly

### ISSUE THREAD

**Issue by korhaliv** [LN-Zap/zap-desktop#3127]
## Description
Currently when you click a button it goes into "focus" state and stays as such until you click outside.
This can cause minor visual glitches when using buttons as dropdown toggles etc. The offending style is located in `base.js` for next and `themes/utils.js` for master

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/3143
