### ISSUE TITLE
Run LNCLI commands

### ISSUE THREAD

**Issue by baebb** [LN-Zap/zap-desktop#3136]
## Detailed Description

It would be nice to be able to run LNCLI commands on my lnd instance that Zap installed

## Context

Zap is great for a quick and easy mainnet lnd instance to test out my LAPPS as I'm developing them. It would be nice if I could run some commands against the lncli instance Zap creates to get inbound channels from LNBIG or other stuff.

## Possible Implementation

A 'secret' tab inside the desktop app that would allow a user to run lncli commands (see Breez mobile app for an example of this)

**Comment by xraid** [comment]
i second the above ...

Zap would be very much more poweful if easy access to the running LND
