### ISSUE TITLE
Empty receive address 

### ISSUE THREAD

**Issue by korhaliv** [LN-Zap/zap-desktop#3173]
## Description
Under some unknown circumstances receiving address in missing in `ReceiveModal`

**Comment by bolatovumar** [comment]
> unknown circumstances

as in this issue has been reported but we don't know how to repro the issue?

**Comment by korhaliv** [comment]
Yes currently i don't have consistent repro for this

**Comment by mrfelton** [comment]
I believe this will have been addressed by https://github.com/LN-Zap/zap-desktop/pull/3185 . Closing as duplicate
