### ISSUE TITLE
Hitting refresh in activity screen triggers next page load

### ISSUE THREAD

**Issue by korhaliv** [LN-Zap/zap-desktop#3174]
## Description
When you hit refresh in activity view it presumably triggers loading of the next page

**Comment by bolatovumar** [comment]
Tried repro-ing this on master branch but couldn't.

![2019-11-13 19 22 51](https://user-images.githubusercontent.com/1934678/68824253-14d46880-064b-11ea-995d-f4645cdbb998.gif)

**Comment by korhaliv** [comment]
Maybe this is the entire activity you have. You can observe the behavior through redux log.
