### ISSUE TITLE
99% lnd HELP

### ISSUE THREAD

**Issue by joaoviniciussr** [LN-Zap/zap-desktop#318]
The zap wallet is 99% forever, the other time, I deleted the lnd folder, and synchronized from scratch, I had about 20tBTC and lost everything, now I have much more, will I lose again? because I deleted the lnd folder of appdata and now it is 0% forever, my log for someone help me grate brothers
[lnd.log](https://github.com/LN-Zap/zap-desktop/files/1750391/lnd.log)
@JimmyMow

**Comment by joaoviniciussr** [comment]
[lnd.log](https://github.com/LN-Zap/zap-desktop/files/1754520/lnd.log)
can anyone help erase the lnd folder, and sync, does not exit 0%

**Comment by JimmyMow** [comment]
@joaoviniciussr what Zap version are you running?

**Comment by joaoviniciussr** [comment]
my version is the latest   0.1.1   I believe.
if I need to uninstall and install again how do I back up so I do not lose the balance? @JimmyMow

**Comment by joaoviniciussr** [comment]
@JimmyMow Please help me.

**Comment by fiddybux** [comment]
Lucky to get to 99%! Unlucky with the coin.

**Comment by mrfelton** [comment]
I'm closing this issue as there are known synchronisation issues with version  0.1.1. You must either build and run from the latest source or wait for a new release. Please feel free to reopen this issue if you experience the same issue with the latest code and let us know the steps to reproduce. Thanks.

@joaoviniciussr - If you need help to restore your coins, please ask for help in slack. Thanks
