### ISSUE TITLE
Clicking "Install" for update doesn't restart application.

### ISSUE THREAD

**Issue by SteliosRammos** [LN-Zap/zap-desktop#3198]
# Description

When I get the pop up that prompts me to download the new version of the application, I click "Install" and the application seems to be restarting but it's not actually shutting down. So the installation does not complete and I get the prompt again after a few minutes. 

I needed to quit the app manually to complete the installation. 

Not  sure if it counts as a bug, but it'd be nice if the application just restarted on its own.

- Zap version: 0.6.2 beta
- Operating System and version: macOS Catalina 10.15.2 Beta

**Comment by mrfelton** [comment]
Hi, this is indeed a bug - thanks for reporting. We will look to have this fixed for future updates.
