### ISSUE TITLE
Compile from source for Raspbian

### ISSUE THREAD

**Issue by Arno-GitHub** [LN-Zap/zap-desktop#3235]
Following https://github.com/LN-Zap/zap-desktop/blob/master/docs/ADVANCED.md#compiling-zap-from-source

After 'cd zap-desktop'
The step 'sudo yarn' displays error:
There are no scenarios; must have at least one

'sudo yarn test':
[Errno 21] Is a directory: 'test'

## Expected Behavior

Build application

## Actual Behavior

Error

## Steps to Reproduce

- 1. Follow https://github.com/LN-Zap/zap-desktop/blob/master/docs/ADVANCED.md#compiling-zap-from-source

## Your Environment

- Zap version: 0.6.2
- Operating System and version: Raspbian Buster 10.2 (up to date)
- Raspberry Pi4B / Raspbian / Pixel

**Comment by bolatovumar** [comment]
@LEDEuser see this: https://github.com/yarnpkg/yarn/issues/2821

**Comment by LEDEuser** [comment]
Very helpful.
Updated yarn and nodejs.

Now I got many warnings and an error.
In the output there is a line
... No prebuilt binaries found (target=12.13.1 runtime=node arch=arm libc= platform=linux)

Shouldn't that be arch=armhf? I'm using a Pi4B/Raspbian.

**Comment by mrfelton** [comment]
Hi @LEDEuser unfortunately we don't support building arm devices, since this is currently not well supported by electron itself.

**Comment by LEDEuser** [comment]
Hi @mrfelton, OK, hopefully in the future.
Offtopic: Do you know a lightning wallet for Raspbian?

**Comment by mrfelton** [comment]
Usually people run a wallet app like Zap on their desktop/laptop and connect it to an lnd node that they have running on their arm devices. Do you really need to run the wallet UI directly on the device?

**Comment by LEDEuser** [comment]
I use a portable Pi with touchscreen as satnav/browser/office and hopefully (lightning) wallet. I don't use a smartphone.

**Comment by bolatovumar** [comment]
@LEDEuser have you tried Ride The Lightning web UI for LND? It should run just fine on a Raspberry Pi.

https://github.com/Ride-The-Lightning/RTL

**Comment by LEDEuser** [comment]
@bolatovumar Isn't that for a node? On another Pi I'm installing Raspiblitz.(uses RTL afaik).

I want to use a bitcoin wallet (preferably with lightning) on a Pi with touchscreen.
Looking now into Wasabi/Breeze/Armory. If one will run on a Pi and I can use on the go.

**Comment by mrfelton** [comment]
I think RTL is a web based UI, so you could install lnd and RTL on the PI and then access the RTL UI in a browser.

**Comment by bolatovumar** [comment]
@LEDEuser as @mrfelton said, RTL is a web UI on top of LND. You get an on-chain wallet and a lightning wallet with it.

Looks like they were able to build Wasabi on ARM so you might be able to as well:

https://twitter.com/HillebrandMax/status/1201440796811169792

**Comment by mrfelton** [comment]
Closing as we don't support building for arm due to current limitations with electron-builder. As discussed there are other options for that will work on arm such as RTL
