### ISSUE TITLE
Export private key from Zap?

### ISSUE THREAD

**Issue by AzerChainToken** [LN-Zap/zap-desktop#3257]
## how export Private key from Zap?

Is it possible to find out private keys from your Zap wallet? Let's say my address for accepting bitcoin is 31rvH4y7Skqr3UHCxSJYeRMyYx5vxnFjHn! How can I find out my private key from this wallet? I tried to return 24 words in the Electrum program! Do not get it!

**Comment by bolatovumar** [comment]
@AzerChainToken you can use your 24 word seed to restore your wallet in the app in which you created the wallet initially. If you created it in Electrum then you should use Electrum to restore the wallet.

**Comment by AzerChainToken** [comment]
> @AzerChainToken you can use your 24 word seed to restore your wallet in the app in which you created the wallet initially. If you created it in Electrum then you should use Electrum to restore the wallet.

I creat wallet on ZAP!  I can restore this on Electrum ?  i need a accesing to the private keys

**Comment by bolatovumar** [comment]
@AzerChainToken Zap doesn't allow exporting the private key as far as I'm aware. Why do you need the private key? In most cases the raw private key is not needed. If you absolutely need to export a private key, you can send your funds from Zap to Electrum and export the private key from Electrum.

**Comment by AzerChainToken** [comment]
> @AzerChainToken Zap doesn't allow exporting the private key as far as I'm aware. Why do you need the private key? In most cases the raw private key is not needed. If you absolutely need to export a private key, you can send your funds from Zap to Electrum and export the private key from Electrum.

I want to store funds in a ZAP wallet! But at the same time and have access to the Elektrum!

**Comment by bolatovumar** [comment]
@AzerChainToken this may not work as Electrum uses its own modified way or generating a seed phrase. You should stick with either Zap or Electrum. If you require more advanced functionality which Zap doesn't offer yet, use Electrum. You can also file a request to add ability to export a private key to Zap but this feature may not come anytime soon.

**Comment by AzerChainToken** [comment]
> @AzerChainToken this may not work as Electrum uses its own modified way or generating a seed phrase. You should stick with either Zap or Electrum. If you require more advanced functionality which Zap doesn't offer yet, use Electrum. You can also file a request to add ability to export a private key to Zap but this feature may not come anytime soon.

Electrum not support lightning technology((((

**Comment by bolatovumar** [comment]
@AzerChainToken next version of Electrum will have Lightning Network support. They have all the code merged into their master branch already. It's just a matter of time before they release it.

**Comment by AzerChainToken** [comment]
> @AzerChainToken next version of Electrum will have Lightning Network support. They have all the code merged into their master branch already. It's just a matter of time before they release it.

yeah. im waiting for 4.0.0 version of electrum with ln)

**Comment by mrfelton** [comment]
Closing this issue as it's been discussed that Zap and Electrum are different types of wallet with different seed formats.

**Comment by MocroNL** [comment]
Worst case scenario: What if the ZAP wallet disapears and not being able to use it again. Is there any other hardware wallet we can use to recover?

**Comment by Barcode534** [comment]
^ happening to me now

**Comment by 0xc0de44** [comment]
Same for me, i funded my newly created wallet, then i'm unable to access it now. 
Unable to recover the wallet on another app due to the incompatibility mentioned above. 
If zap is no longer maintained but anyway still available for download and use, i think many other users will lose funds :(

**Comment by Barcode534** [comment]
I successfully recovered funds using instructions from a crypto recovery person. Their exact comment was as follows:

If it's the on-chain stuff then recovery should be straightforward, thought likely uses aezeed, not BIP39 for seeds.

The basic process you need is outlined here

[https://github.com/openoms/lightning-node-management/blob/en/technicals/restorelndonchainfundsinelectrum.md]

But BE WARNED - I successfully recovered access, but because it was a new hot wallet with a small amount of funds, I didn't take proper security measures, and I exposed the mnemonic somehow (not sure where the leak happened yet, PC infected, or website infected, or man in the middle, etc). So the small funds were sent to an address I don't recognise.

The encryption/decryption websites can apparantly be used offline - so do that and maybe you will avoid the fate I had.

**Comment by 0xc0de44** [comment]
Finally i recovered my funds using bluewallet which, fortunately, is compliant with the used P2SH wallet. Thanks for the advice anyway !
