### ISSUE TITLE
ZAP chanel backups or move to other PC

### ISSUE THREAD

**Issue by KriptoQraf** [LN-Zap/zap-desktop#3265]
How can I move the zap to another PC without losing open channels?

What folders and files need to be moved to another PC?  Or how to backup channels to restore them on another computer?

**Comment by bolatovumar** [comment]
@KriptoQraf it's probably safest to to close all of your channels and re-open them again later instead of attempting to move over your channel backups to another computer.

**Comment by mrfelton** [comment]
All zap data is stored in per-user application data directory, which by default points to:

`%APPDATA%\Zap` on Windows
`$XDG_CONFIG_HOME/Zap` or `~/.config/Zap` on Linux
`~/Library/Application Support/Zap` on macOS

If you copy this directory over to your other PC then you should have everything you need for Zap to run with your walets.

But - do not run the same copy of zap on multiple computers. If you copy it over to another machine and run it there, do not start it up again on the old machine as you will risk broadcasting old channel state and loosing funds.
