### ISSUE TITLE
Pending Channel - Funds Stuck - HELP

### ISSUE THREAD

**Issue by squatz1** [LN-Zap/zap-desktop#3276]
HERE IS MY ORIGINAL TICKET - THIS IS THE SAME PROBLEM FROM JUL 22 (#2591)

So I had had my Zap-Desktop on AutoPilot, and due to this it has opened some channels. One of them had been pending, and it is still pending for weeks. I'm unable to close / force close it as it is still open.

Also -- The TX that it has provided to show that it's opening can't be found, which is why this is still stuck.

Channel should open and then allow me to close it.

Actual Behavior
Possible Fix
Steps to Reproduce
Context
I'm trying to withdraw my funds, though I'm stuck on pending.

Your Environment
Zap version: Newest verison
Operating System and version: Windows 10

**Comment by mrfelton** [comment]
Hi,

It sounds like you are affected by this issue - https://github.com/LN-Zap/zap-desktop/issues/2531 - which is a bug in lnd. As mentioned in that thread, the only way that I'm aware of to rectify this is to use a debug build of lncli and call `lncli abandonchannel` on the channel. This is not something that's currently supported in Zap itself.

**Comment by squatz1** [comment]
> Hi,
> 
> It sounds like you are affected by this issue - #2531 - which is a bug in lnd. As mentioned in that thread, the only way that I'm aware of to rectify this is to use a debug build of lncli and call `lncli abandonchannel` on the channel. This is not something that's currently supported in Zap itself.

Ah, thanks for the prompt reply.

I assume that means that the funds are stuck for now? Unless Zap implements this?

**Comment by mrfelton** [comment]
Not if you build yourself a debug build of lnd and use lncli to run the aforementioned command against the lnd instance that Zap runs for you.

**Comment by squatz1** [comment]
> Not if you build yourself a debug build of lnd and use lncli to run the aforementioned command against the lnd instance that Zap runs for you.

Hm. Sounds a tad intense, but probably just cause I don't really know what any of that means. Anychance you'd be able to point me in the right direction for doing that?

**Comment by mrfelton** [comment]
If you hop into our slack channel I can probably better help you there

**Comment by squatz1** [comment]
@mrfelton Bit of a big delay here, but wanted to do this now if you have sometime. Let me know!

**Comment by grubeli** [comment]
DONE.
Okay. I found a way to return our funds.
if your funds are stuck like mine, I mean you send them from Zap (on-chain) wallet to Zap Lightening and is stuck on Pending.
What you need is to copy your recovery words, download new app on a different PC and recover (!) your wallet from the seed numbers you copied before. if you don't have a different PC you can use virtualization software like virtualbox (https://www.virtualbox.org) to create a virtual PC and install Zap on it.

After that, when you open your Zap on that new PC you will see all your coins on On-Chain, it means you can send it back to your original account/address or any other address
