### ISSUE TITLE
All Channels Disappeared

### ISSUE THREAD

**Issue by nlebowitz** [LN-Zap/zap-desktop#3291]
I updated to the newest release after uninstalling the old version(since it didn't get rid of the old files when I installed the newest release the first time).  I inserted my 24 word mnemonic to bring up my wallet again and all my channels were gone, with only a fraction of the satoshis sent back to my wallet.  I did not willingly close any of my channels.  Does anyone know why this happened?

**Comment by mrfelton** [comment]
When upgrading you should not delete any files but rather just download the new version and open it.

It sounds like instead you deleted all of your data, including your wallets - am I understanding that correctly?

Restoring from a seed will only restore your onchain funds - this is normal. You will need a copy of your channel backup file in order to restore your channels.

**Comment by nlebowitz** [comment]
Unfortuantely I use IOBit uninstaller instead of the proprietary windows package uninstaller.  I think it may have deleted everything.  When I did it I thought I was merely getting rid of the old version and instead I noticed it deleted both versions.  There's no way of restoring channels or getting my funds back by closing them without the channel backup file?  Thanks for your response.

**Comment by mrfelton** [comment]
Unfortunately not, the only way to restore and close channels after restoring from seed is with your channel backup file.

I’m not familiar with IOBit uninstaller, but for future reference you don’t need to uninstall anything to upgrade.

**Comment by mrfelton** [comment]
Note - I’m not sure what version of zap/lnd you had previously been running, but if it was a recent version then if/when your remote channel party force closes your channels, your funds from that channel may be returned directly to your onchain wallet.

**Comment by nlebowitz** [comment]
Only a small fraction of sats were returned.  I believe it was the most recent 0.5.X version before 0.6.0, but I can't be sure.  Is there a way to get your channel funds back eventually once the channels are closed from the other end?

**Comment by mrfelton** [comment]
Lnd 0.8.0 and later includes a feature called SAFU Commitments which ensures that if a remote party force closes your channel,
the funds from it will be returned to one of your onchain addresses.

However if your channels were opened using an earlier version then this is not the case so short of the channel backup file there is no way to recover funds from your lost channels.
