### ISSUE TITLE
Channel balance incorrect during force close of channel

### ISSUE THREAD

**Issue by dannypaz** [LN-Zap/zap-desktop#3310]
## Description

CC: @mikepred

The balance is doubling when a force close channel is waiting to be confirmed.

#### Starting Screen

![full-window-pending-channel-close](https://user-images.githubusercontent.com/5478311/72576879-bf544c00-3885-11ea-8619-070b71640571.png)

#### Close channel, then Force closed channel from Zap (this also includes 2 payments that I made)

![channel-close](https://user-images.githubusercontent.com/5478311/72576893-cd09d180-3885-11ea-9ebd-ece05bc49072.png)

#### Balance on the dashboard
![regtest-double-balance-weirdness](https://user-images.githubusercontent.com/5478311/72576939-e874dc80-3885-11ea-8bb6-4815933b88e0.png)

#### Balance on the pay screen
![balance-pay](https://user-images.githubusercontent.com/5478311/72576961-f9bde900-3885-11ea-87ac-94540bbee222.png)

#### Force close confirmed

![force-close-finish](https://user-images.githubusercontent.com/5478311/72577094-59b48f80-3886-11ea-8600-3f46bbb38dad.png)

The user will be in a state where the balances are incorrect for a long time due to the nature of force close (typically 24 hour default close but could be longer)

## Expected Behavior

Balances should reflect force close transactions

## Actual Behavior

Balances incorrect on dashboard during the force close process for channels

## Steps to Reproduce

- 1. Force close a channel
- 2.
- 3.
- 4.

## Your Environment

- Zap version: Master (0.6.2)
- Operating System and version: Linux/Ubuntu 18

**Comment by mrfelton** [comment]
Hi @dannypaz thanks for the report.

Maybe I'm not following along correctly... At what point do you see the balances as doubled? At that point, what balance do you see, and what did you expect to see?

**Comment by mrfelton** [comment]
Closing as I believe this is now fixed in master as part of https://github.com/LN-Zap/zap-desktop/pull/3526
