### ISSUE TITLE
Ability to change Backup Method

### ISSUE THREAD

**Issue by jamesturnernz** [LN-Zap/zap-desktop#3343]
## Detailed Description
In the Zap desktop app, Profile > Node Info > Backup Method
I would like to be able to change Backup Method.
When installing, I was given 3 options, it appears the current version of the app, the Google Drive method has issues #3309 

## Context

It would allow me to change to the local backup method, and that would stop the Google login popup that doesn't work.

## Your Environment

- Zap version: 0.6.2-beta. Node v0.8.0-beta-2-gb95a0a0f
- Operating System and version:
MacOS 10.15.3 (19D76)

**Comment by bolatovumar** [comment]
@mrfelton is there interest in having this feature? If so, I can take a look into implementing this.

**Comment by mrfelton** [comment]
Hey @bolatovumar . Yes this looks like a duplicate of https://github.com/LN-Zap/zap-desktop/issues/2230 and is something we'd love to see implemented.

Closing this as dupe of the other.
