### ISSUE TITLE
Zap Tutorials link is dead

### ISSUE THREAD

**Issue by agebben** [LN-Zap/zap-desktop#3344]
Pressing the "Zap Tutorial" button in app goes to to a dead link

## Description
In the welcome page of the app, pressing the "zap tutorials" button leads to the dead link _https://ln-zap.github.io/zap-tutorials/zap-desktop-getting-started_

## Expected Behavior

Have the link go to available documentation, or else remove it until a suitable tutorial is in place

## Possible Fixes

- Link to available documentation such as the github readme
https://github.com/LN-Zap/zap-desktop/blob/master/README.md
- Link to youtube tutorial (outdated version)
https://www.youtube.com/watch?v=Z2XDt7iKE7A&list=PLMj6UA3-f3cQq_TjCXAAeP1mmRnjgnDrI
- Add scrolling tips to users in text form
- Remove the link 

## Steps to Reproduce

1)
![Screenshot_20200304_120155](https://user-images.githubusercontent.com/61802067/75914123-7181ac00-5e11-11ea-955a-94086f45058e.png)
2)
![Screenshot_20200304_121436](https://user-images.githubusercontent.com/61802067/75914181-8a8a5d00-5e11-11ea-85cb-c388831fd25b.png)

## Context
As a new user this bug makes onboarding more difficult. While it does not affect functionally I think it is important to provide first time users with as fluid a experience as possible. 

Even removing the link would make the experience a bit nicer.

## Your Environment

- Zap version: Zap 0.6.2-beta
- Operating System and version: linux appimage
- Web-browser: Firefox and Brave

**Comment by bolatovumar** [comment]
@agebben this has been fixed here: https://github.com/LN-Zap/zap-desktop/commit/1f480b6cc77f4f46641154722d3f4c2c66212b1a
