### ISSUE TITLE
Seeing Error: spawn UNKNOWN (after Screen 2)

### ISSUE THREAD

**Issue by nm123github** [LN-Zap/zap-desktop#337]
I am attempting to setup zap-desktop (on testnet), OS Windows 7 (32 bit). I copied pasted lnd.exe in the bin folder (from the console logs, it seemed to expect it to be there). I ran `npm start' and the electron app opened successfully.

However, after i enter my Name (Screen 1) and Enable Autopilot (Screen 2) i came across the following error.
![image](https://user-images.githubusercontent.com/8527474/37388171-9d98c2ca-271c-11e8-9fab-04c1860b8c0c.png)

After clicking 'Ok' i do see the 'Synching to Blockchain' Screen however it seems to be stuck at 0%. Not sure if its doing anything at this point.
![image](https://user-images.githubusercontent.com/8527474/37388962-b57978c8-271f-11e8-8c82-e7edd4fbee86.png)

**Comment by Empact** [comment]
Looking into this, seems your LND is not running properly. Could you answer these?:
```
* does the same command work when running from system console?
* what Node.js version do you use?
* do you have 'Include parent environment variables' enabled in your Node.js run configuration? Open 'Environment variables' dialog using ellipsis button in Environment field to check it
```
https://github.com/Medium/phantomjs/issues/478

**Comment by nm123github** [comment]
* does the same command work when running from system console?
I ran `npm start` from the console. 

* what Node.js version do you use?
v8.10.0

* do you have 'Include parent environment variables' enabled in your Node.js run configuration? 
Open 'Environment variables' dialog using ellipsis button in Environment field to check it
Not sure where i can check this. Is it the Environment Variables dialog in System Properties?
![image](https://user-images.githubusercontent.com/8527474/37422642-e657bd02-2778-11e8-8b9a-75c812b4f7c9.png)

On a side note, i tried running lightning.exe directly from [lightning-app](https://github.com/lightninglabs/lightning-app) folder and i see similar error. Let me know if you think this might be an LnD issue and not LN-Zap.
![image](https://user-images.githubusercontent.com/8527474/37422553-98fb38c2-2778-11e8-9d27-0c3139c54205.png)

**Comment by Empact** [comment]
What happens when you run `lnd --version` from the terminal?

**Comment by nm123github** [comment]
Looks like the lnd version i got (by default) is 64 bit version. I'm on 32bit windows 7.
![image](https://user-images.githubusercontent.com/8527474/37444352-3cf066dc-27ce-11e8-8034-fcc6a3d028ca.png)

Pretty evident what the issue is. We could go ahead and close it i guess. Thanks for the help.
