### ISSUE TITLE
Slack invite link no longer working (long term fix needed)

### ISSUE THREAD

**Issue by mrfelton** [LN-Zap/zap-desktop#339]
It seems that the slack invite link on the README is no longer working. It seems that this is a recurring issue - this same issue has been created over 20 times by various people.

This is a barrier and blocker that in some cases may prevent people from participating in the community entirely.

See https://github.com/LN-Zap/zap-desktop/search?q=slack&type=Issues&utf8=%E2%9C%93

It appears that the root issue is that the slack invite link is temporary and expires after 14 days. That means that every 14 days we get a broken link in the README that remains broken until someone notices and takes the time to fix it.

As a possible solution to this reoccurring issue, I would suggest setting up something like https://github.com/rauchg/slackin which we could use to host a very simple slack invite facility (like the one at https://slackin.now.sh/).

**Comment by JimmyMow** [comment]
Can I close this?

**Comment by mrfelton** [comment]
I don't think the issue has been fixed @JimmyMow . Every 14 days the link breaks. Just updating the link every 14 days isn't going to cut it. What happens is that other people find the broken link before someone with commit access has noticed that it has become broken again and has the time to fix it.

The link is broken again right now.

Yet another new user has tried to access the slack channel but failed today (see https://github.com/LN-Zap/zap-desktop/issues/388). This person bothered to create an issue to tell us about his problem. Many other users will not bother and get frustrated. It's not a great first experience for people that are looking for help or ways to get involved.

If you search the github issues of this project you will see that over 20 unique issues have been created to report this single issue, time and time again.

We need a longer term fix for this issue - such as the one I suggested in the description of this issue. above.

**Comment by Andimaxgt** [comment]
Whats the issue ?

**Comment by mrfelton** [comment]
@Andimaxgt - see my comments above https://github.com/LN-Zap/zap-desktop/issues/339#issue-305546847

Slack invite links are only valid for 14 days. It's just a limitation of how how slack invite links work. This is the reason tools like https://github.com/rauchg/slackin exist.

**Comment by highvolt4ge** [comment]
Yeah, invite link is dead once again.

**Comment by mrfelton** [comment]
Closing this issue as we now have a permanent slack invite link.

@JimmyMow I think you can close out https://github.com/LN-Zap/zap-desktop/issues/388 too
