### ISSUE TITLE
Reduce duplication in pay form components

### ISSUE THREAD

**Issue by mrfelton** [LN-Zap/zap-desktop#3417]
## Description

The pay form components are a little unwieldy in parts with some duplication of props that could be consolidated a little,

e.g. https://github.com/LN-Zap/zap-desktop/pull/3393#discussion_r397050820

## Possible Fix

- Consolidate `isOnchain` `isBolt11` and `isPubkey` bools into an enum.
- Review Pay form components for other possible simplifications.

**Comment by bolatovumar** [comment]
I think I promised to do this long time ago when I did pay form components refactor the last time around but never got to it. I can take a look.

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/3460
