### ISSUE TITLE
Outgoing payments from other clients not displayed on refresh

### ISSUE THREAD

**Issue by blacktemplar** [LN-Zap/zap-desktop#3420]
I use zap-desktop and zap-android to connect my desktop and my mobile phone to my own LND node. When I pay something with zap-android or directly via LND the payment gets not displayed in zap-desktop, even after hitting Refresh activity list. The only way to really refresh is to disconnect and reconnect.

## Description

Sending an outgoing payment with another client results in zap-desktop not displaying this payment, even after hitting refresh. Incoming payments are recognized instantly (even without hitting refresh).

## Expected Behavior

At least after hitting refresh activity list outgoing payments done by other clients of the lnd node should be displayed in the list.

## Actual Behavior

The outgoing payments are not displayed after refreshing (only reconnecting helps).

## Steps to Reproduce

- 1. Connect zap-desktop to own LND-node
- 2. Send payment using lncli directly
- 3. Payment does not show up in zap-desktop, even after refreshing

## Your Environment

- Zap version: 0.6.2
- Operating System and version: arch linux

**Comment by mrfelton** [comment]
@blacktemplar the current 0.6.2 release has a bug in the refresh logic - see https://github.com/LN-Zap/zap-desktop/issues/3174

This has been fixed in the master branch.
