### ISSUE TITLE
Unable to run Zap-Desktop on lnd beta

### ISSUE THREAD

**Issue by LachlanSean** [LN-Zap/zap-desktop#343]
I'm running lnd 0.4 using bitcoind 0.16 as the backend. lnd is synced to LN mainnet, autopilot is managing channels and paying invoices is fine via CLI.

Unable to run Zap-Wallet on top of lnd - either Zap via the debian install package or the master. 
I've tried both with lnd already running in the background and not.
Popup error is

![zap error](https://user-images.githubusercontent.com/37492868/37562373-a19ae456-2aba-11e8-852a-2094988c01c1.png)

While in the terminal window I get 
```
bitcoin@Bitcoin-fullnode:/home$ zap-desktop
icon:  /opt/Zap/resources/resources/icon.icns
LND ALREADY RUNNING
E0318 14:34:44.744573367    3280 ssl_transport_security.c:970] Handshake failed with fatal error SSL_ERROR_SSL: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE.
```

**Comment by mrfelton** [comment]
There is a fix for this here: https://github.com/LN-Zap/zap-desktop/pull/338

**Comment by LachlanSean** [comment]
Thanks. So the process would be to wait for this commit to get merged, then I'd just clone the master, recompile and it should run?
