### ISSUE TITLE
Crazy high CPU usage on Mac

### ISSUE THREAD

**Issue by pors** [LN-Zap/zap-desktop#344]
I just installed release v0.1.1-beta for Mac OS and it works fine, but every now and then it goes crazy with CPU usage. The fans kick in and it won't stop after that. 

![screen shot 2018-03-18 at 11 55 15 am](https://user-images.githubusercontent.com/1078320/37564676-5cf189fc-2aa3-11e8-9eda-edbc284d7b43.png)

**Comment by Empact** [comment]
Hey, looks like the issue you're referring to is with LND:
https://github.com/lightningnetwork/lnd

I take it you're relying on the bundled lnd, not running your own?

**Comment by pors** [comment]
@Empact yes I run it bundled. Am I the only one having this issue? I downloaded a compiled release so you would think everyone would have this?

I'll refer to this issue at LND anyway, thanks.

**Comment by Empact** [comment]
@pors we’re currently bundling lnd 0.3.0, so you could try running the current version, lnd 0.4.0, yourself. If Zap detects an active lnd process on startup it will use that rather than start its own.

**Comment by pors** [comment]
OK, will give that a try!

**Comment by Empact** [comment]
If you run LND, then start Zap, and Zap successfully detects LND, you should see: "LND ALREADY RUNNING" in the log, and it should skip onboarding.

If you don't see that in the log, you may be running into #124

**Comment by pors** [comment]
I installed lnd 0.4.0 and it is up and running. Running Zap now results in this error:

![screen shot 2018-03-28 at 5 24 26 pm](https://user-images.githubusercontent.com/1078320/38035403-0102fcb8-32ad-11e8-8129-4c859e1e94e8.png)

**Comment by JimmyMow** [comment]
@pors what version of Zap are you trying to run? LND 0.4.0 may not be able to run with the old Zap releases. The API has changed and there is a new onboarding flow for creating and unlocking your wallet. I'd pull from master if you'd like to use Zap with new LND releases

**Comment by pors** [comment]
@JimmyMow I used v0.1.1-beta for Mac so I don't have to build it myself. When do you think you'll release a new version? Otherwise, I can try to build it myself from master.

**Comment by mrfelton** [comment]
Given that this bug report relates to a very old version of lnd and zap I'm going to close this issue as no longer relevant. @pors please feel free to reopen if you experience the same issue with the most recent release of Zap (currently 0.2.1). Thanks,
