### ISSUE TITLE
Add Contacts screen needs more instructional help

### ISSUE THREAD

**Issue by hoffmabc** [LN-Zap/zap-desktop#345]
As a first time user or someone not too familiar with lightning, it would be good to see this screen help people out a little further as to what this UI is for.

![image](https://user-images.githubusercontent.com/45482/37569465-26077512-2ab9-11e8-91ca-7a4a0efaa7f8.png)

**Comment by mrfelton** [comment]
I'm closing this issue a the screenshot here refers to a very old version of the app, and the channel management area has had a full redesign and rebuild since.
