### ISSUE TITLE
"Zap Tutorial" button directs to dead page

### ISSUE THREAD

**Issue by HenrySabio** [LN-Zap/zap-desktop#3473]
## Description

When setting up or restoring a wallet, the "Zap Tutorials" button directs to a non existent page.

## Expected Behavior

When clicked the button should take you to the zap documentation or tutorial page.

## Actual Behavior

When clicked, this button opens a window to "https://ln-zap.github.io/zap-tutorials/" which is no longer a hosted page.

## Possible Fix

According to the zap-tutorials repo, this is now hosted at: "https://docs.zaphq.io/"
The link used in the desktop app must be updated 

## Steps to Reproduce

- 1. Set up a new wallet or restore an existing one
- 2. While block chain is syncing or wallet is restore click "Zap Tutorials" button that is visible in center screen

## Context

I'm a new user and looking to learn more about the platform and how to make the most of the app.
(I don't run my own node or anything and inbound capacity sure has been confusing.)

I would fix this myself but I don't have a lot of experience contributing on github and would have to figure out how to begin. I might give it a shot for fun if someone else doesn't get to it by the time I figure it out.

## Your Environment

- Zap version: 0.6.2 Beta
- Operating System and version: Mac OS Catalina 10.15.4

**Comment by bolatovumar** [comment]
@HenrySabio this was fixed here: https://github.com/LN-Zap/zap-desktop/pull/3295. Just hasn't been released yet.
