### ISSUE TITLE
Notification for on-chain bitcoin received shows as "Bitcoins sent"

### ISSUE THREAD

**Issue by RubenWaterman** [LN-Zap/zap-desktop#3477]
Instead of getting a notification that bitcoin has been received, the notification indicates that bitcoin were sent out of the wallet:

![Screenshot 2020-04-20 at 12 21 31](https://user-images.githubusercontent.com/5938863/79741811-27418500-8302-11ea-9dee-e35f49339b66.png)

## Expected Behavior
I was expecting a notification that would say: "On-chain Transaction Received!"

## Current Behavior
I get an "On-chain Transaction Sent" notification

## Steps to Reproduce
1. Send on-chain bitcoin to your lnd wallet

## Context (Environment)
- Zap version: 0.6.2 Beta
- LND: 0.10.0-beta.rc2
- Operating System and version: Mac OS Catalina 10.15.3

**Comment by mrfelton** [comment]
Hi, thanks for your report. This has already been fixed in the next branch and will be included in our next release.
