### ISSUE TITLE
Zap onchain BTC address does not belong to lnd wallet to which I'm connected to

### ISSUE THREAD

**Issue by stefan-mihaila** [LN-Zap/zap-desktop#3478]
## Description

I'm using Zap with my own lnd node. I had a lnd node, closed all channels and emptied out the wallet. Formatted HD, created new lnd node, restored a different older wallet.

Connected Zap to it. At this point, I think the sync for lnd wasn't finished. Then I was reckless, and sent a considerable sats amount in the address generated in Zap. The funds didn't show up, I thought it was because the node didn't sync yet. But, after syncing, funds not there yet.

~~Connecting to lnd, `lncli newaddress` generates different address than that found in Zap.~~ I seems that the address generated by Zap does not belong to my wallet. I tried running [dropwtxmgr](https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md#forced-in-place-rescan) on my lnd wallet. This resulted in some older tx for this wallet (a few months old, since this was a restored, but empty wallet) showing up, but not the one that I just did.

Confirmed with small amounts that new transactions to the address in Zap don't show up, but the ones to the `lncli newaddress` do show up.

Edit: sorry for the description not being clear enough, see: https://github.com/LN-Zap/zap-desktop/issues/3478#issuecomment-619617989

## Expected Behavior

~~Onchain address in Zap should be the same with the one in `lncli neweaddress`~~

Onchain address in Zap should belong to my lnd wallet

## Actual Behavior

~~Different address~~

Address doesn't belong to my wallet

## Possible Fix

I hope there is one 

## Steps to Reproduce

I tried to reproduce it now on a Polar simnet network (just once tbh) using dev, but didn't manage to. Still, my release Zap is in this inconsistent state.

## Your Environment

- Zap version: 0.6.2-beta
- Operating System and version: mac OS Catalina
- lnd: 0.9.2-beta

**Comment by stefan-mihaila** [comment]
oh, also, starting development Zap with the same lndconnect string, seems to work as expected, meaning it seems to generate valid addresses.

**Comment by stefan-mihaila** [comment]
he address in Zap didn’t change after depositing in it, even though I can see the tx with multiple confirmations on the blockchain. it's still there, I can still deposit to it and the balance doesn't get updated

**Comment by mrfelton** [comment]
`lncli newaddress` generates a new address every time you run it, so I wouldn't expect it to show you the same address as you see in zap. The address that we show in zap is also generated by running the lnd `newaddress` command though (the newaddress rpc command actually). I can't think of any reason why it would give you an address that you can's receive coins to.

> Formatted HD, created new lnd node, restored a different older wallet

Can you elaborate on exactly what you did here? You said that you were connecting to your own lnd node, so I'm not sure what you mean about "restoring a different older wallet" What exactly did you restore and hw did you do it?

**Comment by stefan-mihaila** [comment]
Sorry, I tried to give as much details as possible and maybe those details were not relevant, and were just confusing. Let me try to stick to what is relevant, and I can give further details if you think they are needed.

What's relevant, is that I had an old Zap wallet, connected to an old lnd node. I deleted the wallet in Zap. I created a new wallet in Zap, and connected to a new lnd node. And right now I can see a deposit address in Zap, but that address doesn't belong to my lnd wallet to which I'm sure I am connected. Depositing to that address in Zap doesn't lead to a new address being created in Zap (as that address doesn't belong to my lnd wallet, so Zap doesn't receive events about those deposits). I can confirm by other means that Zap is connected to the correct lnd node.

Right now my suspicion is that somehow the address that I see in Zap doesn't belong to the lnd node that I'm connected to, but maybe to one of my previous wallets I had in Zap. Sadly, I don't have access to the old node or the seed of that wallet confirm this suspicion. Then again, maybe my suspicion is completely wrong. But it definitely looks like a bug right now, unless I'm really missing something it does look like the address I see in Zap doesn't belong to my lnd wallet to which I am connected to.

I can confirm that I am connected to that lnd node, cause if I deposit to addresses created with lncli newaddress, those deposits show up in Zap correctly. But depositing to the address I see in Zap seems to just result in lost funds...

**Comment by mrfelton** [comment]
What version of zap are you using now? And what version of zap were you using when you connected to the first wallet?

Do you still have access to that first lnd node that you connected to? Do your deposits show up there?

Also, were either of these lnd nodes that you connected restored from a seed?

**Comment by stefan-mihaila** [comment]
Right now I'm on Zap 0.6.2-beta. I've been using it for a long time, but I think I've always updated. I've been using it with multiple nodes I guess, since it has a history...

I don't have access to the 1st node anymore (not really 1st, since I've been using Zap for a while now), neither to the seed 😔 My bad, but since I wanted to reinstall a new node and I just emptied that wallet completely I didn't care about the seed. Actually, now because of this I looked through notes of old seeds and found one, but I really don't think that is the one, but I'll check to make sure.

Yes, the last one that I'm now running was restored from a seed. At 1st I didn't see old onchain tx in Zap. But then I actually did a [droptxmgr](https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md#forced-in-place-rescan) on it and old transactions from a few months ago showed up, but not the new one.

**Comment by mrfelton** [comment]
How is this lnd node running? Is it connected to a bitcoind node or are you running it as a neutrino client?

**Comment by stefan-mihaila** [comment]
connected to bitcoind

**Comment by mrfelton** [comment]
When you restored the node from seed, what did you use as the recovery window?

**Comment by stefan-mihaila** [comment]
The default one, I think is 1500. But tried with 3000 or more also. I don't see any way in the world that I would have thousands of unused addresses.

**Comment by stefan-mihaila** [comment]
but I can try it again just to make sure

**Comment by mrfelton** [comment]
Can you start zap with `DEBUG_PROD=1` which should bring up chrome devtools, and then inspect the indexedDb database. Have a look at the nodes table and verify that the wallet address that you are seeing in zap is associated with the correct pubkey in there (from the node you are connected to). See screenshot below:

![image](https://user-images.githubusercontent.com/200251/80319455-8a567e80-8810-11ea-8d3c-c5b1c604e3a5.png)

See https://github.com/LN-Zap/zap-desktop/blob/master/docs/DEBUGGING.md for info on debugging.

You should be able to fix the problem by deleting the relevant entry from the `nodes` table and then reload zap - which should cause zap to regenerate a new address for that node - but I'd rather you didn't. I want to understand what's happed.

**Comment by stefan-mihaila** [comment]
Yes, exactly, I think this is a serious bug if we confirm it and it's better to get it fixed, that's why I didn't mess up too much with my node since this happened. Okay, I'll take a look. I'm also on Slack if you prefer that.

**Comment by mrfelton** [comment]
Yeah, slack would be good. I'm there.

**Comment by stefan-mihaila** [comment]
This is definitely not a bug in Zap. Zap got the address by calling the node's gRPC NextAddr while lnd was restoring from a backup. Looks like somehow that address returned by lnd was outside the default recovery window. Using a window larger than the default did the trick. Thank you @mrfelton for the support!
