### ISSUE TITLE
AppImage fails to execute on Debian 10.3

### ISSUE THREAD

**Issue by guycall** [LN-Zap/zap-desktop#3481]
Executing the latest AppImage (`Zap-linux-x86_64-v0.6.2-beta.AppImage`) on a fresh install of Debian 10.3 gives the following error: 

```
FATAL:setuid_sandbox_host.cc(157) The SUID sandbox helper binary was found, but is not configured correctly. 
Rather than run without sandboxing I'm aborting now. 
You need to make sure that /tmp/.mount_Zap-XXXXXX/chrome-sandbox is owned by root and has mode 4755
```

Seems like lots of Electron apps are now suffering with this:

https://github.com/tutao/tutanota/issues/1565
https://github.com/electron/electron/issues/17972#issuecomment-516957971
https://github.com/laurent22/joplin/issues/2246

**Comment by mrfelton** [comment]
@guycall could you try building a version from the master branch and see if that works for you please?

See https://github.com/LN-Zap/zap-desktop/blob/master/docs/ADVANCED.md#packaging

**Comment by mrfelton** [comment]
Hi, please give this a try with the latest release?

https://github.com/LN-Zap/zap-desktop/releases/tag/v0.7.0-beta

**Comment by guycall** [comment]
As before running 0.7.0-beta AppImage give an error on Debian 10.3 `FATAL:setuid_sandbox_host.cc(157) The SUID sandbox helper binary was found ...`

**Comment by mrfelton** [comment]
Ok, maybe I’ll look at building a Snap image or something.

**Comment by mauddibbtc** [comment]
debian current rolling release - kali rolling edition
  - will not install on xfce desktop due to gnome-keyring issue (if this is useful to this debian 10.3 issue exact error message can be reproduced and provided)

**Comment by guycall** [comment]
Looks like Electron solved this issue - ﻿https://github.com/electron/electron/issues/17972

**Comment by rahulbile** [comment]
Latest release have electron update. Also tested with latest release on Linux and seems to work fine. Please reopen if you are still facing issue.
