### ISSUE TITLE
Switch neutrino wallet to full node?

### ISSUE THREAD

**Issue by arcbtc** [LN-Zap/zap-desktop#3482]
So I have my glorious neutrino Zap desktop wallet, which works very well, but now I want to use my own block data. 

Can I easily switch the wallet from neutrino to a full LN node, ie just use my own block data?

![image](https://user-images.githubusercontent.com/33088785/80910607-776c0e80-8d28-11ea-9cec-980852090088.png)

**Comment by mrfelton** [comment]
Right now - we don't provide a way to switch from neutrino to direct full node connection. You can however connect to your own neutrino serving full node by editing the wallet settings

![image](https://user-images.githubusercontent.com/200251/80915432-97b0c300-8d52-11ea-8068-606c9a77ac7e.png)

**Comment by mrfelton** [comment]
@arcbtc I'm going to close this issue as I think my comments above address this - you can use your own full node for block info by changing the configured neutrino nodes in the wallet settings page.
