### ISSUE TITLE
Add value box for --amt after scanning 0 amount QR codes

### ISSUE THREAD

**Issue by The34Goon** [LN-Zap/zap-desktop#3543]
## Can't proceed when scanning tippin.me or other 0 AMT pay_req QR codes.

![image](https://user-images.githubusercontent.com/60571408/83802611-5726cb00-a6ab-11ea-8468-53b8b628328e.png)
Hodlonaut's Tippin.me

![image](https://user-images.githubusercontent.com/60571408/83802709-905f3b00-a6ab-11ea-997a-6287502f3105.png)
Can't proceed in ZAP // most users won't go down to the CLI
lncli sendpayment --pay_req value --amt value

## It would be nice to add the amount in ZAP after scanning such pay_req.
Fix: Adding a small box where the amount of sats can be set.

## Your Environment
LND 0.10.0-beta / ZAP 0.6.2-Beta

**Comment by mrfelton** [comment]
We don't support invoices with a zero amount because of associated security concerns (we used to, but have since removed support). The next version of zap will support spontaneous payments using keysend rather than zero amount invoices.
