### ISSUE TITLE
Google Backup: "Couldn't sign you in"

### ISSUE THREAD

**Issue by blankscreengithub** [LN-Zap/zap-desktop#3555]
When using the windows installer and setting up the wallet the first time, I selected Google Drive as the backup option. After I put in my email address, I get an error from Google.

This is the error I receive: "Google Couldn't sign you in. This browser or app may not be secure. Learn more. Try using a different browser. If you're already using a supported browser, you can refresh your screen and try again to sign in."

See attached picture.
![google error](https://user-images.githubusercontent.com/66571264/83978726-0bed0200-a8cf-11ea-9f0a-a6e47304fc97.jpg)

## Expected Behavior

I should be able to put in my Google account password and back up to my Google account.

## Actual Behavior

The Zap app times out on the Google log in screen and goes straight to my wallet. When I go the "Profile" screen -> "Node Info", "Backup Method" is listed as "Google Drive", even though I never actually was able to put in my password for the backup method.

## Possible Fix

I am unable to backup to my Google Drive and I am unable to change the backup method under the "Profile" -> "Node Info" screen.

## Steps to Reproduce

- 1. Install software
- 2. Setup new wallet
- 3. Select Google Drive as backup option
- 4. Enter email address
- 5. Receive error from Google about insecure browser

## Context

Trying to setup my back location to Google Drive and right now I do not have a backup setup.

## Your Environment

- Zap version: 0.6.2-beta
- Operating System and version: Windows 10 Home - Version 1909 - OS Build 18363.836
- Google Chrome: Version 83.0.4103.61 (Official Build) (64-bit)

**Comment by mrfelton** [comment]
Hi, this is already fixed in the `master` branch and will be included in the next release. Thanks.
