### ISSUE TITLE
[UX] Concepts explanation when the wallet is syncing are too superficial

### ISSUE THREAD

**Issue by patestevao** [LN-Zap/zap-desktop#357]
When bootstrapping the wallet, I noticed there are some slides trying to explain somethings about LN for the use.

**Version** is v0.1.0-beta release for MacOs and run on a macOS High Sierra v10.13.3.

While the “Lightning Network” concept is good, the others are a little too superficial for someone to understand (people will only understand if they already know those concepts).

Maybe that space could give some practical tips and explanations about the wallet’s usage and have a “learn more” link where the person can go and see a better explanation of the technical concepts.

The intention of the explanations is very good but the problem here is that if they are too superficial  for whatever reason (e.g. there's not enough space to explain details), the user may get more confused than before.

Any thoughts on this? Let me know if I can help with the discussion and some ideas, of course.

**Comment by mrfelton** [comment]
These messages were removed some time ago in favour of more direct status updates during the sync process where we now show a breakdown of the sync progress to help users understand how much longer there is left in the sync process, as well as a link to our getting started tutorials.
