### ISSUE TITLE
Password reported as incorrect

### ISSUE THREAD

**Issue by dennisreimann** [LN-Zap/zap-desktop#3598]
## Description

Since upgrading to v0.7.0 I cannot log in using my password anymore – the password is reported as incorrect, even though it's correct.

## Your Environment

- Zap version: v0.7.0
- Operating System and version: macOS 10.14.6

**Comment by mrfelton** [comment]
We will he releasing an update to address this issue shortly. In the meantime you can download the previous release and continue to use that. Apologies for the inconvenience.

**Comment by dennisreimann** [comment]
No problem, just wanted to report it and see if others are also experiencing this. Thanks for fixing and keep up the good work!

**Comment by mrfelton** [comment]
Hi, I've just published v0.7.1 that should resolve this issue.

https://github.com/LN-Zap/zap-desktop/releases/tag/v0.7.1-beta

Cheers

**Comment by dennisreimann** [comment]
Upgrade via the in-app update mechanisms – works like a charm again. Thanks 🍰
