### ISSUE TITLE
24 hour time format

### ISSUE THREAD

**Issue by klauslovgreen** [LN-Zap/zap-desktop#3600]
## Detailed Description
Please can you enable support for 24H the format for the Mac Desktop app (ideally just replicate whatever the system is currently using). It already works on iOS ;-)

## Context

Some people have issues figuring am/pm out.. :-)

## Your Environment

- Zap version:
- Operating System and version:

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/3688
