### ISSUE TITLE
After updating - Lnd has unexpectedly quit! (SCB file access issue)

### ISSUE THREAD

**Issue by rexmint** [LN-Zap/zap-desktop#3601]
I had downloaded Zap v0.6.2-beta.exe from the website and been using it for months now. 

Today I downloaded Zap-win-v0.7.1-beta.exe and updated Zap.

When I load my wallet from my PC it syncs then within 10 seconds usually this error appears;

Lnd has unexpectedly quit!
Error code: 1
Error signal: Unknown
Error message: Unknown

I have tried uninstalling then reinstalling v0.6.2, v0.7.0 and v0.7.1 but now I can't access my wallet that I have on this PC.

I tested to see if I could connect my BTCPayServer I have on a Lunanode server and it connects just fine.

![2020-07-13](https://user-images.githubusercontent.com/44492473/87353433-c86b6080-c52a-11ea-8684-f6491c8ba4c8.png)

I have 2 channels opened with this wallet that are connected to my node on Lunanode, hoping I can somehow save my coins at the very least.

**Comment by NotNotGoodCo** [comment]
I have the exact same issue.

**Comment by mrfelton** [comment]
Hi, I'm guessing that this is the same issue reported here https://github.com/LN-Zap/zap-desktop/issues/3591

Can you try the suggested workaround from there please?

**Comment by NotNotGoodCo** [comment]
Thankyou, that got it working!

**Comment by rexmint** [comment]
Removing file `channel.backup` allowed the wallet and `lnd` to start up correctly.

Issue resolved.

**Comment by mrfelton** [comment]
See https://github.com/LN-Zap/zap-desktop/issues/3601

I'm hoping lnd team will cut a new release 10.x fix with this release soon. If not we'll patch our fork and release an update with the fix.
