### ISSUE TITLE
How does Time Lock work?

### ISSUE THREAD

**Issue by dorothy617** [LN-Zap/zap-desktop#3607]
so i have a invoice says 377 time lock what does this actually mean does it mean when 377 confirms are done the time lock is over i am curious to know cause at times when i try to close a channel it says pending and have to wait a day or 2 to close it please advise.

thanks in advance

**Comment by dorothy617** [comment]
any one any advise?

**Comment by mrfelton** [comment]
In the event of an uncooperative close (force close) of a channel, the time lock is the number of blocks you will have to wait before you can claim your funds again.
