### ISSUE TITLE
Channel creation transaction not appearing in mempool

### ISSUE THREAD

**Issue by craig5999** [LN-Zap/zap-desktop#3615]
Approximately 24 hours ago, I tried opening a channel using the slow option (1 sat/byte). I think I should I be seeing my txid in the mempool, but it's not there...

What to do?

**Comment by mrfelton** [comment]
Sometimes lnd can fail to broadcast the funding transaction. You can try to restart your node which may cause it to get rebroadcast. Failing that, and if you are sure the transaction never got broadcast you can use the `abandonchannel` RPC to abandon the channel.
