### ISSUE TITLE
Lost Funds on Zap Please Help!!!

### ISSUE THREAD

**Issue by james1048** [LN-Zap/zap-desktop#3624]
Well i was running my zap wallet on my server but the server crashed i always new if it crashed i would loose funds so i backed up the seed the zap folder it self and the channels i saved locally.

Now when i replicate exactly how it was on my server put the zap folder the channels i get this 

Lnd has unexpectedly quit!
Error code:
1
Error signal:
Unknown
Error message:
Unable to open channeldb: channel db cannot revert to prior version

Then i recovered my wallet from seed but now the channels have disappeared i had 3 channels pending closing after 1466 confirms  my main question is once they reach the confirm of 1466 will funds show in my wallet since now i can t import my channels what do i do  i can keep track if funds will come or not can any one help i'd be willing to pay if i can recover the funds my experience in this is very small but i did back all necessary files not sure if i can recover funds or not please advise?

**Comment by mrfelton** [comment]
> Unable to open channeldb: channel db cannot revert to prior version

That sounds like you are trying to use your wallet data with an older version of lnd. 

> I recovered my wallet from seed but now the channels have disappeared

Restoring from a seed does not recover funds from channels. Please see https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md for details on how to fully restore the funds.

**Comment by onefedora** [comment]
what if we don't have a ln channel backup?  i use zap desktop and it did not even prompt me to do a backup when i opened a ln channel.

**Comment by mrfelton** [comment]
Sorry you experienced this issue

>  what if we don't have a ln channel backup? i use zap desktop and it did not even prompt me to do a backup when i opened a ln channel.

It does provide some details about and options for backing up the wallet state data when you go through the wallet creation flow. I think those warnings that are provided in the wallet creation flow are adequate. Backing up the wallet data is the responsibility of the user.

**Comment by dpgaller** [comment]
Hi, I keep getting the following error message on my ZAP bitcoin Wallet for Desktop: 
Lnd has unexpectedly quit!
Error code:
1
Error signal:
Unknown
Error message:
Shutting down because error in main method: error creating wallet config: unable to initialize neutrino backend: unable to create neutrino light client: unable to read header: EOF

Please help me get back into my wallet, not sure what to do here?
