### ISSUE TITLE
Current Confirmed Balance not updating.

### ISSUE THREAD

**Issue by citizenanalog** [LN-Zap/zap-desktop#3625]
#200  Description

When attempting to make a payment from Lightning wallet, the confirmed on-chain balance does not update. The value reported here is static from whenever Zap was started. 

## Expected Behavior

Pay Screen: 'Your currrent balance' (onchain) value should update dynamically.

## Actual Behavior

Pay Screen: 'Your currrent balance' (onchain) value is read on Zap startup and not updated.

## Possible Fix

Zap not fetching lncli walletbalance periodically?

## Steps to Reproduce

1. Connect Zap to lnd wallet. Verify onchain wallet balance matches in Zap main screen, and on Pay (send bitcoin) screen, and in command line lncli walletbalance (confirmed balance).

2. Send or Receive btc to Zap connected lnd wallet and do not close Zap. Once transaction is confirmed (check via command line), check ''Your currrent balance' (onchain) value at the bottom of Pay screen (send bitcoin). This value does not update dynamically.

3. Restart Zap and current onchain balance is updated to correct value.

## Context

Was trying to send funds and getting error (not enough confirmed funds).

## Your Environment

- Zap version: 0.7.2 beta
- Operating System and version: Ubuntu 20.04.1 LTS

**Comment by quantumas** [comment]
I have exact same issue but with built in lnd and neutrino. Sometimes it works but most of time it does not and usually have to hit log out and log in every hour or so to refresh channel states and wallet balances.

**Comment by mrfelton** [comment]
Some updates were made to the balance handling in next branch and I've verified this behaviour to be working as expected. Will be included in next release
