### ISSUE TITLE
Sort by "Capacity" in channel list is broken

### ISSUE THREAD

**Issue by danielalexiuc** [LN-Zap/zap-desktop#3633]
## Description

Sort by "Capacity" doesn't work very well.

## Expected Behavior

It should sort channels by the total amount of capacity in the channel (i.e. the 'capacity' heading on the node.

## Actual Behavior

Not sure exactly, I think it's doing some kind of alphabetic sort instead of sorting by the amount of capacity in the channel. Perhaps it's only an issue with Wumbo channels? I've never noticed it before.

See screenshot for a better description.

![Zap 2020-09-24 07 17 38](https://user-images.githubusercontent.com/139083/94070755-1c04ff00-fe36-11ea-90f2-4a407a868fdf.png)

## Steps to Reproduce

- 1. Cllick 'Channels', Manage
- 2. Select 'Capacity' in the 'Sort by'  dropdown
- 3. Try ascending and descending, both sort channels incorrectly

## Context

I'm trying to bring my largest capacity channels to the top of the list so I can observe them.

## Your Environment

- Zap version: 0.7.2-beta

- Operating System and version: Windows 10

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/3634
