### ISSUE TITLE
Why my Zap creates new channel himself?

### ISSUE THREAD

**Issue by JHPSoft** [LN-Zap/zap-desktop#365]
I have only added yalls.org node(039cc950286a8fa99218283d1adc2456e0d5e81be558da77dd6e85ba9a1fff5ad3@34.200.252.146)
to my zap wallet.

But sometimes zap creates new connection (ex, lightnode.ch , Thunderstream.io ...)
Each channel pend 0.16768528 tBTC (+ used my 2652 satoshis for tx fee. wtf)
When I tried to disconnect them, they fall into 'Removing',
and to refund pended btc, I had to wait almost 7 days
(Is this hashed time lock?)

Few hours or days later, zap creates new connection again and again.

**Comment by guggero** [comment]
Hi
Did you activate the 'autopilot' feature?
The autopilot automatically creates channels for up to 60% of your on-chain funds.

**Comment by archchi** [comment]
I'm having the same issue as JHPSoft. 
guggero, I did not knowingly activate an 'autopilot' feature, nor did I realize there was one. There's no settings I can find on the UI, so where's the config file located on Linux and how do I modify that setting or disable it? Thanks.

**Comment by guggero** [comment]
Did you start `lnd` yourself or did Zap do it for you?
In the current version there is an 'Onboarding' process that starts right after you start the GUI (in case Zap starts the `lnd` process). It first asks you for an alias and then if you want to activate the autopilot.
If you started `lnd` yourself, check your `lnd.conf` if autopilot is set to 1

**Comment by archchi** [comment]
Zap starts lnd, but I was neither asked for an alias nor if I wanted to activate the autopilot. Also, there is no lnd.conf on my system, only the lnd binary and a lnd.log file.

**Comment by archchi** [comment]
I should mention that deb files are not natively supported on Arch, so I had to use a tool to convert it to a Pacman-friendly (Arch package manager) format to install it. That could be part of the problem, perhaps. Also, the program never prompted me to write down a wallet seed, so there's no way to recover my coins if the installation gets corrupted and I need to reinstall. There was the threat of that when I manually killed the lnd process and the next time I opened Zap, I got a cryptic javascript error message that I wasn't able to copy at the time, and the application just hung on "loading" and I couldn't access anything. Fortunately, that seems to resolve itself after a few attempts.
Perhaps you could [paste an example lnd.conf](https://bpaste.net/) and tell me where it should live on my system and I'll see if I can disable the autopilot feature that way.

**Comment by archchi** [comment]
I modified the lnd.conf file to turn off the autopilot, but it didn't make a difference. I have the lnd.conf located in the POSIX default of ~/.lnd/data
Does Zap read it from a different location?

**Comment by archchi** [comment]
@JHPSoft, I moved it to ~/.lnd but autopilot still persists even though I have it set to "off"
`~/.lnd/lnd.conf`
`autopilot.active=0`

**Comment by JHPSoft** [comment]
@archchi 
I wrote `autopilot.active=0` too. 
But my zap still open channel automatically.
So I added `autopilot.maxchannels=0`
And it looks stop to open channel

**Comment by archchi** [comment]
@JHPSoft 
Yes, that seems to work.
I think the autopilot.maxchannels=0 should only have relevancy if autopilot.active=1 but I guess that's for the devs to decide.
Thanks for your help.

**Comment by JimmyMow** [comment]
Zap's LND config is in https://github.com/LN-Zap/zap-desktop/blob/master/app/main.dev.js

The `testnet` release we set `autopilot` on by default. Our next upcoming release you will be able to configure `autopilot` in the onboarding flow along with things like `alias`, `remote node setup`, `wallet encryption`, etc.

I am going to close this as it is not an "issue" :)
