### ISSUE TITLE
pending open for 12 hours, channel Zap Technologies

### ISSUE THREAD

**Issue by junl2004** [LN-Zap/zap-desktop#3702]
## Description

pending open for 12 hours, channel Zap Technologies
Funding Transaction b6c8153782507fac3296e376054e68939cd755e32aec411ee67220837d0b631d
how to cancel and get fund back?
![image](https://user-images.githubusercontent.com/39245652/104108071-8bccb780-5276-11eb-9d96-07c371527fb8.png)

## Expected Behavior
expect online tx loaded into channel

  

## Actual Behavior
pending

## Steps to Reproduce

- 1.
- 2.
- 3.
- 4.

## Your Environment

- Zap version:0.7.2
- Operating System and version: win10

**Comment by bolatovumar** [comment]
@junl2004 looks like you transaction is still pending: https://blockstream.info/tx/b6c8153782507fac3296e376054e68939cd755e32aec411ee67220837d0b631d

It was sent with a very low fee which at current fee rates (see https://twitter.com/bitcoin_fees for approximate fee rates) will take a while to confirm. There might be a way to re-broadcast the transaction with a higher fee but I don't believe you can do this from the Zap UI. @mrfelton do you know if the tx can be re-broadcast with a higher fee?

**Comment by kdavis91** [comment]
ZAP has RBF enabled, but I don't think it allows you to broadcast again with higher fees.

**Comment by junl2004** [comment]
Hello, I checked the TX, it shows "Transaction not found" now.
What is the next step? do I lose 50k Sat?

**Comment by bolatovumar** [comment]
> Hello, I checked the TX, it shows "Transaction not found" now.
> What is the next step? do I lose 50k Sat?

Looks like the tx is still pending?https://blockstream.info/tx/b6c8153782507fac3296e376054e68939cd755e32aec411ee67220837d0b631d

I would wait for it to clear which might take a while until fees are low enough again. Alternatively you could probably build your own version of LND and use it to rebroadcast your transaction but that would require some work.

**Comment by grubeli** [comment]
DONE.
Okay. I found a way to return our funds.
if your funds are stuck like mine, I mean you send them from Zap (on-chain) wallet to Zap Lightening and is stuck on Pending.
What you need is to copy your recovery words, download new app on a different PC and recover (!) your wallet from the seed numbers you copied before. if you don't have a different PC you can use virtualization software like virtualbox (https://www.virtualbox.org) to create a virtual PC and install Zap on it.

After that, when you open your Zap on that new PC you will see all your coins on On-Chain, it means you can send it back to your original account/address or any other address

**Comment by mrfelton** [comment]
Closing as OP resolved their issue. Also, the blockchain explorer shows that the low fee transaction did eventually confirm.
