### ISSUE TITLE
blockchain  not syncronizing

### ISSUE THREAD

**Issue by WillSteiner72** [LN-Zap/zap-desktop#3703]
blockchain on ZAP is not syncronizing

see picture. I have sent some sathoshi to the wallet, but I cannot see them, the blockchain is not syncronizing. Transaction was confirmed

blockchain should syncronize and I should see the sathoshi

blockchain is not syncronizing and I do not see the satoshi

No suggestion
![Zap bug](https://user-images.githubusercontent.com/77378952/104418309-fcc1e700-5576-11eb-832a-f9ad0cd48616.jpg)

## Your Environment

iOS14.2

- Zap version: ZapiOs
- Operating System and version:

**Comment by bolatovumar** [comment]
@WillSteiner72 this repo is for the desktop version of Zap. You should close this issue and create an issue in the iOS repo instead. https://github.com/LN-Zap/zap-iOS

**Comment by WillSteiner72** [comment]
Yes, you are right, will do. Thanks (by the way, now seems to synchronize, 12% in 10 minutes.....)
