### ISSUE TITLE
There is no intuitive way to sweep a wallet

### ISSUE THREAD

**Issue by archchi** [LN-Zap/zap-desktop#371]
I want to completely empty out my wallet to zero balance for testing purposes, but if I put in the full amount I get:
`Error: insufficient funds available to construct transaction`
because, obviously, network fees need to be factored in. There should be a "sweep wallet" feature that factors this in automatically.

**Comment by JimmyMow** [comment]
👍 nice. I think that would be a cool feature

**Comment by mrfelton** [comment]
This will be handled in https://github.com/LN-Zap/zap-desktop/issues/142 so closing this as a duplicate.
