### ISSUE TITLE
Onchain Payments don't work

### ISSUE THREAD

**Issue by JIBSIL** [LN-Zap/zap-desktop#3716]
I'm trying to send an onchain payment from my Zap wallet to another wallet of mine. I've selected the fee as 82 sat/byte and it's unconfirmed, but the transaction doesn't show up in the mempool or when you search for it on the blockchain. Even the inbuilt one where you click on the transaction and it opens it in the browser does not work.

Payments should clear to the blockchain

Payments don't show up in the blocjchain

Not sure, I'm not good at blockchain coding stuff

Send an onchain payment with no channels open

## Steps to Reproduce

- 1. Click pay,
- 2. enter your address
- 3. pay with medium fee or low fee (I tried both)
- 4. it doesn't work

## Context

Paying myself

## Your Environment

- Zap version: latest. I retrieved it a day or so ago
- Operating System and version: windows server 2016 64bit

**Comment by JIBSIL** [comment]
More info.
The transaction: https://blockstream.info/tx/43282e64f83fb9160fb9ee2026ef1b1b296878182cc1ed4246d6e97cfc102808
The address: https://blockstream.info/address/395DWkso1Lr9AZcthsnE38YLmdJ95w7zDf

**Comment by bolatovumar** [comment]
@JIBSIL Were the funds actually moved out of your wallet? If the transaction hasn't actually been broadcasted you can just send it again. If your wallet shows that the funds have been moved but you are sure they have not been moved you can try restoring your wallet again. The funds should be there.

**Comment by JIBSIL** [comment]
I found out that it was only a 2 satoshi fee.. I'll just wait for it to bounce, the fee probably wasn't enough to even cover the broadcast

**Comment by rahulbile** [comment]
@JIBSIL as the transaction was finally broadcasted and added to the block. Closing the issue.
