### ISSUE TITLE
My wallet isn't opening!

### ISSUE THREAD

**Issue by NoSkyline** [LN-Zap/zap-desktop#3719]
## Description
This won't let me use the wallet at all I can create new ones but the on with my founds doesn't work

## Actual Behavior

Wallet not opening
![Error Zap!](https://user-images.githubusercontent.com/80104086/110114284-c50f3880-7d8a-11eb-938b-e7af1ab4ee52.jpg)

## Steps to Reproduce

- 1. Create a channel with Zap node
- 2. With the minimum fee
- 3. Then wait 5-10 days
- 4. Try to open the wallet

## Context

I don't know how to get my founds back I am concerned that this might be irreversible.

## Your Environment

- Zap version:0.7.2-beta
- Operating System and version: windows 10

**Comment by bolatovumar** [comment]
Your funds should be safe. Even if this error keeps appearing you should still be able to recover the funds in other ways.

**Comment by NoSkyline** [comment]
What other ways?

**Comment by bolatovumar** [comment]
> What other ways?

By compiling LND from source and using the command line interface. See here: https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md

**Comment by NoSkyline** [comment]
I solved it!

I'm not sure
