### ISSUE TITLE
stuck at 100%

### ISSUE THREAD

**Issue by AndreiD** [LN-Zap/zap-desktop#3723]
- Zap version: 0.7.3-beta
- Operating System and version: MacOS lateste
![image](https://user-images.githubusercontent.com/542665/113161118-c1b28400-9246-11eb-9f76-f238b75e84e5.png)

ZAP 0.7.3-beta

**Comment by AndreiD** [comment]
any ideas

**Comment by digitalbuddha0101** [comment]
Same problem for me:

Zap version: 0.7.3-beta
Operating System and version: Windows 10

![Zap stuck at 100](https://user-images.githubusercontent.com/81981059/113597973-c018ff80-963c-11eb-95bf-57248e005bc7.png)

**Comment by bliotti** [comment]
Same issue beta 0.7.2 on Mac Big Sur

**Comment by AndreiD** [comment]
they stopped development on this project. RIP.... was a good nice wallet :(

**Comment by progone** [comment]
> they stopped development on this project. RIP.... was a good nice wallet :(

@AndreiD Which directory will I find my BTC?  I'd like to get my BTC out of this wallet.  Its not much but its something

**Comment by progone** [comment]
Can someone give me an answer?  It appears someone has updated the app 7 days ago.

**Comment by bolatovumar** [comment]
@progone Zap wallets are actually LND wallets so you will only be able to restore your wallet with LND and nothing else. If you have your recovery seed you should be able to restore it using LND.

**Comment by Papi969** [comment]
i have the same issue, is there a way to recover my btc? i only have a backup file

zap 0.7.2
W10

**Comment by AndreiD** [comment]
option 1) learn to do it yourself. option 2) hire a trustworthy developer
