### ISSUE TITLE
Recovery error with Trezor seed

### ISSUE THREAD

**Issue by cpshoemake** [LN-Zap/zap-desktop#3725]
I have a 24-word recovery seed originally generated by a Trezor 1. I attempted to import it into Zap for Windows (0.7.2-beta) to take advantage of the Lightning Network features, but I receive this error:
```
An error has occurred
The following error has occurred when recovering a wallet:
2 UNKNOWN: wrong seed version
```
Is this expected? Is there a workaround?

**Comment by mrfelton** [comment]
No, it's  different type of seed. lnd uses aezeed, Trezor uses BIP39.

https://github.com/lightningnetwork/lnd/tree/master/aezeed

**Comment by cpshoemake** [comment]
Thanks for the link @mrfelton . I understand now.
