### ISSUE TITLE
ZAP suggested a too low fee - Payment stuck for 2 weeks

### ISSUE THREAD

**Issue by AkumaNoTsubasa** [LN-Zap/zap-desktop#3726]
Win 10
Zap 0.7.2-Beta

I sent a payment 2 weeks ago with a fee ZAP suggested with a possible wait time of 24h. Sadly this fee way seemingly way too low. My transaction only started to be "visible" in the network 5 days ago and does not get confirmed.

Does ZAP have the functionality to bump the fees or cancel the payment?

Payment in Question: https://www.blockchain.com/btc/tx/7548c721ae4228f9c927345b6c321d3441846bf6813801f9720972fd344405e6

kind regards

**Comment by bolatovumar** [comment]
@AkumaNoTsubasa no, there is no functionality to bump the fee or cancel the transaction through Zap itself. You can wait for the payment to fall out of the mempool. Your funds are safe.

**Comment by AkumaNoTsubasa** [comment]
> @AkumaNoTsubasa no, there is no functionality to bump the fee or cancel the transaction through Zap itself. You can wait for the payment to fall out of the mempool. Your funds are safe.

And how long does it take to fall out of the mempool? Because almost 3 weeks now is seriously a damn long time :(

**Comment by bolatovumar** [comment]
> > @AkumaNoTsubasa no, there is no functionality to bump the fee or cancel the transaction through Zap itself. You can wait for the payment to fall out of the mempool. Your funds are safe.
> 
> And how long does it take to fall out of the mempool? Because almost 3 weeks now is seriously a damn long time :(

Can take a while. No guaranteed time.

**Comment by 88plug** [comment]
This is good to know! - but you also need to add export private key when wallet is running like every other wallet.

**Comment by escapedcat** [comment]
Can this be closed?

**Comment by mrfelton** [comment]
Yes, there is no issue with Zap here - there is no such thing as a too low fee. There is a fee estimate, and there are market conditions that determine actual fees. The two can and do diverge all the time since predicting the future is impossible.
