### ISSUE TITLE
Backup recovery words / private key after wallet is already setup

### ISSUE THREAD

**Issue by 88plug** [LN-Zap/zap-desktop#3727]
I cannot seem to backup my wallet/private keys after it has been setup.  Where can I find this function? If not available, can it be added?

I am using the AppImage

**Comment by bolatovumar** [comment]
I don't remember this for certain but I believe there is a back-up option when you first create the wallet. Not sure if this same option is available once the wallet has been created though.

**Comment by 88plug** [comment]
That is exactly the problem - every other wallet also lets you backup once running!

**Comment by mrfelton** [comment]
The wallet deliberately doesn't keep a copy of your seed, for obvious reasons. You must back it up when creating the wallet.

**Comment by mrfelton** [comment]
Closing as this is by design. The wallet deliberately does not store a copy of your seed, for your own security.
