### ISSUE TITLE
WalletUnlocker service is no longer available (pending lnd 0.13.0 breaking change)

### ISSUE THREAD

**Issue by musdom** [LN-Zap/zap-desktop#3730]
## Description

zap-desktop no longer works with lnd built from recent master branch . My zap-iOS however still works with the same lnd.

## Expected Behavior

zap-desktop connects to lnd as usual

## Actual Behavior

Displays a password prompt to unlock my already unlocked lnd wallet. When password is entered, encountered error: `2 UNKNOWN: wallet already unlocked, WalletUnlocker service is no longer available`

## Possible Fix

This merged lnd PR may be relevant: https://github.com/lightningnetwork/lnd/issues/3982

## Context

I accidentally built and ran lnd from master instead of the 0.12.1 tag, and now can't go back as it did a channel.db migration. 

## Your Environment

- Zap version: 0.7.2
- Operating System and version: Ubuntu 20.04

**Comment by sortofasian** [comment]
Same issue on Mac and Windows, remote or local using prebuilt binaries of lnd 0.13.0-beta.rc2. Still works normally on mobile.

**Comment by rbrooklyn** [comment]
Issue is unfortunately persisting in the latest 0.7.3 release.

**Comment by mrfelton** [comment]
We do not currently support lnd 0.13 though this is being worked on.

**Comment by rahulbile** [comment]
This is fixed in latest release 0.7.4-beta
