### ISSUE TITLE
Channels stuck in limbo closing

### ISSUE THREAD

**Issue by dorothy617** [LN-Zap/zap-desktop#3735]
So i have 4 channels open 1 is pending force close which may take few days the other 3 are just stuck in closing no on chain is being made what do i do if i abandonchannels do i loose funds?

i am unable to close them cause they don t exist as channel but as pending channels do i wait it out and hope to get a on chain payment back

any ideas?

**Comment by bolatovumar** [comment]
`abandonchannel` won't work here (see https://api.lightning.community/#abandonchannel). The easiest thing to do is to wait it out.

**Comment by dorothy617** [comment]
thanks i force closed channels all good
