### ISSUE TITLE
Receiving 70% less than I sent to my ZAP WALLET... WHY!!!?

### ISSUE THREAD

**Issue by mrpepe69** [LN-Zap/zap-desktop#3745]
Sending  52.33USD to my zap WALLET receiving 18.5USD?

##  Sending from my crypto wallet 0.001504BTC (52.33USD) receiving 0.00053 using On-chain payment.

I don't know what is happening because im checking Has id: https://blockchair.com/bitcoin/transaction/6bb9937fb969eec90122f9c126784ae9344f41243b51dfb722e3f410baf05a6b and I dont see any issue or any additional Fee...

More here: https://blockstream.info/tx/6bb9937fb969eec90122f9c126784ae9344f41243b51dfb722e3f410baf05a6b

I dont know how what is happening, I don't know if this is fixable but probably funds are lost...

## Recover funds

Used: zap-win-v0.7.2 beta

**Comment by bolatovumar** [comment]
@mrpepe69 0.001504 BTC is how much you paid in fees. Take a look at your transaction again and you will notice this:

![Screen Shot 2021-07-06 at 11 02 08 AM](https://user-images.githubusercontent.com/1934678/124646535-a197ef80-de49-11eb-90c7-455db7359980.png)

Also, I'm pretty sure this is not your transaction as this transaction sends 1.62002062 BTC and pays 0.001504 BTC in fees which makes sense. You are claiming that you sent 0.001504 BTC which is not what that transaction is doing.

**Comment by mrfelton** [comment]
It was a batch transaction that paid to 41 different outputs. One of them is OPs 0.00053 UTXO.

**Comment by bolatovumar** [comment]
@mrfelton yeah, that has nothing to do with Zap though. 0.001504 BTC is the tx fee and 0.00053 BTC is the output amount. So seems like this issue should be raised with whatever wallet initiated the send.

**Comment by mrfelton** [comment]
Yep

**Comment by mrfelton** [comment]
Closing as this is unrelated to Zap Desktop.
