### ISSUE TITLE
Error: EOF

### ISSUE THREAD

**Issue by archchi** [LN-Zap/zap-desktop#375]
Why do I keep getting this message when trying to open a channel?
Here's is the node I'm trying to connect to:
038f80b541c3a9c1bbd54b4b15a379db83221e3fb50d5ffc543cef6d62a7f71631@35.185.13.214
Can someone else try opening a channel to that node to help me troubleshoot?

**Comment by JimmyMow** [comment]
Just means the person you're trying to connect to isn't available or rejected the connection. Not a Zap or LND issue. Everything worked accordingly. Closing

**Comment by odb366** [comment]
We should use a more user friendly description, like: "The connection isn't available at this moment or it is rejected", rather than "EOF" ?
