### ISSUE TITLE
Transaction Error: IncorrectCltvExpiry

### ISSUE THREAD

**Issue by archchi** [LN-Zap/zap-desktop#376]
When trying to pay for a Starblocks coffee, the transaction failed with this message:
`IncorrectCltvExpiry(expiry=1294573, update=(lnwire.ChannelUpdate) { Signature: (*btcec.Signature)(0xc4233b2050)({ R: (*big.Int)(0xc423308d20)(75594086893570983287303355837468686514989197996746461084519568615634764188025), S: (*big.Int)(0xc423308d40)(36014512919534465459718555141430061390471993979039519380171766794937867024625) }), ChainHash: (chainhash.Hash) (len=32 cap=32) 000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943, ShortChannelID: (lnwire.ShortChannelID) 1288195:254:0, Timestamp: (uint32) 1524581708, Flags: (lnwire.ChanUpdateFlag) 1, TimeLockDelta: (uint16) 144, HtlcMinimumMsat: (lnwire.MilliSatoshi) 1 mSAT, BaseFee: (uint32) 1000, FeeRate: (uint32) 100 }`

**Comment by JimmyMow** [comment]
This is not a Zap error but an LND error. 

Also what version of Zap were you running? This was fixed in LND recently and is in master. You can compile and run LND yourself if you'd like the fix
