### ISSUE TITLE
Zap Linux desktop AppImage fails to start: `Fatal process out of memory: Failed to reserve memory for new V8 Isolate`

### ISSUE THREAD

**Issue by abetusk** [LN-Zap/zap-desktop#3762]
Downloading or upgrading to `Zap-linux-x86_64-v0.7.4-beta.AppImage` and running causes a crash within 1s of starting:

```
$ ./Zap-linux-x86_64-v0.7.4-beta.AppImage 


#
# Fatal error in , line 0
# Fatal process out of memory: Failed to reserve memory for new V8 Isolate
#
#
#
#FailureMessage Object: 0x7ffe9d4b0b90Illegal instruction (core dumped)
```

## Description

Download v0.7.2 from the ["Download" page](https://zaphq.io/download) from zaphq.io runs without issue. When running v0.7.2, there is a popup asking to upgrade. Doing so removes the v0.7.2 image and installs v0.7.4. Subsequent executions of v0.7.4 cause an immediate crash with the following error:

```
$ ./Zap-linux-x86_64-v0.7.4-beta.AppImage 


#
# Fatal error in , line 0
# Fatal process out of memory: Failed to reserve memory for new V8 Isolate
#
#
#
#FailureMessage Object: 0x7ffe9d4b0b90Illegal instruction (core dumped)
```

## Expected Behavior

That is runs without crashing.

## Actual Behavior

It immediately crashes on initial execution.

## Possible Fix

Doing a Google search, it looks like maybe signing the image can cause the issue? See [here](https://forum.qt.io/topic/102212/qtwebengine-signing-issues/18) and [here](https://forum.qt.io/topic/122388/qtwebenginecore-on-macos-fatal-process-out-of-memory-failed-to-reserve-memory-for-new-v8-isolate/2).

## Steps to Reproduce

```
$ wget 'https://github.com/LN-Zap/zap-desktop/releases/download/v0.7.4-beta/Zap-linux-x86_64-v0.7.4-beta.AppImage'
$ chmod u+x Zap-linux-x86_64-v0.7.4-beta.AppImage 
$ ./Zap-linux-x86_64-v0.7.4-beta.AppImage 


#
# Fatal error in , line 0
# Fatal process out of memory: Failed to reserve memory for new V8 Isolate
#
#
#
#FailureMessage Object: 0x7fffcffacde0Illegal instruction (core dumped)
```

## Context

I am unable to run v0.7.4. Running v0.7.2 works so long as I remember to always hit the 'install later' popup and have a backup of v0.7.2 to run when the application removes it from under me.

### Zap version

Zap-linux-x86_64-v0.7.4-beta.AppImage

### Operating System and version:

```
$ uname -a
Linux mill 4.4.0-210-generic #242-Ubuntu SMP Fri Apr 16 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ free -h
              total        used        free      shared  buff/cache   available
Mem:           7.7G        2.8G        1.5G        345M        3.4G        4.2G
Swap:          7.9G        866M        7.0G
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.7 LTS"

```

**Comment by rahulbile** [comment]
Thanks for reporting the issue @abetusk , I tested the app image on Linux and worked fine for me. Will recheck again with existing install update this week. If you find anything, please do update us.

**Comment by abetusk** [comment]
It might be a quirk of my system, either because my Ubuntu setup is old or because of some random libraries I installed. It would be nice to turn off updates and not have it remove the old install out from under me but I have a functional workaround.

**Comment by rahulbile** [comment]
Thanks for updates @abetusk.  Glad you got it working.

In Preferences -> General you can disable "Automatically download and install updates."

I am going to close the issue, feel free to open again if you see any Zap specific issue.
