### ISSUE TITLE
How do I recover a channel on ZAP

### ISSUE THREAD

**Issue by mpersico93** [LN-Zap/zap-desktop#3768]
Hi, 

I reset my PC and the lightning channel info has been lost.

I restored the BTC wallet in ZAP but I can just the see the on chain balance. I cannot see the lighting channel balance. 
I did not do a backup of the channel info.

Is there a way to recover my lightning funds?
I am using Linux

Thank you!

**Comment by onefedora** [comment]
I have the same question.  Did you figure this out?

**Comment by mrfelton** [comment]
Hi, Zap Desktop doesn't currently support recovery on funds in channels when importing from a seed backup. You can recover using lnd directly. See https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md if you have a backup of the Static Channel Backup file.
