### ISSUE TITLE
Reusing payment request is correct?

### ISSUE THREAD

**Issue by JHPSoft** [LN-Zap/zap-desktop#377]
I tried to read articles on y'alls.

When I paid 150 satoshis,
zap showed this error message
> Shoot, we're having some trouble sending your payment.

I thought 'Oh, it failed to pay' and clicked "Pay" button twice more.
(using same payment request address)

30 seconds later,
suddenly zap showed
> Successfully sent payment 

Three lighting transactions has same TXID.
But each transaction withdrew 150 satoshis.
As a result, 450 satoshis was spent.

I know every transactions must have different TXID.
And multiple spending must be impossible.

**Comment by JimmyMow** [comment]
Are you using a Zap release? This should be fixed in the latest master.

Before we would set a 10 second timeout because LND would hang back then. This is fixed now and the user can't submit the form again until the LND request finishes.

**Comment by JHPSoft** [comment]
OK, Now I got '0% download' error.

It looks fixed in latest version, so I close issue
