### ISSUE TITLE
Why download the blockchain?

### ISSUE THREAD

**Issue by mot3** [LN-Zap/zap-desktop#3770]

**Comment by suchdatums** [comment]
It seems like it downloads the block headers -- which took about 5 minutes for me -- not the entire blockchain.

**Comment by EAWF** [comment]
All wallets need to have some link to the blockchain data. Some use a third party server's full blockchain, some pull the block headers and pertinent utxo's for their own use. There is no other way to maintain which utxo's are under control of the wallet private key.

**Comment by mrfelton** [comment]
As others have said, syncing some data form the blockchain is essential to the functioning if the wallet. Zap Desktop runs lnd  as a Neutrino client which downloads minimal blockchain data - only the headers and compact filters. See https://github.com/lightninglabs/neutrino for more information.
