### ISSUE TITLE
ZAP desktop for Windows - not working with the latest lnd v0.14.1-beta

### ISSUE THREAD

**Issue by AgXCz** [LN-Zap/zap-desktop#3774]
I was successfully running ZAP 0.7.4 beta with lnd v0.13.1-beta.
When I updated to latest lnd v0.14.1-beta, ZAP is not working anymore (empty window shown).
When ZAP uninstalled and installed again, I am unable to connect.

ZAP for Android still works.
Joule Chrome extension still works.

**Comment by majikaz** [comment]
Platform : Win10 x64 (Intel) Microsoft Windows [Version 10.0.19043.1348]
Zap Client : Zap Desktop version 0.7.4-Beta

Hi, 
My previously working Zap Desktop fails to open/loadup fully. On execute of the the app shortcut It partially loads the GUI then fades to a Blank screen.. 

It works on my Android device which is connecting to my local own node. I tried to uninstall zap desktop then reinstall latest version from here but there is just a blank screen..  Strange. 
I have tested if its any HIPS from my AV software (I completely disabled it, Tested in safe-mode just to Test Nothing)
Tested Zap-Desktop again Nothing..

Hope this helps.

**Comment by maximusmaximalistus** [comment]
Platform: Linux (Slackware 64 14.2) 
LN Node: lnd 0.14.1 beta and 0.13.3-beta
Bitcoin client: Satoshi Client 22.0
Zap Wallet: Zap Desktop version 0.7.4 Beta

I am also having this problem!
I have two machines with two different lnd nodes and bitcoin nodes. 
One machine is still using lnd 0.13.3-beta.
In that one Zap wallet works with no problems. And even could use lndconnect to create the url to paste on Zap wallet.
But in the one where I run lnd 0.14.1-beta, lndconnect doesn't work. I even tried with tls.cert and admin.macaroon and nothing. Keeps me asking about the password.

**Comment by pcharest** [comment]
Same here too, impossible to start zap with LND 0.14.1

**Comment by mrfelton** [comment]
Please try with latest version of the app which has support for lnd 0.14: https://github.com/LN-Zap/zap-desktop/releases/tag/v0.7.5-beta

**Comment by AgXCz** [comment]
@mrfelton Unfortunately, in my case still the same with 0.7.5-beta, it keep asking about the password and then "Cannot read property 'unlockWallet' of null."
Lnd version 0.14.1-beta is running correctly, ZAP for Android still works.

**Comment by harshil21** [comment]
thank you, the new version is working for me.

**Comment by hazrulnizam** [comment]
New version Zap 0.7.5-beta still doesn't work for me to connect to my lnd node 0.14.1-beta.

**Comment by ArbenKarb** [comment]
Same issue here

**Comment by pcharest** [comment]
I was able to connect it. the wallet must be locked the first time you connect zap to your node.

**Comment by pcharest** [comment]
LND need to be locked to be able to start zap here.

**Comment by kshartman** [comment]
I have the zame issue with lnd 0.14.1-beta and the latest Zap appimage under linux mint (ubuntu fork).  If lnd wallet is locked, zap prompts to unlock and when I provide the password lnd continues and zap wallet opens.  if lnd is locked, zap still prompts for wallet password and fails to unlock because it already is unlocked so zap will not open.

Curiously, the ios app under ios 15.2 on my iphone still works just fine with the new lnd.  I did not have to do anything to make it work after the lnd upgrade.

**Comment by mrfelton** [comment]
Please can you try with the latest release - [v0.7.6-beta](https://github.com/LN-Zap/zap-desktop/releases/tag/v0.7.6-beta)

**Comment by hazrulnizam** [comment]
Latest release works for me now. Thanks! Seems to have fixed excessive RAM usage as well!

**Comment by AgXCz** [comment]
It seems that latest version 0.7.6 fixed this issue.
It is able to link both to locked and unlocked lnd now. 
Thanks

**Comment by kshartman** [comment]
Latest release works.  Thanks!!
