### ISSUE TITLE
Getting = Cannot read property 'unlockWallet' of null when trying to connect to my lnd note

### ISSUE THREAD

**Issue by zenonasz** [LN-Zap/zap-desktop#3775]
## Description

I have setup a btcpay server with lnd and ride the lighting.
i have funded the onchain and without establishing and funding any new channels for outbound, I am trying to connect zap.

## Expected Behavior

Without performing the same workflow before, it was supposed to connect zap wallet to lnd without asking for wallet password as the video below.
https://www.youtube.com/watch?v=yBQX0CFnAh4
## Actual Behavior

Zap asks for wallet password and when assigning a new password, it returns the following error : Cannot read property 'unlockWallet' of null 
I see nothing related on my lnd logs
## Possible Fix
No idea, just reporting

## Steps to Reproduce

1. fresh lnd node
2. try to connect zap

## Your Environment

- Zap version: can't find the version, it has been updated with auto-update right after I install it.

- Device: mac os x
- LND Version: Version: 0.13.3-beta commit=basedon-v0.13.3-beta-fresh-btcpay

**Comment by finned-palmer** [comment]
I'm seeing the same issue on Linux (via the AppImage binary).

**Comment by joshuanapoli** [comment]
I see the error when trying to connect to a lnd server which is already unlocked. When the server is not yet unlocked, then the zap desktop connects after correctly unlocking it. I think that there is a related problem, where the app just shows a blank screen if it is restarted while lnd is unlocked.

**Comment by mrfelton** [comment]
Hi, please try with the latest version of the app - 0.7.5 https://github.com/LN-Zap/zap-desktop/releases/tag/v0.7.5-beta

**Comment by finned-palmer** [comment]
The issue remains for me.

**Comment by hirishh** [comment]
as @joshuanapoli, this happens when the lnd node is already unlocked. Indeed if you restart it and it's in lock state (waiting fon lncli unlock) zap will ask for the password and successfully unlock it, then it allows you to open the wallet.

Please fix it :)

**Comment by kshartman** [comment]
This is probably the same as issue #3774. Zap for Linux/Windows cannot connect to LND v0.14.1-beta unless the wallet is locked in LND (which will not be true if the server is running).  Starting LND, leaving it locked, starting Zap and unlocking the wallet is a cumbersome workaround.  This is true when using Zap v0.7.5-beta for Linux.  The iphone app, which was previously connected still works however.

**Comment by majikaz** [comment]
I concur with @kshartman and arrived at same conclusion.. I am having the same issue as the OP of this bug and also have the same LND server version and have tested this across multiple versions upto latest zap desktop client of v0.7.5-beta.exe (windows)
The strange thing is that Zap wallet is still working fine on my Android handset. Even after update to latest UmbrelOS my Android Zap Wallet works fine. Its The desktop version which throws the error "Cannot real property 'unlockWallet' of null" 

This "error/Bug" has changed from the original issue that Zap Desktop had which just left the GUI in a "blank" state partially loaded GUI. 

-- The suggested workaround is not really feasible when running a 24/7/365 BTC node. 
Good Luck.

**Comment by VajraOfIndra** [comment]
I have the same issue as described by other users above. I get the `Cannot read property 'unlockWallet' of null` after inputting my wallet password.

Environment: Ubuntu 20.04
Version: Zap 0.7.5 Beta (Zap-linux-x86_64-v0.7.5-beta.AppImage)

**Comment by hirishh** [comment]
@mrfelton could you please advice about this issue? Currently zap-desktop on linux is not usable with the last version of lnd.

**Comment by hirishh** [comment]
I did some digging and the error comes from here: https://github.com/LN-Zap/node-lnd-grpc/blob/master/src/services/walletUnlocker.js#L24

**Comment by hirishh** [comment]
Ok, it's 5 AM but this job had to be done.
I've found the issue and submitted the PR. Once @mrfelton merge and integrate this new version of node-lnd-grpc it will fix this issue.

It's time to sleep now :P

**Comment by Javihache** [comment]
Was this solved? I have 0.7.6 installed on my mac and still see this problem.

**Comment by hirishh** [comment]
@Javihache I've 0.7.6 installed on my Linux and I have no issues connecting to my lnd node anymore. I will try with my old mac

**Comment by iacou** [comment]
@Javihache @hirishh I'm running 0.7.6-beta on Mac OS and getting the same issue

**Comment by iacou** [comment]
Seems the error was a red herring, I switched from 'server.local' to '192.168.x.x' in the connection settings and it unlocks fine with lnd unlocked

**Comment by Uter1007** [comment]
Still get the error on linux with btcpay
