### ISSUE TITLE
Restore Zap Off Chain Channels Easily for noob (I have seed phrase and channels.backup file)

### ISSUE THREAD

**Issue by btxyz62** [LN-Zap/zap-desktop#3779]
Hi,

After a stuck 100% open bug on my zap wallet, i recover my wallet with the seed phrase.

Unfortunately, all my off-chain channels disappear....

I am a windows 10 user .... 

I'd like to see them again but it seems to be difficult for a none Linux user to do (I've read that it's necessary to connect manually to LND mode to use the channels.backup file....)

Thanks for your understandable explanations,

BTX

**Comment by onefedora** [comment]
I have the same question.  I recovered my wallet but all of my lightning channels are gone.

**Comment by mrfelton** [comment]
Hi, Zap Desktop doesn't currently support recovery on funds in channels when importing from a seed backup. You can recover using lncli directly if you have a backup of the Static Channel Backup file. See https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md
