### ISSUE TITLE
Changing to testnet via confgi directory on macOS ?

### ISSUE THREAD

**Issue by iangregsondev** [LN-Zap/zap-desktop#3781]
Hi,

I checked the docs and it appears you can change to testnet by adding a config file.

I installed zap but I don't know where the config directory is 

I found this (i am on a mac)

~/Library/Application Support/Zap

but although it exists, doesn't seem to be any config directory.

Can anyone help ?

Thanks in advance

**Comment by mrfelton** [comment]
You need to run a development build of zap in order to leverage testnet.
