### ISSUE TITLE
Zap starts with blank window, is there a log file somewhere?

### ISSUE THREAD

**Issue by fabianfabian** [LN-Zap/zap-desktop#3785]
Zap starts with empty screen, probably the issue is on my end as I mess around a lot with different lnd versions / ssh tunnels / certs and what not. 

Before I bother you too much I'd like to troubleshoot myself but I don't know where to start. **Is there a log file, console or error output somewhere** so I can find out what is happening in the background?

## Expected Behavior

Zap should show my wallet balance and channels

## Actual Behavior

Zap starts with blank window. I can open and close Preferences but nothing more. No error, just blank window:

![Screen recording of the problem](https://media.giphy.com/media/7b6BHfiIKU760im1yW/giphy.gif)

## Context

I occasionally use Zap desktop as a "view" to my LND node on a different device through a SSH tunnel.
After a few months I started Zap again, it auto updated and showed me a blank screen.

## Your Environment

- Zap version: 0.7.5-beta
- Operating System and version: macOS 12.1 / M1 air

**Comment by NateNate60** [comment]
This appears to be the same bug as #3774

**Comment by mrfelton** [comment]
What version of lnd are you connecting to?

**Comment by fabianfabian** [comment]
lnd version 0.14.1-beta commit=v0.14.1-beta

**Comment by mrfelton** [comment]
Could you try with a build from `master` branch where I think this issue is fixed (assuming it's the same as https://github.com/LN-Zap/zap-desktop/issues/3774)?

Checkout the code, run `yarn && yarn package` and then try starting the resulting package. See https://github.com/LN-Zap/zap-desktop/blob/master/docs/ADVANCED.md#packaging

**Comment by fabianfabian** [comment]
> #3774

I haven't tried `master` yet but locking LND (by restarting it) and then starting Zap works, I can unlock with Zap and then continue.

Restarting Zap after LND is already unlocked gives the problem again.

**Comment by mrfelton** [comment]
Yeah, then it's the same issue as #3774. Closing as a duplicate.
