### ISSUE TITLE
Recover Lighting Channels after backup recovery

### ISSUE THREAD

**Issue by onefedora** [LN-Zap/zap-desktop#3786]
I noticed that the Zap desktop was not showing my wallet including the actual balance and lightning channels I had open.  Therefore, I deleted the wallet and recovered the wallet again in Zap with my seed phrase.  Now, I can only see my on chain balance in my wallet and the bitcoin that I had locked in lightning channels is no longer viewable.

I saw somewhere that I should have downloaded a backup file for each LN node that was opened.  However, I was never prompted by Zap to download any backup.  In fact, I also used the 'auto-pilot' mode and didn't even know what nodes were being opened.

How do I recover my LN channels or get the counterparties to close the channels so that the bitcoin comes back to my on-chain wallet?

**Comment by mrfelton** [comment]
Hi, Zap Desktop doesn't currently support recovery on funds in channels when importing from a seed backup. You can recover using lnd directly. See https://github.com/lightningnetwork/lnd/blob/master/docs/recovery.md if you have a backup of the Static Channel Backup file.
