### ISSUE TITLE
Connect to another node when needed

### ISSUE THREAD

**Issue by basharov** [LN-Zap/zap-desktop#3794]
I use Zap in MacOS to build and but my local lnd-based project. So, when I start Zap for the first time, I have an option to connect to my own lnd node. I use Polar to orchestrate lnd nodes so I can remove or add new ones to which I'd like to connect. As I switch between nodes all the time, it would be great to somehow be able to connect to another node in Zap.

However now the only solution I see and use is to remove Zap app completely and then copy it again from the downloaded version then start.

Is there a simpler way to switch to another node?

**Comment by mrfelton** [comment]
Zap does support multiple wallet connections. You can set up as many wallets as you like and switch between them. You just need to click the `X` button in the top corner to close out of the current wallet which will take you to the wallet selector screen from where you can set up a new wallet connection or reconnect to an already established one.
