### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by paboum** [LN-Zap/zap-desktop#3799]
I filed two bug reports weeks ago, both of which were completely ignored by the dev team.

**Comment by roger-eosuk** [comment]
Also wondering the same, I only just downloaded for the first time today and have a couple of issues I could report by way of contribution but this repo looks like it ha snot been updated since 2019?

**Comment by paboum** [comment]
No commits since January, no response to the question above since June, so I guess we can pronounce.

**Comment by mrfelton** [comment]
The project is very minimally maintained and has not been updated in a while. I will update the README to make more clear the current maintenance status of the project.
