### ISSUE TITLE
Websocket handling for transactions and sendpayment

### ISSUE THREAD

**Issue by fresheneesz** [LN-Zap/zap-desktop#38]
I wrote a websocket-friendly RPC/event protocol called RPEP, based on a module I implemented for a project based on websocket server-client communication. If you're interested in using the protocol, I could open source a javascript implementation that you could use in this project. Here's the spec: https://github.com/Tixit/RPEP .

**Comment by jackmallers** [comment]
Sorry, I need to update the README badly, I'll do that right now. Zap moved away from relying on a Node.js server w/ Websockets and now uses ipcRenderer instead

https://electron.atom.io/docs/api/ipc-renderer/
