### ISSUE TITLE
BTC(On-Chain) wallet address changed

### ISSUE THREAD

**Issue by MocroNL** [LN-Zap/zap-desktop#3803]
Hi admins,

Ive have just tested zap desktop by sending some btc to my wallet. Ive also tested sending the funds back. Both worked.

Now I want to send some funds again but my btc address on zap wallet changed. Is this normal?

Thank you in advance.

**Comment by MocroNL** [comment]
If I open the same 24 seed wallet on 2 different desktops. Both have a different BTC address(QR Code). But the node pubkey is the same. Why are is the btc address not similar and when/why do they change?

**Comment by rahulbile** [comment]
Hi @MocroNL,  a new wallet address is generated  when the last address generated has been used. (i.e funds transferred to that address)

Please reopen issue if you still have any qeestion.
