### ISSUE TITLE
No effect evern when the blockchain downloading has been 100% for 2 hours

### ISSUE THREAD

**Issue by taurenshaman** [LN-Zap/zap-desktop#3809]
## Description

The blockchain downloading has been 100% for 2 hours, but no more response.
![image](https://user-images.githubusercontent.com/1308706/218041356-c9a8d272-2f4d-4c73-8511-58a81df1668b.png)

## Expected Behavior

Enter the wallet.

## Actual Behavior

Still show the loading page.

## Your Environment

- Zap version: 0.7.6-Beta
- Operating System and version: Windows 11

**Comment by oddaran** [comment]
I've got the same issue (50% vs 100%) after I sent my funds out to an on-chain wallet address. Help!

**Comment by matthewcieplak** [comment]
Same behavior here. Made one transaction and the entire wallet became unusable.

**Comment by mrfelton** [comment]
Please can you try with the latest release, https://github.com/LN-Zap/zap-desktop/releases/tag/v0.7.7-beta. Thanks.

**Comment by taurenshaman** [comment]
v0.7.7 worked... ♥♥♥
![image](https://user-images.githubusercontent.com/1308706/229386951-b3e13429-05a5-40d8-ad7a-e7f7611b23ff.png)
