### ISSUE TITLE
No effect of fetching latest data from blockchain 100%

### ISSUE THREAD

**Issue by dacukel** [LN-Zap/zap-desktop#3811]
## Description
![image](https://user-images.githubusercontent.com/111083058/218535223-353c8e57-11ca-41c3-a096-df694e3d1230.png)

## Steps to Reproduce

- 1.
- 2.
- 3.
- 4.

## Your Environment

- Zap version:
- Operating System and version:

**Comment by oddaran** [comment]
I've got the same issue (50% vs 100%) after I sent my funds out to an on-chain wallet address. Help!

**Comment by AAlex1980** [comment]
The fetching latest data from the Blockchain screen is not chainging. According to the "Commitment Filter", Zap should be insync but no shreen change happens. Also tried shutting down and restarting Zap several times. Does someone can help? Thx.

**Comment by mrfelton** [comment]
Please can you try with the latest release, https://github.com/LN-Zap/zap-desktop/releases/tag/v0.7.7-beta. Thanks.

**Comment by AAlex1980** [comment]
Hallo mrfelton, thanks, Zap v0.7.7-beta fixes the issue. Zap Wallet opens up without any issues after the synch with the Chain is done.
