### ISSUE TITLE
REJECT_MALFORMED cmd when trying to sync wallet

### ISSUE THREAD

**Issue by evertvr** [LN-Zap/zap-desktop#391]
Hi all,

I've been getting strange error message when trying to sync my zap desktop wallet.

Attached is my lnd.log, it looks like peer 188.166.148.62 is sending a header which exceeds the max header length.

Anyone knows what could be wrong here?

[lnd.log](https://github.com/LN-Zap/zap-desktop/files/1995025/lnd.log)

**Comment by mrfelton** [comment]
The issue here seems to be that the zap wallet currently uses `188.166.148.62` as the backend btc node for the neutrino light-client, and this node appears to be having some issues. @JimmyMow can you check your bitcoin node please?

**Comment by JimmyMow** [comment]
@mrfelton the BTCD node hosted at `188.166.148.62` is fine

@evertvr what version of Zap are you running?

**Comment by evertvr** [comment]
Version 0.1.0

-------- Original Message --------

**Comment by mrfelton** [comment]
Lastest code in master @JimmyMow 

I have also tried adding `faucet.lightning.community:18333` as an additional neutrino node and it's unable to sync from that one too.

I'm using the latest lnd v0.4.1-beta release.

You can test by wiping out your LND data dir snd try setting up a new wallet from scratch

**Comment by REGOJO** [comment]
same problem, is it solved?

**Comment by fiddybux** [comment]
Same problem. Stuck at 75% on 0.1.1 beta for Windows 10 and Linux versions.

**Comment by mrfelton** [comment]
@fiddybux I would suggest that you try using the latest code from the master branch, along with the most recent build of lnd.

**Comment by crashtest7** [comment]
Hi, 

I am currently stuck at 0% can anyone help? here is the log https://pastebin.com/m8F3ZJWz

Thanks:

**Comment by fiddybux** [comment]
I plonked the latest lnd into /opt/zap et al, and it seems to be syncing
properly now. Up to 35% of gradual increase rather than stuck at 0% or
instantly up to 75%. I'm getting Java errors on executing zap-desktop, but
it doesn't seem to be hindering the sync progress.

**Comment by mrfelton** [comment]
I'm closing this issue as it relates to an older version of Zap. The sync process has had an overhaul in v0.2.0.
