### ISSUE TITLE
Zap should handle failures to load the suggested nodes list gracefully

### ISSUE THREAD

**Issue by mrfelton** [LN-Zap/zap-desktop#392]
When the app starts up, it tries to connect to http://zap.jackmallers.com/suggested-peers. Currently, this URL is returning a 404. This is causing errors in the console:

```
GET http://zap.jackmallers.com/suggested-peers 404 (Not Found)

warning.js:33 Warning: Failed prop type: The prop `suggestedNodes` is marked as required in `SuggestedNodes`, but its value is `undefined`.
```

This seems to prevent the app from getting past the onboarding phase on startup with the user being stuck on the final 'loading' screen.

What is http://zap.jackmallers.com/suggested-peers supposed to provide?

Is it necessary?

**Comment by JimmyMow** [comment]
It provides an array of nodes but the app shouldn't break if the API call fails. I'll work on a fix
