### ISSUE TITLE
Syncing your lightning network node to the blockchain stuck at 76%

### ISSUE THREAD

**Issue by BTCDCA** [LN-Zap/zap-desktop#399]
Why is this stuck at 76%?   How long does it take to sync?

**Comment by mrfelton** [comment]
This this is the same issue as https://github.com/LN-Zap/zap-desktop/issues/391

**Comment by dmp1ce** [comment]
I think I'm experiencing the same thing. I am using the linux_unpacked build.

**Comment by mrfelton** [comment]
@BTCDCA please can you confirm which version of Zap you are using? Can you reproduce the issue with the latest code in the master branch? Thanks.

**Comment by dmp1ce** [comment]
I experienced this with v0.1.1-beta. I downloaded from the releases. I haven't gotten master running on my machine yet.

**Comment by mrfelton** [comment]
I'm closing this issue as it relates to an older version of Zap. The sync process has had an overhaul in v0.2.0.
