### ISSUE TITLE
Missing password validation during onboarding

### ISSUE THREAD

**Issue by odb366** [LN-Zap/zap-desktop#415]
During onboarding process users are asked to create a pass for unlocking ZAP. The pass should be 8 or more characters, but users are able to create one with less than 8 characters and proceed. Inline validation is missing. Consequently, on the last step of the onboarding they cannot proceed, and are unable to start ZAP.

Update: the user can even proceed without entering the confirmation password on this screen.

![screenshot 32](https://user-images.githubusercontent.com/14116101/41280696-41780ca4-6e38-11e8-919f-7719e00b024e.png)

**Comment by odb366** [comment]
Wow, how did I missed that. Thanks @mrfelton. Fix incoming.

**Comment by odb366** [comment]
Another usability issue is that we don't have a back button on this screen. Should I add back functionality to the autopilot step?

**Comment by JimmyMow** [comment]
No. That's more complex than you think. We'd have to shut down our LND process we just started. No back button there

**Comment by odb366** [comment]
@JimmyMow Ok

**Comment by odb366** [comment]
Issue fixed, closing

**Comment by odb366** [comment]
The issue is reopened because it is possible to proceed with 2 different passwords ..
