### ISSUE TITLE
Error handling when creating a channel

### ISSUE THREAD

**Issue by jackmallers** [LN-Zap/zap-desktop#43]
Right now all errors are simple logged to the console. We need to display errors that happen when trying to create a channel.

Work with @JimmyMow and @brandnanthny on the design

**Comment by mecampbellsoup** [comment]
@jackmallers so the error you want to display in the app is "failure to create channel" or something like that, and right now it's *only* being logged to the console?

**Comment by joaodealmeida** [comment]
This has been achieved with PR #64 .
