### ISSUE TITLE
Stuck at 0%

### ISSUE THREAD

**Issue by crashtest7** [LN-Zap/zap-desktop#430]
Hi,

I am currently stuck at 0% can anyone help? here is the log https://pastebin.com/m8F3ZJWz

Thanks!

**Comment by fiddybux** [comment]
Try downloading the latest lnd (google it), and putting in application folder. On win this will be something like:

C:\Users\YOU\AppData\Local\Programs\zap-desktop\resources\bin

**Comment by crashtest7** [comment]
I put lnd.exe in the app folder as you mentionned but it still keeps on trying to connect...
from what I gathered could that be because of an issue with the win firewall? anyway thanks for the reply.

**Comment by mrfelton** [comment]
@crashtest7 it could well be port related. You need to ensure that you accept incoming connections on port 9735. You may need to setup port forwarding on your router.

See https://medium.com/@jadmubaslat/bitcoin-lightning-network-node-easy-setup-tutorial-for-windows-desktop-users-a-how-to-guide-9937b5a8a669

**Comment by fiddybux** [comment]
Inside /resources, then inside /bin

**Comment by michaelWuensch** [comment]
Same for me, stuck at 0%
I forwarded Port 9735, didn't help.
I then downloaded newest lnd and put it in the "C:\Users\YOU\AppData\Local\Programs\zap-desktop\resources\bin" folder.
Well, it started to sync, but I got some error every time I started it. 
I'll try building from source next...

**Comment by crashtest7** [comment]
It's been a week and I still did not get it to sync despite forwarding port 9735... Installing bitcoin core for now, I'll try it again when the next version rolls out.

**Comment by fiddybux** [comment]
I have to admit, my success is limited. I can sync to 100% but then I get a
JavaScript error and the UI shows, but I have a loading animation that
never ends. This behaviour is the same on Win10 and Linux.

**Comment by JohnnyBackflip** [comment]
Same here, just installed it on Ubuntu 18.04. Stuck at 0%.

**Comment by fiddybux** [comment]
Hoping for a new release soon. Seems mostly broken.

Do you get Java errors?

**Comment by bradyswenson** [comment]
Also stuck at 0% attempting to install on Mac OSX.

**Comment by damianobonazzi** [comment]
I was stuck at 74% after first launch, then I came here, read this post about forwarding port 9735, did it, but still stuck.
I restarted the program, and now I'm stuck at 0%.

**Comment by michaelWuensch** [comment]
Just for the record, I pulled from source and it worked. Latest release seems broken. So you either have to wait for the next release or get the latest version by pulling from source.

**Comment by fiddybux** [comment]
Good to know. I'm reluctant and lazy though on my Windows machine, as I use
it for important work, so'll wait for the binary. I might dig my Linux
machine out and make a mess of it compiling stuff.

On 3 Jul 2018 3:32 pm, "Michael Wünsch" <notifications@github.com> wrote:

Just for the record, I pulled from source and it worked. Latest release
seems broken. So you either have to wait for the next release or get the
latest version by pulling from source.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/LN-Zap/zap-desktop/issues/430#issuecomment-402178683>,
or mute the thread

**Comment by dolebas** [comment]
+1 with this release https://github.com/LN-Zap/zap-desktop/releases/download/v0.1.1-beta/zap-mac-release-v0.1.1-beta.zip

Seems to be related to https://github.com/LN-Zap/zap-desktop/issues/468 and https://github.com/LN-Zap/zap-desktop/issues/455

**Comment by mrfelton** [comment]
Closing this issue as there are known issues with lnd synchronisation in the v0.1.1-beta release. You must pull and build from source or wait for a new release.
