### ISSUE TITLE
Cannot toggling channel details when you package master

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#453]
For some reason when I run `npm run package` and run the build on Mac I cannot open the channel details when I click a channel. It works when running `npm run dev`. Bizarre.

Any ideas @Empact @mrfelton?

**Comment by mrfelton** [comment]
Just to confirm I can reproduce the issue. Not sure why that would be though.

**Comment by JimmyMow** [comment]
I know so weird. No errors or warnings in `dev` either. I'll have some time in a sec to do some more serious debugging and will report back
