### ISSUE TITLE
Sass-loader cannot resolve non-relative imports

### ISSUE THREAD

**Issue by VonIobro** [LN-Zap/zap-desktop#46]
For Sass files, when replacing `@import '../../../../../../variables.scss'` with `@import 'variables.scss'`, the sass-loader cannot resolve the path when `npm run build-renderer`. However the resolved-paths are fine in the development environment.

There seems to be a problem with webpack/css-loader/sass-loader not recognizing the resolved paths. While preparing to `npm run test`, `npm run build-renderer` fails when resolved-paths for scss imports: 
```
 ERROR in ./node_modules/css-loader?{"modules":true,"importLoaders":1,"localIdentName":"[name]__[local]__[hash:base64:5]"}!./node_modules/sass-loader/lib/loader.js!./app/routes/wallet/components/Wallet.scss
    Module build failed: 
    @import 'variables.scss';
    ^
          File to import not found or unreadable: variables.scss.
```

This problem was found in PR https://github.com/LN-Zap/zap-desktop/pull/40

(I vote for styled-components^^)

**Comment by joaodealmeida** [comment]
This has been achieved with PR #40 .
