### ISSUE TITLE
Javascript error in main process (Production)

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#470]
With a production build: if you close and open the app too soon or sometimes at all we get weird `error in main process`. The error isn't always consistent but always has something to do with LND or gRPC. Seems as if we aren't properly shutting down the application and our LND process.

cc @Empact @mrfelton 
<img width="421" alt="screen shot 2018-06-21 at 10 40 20 pm" src="https://user-images.githubusercontent.com/4040039/41777328-83ef5550-75f0-11e8-8a2c-d96c27eb99ea.png">

**Comment by mrfelton** [comment]
I have noticed this too. Sometimes I have to do `killall lnd` to fix it.
