### ISSUE TITLE
Conflicting max-length lint rule causing issues on commit

### ISSUE THREAD

**Issue by mrfelton** [LN-Zap/zap-desktop#472]
@Empact I think the change introduced in https://github.com/LN-Zap/zap-desktop/pull/459 may be causing some issues.

I am finding that prettier formats things one way when you save the document, only for those things to be considered invalid by eslint after (due to difference in expected whitespace between what prettier created, and what eslint things it should be).

It is mentioned in the notes on https://github.com/prettier/eslint-config-prettier#max-len that this setting can cause you to have to reformat things. The problem is that the only way to reformat them it to open up the files in an editor that doesn't have prettier enabled otherwise when you try to fix the lint issues, prettier breaks them as soon as you save the file.

This can make it impossible to commit things given that we auto lint on commit.

I think we need to have these values set the same, or not set at all in eslint.

**Comment by Empact** [comment]
Can you post an example code segment? As it is max-len is set higher than the prettier length, so if the line is invalid under eslint it should be because of content that is not specifically sized by prettier, eg a long string or a comment.

**Comment by mrfelton** [comment]
I can't reproduce this anymore so I'm going to close this. Possibly my eslint cache was stale at the time as I was switching between various branches with differing eslint configurations.
