### ISSUE TITLE
Fetch balance when there's new on-chain/ln transaction and channel updates

### ISSUE THREAD

**Issue by jackmallers** [LN-Zap/zap-desktop#49]
Now that we subscribe to new transactions for both on-chain/LN and channel updates we should be updating the wallet/channel balance accordingly. 

There is a `fetchBalance` function in the `balance` reducer already, it just needs to be called in the right places for async updates

**Comment by joaodealmeida** [comment]
This has been achieved on commit bbb20214d1f9a9a3752db75313a0ecaa125a4c3f .
