### ISSUE TITLE
Repeated error messages shown in devtools console

### ISSUE THREAD

**Issue by mrfelton** [LN-Zap/zap-desktop#490]
If you start up the app in dev mode, open up devtools, and navigate to the devtools network tab and then scroll the list of network requests messages like this one show repeatedly in the devtools console.

> [41299:0626/125127.138907:ERROR:CONSOLE(105)] "Uncaught (in promise) Error: Could not instantiate: ProductRegistryImpl.Registry", source: chrome-devtools://devtools/bundled/inspector.js (105)

This is an incompatibility between devtools and electron 2.x.

See https://github.com/electron/electron/issues/13008#issuecomment-400261941

A possible workaround for this has been provided in https://github.com/electron/electron/issues/13008#issuecomment-400261941

**Comment by JimmyMow** [comment]
Tested ACK d4cb99f
