### ISSUE TITLE
Unable to use app after entering invalid connection details for custom lnd instance

### ISSUE THREAD

**Issue by mrfelton** [LN-Zap/zap-desktop#493]
## Current behaviour

After selecting to use a custom connection during the onboarding process and then submitting the form with some invalid connection details:

Error message in the terminal:
`Error: 14 UNAVAILABLE: Name resolution failure`

Error in the app:
`A JavaScript error occurred in the main process`

Clicking OK after the error message takes you to a broken application window.

## Desired Behaviour

User should see a user friendly error message and then be taken back to connection setup page so that they can try again

**Comment by JimmyMow** [comment]
@mrfelton related thought. Should we allow users the ability to paste in their macaroon and cert directly so they don't have to copy it over to their local machine?

**Comment by mrfelton** [comment]
@JimmyMow the cert could be easily copy/pasted by the user and stored and secured by us via the app. Hover I think the macaroon is more tricky since it is stored as binary data in the `admin.macaroon` file which can't easily be copy/pasted by the user without first converting it to hex format. This may require some enhancements in lnd to provide other ways of exporting/accessibng the macaroon.
