### ISSUE TITLE
Feature: Implement SubscribeChannelGraph

### ISSUE THREAD

**Issue by jackmallers** [LN-Zap/zap-desktop#50]
Subscribe to ChannelGraph graph topology updates on the backend (inside the `app/lnd/subscribe` folder: https://github.com/LN-Zap/zap-desktop/tree/master/app/lnd/subscribe)

**Comment by JimmyMow** [comment]
@joaodealmeida this is just a simple ticket to create the subscribe functionality in the backend. I will tie it to front end notifications when this is done

**Comment by joaodealmeida** [comment]
ok, i'll work on this.

**Comment by JimmyMow** [comment]
nice

**Comment by JimmyMow** [comment]
this is now in master. closing
