### ISSUE TITLE
"UNAVAILABLE: TCP Read failed" error while syncing

### ISSUE THREAD

**Issue by mntetai** [LN-Zap/zap-desktop#504]
Got an error while syncing bitcoin network.

log as follows : 
`Thu, 28 Jun 2018 11:59:34 GMT zap:lnd  [ERR]  2018-06-28 14:59:34.771 [ERR] SRVR: unable to start server: Couldn't get basic filter for block 1342004 (000000000001d04d2ef6c3f6cf909650507c1a7fc66bbdda86de70712b50113b)
Thu, 28 Jun 2018 11:59:34 GMT zap:lnd  [ERR]
Thu, 28 Jun 2018 11:59:34 GMT zap:lnd  [DBG]  2018-06-28 14:59:34.771 [DBG] BTCN: Sending getcfheaders to 188.166.148.62:18333 (outbound)
Thu, 28 Jun 2018 11:59:34 GMT zap:lnd  [INF]  2018-06-28 14:59:34.771 [INF] BTCN: Block manager shutting down
Thu, 28 Jun 2018 11:59:34 GMT zap:lnd  [INF]  2018-06-28 14:59:34.771 [INF] BTCN: Address manager shutting down
Thu, 28 Jun 2018 11:59:34 GMT zap:lnd  [INF]  2018-06-28 14:59:34.830 [INF] UTXN: Attempting to graduate height=1341991: num_kids=0, num_babies=0
Thu, 28 Jun 2018 11:59:34 GMT zap:lnd  [INF]  Couldn't get basic filter for block 1342004 (000000000001d04d2ef6c3f6cf909650507c1a7fc66bbdda86de70712b50113b)`

error in zap :
![zap_error_screen2](https://user-images.githubusercontent.com/1884392/42033193-b81af2b4-7ae4-11e8-92d2-9116fa7520ec.png)

OS : win 10 pro
zap version : commit 00fa22b253fdfaf78a14dcae221839b466d3fb53 [00fa22b] on master branch ( 22 june )

**Comment by mrfelton** [comment]
@mntetai can you update your master branch and try again and let me know if this is still an issue. Thanks.

**Comment by mntetai** [comment]
fixed ! Good Job !
