### ISSUE TITLE
GUI: when an empty channel list is selected the channel menu disappears.

### ISSUE THREAD

**Issue by emanuelelaface** [LN-Zap/zap-desktop#507]
Under My Network column there is the possibility to filter out the channels to show. By default the option is All but it is possible to select also Online, Offline, Pending and Closing.
If I select one option that has no entries, for example Pending while I do not have any pending channel, the result is "Hmmm, looks like you don't have any channels yet. Here are some suggested nodes to open a channel with to get started"
This looks fine but it disappear the drop down menu, so I cannot return to the All or any other channel selection. The only option to see the full list of channels is to shutdown and restart the application.

**Comment by mrfelton** [comment]
Tested this and can confirm the issue
