### ISSUE TITLE
The funding address displayed during syncing changes every time I restart zap, although I never funded it

### ISSUE THREAD

**Issue by mrfelton** [LN-Zap/zap-desktop#519]
> Shouldn't the address stay the same until it is actually used?
 -- @michaelWuensch

**Comment by mrfelton** [comment]
@michaelWuensch could you give the PR at https://github.com/LN-Zap/zap-desktop/pull/527 a test please, which address this issue

**Comment by michaelWuensch** [comment]
@mrfelton Yes, I can test it. I am quite new to the whole github workflow though. Is there an easy way to merge your changes into my local master branch, or do I have to clone your whole Zap repository as a new project and test it there?

**Comment by michaelWuensch** [comment]
@mrfelton never mind, I think I found out how to do this. I'll try it in a few hours when I am back home.

**Comment by michaelWuensch** [comment]
@mrfelton I tested your PR. Unfortunatelly the address still changes on my system every time I restart Zap.
Furthermore I noticed that your PR changes the displayed address to bech32 while before it was Base58Check. I welcome that, but I think you should at least mention it somewhere in the PR.
I could not test if sending funds to the address works, as I am again stuck at 100% syncing...

**Comment by mrfelton** [comment]
@michaelWuensch you may need to look at https://github.com/LN-Zap/zap-desktop/pull/526 to get past the syncing issue

**Comment by mrfelton** [comment]
The address type shouldn't have been changed in that PR. I know that the address type that we use was recently changed however as part of https://github.com/LN-Zap/zap-desktop/pull/477

**Comment by michaelWuensch** [comment]
@mrfelton Yes it should not change, but at least on my system it does. I switched between master branch and your PR and it definetly changed. Checking out master reversed it again. I also thought it is strange as I couldent find that change in your code...

**Comment by mrfelton** [comment]
My bad - there was a bug in my PR. I have pushed an updated version. You'll probably want to run with the the changes from #477  in addition to #526 and so that you don't get stuck syncing

**Comment by michaelWuensch** [comment]
@mrfelton Tested it again. This time it worked. Address stayed the same for each restart. Address fromat is back to Base58 and address changed after funding.
Furthermore I can confirm that #526 fixed the syncing problem.
I did nothing in regards to #477 though as this was merged into master 8 days ago.
