### ISSUE TITLE
Users should be advised of the importance of keeping their seed safe and secure during the onboarding process

### ISSUE THREAD

**Issue by mrfelton** [LN-Zap/zap-desktop#522]
Some feedback from Slack:

> When creating the seed it is explained that it is used for recovery. I think for the next five years or so we have to also show a big warning, that anyone who gets the seed will be able to steal your money. New users might not know this.
 -- @michaelWuensch

**Comment by seanyesmunt** [comment]
Working on this

**Comment by mrfelton** [comment]
Fixed via #1029
