### ISSUE TITLE
Received on-chain transaction shows as a sent transaction in the transaction detail modal

### ISSUE THREAD

**Issue by mrfelton** [LN-Zap/zap-desktop#539]
Click on a received on-chain transaction from the transaction list and you see something like this:

<img width="880" alt="screenshot 2018-07-06 18 12 49" src="https://user-images.githubusercontent.com/200251/42389196-351bdf62-8148-11e8-9be9-b451d789d51b.png">

In the top left is shows 'Sent', yet tis was an incoming transaction.

**Comment by SteliosRammos** [comment]
The Zap notification on Mac also mentions a send transaction instead of receiving funds.

**Comment by bolatovumar** [comment]
Thanks for the catch @SteliosRammos.
