### ISSUE TITLE
build fails on master

### ISSUE THREAD

**Issue by mntetai** [LN-Zap/zap-desktop#561]
Os : win 10 pro
Commit : 37b9f896e756411698f4a56bb3877057e77c9b61 on master branch
steps to reproduce :
yarn
npm run build
npm  run test

App fails .

log is attached 
[npm_log_16_07_2018.txt](https://github.com/LN-Zap/zap-desktop/files/2198837/npm_log_16_07_2018.txt)

**Comment by mntetai** [comment]
I am seeing this on the yarn log 

`
./node_modules/electron-debug/index.js 101:45-58
  0:0  warning  Critical dependency: the request of a dependency is an expression

./node_modules/electron-debug/index.js 102:61-74
  0:0  warning  Critical dependency: the request of a dependency is an expression`

**Comment by nettijoe96** [comment]
I also have this same error. Although the install does not halt. npm run dev can still be run and npm run test passes all tests. However, after I run npm run dev, I am getting a "unknown service lnrpc.Lightning" error, even though I have the custom lnd executable in resources/bin/linux

**Comment by Empact** [comment]
Closed with #564
