### ISSUE TITLE
Feature Request: Display of [Sum of all Local_balances]  And [Sum of all Remote_balances]

### ISSUE THREAD

**Issue by ZapUser77** [LN-Zap/zap-desktop#582]
I would love to have a display of [Sum of all Local_balances]  And [Sum of all Remote_balances].

As a hub, this is extremely useful information.  If [Sum of all Local_balances] is Greater than [Sum of all Remote_balances] then adding more funds to channels doesn't increase liquidity.
Whereas, if [Sum of all Remote_balances] is greater than [Sum of all Local_balances] then creating new channels can potentially increase liquidity.

Even putting it on an "Advanced Features" tab would be cool.

**Comment by mrfelton** [comment]
@ZapUser77 can you clarify what you mean by "remote balances" please? Are you referring to money that is on the other end of your direct channels?

**Comment by ZapUser77** [comment]
LNCLI Listchannels
Add up "Remote_balance" and "Local_balance" of all channels, and display.

**Comment by mrfelton** [comment]
I'm going to close this issue since recent versions of zap have a more complete channel management page where you can easily see your local channel balances vs remote channel balances.

![image](https://user-images.githubusercontent.com/200251/82788504-e096fb80-9e68-11ea-8ce6-1a1efbb6a329.png)
