### ISSUE TITLE
Incorrect password when I haven't created one..

### ISSUE THREAD

**Issue by BitSenseApp** [LN-Zap/zap-desktop#591]
Just downloaded the mac version. It is behaving as if I have already set up a node and telling me my password is incorrect. Also tells me I can just create a new wallet without actually giving me the option to create a new wallet. Please advise..

I have never used the software before so I have no idea why it thinks I am a returning user.

Cheers

**Comment by JimmyMow** [comment]
@BitSenseApp you must have LND data on your machine already.

If you want to remove old LND data and start over make sure you close all channels and send all funds from the wallet. Then you can remove the LND data located at:

MacOS: `$HOME/Library/Application Support/Lnd`
Windows: `%LOCALAPPDATA%\Lnd`
Linux: `~/.lnd`

**Comment by BitSenseApp** [comment]
I had it downloaded LND before but I had removed it. $HOME/Library/Application Support/Lnd no longer exists. Any ideas? It seems theres something still on my computer thats blocking the set up. 

TIA

**Comment by BitSenseApp** [comment]
That worked thanks!

**Comment by themickeyc** [comment]
I am having the same problem, I also downloaded LND, but I don't see that file in the location you mentioned

**Comment by SamWouters** [comment]
I have this problem too, but there is no Lnd folder under Application Support. (Mac)

**Comment by mrfelton** [comment]
@SDWouters are you definitely looking in The Application Support dir under your homedir (`~/Library/Application Support/Lnd` and not the system-wide one (`/Library/Application Support/Lnd`)

**Comment by SDWouters** [comment]
TIL my Mac has not 2, but 3 folders called Library. Could only find that one through the Terminal 🤨Thanks!
