### ISSUE TITLE
Waiting for Peers - No Progress

### ISSUE THREAD

**Issue by themickeyc** [LN-Zap/zap-desktop#593]
![screen shot 2018-07-24 at 6 02 03 pm](https://user-images.githubusercontent.com/41479075/43168539-b32872d6-8f6b-11e8-8e7a-11547f889abf.png)

I have bee sitting and watching this screen with no progress for about 15 minutes

Syncing to the blockchain

Waiting for peers...
It looks like this could take some time - you might want to grab a coffee or try again later!

**Comment by JimmyMow** [comment]
@themickeyc it seems the BTCD node that was serving the neutrino filters died with all the traffic after release, which would explain users not being able to sync. 

I just resized the box and BTCD is back up and running. If you restart Zap do you still have this issue?

**Comment by themickeyc** [comment]
huzzah! Its working now!

**Comment by JimmyMow** [comment]
🍻
