### ISSUE TITLE
Create New Wallet from "Welcome Back" Screen

### ISSUE THREAD

**Issue by DanielHinton** [LN-Zap/zap-desktop#594]
I uninstalled an older Zap version and upon loading v0.2.0 it looks like the "Welcome Back" page is missing a button to create a new wallet.

![zap-create-new-wallet](https://user-images.githubusercontent.com/7569926/43168441-4373bba8-8f6b-11e8-8d16-6f9c37b8943c.JPG)

**Comment by JimmyMow** [comment]
This is due to the new WalletUnlocker with LND. You must already have an LND wallet on your machine that’s old and needs to be removed. What OS are you on?

**Comment by DanielHinton** [comment]
I'm on Windows.

Saw the slack comments and got it worked out. Issue resolved. Thanks! I did have an old LND file that I was able to delete.

MacOS: $HOME/Library/Application Support/Lnd
Windows: %LOCALAPPDATA%\Lnd
Linux: ~/.lnd

**Comment by JimmyMow** [comment]
👍 cheers
