### ISSUE TITLE
Can't advance during onboarding step

### ISSUE THREAD

**Issue by r0zar** [LN-Zap/zap-desktop#597]
I installed the v0.1.1 but have no knowledge of an install directory so basically I'm stuck here.
![zapbug1](https://user-images.githubusercontent.com/4655474/43176491-8ea67f2a-8f89-11e8-940f-3011b98babd2.PNG)

**Comment by JimmyMow** [comment]
Check out #591

**Comment by r0zar** [comment]
Yep. That's it. I've periodically worked with lnd.
