### ISSUE TITLE
"Stream removed" Javascript Error when connection to LND is lost

### ISSUE THREAD

**Issue by skcheffy** [LN-Zap/zap-desktop#601]
Received this error which ends up shutting ZAP down.  Computer was sleeping and when i Logged back into ZAP the error popped up and once I clicked OK ZAP closed.  Picture below to show the error.

![screen shot 2018-07-25 at 5 30 24 am](https://user-images.githubusercontent.com/31999006/43192734-30d52692-8fcc-11e8-874b-84ca643d9ff2.png)

**Comment by mrfelton** [comment]
@skcheffy can you tell me if you were running Zap in the default mode or were you using the custom mode and connecting to an external lnd instance?

**Comment by skcheffy** [comment]
Sure thing.  This was running in default mode.  I have since restarted multiple times and it is working now.

Not sure what the issue was but wanted to leave open in case of bug.
