### ISSUE TITLE
Option create new wallet is not displayed

### ISSUE THREAD

**Issue by mklph** [LN-Zap/zap-desktop#602]
When I open the app and go through the onboarding I get stuck at this screen:

![image](https://user-images.githubusercontent.com/3105907/43194541-e60e6f9c-9002-11e8-94df-45fe3255a659.png)

I don't see an option to create a new wallet? I haven't created one so have no password yet.

**Comment by mrfelton** [comment]
Hi, @mklph this indicates that Lnd has found an existing wallet on your machine. Please see https://github.com/LN-Zap/zap-desktop/issues/591

**Comment by mklph** [comment]
Aha, thought it might be something like that. I tried removing zap folder in application support but I see it's this folder: `/Library/Application Support/Lnd` . Probably some old installation. It works now, thanks!
