### ISSUE TITLE
Slack link not working

### ISSUE THREAD

**Issue by calvin-pietersen** [LN-Zap/zap-desktop#61]
Slack link is no longer available.

https://zaphq.slack.com/join/shared_invite/enQtMjQ2NTg3NzA5NTkwLTRjNjNhMDc5ZmIyNTA4ZTJiNDNiYzlkM2E5NzhlOTU5ZTI5ZGIxYzQ4NWI5NTcyYjQxZDEzNTQwNmJkNzQ1NmE

**Comment by JimmyMow** [comment]
Sorry! Here ya go:

https://join.slack.com/t/zaphq/shared_invite/enQtMjYzNDQyMTQxOTU4LTY3ZDk4M2Y3YmEzOTM1ODk1NjEwYjJmMmY3NmU2YTM3ZmJmOTViODcxN2E3MmYyNjAxOGNmNzY1ZDhhYmEwMDI

**Comment by JimmyMow** [comment]
Will update README in a sec
