### ISSUE TITLE
Testnet Bitcoin do not reach the wallet

### ISSUE THREAD

**Issue by BitRixx** [LN-Zap/zap-desktop#622]
I ´ve sent an amount of testnet BTC to my ZAP.
Synch has been fully completed. The balance does not change.

BTC Testnet Explorer shows confirmed tBTC on wallet´s adress.

**Comment by mrfelton** [comment]
@BitRixx  How long did you wait? Is it still not showing?

**Comment by BitRixx** [comment]
I made the transaction yesterday when ZAP synched to the network. I did several transactions but nothing arrives in the wallet. Might be usefull, to delete the LND AppData again an resynch.

**Comment by BitRixx** [comment]
In addition: After reinstalling and fully resynching ZAP + creating a new wallet passphrase i am still not able to reseive BTCt coins. While the BTCt Explorer shows all TX to my ZAP adress as confirmed.

**Comment by BitRixx** [comment]
I tried to generate some external mnemonics(IAN COLEMAN) in order to import them. ZAP is unable to import mnemonics (24words) the NEXT button is just not reacting. Maybe there´s an issue by generating wallets.

**Comment by BitSenseApp** [comment]
I have the same error, don't actually receive my testnet bitcoins from transaction...: 590e0dbbd1c86e5c29e7da63f924cb98ee46ad04f30184ee2cef77fc0b67bd60

**Comment by mntetai** [comment]
same problem here with tx id : f5fd4d84e43967de161842463010e3b4b4f34ac321d91248b47d9d07425ee6ae

**Comment by mntetai** [comment]
I noticed something ..
My bitcoin testnet address remains constant. 
It used to change each time I opened the address form.

**Comment by mrfelton** [comment]
@mntetai that behaviour has been updated - It now only changes once the address has been used.

**Comment by mrfelton** [comment]
@mntetai could you make a backup of the files in `~/Library/Application Support/Zap` and then remove that directory and try again please.

**Comment by mntetai** [comment]
Since I am running on win10 pro it might be located on a different path ?

**Comment by mrfelton** [comment]
@mntetai - yes, it will be in `C:\Users\...\AppData\Roaming\Zap`

**Comment by mntetai** [comment]
mmm no .. I don't think that the problem is related to the address of the wallet or the cache...
I would look in the direction of the btcd daemon . ( which relays the transactions to the wallet )

**Comment by mntetai** [comment]
I did what  you told me to. No effect .

**Comment by mrfelton** [comment]
@mntetai after doing what I said, did you get a new wallet address when you opened up the wallet?

**Comment by mntetai** [comment]
yes

**Comment by mrfelton** [comment]
Ok, great. Have you tried / can you try sending new coins to this new address please?

**Comment by mntetai** [comment]
I just did .
I have tried it also with lndcli yesterday .. did not work :-(

**Comment by mntetai** [comment]
Seems to me that since I am not the only one with this problem .. you might talk to @jackmallers - maybe the problem is with the btcd instance we connect to ( default mode ).
we can check this with a custom connection.

**Comment by mrfelton** [comment]
@mntetai if you jump into our slack room we can probably help you better.

**Comment by JimmyMow** [comment]
I can confirm that this issue is a BTCD <-> LND (Neutrino) issue. `0.2.0` is a BTCD node that is manually patched as BTCD and Neutrino are being updated to match the recent changes in BIP 158. 

I am currently working on a solution. If you'd like to use Zap beforehand I'd suggest using custom connection to your own BTCD<->LND in the meantime.

**Comment by btc21cluib** [comment]
I have the same problem, don't actually receive my testnet bitcoins to my address
2N999A6HfL1zErB2VrNBcE7YhToYhRfpVos

**Comment by mrfelton** [comment]
This issue should be resolved with the latest 0.2.1 release.

**Comment by JimmyMow** [comment]
I can confirm this is working in 0.2.1
