### ISSUE TITLE
How can I configure it to mainnet

### ISSUE THREAD

**Issue by kiikoh** [LN-Zap/zap-desktop#629]

**Comment by mrfelton** [comment]
@kiikoh currently we only support testnet by default. You can however set up your own bitcoin fullnode and lnd node and connect Zap to that.

See https://ln-zap.github.io/zap-tutorials/iOS-remote-node-setup for some help setting up those nodes (you can ignore the part about `Zap Connect` if you only want to connect from Zap Desktop.

When you start up Zap, select the `custom` mode to connect to your own mainnet lnd node.

**Comment by glensidecross** [comment]
I have a RaspiBlitz node running and have it connected to Zap on my iPhone. I'd like to get it connected to Zap on my desktop. How do I find out the necessary info?

**Comment by mrfelton** [comment]
@glensidecross we don't yet have a tutorial for this, but basically you ned to:

1. Copy the files `tls.cert` and `admin.macaroon` from the lnd node over to your desktop machine.
2. Start up Zap Desktop, select the `custom` connection mode and when asked, enter the paths to those files.

**Comment by glensidecross** [comment]
Thanks!  I'll give it a try.
