### ISSUE TITLE
Unable to deposit tBTC

### ISSUE THREAD

**Issue by BitSenseApp** [LN-Zap/zap-desktop#630]
I get this error after trying to fund Yalls channel with 20,000 sats:

<img width="1280" alt="screen shot 2018-07-30 at 4 58 30 am" src="https://user-images.githubusercontent.com/41635928/43376965-a7a69250-93b5-11e8-936f-4d7eff9821be.png">

<img width="1280" alt="screen shot 2018-07-30 at 4 58 37 am" src="https://user-images.githubusercontent.com/41635928/43376950-83b0904e-93b5-11e8-9704-22dce12912ff.png">

**Comment by mrfelton** [comment]
@BitSenseApp this issue was reported in https://github.com/LN-Zap/zap-desktop/issues/523 and was recently fixed in https://github.com/LN-Zap/zap-desktop/pull/606. Please try with `master` or wait for the `0.2.1` release which will include this fix.
