### ISSUE TITLE
Stuck in "Sending your transaction"

### ISSUE THREAD

**Issue by SDWouters** [LN-Zap/zap-desktop#637]
I tried to buy some coffees from the Acinq store through the Lightning testnet, with a funded channel to Yalls.org (02212d3ec8) and another to Endurance (03933884aa). When I send a transaction, it infinitely remains stuck in the loading animation "Sending your transaction".

I'm running 0.2.0-beta on Mac.

Displaying the problem in the GIF below, plus another visual bug where refreshing leads to old transactions changing from Received to sent and + to -

![2018-07-31 16 23 34](https://user-images.githubusercontent.com/6563736/43465734-3d5eae12-94de-11e8-8d6c-235e7508cf32.gif)

**Comment by JimmyMow** [comment]
closing for #721
