### ISSUE TITLE
Transition is invalid in current state

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#641]
When refreshing (`cmd + r`) in dev mode I get the following error

<img width="951" alt="screen shot 2018-08-01 at 1 16 45 pm" src="https://user-images.githubusercontent.com/4040039/43540570-baecfcda-958d-11e8-9912-90d60a7b0b35.png">

**Comment by mrfelton** [comment]
@JimmyMow out of interest, what is the use case of using `cmd+r` to refresh the page?

**Comment by JimmyMow** [comment]
@mrfelton for development. refreshing the page to get new state/new saved changes
