### ISSUE TITLE
zap desktop can not get filter

### ISSUE THREAD

**Issue by mntetai** [LN-Zap/zap-desktop#648]
Os : win 10 pro
lnd version : 0.4.2
Zap version : commit id 61daf159946024539d1f1e52fc800c127056f4c0 on mater branch.

Steps to reproduce : 
Pull from master.
Yarn.
Run zap. 

Zap logs attached.
[zap_error_can_not_get_filter.txt](https://github.com/LN-Zap/zap-desktop/files/2253332/zap_error_can_not_get_filter.txt)

**Comment by mrfelton** [comment]
@mntetai  please test with #658 which updates lnd and the btcd backend that it connects to which I believe will resolve this issue. Thanks.

**Comment by mrfelton** [comment]
This issue should now be resolved in the new 0.2.1 release.

**Comment by JimmyMow** [comment]
@mntetai can you confirm this is fixed with 0.2.1? I'd like to close this

**Comment by mntetai** [comment]
I tried to sync the network .. I did not work .
I can confirm that this is resolved.

**Comment by JimmyMow** [comment]
What was the issue? I have had no issues fetching filters with 0.2.1 or master

**Comment by mntetai** [comment]
![zap_sync_25_08_2018](https://user-images.githubusercontent.com/1884392/44621231-1df0e280-a8ab-11e8-905d-2d445a45464e.png)

**Comment by JimmyMow** [comment]
This is master @mntetai?

**Comment by JimmyMow** [comment]
@mntetai can you download the new release (0.2.2) and verify this is resolved?

**Comment by mrfelton** [comment]
The sync process within lnd has been much improved over the last couple of months. I'm going to close this issue due to lack of activity.
