### ISSUE TITLE
Invoice shows value instead of amt_paid on settled invoice

### ISSUE THREAD

**Issue by wraithm** [LN-Zap/zap-desktop#654]
If I made a payment request with `value = 0` and then the invoice gets paid with a different amount (the value of `amt_paid`), Zap displays the paid amount as `0` ie. `value`, when I would intuitively expect it to display the `amt_paid`.

On line 38 of `app/routes/activity/components/components/Invoice/Invoice.js`: 
```
<Value value={invoice.value} currency={ticker.currency} currentTicker={currentTicker} />
```
I also found a similar value in `app/components/Activity/InvoiceModal.js`.

I'd expect the code to do something like `value={invoice.settled ? invoice.amt_paid : invoice.value}`.

Edit: I started messing around with the code to add this, and I found that `invoice.amt_paid` isn't coming across the `ListInvoices` rpc call. I'm a little confused because that field is definitely described in the [API docs](https://api.lightning.community/#invoice). I have an invoice that shows `amt_paid` when I use `lncli` on the lnd node that I'm connecting to. It's a settled invoice.

**Comment by mrfelton** [comment]
@WraithM the current version of lnd that we bundle doesn't support the new `amt_paid` property. This will be updated as part of  #658
