### ISSUE TITLE
Stuck at password unlock

### ISSUE THREAD

**Issue by gonzaloaune** [LN-Zap/zap-desktop#655]
It seems at some point I set up a password but I can't remember which one is it, where is this information stored (Which directory), so I can go ahead and delete and start over? I think this should be added to the README. Thanks.

**Comment by gonzaloaune** [comment]
I'll close this one since I just saw my answer in the closed issues. I still believe we should let the users know they can delete the folder `~/Library/Application\ Support/` (Mac) in the README.

**Comment by mrfelton** [comment]
@gonzaloaune in the latest (as yet unreleased) version of the app we show the user the path to the wallet that we have detected so that they can easily see which wallet zap is asking them to unlock (or which directory they need to remove in your case)
