### ISSUE TITLE
npm run build-dll exited with code 0 flow-typed exited with code null

### ISSUE THREAD

**Issue by Otomakan** [LN-Zap/zap-desktop#66]
When using node 8.1.3 running on Ubuntu 16.04 I got the following message

```
npm run build-dll exited with code 0 
flow-typed exited with code null
```
Then the install doesn't continue with no error message

Simply solved the issue by upgrading to 8.9. Someone might want to look into it

**Comment by JimmyMow** [comment]
Interesting. `8.1.3` shouldn't have given you an error. I will look into it, thanks.

Closing because this seems to be resolved
