### ISSUE TITLE
Mouse hover shows the text "Payment Fee" instead of "Fiat X value"

### ISSUE THREAD

**Issue by zanderisrael** [LN-Zap/zap-desktop#662]
<img width="160" alt="screen shot 2018-08-12 at 1 31 16" src="https://user-images.githubusercontent.com/835546/43996624-78429792-9dcf-11e8-86bf-030196a6e5bb.png">

**Comment by JimmyMow** [comment]
Why is that an issue @zanderisrael? Confused as to what the problem is

**Comment by zanderisrael** [comment]
Well its not the fee value...
Its the actual transaction value, not the fee.

**Comment by JimmyMow** [comment]
Ah got it, thanks. Will fix this
