### ISSUE TITLE
Cannot request more than ~.04BTC

### ISSUE THREAD

**Issue by Ulmo** [LN-Zap/zap-desktop#671]
There is a bug that I cannot request more than ~.04BTC.  Why?

If it has to do with existing capacity, the sender could open their own new channel to me, or use multiple aggregate smaller payments.

**Comment by mrfelton** [comment]
@Ulmo this limit is set by lnd and will most likely be lifted once it comes out of beta.

See https://github.com/lightningnetwork/lnd/blob/35363ee9a8c3ca6d19377080f507e26c73706410/rpcserver.go#L2085-L2095
```
// Currently, within the bootstrap phase of the network, we limit the
// largest payment size allotted to (2^32) - 1 mSAT or 4.29 million
// satoshis.
```


Also See https://github.com/lightningnetwork/lnd/blob/35363ee9a8c3ca6d19377080f507e26c73706410/rpcserver.go#L54-L57
```
// maxPaymentMSat is the maximum allowed payment currently permitted as
// defined in BOLT-002. This value depends on which chain is active.
// It is set to the value under the Bitcoin chain as default.
```

**Comment by Ulmo** [comment]
Oops!  I forgot about LND's limits being lower than C-Lightning's.  Thank you!
