### ISSUE TITLE
Zap 0.2.1 Problem persists with scannable barcodes

### ISSUE THREAD

**Issue by d4amenace** [LN-Zap/zap-desktop#675]
![example3](https://user-images.githubusercontent.com/29969146/44168837-202b9380-a098-11e8-914b-1f143b1c29af.png)

I am using Zap 0.2.1 on windows 10.

I have experienced a problem with the QR codes generated for both bitcoin addresses and payment requests and lightning netword payment requests are not scannable and not recognized by QR scanners on my phone.  This is definitely application specific, as since I also use Eclair, their barcodes are scannable by the same programs.

**Comment by mrfelton** [comment]
@d4amenace I believe this issue is now resolved in master by https://github.com/LN-Zap/zap-desktop/pull/732
