### ISSUE TITLE
Make it more clear to users which network they are connecting/connected to (testnet vs mainnet)

### ISSUE THREAD

**Issue by rashbit** [LN-Zap/zap-desktop#676]
Installing Zap on Win10 Pro. Right after the install, created the wallet and suggested to fund it. Bitcoin address (both QR and text) are invalid bitcoin address. This: 2MtYDfkWfWvzia1oA5M8mdxprHyRi97bka1

**Comment by mrfelton** [comment]
@rashbit note that when you are using the `default` mode the app is connected to the bitcoin testnet. The address you see is a valid testnet address.

You can send some testnet bitcoins to your wallet from https://testnet.manu.backend.hamburg/faucet

If you want to use the wallet on mainnet you will need to setup your own bitcoin+lnd fullnode and then use the  `custom` option when starting zap to connect to your lnd node.

**Comment by rashbit** [comment]
Thanks. Perhaps a note on the screen explaining that could be helpful for new users. I guess many just give up trying...

**Comment by mrfelton** [comment]
Note that this is just a temporary situation. As soon as lnd is ready for usage on the mainnet we will default our app to connecting to the mainet. Until then we are defaulting to the testnet.

But that said, I agree that this could be made clearer to users so I'm going to reopen this story and re-purpose as a feature request to add some help text within the app to make this more clear for users.

Thanks for the feedback @rashbit

**Comment by ZacharyATanenbaum** [comment]
In addition to the pill I would suggest adding some text next to the default option. Stating that Zap will connect to the testnet by default.

**Comment by songproducer** [comment]
This is still an issue on the latest Mac client  (Version 0.3.2-beta (0.3.2-beta.5107))
