### ISSUE TITLE
Error: 2 UNKNOWN: invoice not for current active network 'testnet3'

### ISSUE THREAD

**Issue by skcheffy** [LN-Zap/zap-desktop#686]
Went to Yall's.org to try out some payments from my Mac.  Everything on the wallet itself seems to be fine but went to pay, it auto pulled up ZAP with Invoice but no satoshi in the pay box.  Attached is the error that pulled up.

![screen shot 2018-08-17 at 4 10 29 pm](https://user-images.githubusercontent.com/31999006/44286854-8e0ec100-a238-11e8-8783-48850aed23cb.png)

**Comment by mrfelton** [comment]
I believe https://yalls.org/ is now running on the bitcoin mainnet, where as the default for zap is currently testnet. You could try some of the other testnet stores listed on http://lightningnetworkstores.com/testnet

**Comment by sysout** [comment]
Try https://testnet.yalls.org
