### ISSUE TITLE
Git treatmeant of line endings

### ISSUE THREAD

**Issue by torkelrogstad** [LN-Zap/zap-desktop#69]
This might be more of a git issue than zap-desktop issue, but I don't really know where else to ask. When I enter the zap-desktop dir, I get the following message:
```
Warning: CRLF will be replaced by LF in resources/bin/linux/lnd.
The file will have its original line endings in your working directory.
```

It also becomes super slow to navigate around the repo, I assume this is because git is doing something wonky with the line endings for every command I issue.

Any ideas on what I should do about this?

EDIT: I'm running Linux Mint, by the way.

**Comment by avlo** [comment]
LMint 17.2 here.  just cloned the repo & on master branch, navigating all project dir w/o issue.

if you haven't already, try turning autocrlf off:

```git config core.autocrlf false```

and see if that works.  if it doesn't double check <project_root>/.git/config and ~/.gitconfig and delete any/all lines containing ***autocrlf***, restart your shell, then try navigating again.

if that doesn't work, make sure you've got the most recent version of git:

```bash
$ git --version
git version 1.9.1
```

delete existing project dir and git clone fresh again.

**Comment by torkelrogstad** [comment]
None of the steps you suggested worked. `git version` gives me 2.7.4, so I doubt that's the issue.  

However, adding `resources/bin` to `.gitignore` and doing `git rm --cached` on the binaries provided makes navigation fast. I guess that's git doing something with line endings on those files, even though they are binary. They are 26M, so changing all perceived 'line endings' must've been what took so long.

**Comment by JimmyMow** [comment]
Was there ever any solution to this?

**Comment by torkelrogstad** [comment]
Nothing other than ignoring the supplied binary files. It doesn't cause any problems for me as long as I run `lnd` separately. If I shut down lnd and then run `npm run dev`, I'm stuck at 0% syncing and `lnd shutting down null` in my terminal.

**Comment by torkelrogstad** [comment]
Eh, this is kinda weird, but now I don't manage to reproduce this... I was poking around for solutions, and I realized this problem wen't away, even though I kept the original `.gitignore`. I was hoping I could fix this to prevent the same problem for others in the future, so that's actually kinda frustrating...

**Comment by JimmyMow** [comment]
@torkelrogstad yeah so git doesnt like my binary files. if you manually put your `lnd` binary inside `resources/bin/darwin` or whatever it will work. dang! i will do some research in a bit

**Comment by torkelrogstad** [comment]
Theres also the possibility of adding `resources/bin/* -text` to `.gitattributes` [docs here](https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes), if the problem arises again.

**Comment by JimmyMow** [comment]
Wanna submit a PR for that? Looks good

**Comment by torkelrogstad** [comment]
Sure, #83

**Comment by JimmyMow** [comment]
Nice. Closing

**Comment by torkelrogstad** [comment]
The problem is back... Even with the updated attributes file...
