### ISSUE TITLE
"Lnd has unexpectadly [sic] quit"

### ISSUE THREAD

**Issue by groundstart** [LN-Zap/zap-desktop#696]
<img width="950" alt="screen shot 2018-08-21 at 10 03 09 am" src="https://user-images.githubusercontent.com/23239196/44410310-bdb81480-a529-11e8-94f3-e1ee3266da00.png">

Error message appears a few seconds after sync begins.
Occurs at every launch since 0.2.1 update.

**Comment by mrfelton** [comment]
@CaptainHadacol there are a couple of things that you could do to try to debug this:

1) check out the code from the master branch, and run that. There are a number of fixes merged recently that partially address this issue, including a change that can enhance that particular error message with some additional details about why it quit.

2) Start the app in debug mode, which you can do like so:

a) if you are running the 0.2.1 release:
  ```
  DEBUG=zap* DEBUG_LEVEL=debug /Applications/ZapDesktop.app/Contents/MacOS/ZapDesktop
  ```
b) if you are running the code from a clone of the master branch
  ```
  DEBUG=zap* DEBUG_LEVEL=debug yarn dev
  ```

This will allow you to see the logs from the app and from lnd and get some more insight into why it crashed.

Additionally, you can inspect the lnd logs directly which you can find at:

if you are running the 0.2.1 release:
```
 ~/Library/Application\ Support/Zap/lnd/bitcoin/testnet/wallet-1/logs
```

If you are running in dev mode from a git clone.
```
 ~/Library/Application\ Support/Electron/lnd/bitcoin/testnet/wallet-1/logs
```

**Comment by Darkbladecr** [comment]
Thought I would add my logs for the exact same problem

[zap-crash.log](https://github.com/LN-Zap/zap-desktop/files/2343689/zap-crash.log)

**Comment by mrfelton** [comment]
@Darkbladecr thanks for the details. Please could you try running with more debugging enabled as per my comments above, and post the logs from that? Thanks.

**Comment by Darkbladecr** [comment]
No logs present on the release version so I will have to rebuild from source, let me see if I get the same issue.

**Comment by kaloudis** [comment]
I think this happens if the admin.macaroon file cannot be found or opened

**Comment by CaptainHadacol** [comment]
Attached: log details from debug mode; launch Sep 6
[zap-lnd-log.txt](https://github.com/LN-Zap/zap-desktop/files/2361144/zap-lnd-log.txt)
[zap-bash.txt](https://github.com/LN-Zap/zap-desktop/files/2361145/zap-bash.txt)

**Comment by mrfelton** [comment]
I'm going to close this issue as it hasn't been updated for about a month, however please feel free to reopen if you experience the issue with the latest version of Zap which should now also provide more detail as to the specific cause of the error.
