### ISSUE TITLE
Syncing Problem with the Testnet

### ISSUE THREAD

**Issue by ZacharyATanenbaum** [LN-Zap/zap-desktop#709]
I set up Zap with the default configuration - which automatically configures Zap to use the Testnet. It came to my understanding that the Testnet has been unusable recently which might be causing the below issue.

My Zap Wallet happens to sync indefinitely with the Testnet. Once all of the blocks have been downloaded and the Commitment Filter run it hangs at 100%. Whenever a new block appears Zap will drop to 99% before quickly running the Filter on the new block.

If this is strictly a problem with the Testnet there should also be a designation that the Testnet is being used and is the problem on the below screen. Similar to this issue: https://github.com/LN-Zap/zap-desktop/issues/676.

It might not be strictly a problem with the Testnet. As Zap seems to fully download the blockchain and wait even if there are no additional blocks to download.

![image](https://user-images.githubusercontent.com/9688904/44592747-7af77600-a78f-11e8-8782-4c65b76baa89.png)

This as occurred on two computers:
* Mac OS 10.13.4 using 0.2.1 on 08/17/18
* Ubuntu 18.04 LTS using 0.2.1 on 8/24/18

**Comment by ZacharyATanenbaum** [comment]
I just got it to work by closing the wallet and reopening!

**Comment by mrfelton** [comment]
There are some known sync related issues in 0.2.1 which would be addressed in the upcoming 0.2.2 release. Glad you got it working @ZacharyATanenbaum
