### ISSUE TITLE
Please provide AppImage for download

### ISSUE THREAD

**Issue by probonopd** [LN-Zap/zap-desktop#72]
As per

https://github.com/LN-Zap/zap-desktop/blob/5f389c19362405db41c659ed593e6fe416a0a2f5/package.json#L69

LN-Zap is already configured to be bundled as an AppImage. It would be great if you could provide an AppImage for download on [GitHub Releases](https://github.com/LN-Zap/zap-desktop/releases).

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by JimmyMow** [comment]
Thanks for creating this issue. Yes, this is needed. I have been very busy but will be working on Zap Desktop now getting it ready for mainnet testing. I will keep this open until I provide a release

**Comment by probonopd** [comment]
Please let me know if I can assist in any way. Thanks.

**Comment by thinkjanis** [comment]
Ultimately a [snap](https://snapcraft.io/) package would be the best and simplest option because some distros will start to integrate snapd into their app stores so that it is a one-click process for the user. But I guess you have to provide almost every option anyway since most Linux folks each have their own preference and opinions about what is the best packaging solution.

**Comment by probonopd** [comment]
The day snapd lands in the Red Hat default installation, I buy you a beer. Promised!

**Comment by thinkjanis** [comment]
Fair point @probonopd. Is Flatpak supported on RH?

**Comment by probonopd** [comment]
I don't think Flatpak comes with RHEL 6 or 7 as part of the default installation, but I don't think it's related to the original topic of this ticket.

**Comment by KurtPfeifle** [comment]
@thinkjanis wrote:

> *"Ultimately a snap package would be the best and simplest option"*

If this is your opinion, then maybe you should create create a separate issue for this? And maybe not try to hijack another issue?

I myself struggled with snap for quite a while before I could get the framework installed on a non-Ubuntu system and the first snap package running. I started to look at snap *before* I even heard the first time of AppImage. And I got my first snap working only *after* already a few dozen AppImages were running just fine on my system. Without the need to install a framework first!

So no, for me "a snap package ISN'T the best and simplest solution". By far not!

**Comment by Empact** [comment]
@thinkjanis feel free to open an issue for Snap - closing this given an AppImage is present in the current release: https://github.com/LN-Zap/zap-desktop/releases/tag/v0.1.1-beta

**Comment by KurtPfeifle** [comment]
@Empact:

The link you gave doesn't seem to have an AppImage: https://github.com/LN-Zap/zap-desktop/releases/tag/v0.1.1-beta

Unless that "linux" ZIP has one hidden inside. If so, two issues:

1. Why then doesn't it mention the AppImage on that download side?
1. Hiding an AppImage inside a ZIP is somewhat against the AppImage philosophie...

**Comment by probonopd** [comment]
>Hiding an AppImage inside a ZIP is somewhat against the AppImage philosophie...

...and reduces some of its functionality as is explained on https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#common-mistake:

> Please __DO NOT__ put an AppImage into another archive like a `.zip` or `.tar.gz`. While it may be tempting to avoid users having to set permission, this breaks desktop integration with the optional `appimaged` daemon, among other things. Besides, the beauty of the AppImage format is that you never need to unpack anything. Furthermore, packing an AppImage into some form of archive prevents the AppImage from being added to the central catalog of available AppImages at https://github.com/AppImage/AppImageHub.

**Comment by Empact** [comment]
@KurtPfeifle Yeah the AppImage and Deb are in the archive. @probonopd thanks for the info, sounds like we should split that out. Presumably we should do the same with Deb?

**Comment by KurtPfeifle** [comment]
@Empact:

Exactly. 

A ZIP to many Linux users looks suspicious. They'd have to download it first and peak inside to know what they deal with. And then, the download may even be in vain because the package isn't suitable for their system. Or, what also happens, there is a *`${s.th.-install}`* script inside which they'd have to trust first. Or, ...

Debian users will then recognize that they can install a .deb, and feel better.

AppImage users also recognize the suffix, and will know it will not mess with their system libs when they run it (without installing).
