### ISSUE TITLE
Neutrino rescan ended with error: Couldn't retrieve block X from network

### ISSUE THREAD

**Issue by bradyswenson** [LN-Zap/zap-desktop#722]
## Description

Zap stalls during sync due to a Neutrino error. The UI does not progress to the main app wallet screen but stalls at the syncing 100% user message.   

## Expected Behavior

Zap is expected to finish syncing and update the UI with main app screen

## Actual Behavior

An error occurs that prevents this from happening:

` Neutrino rescan ended with error: Couldn't retrieve block 000000000000002967a31b03fccd152140128d9663b79336a7616e977cfadfaf from network`

[Logs with error (see line 30) and context in this gist](https://gist.github.com/bradyswenson/84f4c4eb13d5d97bcddb3e68b4d52d16). 

## Steps to Reproduce

- 1. pull branch master from repo, build, test, run in dev with `DEBUG_LEVEL=debug yarn dev`  
- 2. watch logs for Neutrino error

## Context

Attempting to start the app

## Your Environment

- Zap Desktop version: 0.2.1-beta (master cloned ~ 10:30 AM Central Time / Chicago)
- Operating System and version: MacOS 10.13.6

**Comment by bradyswenson** [comment]
FYI - I am planning to try again later tonight from a clean slate (as mtfelton suggested in Slack) - I will report back here with findings.

<img width="317" alt="image" src="https://user-images.githubusercontent.com/3144456/44736718-86abab00-aab5-11e8-959f-0d3adbf8d7af.png">

**Comment by mrfelton** [comment]
@bradyswenson could you let us know wether you have this working now please? Thanks.

**Comment by mrfelton** [comment]
I'm going to close this issue due to a lack of activity. The issue itself would have been an issue with lnd and not with Zap itself and as lot of updates have gone into lnd's neutrino support since this issue was created back in August. Please feel free to reopen if this issue persists with the latest release of Zap.

**Comment by bradyswenson** [comment]
Sorry for no t replying! Not experiencing this issue any longer.
