### ISSUE TITLE
create funding transaction failed: not enough witness outputs to create funding transaction

### ISSUE THREAD

**Issue by tailnode** [LN-Zap/zap-desktop#723]
i want create funding transaction in testnet. yesterday i got some testnet bitcoin by this transaction https://testnet.smartbit.com.au/tx/ee4a5937fa0e00217b5e586e90ada1240db4ee1f15d4cb903769842eeb4f99ab, now it had more than 200 confirmations.

1. click the connect button
![image](https://user-images.githubusercontent.com/3156493/44760416-46a9fe00-ab71-11e8-9bbd-8eddd4c83a01.png)
2. submit
![image](https://user-images.githubusercontent.com/3156493/44760435-59243780-ab71-11e8-8ae5-d63ebebd3669.png)
3. want create funding transaction but failed
![image](https://user-images.githubusercontent.com/3156493/44760440-5e818200-ab71-11e8-882c-94d222c32cbe.png)

## Your Environment

- Zap Desktop version: 0.2.1-beta (0.2.1-beta.3731)
- Operating System and version: macOS Sierra 10.12.6

is it possible to check the log, so i can continue to investigate the reasons.
thank you.

**Comment by tailnode** [comment]
@egodigitus Thank you. I tried restart Zap, but not work.

**Comment by Tkoch2** [comment]
I'm having the same issue. Restart didn't help

**Comment by JWWeatherman** [comment]
I just opened 4 channels with 4 other nodes I setup. Worked flawlessly, but now I am getting this error as well. I'm only trying to open a channel for about $7 and I have about $80 in my on chain balance that has not increased in several hours.

**Comment by pieman64** [comment]
I saw same bug with mainnet a few days ago.

**Comment by vega113** [comment]
Any update on this?

**Comment by vega113** [comment]
Looking at https://github.com/lightninglabs/lightning-app/issues/46 it looks like the wallet attempts to pick up UTXO to construct a funding transaction from a transaction that was not confirmed yet.

**Comment by brainharrington** [comment]
Anything new? This is happening to me today on mainnet and my on chain transaction deposits have 5 confirmations

**Comment by marsrobertson** [comment]
`0.4.1-beta`

![image](https://user-images.githubusercontent.com/44369284/58355202-7c171a00-7e6b-11e9-837b-48b80529caac.png)

https://www.blockchain.com/btc/address/3NQRkeJ26VFedhq6HXGzqcDWKKvFuefhsf

`0.0005` on-chain with 14 confirmations so far

**Comment by WilliamConnatser** [comment]
I was getting this error too, but then I reduced the amount in the channel I was trying to open and it worked. Perhaps there is a bug in the part of the code that calculates the available balance and fee?? I feel like it should not say it's a valid amount if there are insufficient funds (without the cryptic error message)

**Comment by JimmyMow** [comment]
@WilliamConnatser Sure. The error we are getting is coming directly from LND. I know improving error handling and reporting is something high on LNDs priority list, but unfortunately, for now, we have to guess and try our best with what we're given.

**Comment by LilChange** [comment]
I just experienced this message and was a bit confused. Persevering, I opened a channel where I lowered the amount to less than full amount of my onchain wallet and it worked.

Given that better feedback from LND is out of Zap's control I propose this solution:

1. If channel amount is higher than `Balance + Fee` show `Amount` field with red (error) border
2. Also display amount of `Fee` next to `Slow, Medium, Fast`

**Comment by PizzaParkerGM** [comment]
I experienced this as well. I'm pretty sure it's because when you open a channel for however much you want, it puts the whole wallet balance in a pending state until the channel is open and confirmed by the network. I'm not too good on the technical's, but currently my raspberry pi is saying my whole wallet balance is pending even though I opened a channel using 8% of my current balance.

**Comment by mrfelton** [comment]
@PizzaParkerGM this is exactly correct. You can not spend change outputs until they have been confirmed.

**Comment by mrfelton** [comment]
Unconfirmed outputs can be used for funding channels in recent releases so this is no longer an issue.
