### ISSUE TITLE
Zap Desktop crashes when requesting anything below <1 satoshi

### ISSUE THREAD

**Issue by Liongrass** [LN-Zap/zap-desktop#735]
## Description

When requesting less than 1 satoshi (eg 0.1 sat), Zap Desktop freezes upon entering the first digit beyond the point. It only shows the black screen. When restarting Zap I encounter a 'Deadline Exceeded' error. Waiting for a while resolves this.

## Expected Behavior

I enter 0.1 Satoshi into the field 'amount'. I expect to either
- be prevented from entering any amount smaller than 1 satoshi
- getting an error message when clicking 'request'
- be able to request sub-satoshi amounts

## Actual Behavior

The screen freezes upon entering the first digit beyond the dot.
Upon restarting Zap I'm unable to get back into my node ("Unable to connect to host: Deadline Exceeded")

## Steps to Reproduce

- 1. Start Zap
- 2. Click on "Request"
- 3. Change ticker to 'satoshi'
- 4. Enter 0.1

## Context

I was unaware the ticker was set to satoshi, I attempted to request, a sub-bitcoin amount.

## Your Environment

- Zap Desktop version: ZapDesktop-linux-amd64-v0.2.1-beta
- Operating System and version: Ubuntu 16.04

**Comment by mrfelton** [comment]
Hi @Liongrass This issue has been resolved in the master branch already and the fix will be included in the upcoming 0.2.2. release.

See https://github.com/LN-Zap/zap-desktop/pull/705
