### ISSUE TITLE
Zap hangs on startup

### ISSUE THREAD

**Issue by toxicacd** [LN-Zap/zap-desktop#738]
## Description
Starting up Zap-Desktop under Win10 and providing it with the credentials to my own LND node.
Wallet comes up but then hangs endlessly at the loading screen.
I included a screenshot of the program's output.

## Expected Behavior
Wallet should open.

## Actual Behavior
Wallet doesn't open.

## Environment
- Zap Desktop version: 0.2.2 beta, commit: 994d3617f7bb5ad92a3376f41a46dd133cea2156
- Operating System and version: Windows 10, Version 1803 (Build 17134.228)

![unbenannt](https://user-images.githubusercontent.com/6892215/45045863-a7a36b80-b074-11e8-99fb-b8d2cd28a148.JPG)

**Comment by mrfelton** [comment]
@toxicacd is your remote lnd node unlocked (`lncli unlock`)?

**Comment by toxicacd** [comment]
@mrfelton My LND wallet is unencrypted, no unlocking needed.

**Comment by mrfelton** [comment]
@toxicacd do you want to hop into our slack so that we can try to get to the bottom of this?

**Comment by toxicacd** [comment]
@mrfelton I don't know if I can be of much help, but I'd gladly try.
