### ISSUE TITLE
missing `electron-rebuild` in package.json

### ISSUE THREAD

**Issue by KevinKelbie** [LN-Zap/zap-desktop#74]
When you follow the readme you have to run the command `./node_modules/.bin/electron-rebuild`. Since the package.json file doesn't include it it means you have to download it yourself which isn't hard, it's just a small inconvenient step.

**Comment by JimmyMow** [comment]
Sorry, the README is so out of date. I just pushed new README updates. `electron-rebuild` isn't needed anymore :)

**Comment by JimmyMow** [comment]
Closing this for now as the new README should solve this
