### ISSUE TITLE
BTCPay Server and Zap - Unable to connect to host: Received http2 header with status: 404

### ISSUE THREAD

**Issue by bitcoinshirt** [LN-Zap/zap-desktop#746]
## Description

I'm getting this error when trying to connect my BTCPay and Zap. 
Unable to connect to host: Received http2 header with status: 404
After I click on the next I get this : A JavaScript error occurred in the main process 
Exception: undefined: transition is invalid in current state

![1](https://user-images.githubusercontent.com/36959754/45106655-7e97df00-b137-11e8-9879-e19e6aee0077.png)
![2](https://user-images.githubusercontent.com/36959754/45106656-7f307580-b137-11e8-8311-08c035ff7000.png)
![3](https://user-images.githubusercontent.com/36959754/45106657-7f307580-b137-11e8-813c-d4d3ac7648f6.png)

## Expected Behavior
The wallet should start.

## Actual Behavior

Wallet does not start due to an error
## Possible Fix

No idea.

## Steps to Reproduce

Followed the tutorial on how to connect. 

1. I was asked to enter the configuration file. 
2. I've added my BTCPay Server connection config file and clicked Next. 
3. Hostname was okay. I clicked Next. 
4. Wallet began loading and then returned me back to and got this config file setup showing a red warning " Unable to connect to host: Received http2 header with status: 404".
5.  When I click next after that I get this: A JavaScript error occurred in the main process 
Exception: undefined: transition is invalid in current state

## Context

I was trying to connect my BTCPay Server and my LND with Zap.

## Your Environment

- Zap Desktop version: ZapDesktop-darwin-v0.2.1-beta.dmg 
- Operating System and version: mac OS High Sierra 10.13.6

**Comment by mrfelton** [comment]
@bitcoinshirt the javascript error at least should be fixed in the latest master branch via https://github.com/LN-Zap/zap-desktop/pull/740

**Comment by mrfelton** [comment]
@bitcoinshirt  regarding the http2 error - the QR code from BTCPay Server is only valid for 10 mins I think. Could it be that your code had expired?

**Comment by NicolasDorier** [comment]
@mrfelton it can't be, the user is copying the full connection string.

**Comment by JimmyMow** [comment]
@bitcoinshirt it looks like you got this working (considering your tweets). What was the issue? Should I close this?

**Comment by bitcoinshirt** [comment]
Hey @JimmyMow , @NicolasDorier identified the issue and fixed it. It was on BTCPay end. I'll go ahead and close it now. Thanks.

**Comment by NicolasDorier** [comment]
Yes, it was a bug where I was not updating nginx configuration for routing gRPC requests after LND started up.
