### ISSUE TITLE
When connecting to btcpayserver lightning node I get an error

### ISSUE THREAD

**Issue by JWWeatherman** [LN-Zap/zap-desktop#766]
## Description
After pasting in the config file I get an error that the remote host is not a valid IP address or domain name, but it is.

After clearing the error by clicking OK, if I try to connect again using the retained configuration data I get a javascript error that indicates an unexpected state.

## Expected Behavior

No error

## Actual Behavior

Here is a short video recording of the bug.

https://drive.google.com/file/d/1DEZasTVEpnXqQdazjExfWRcrzjDlvhYH/view?usp=sharing

## Your Environment

Desktop Mac

- Zap Desktop version:
Version 0.2.1-beta (0.2.1-beta.3731)

- Operating System and version:
Mac OS High Sierra

**Comment by JWWeatherman** [comment]
It looks like the problem is that I am using a really weird URL in my btcpayserver configuration 76.105.62.188.rdns.lunanode.com.

**Comment by JWWeatherman** [comment]
Ok, confirmed that the issue does not repo when using a normal host name. The above weird format is a rDNS format used with luna node. By creating a cname record and then updating btcpayserver and then closing and re-opening zap I was able to provide the updated config info and it worked fine. 

Tempted to close this, but supporting rDNS hostnames might be of interest.

**Comment by vswee** [comment]
I've been encountering that same issue with an ordinary url; btcpay.flat18.co.uk
