### ISSUE TITLE
Channel limits shown with different units...satoshis vs SATS.

### ISSUE THREAD

**Issue by AmazingDroopy** [LN-Zap/zap-desktop#799]
When chosing Statoshis as unit, the channel limits use a different way to show this.

## Description
When showing numbers for channel limits different unit expressions are used.
Its not consistent.

## Expected Behavior
The Channel limits:
Pay Limit:  35000 satoshis
Request Limit:  100000 satoshis

## Actual Behavior
The Channel limits:
Pay Limit:  35000 satoshis
Request Limit:  100000SATS

## Context
ZAP MacOS Desktop Client 0.2.1-Beta, connecting to LND 0.5-beta node.
Operating System and version: MacOS 10.12.6

**Comment by mrfelton** [comment]
That's for reporting @AmazingDroopy . This was actually fixed earlier today in https://github.com/LN-Zap/zap-desktop/pull/797 !
