### ISSUE TITLE
Channels category dropdown not functional

### ISSUE THREAD

**Issue by nandubatchu** [LN-Zap/zap-desktop#80]
The channels category dropdown available (on top left) in the visual preview of channels page is not functional.

**Comment by JimmyMow** [comment]
@nandubatchu can you please be a bit more descriptive? What do you mean by not functional?

**Comment by nandubatchu** [comment]
@JimmyMow I don't see any change in the node graph when I select "All Channels", "Active Channels", "Pending Channels" & "Open Pending Channels".

However, I myself have three channels open with only one active at an instance.

**Comment by JimmyMow** [comment]
Ah like the visual representation of the channels. The black graph? The graph only shows active channels. I can hide the dropdown when the graph is active

**Comment by nandubatchu** [comment]
Yes, the black graph. Can we not get more details of the nodes on hover or something?

**Comment by JimmyMow** [comment]
We can. If you want to make a separate issue for that feature request and assign it to me I can get to it at some point
