### ISSUE TITLE
Connecting Manually - Adding funds defaults dollar amt. to previous dollar amt. input

### ISSUE THREAD

**Issue by mattrolightning** [LN-Zap/zap-desktop#818]
When adding trying to add funds to a channel you're opening manually, the dollar amount below the box where you input the number of Satoshis defaults to the previous amount input in the box while the box itself lists 000000 Satoshis. When you attempt to open a channel manually, the dollar amt. should default to 0 until you input the number of Satoshis in the box above.

![screen shot 2018-09-24 at 11 17 23 pm](https://user-images.githubusercontent.com/43560996/45990841-224a2000-c050-11e8-9b62-a7fbea065a75.png)

- Zap Desktop version: 2.2
- Operating System and version: Mac OS Sierra 10.12.6

**Comment by JimmyMow** [comment]
Ok thanks @mattrolightning. PR #823 fixes this

**Comment by mrfelton** [comment]
Fixed via #823
