### ISSUE TITLE
Unable to connect to host: Failed to connect before the deadline

### ISSUE THREAD

**Issue by vswee** [LN-Zap/zap-desktop#819]
## Description
Pasting the config file from btcpay into Zap 0.2.2-beta macOS produces the error. 
Needless to say the action is completed within seconds from generating the config at the webpage.

## Expected Behavior
Previous Zap version produced a javascript error at the same point so I've not actually been able to connect it to my server running btcpay.

## Actual Behavior
Should link to the server.

## Possible Fix
Provide a more verbose error mechanism.

## Steps to Reproduce

- 1.Paste config string into Zap after choosing BTCPay
- 2.Click Next

## Your Environment

- Zap Desktop version: 0.2.2-beta (0.2.2-beta.4225)
- Operating System and version: macOS 10.13.6 (17G65)

**Comment by mrfelton** [comment]
@vswee this issue should now be resoled - our btcd node was having some problems following some recent issues on testnet.

**Comment by vswee** [comment]
Root of problem discovered here: https://github.com/btcpayserver/btcpayserver-docker/issues/43#issuecomment-426333415
