### ISSUE TITLE
Application stuck after 100% Blockchain sync

### ISSUE THREAD

**Issue by Tigerix** [LN-Zap/zap-desktop#820]
Even after all block headers have been downloaded and all filters applied the application doesn't start, but keeps the same sync screen instead. 

OS: Windows 10

**Comment by JimmyMow** [comment]
@Tigerix Is this your first time running Zap or did you have a previous release? Also would you be willing to share your logs?

**Comment by Tigerix** [comment]
@JimmyMow 
I had the previous release. Which logs do you mean?
The only logs I can find on my computer are from lnd.

[lnd.log](https://github.com/LN-Zap/zap-desktop/files/2424984/lnd.log)
[lnd.log.1.gz](https://github.com/LN-Zap/zap-desktop/files/2424985/lnd.log.1.gz)

**Comment by mrfelton** [comment]
@Tigerix this log is incomplete, so it's a little hard to use for diagnosing the issue.

It does however look like you may have some partially synced lnd data left over from a previous installation of Zap which could be causing issues.

My suggestion would be to remove your Zap data and start a fresh sync using 0.2.2.

On Windows, the Zap data should be at `%LOCALAPPDATA%\Zap`

**Comment by Tigerix** [comment]
I have removed the Zap folder and reinstalled Zap.
After setting up the wallet Zap shows loading.
lnd.exe doesn't transfer any data according to netlimiter.
[lnd.log](https://github.com/LN-Zap/zap-desktop/files/2429498/lnd.log)

**Comment by mrfelton** [comment]
@Tigerix  this issue should now be resoled - our btcd node was having some problems following some recent issues on testnet.

Please remove your Zap data dir and try again.

**Comment by Tigerix** [comment]
Its working now finally! :-) Thanks!

**Comment by nomadkooz1** [comment]
same problem, and i dont have the 24 recovery words, how can i access my wallet
