### ISSUE TITLE
Wallet stops syncing after 49%

### ISSUE THREAD

**Issue by mattrolightning** [LN-Zap/zap-desktop#825]
Wallet appears to stop syncing at 49%. Sometimes it says "Waiting for Peers" but usually just says 49% and the block # as seen in the screenshot:

![screen shot 2018-09-29 at 12 53 21 pm](https://user-images.githubusercontent.com/43560996/46248391-abfa4480-c3e6-11e8-8e54-967264ab6900.png)

I've uninstalled and reinstalled the app, but still have the same issue.

**Comment by mrfelton** [comment]
@mattrolightning   this issue should now be resoled - our btcd node was having some problems following some recent issues on testnet.

Please remove your Zap data dir and try again.

**Comment by mrfelton** [comment]
I'm going to close this due to a lack of activity. I believe the issue was resolved by us bringing our BTCd nodes back into sync.
