### ISSUE TITLE
Sent amount not equal to user input.

### ISSUE THREAD

**Issue by FontaineDenton** [LN-Zap/zap-desktop#848]
## Description
When sending a transaction to open a channel denominated in USD the amount that sent was much larger then what I actually typed into the UI.

## Expected Behavior

Of course the app should only send transactions that are actually put into the UI. 

## Actual Behavior

I wanted to send $6 worth of Bitcoin but it sent $1,000 worth without asking me to confirm the amount. 

## Possible Fix

It would be better to get a confirmation from user reflecting what is about to be sent.
## Steps to Reproduce

- 1.Create a connection to and try and fund a channel.
- 2.Input amount in USD for funding transaction
- 3.Click send
- 4. 

## Your Environment

- Zap Desktop version: 0.2.2
- Operating System and version: MacOS High Sierra 10.13.6

**Comment by mrfelton** [comment]
I'm going to close this issue as it has been addressed already in the master branch, where we now show a confirmation screen before sending any payments so you get a chance to verify everything prior to sending.
