### ISSUE TITLE
lnd binary is checked into repository

### ISSUE THREAD

**Issue by devrandom** [LN-Zap/zap-desktop#86]
At `resources/bin/darwin/lnd`.

Not good practice.

**Comment by JimmyMow** [comment]
Agreed. Opinion on what we should do?

**Comment by devrandom** [comment]
probably best to just expect it to be in $PATH, and point people to the lnd README

**Comment by Empact** [comment]
This can be closed in light of:
d1f664a10d23ed6ce98f1a1b9307d8e0f34e40be
2383ea8f7a8ff9afe5cd0abf6c1b493cebfe21cf

**Comment by JimmyMow** [comment]
👍 closing
