### ISSUE TITLE
Partially formatted public node key

### ISSUE THREAD

**Issue by archchi** [LN-Zap/zap-desktop#875]
I'm trying to create a channel between my zap desktop wallet and my android eclair wallet, but when I scan the URI, eclair gives me the error message that it's expecting the format "nodeid@host:port"
The QR code only contains the public key.

I'm the using 0.2.2 Linux client.

**Comment by mrfelton** [comment]
@archchi did you manage to get past this issue?

**Comment by ZapUser77** [comment]
From my understanding: you can *not* open a channel to mobile eclair wallets.  
You also can not receive using them either.

From an eclair mobile wallet, it's outgoing only.

**Comment by ZapUser77** [comment]
Oh, I misunderstood the problem.

The ZAP wallet lists the full address, but displays a QR code with only the public key?

**Comment by mrfelton** [comment]
@ZapUser77 Zap will determine wether or not to include to ip address in the QR code based on wether or not the node that you are connecting is broadcasting it's address to the network.

When you use Zap's internal lnd, we do not advertise the node to the network and lnd is unaware of your IP address.

If you connect Zap to your own external lnd node and have configured that node to advertise it's address to the network then Zap will include the node's IP address in the QR code.

See https://github.com/LN-Zap/zap-desktop/pull/737 for a little more context.

**Comment by ZapUser77** [comment]
Sounds like your reply answers the original question: It's a feature, not a bug.  ;)
