### ISSUE TITLE
Ability to set custom expiry time on payment requests

### ISSUE THREAD

**Issue by archchi** [LN-Zap/zap-desktop#876]
## Detailed Description

Make it possible to override the invoice expiry time on a per invoice basis.

## Context

By default, invoices are set to expire after 10 minutes. This doesn't fit all use cases.

## Possible Implementation

- Add Expiry Time section to bottom of the Request form
- Add a dropdown that is populated with preset values (10 minutes, 1 hour, 6 hours, 12 hours etc)
- If set, pass selected value through to lnd when creating the invoice

![image](https://user-images.githubusercontent.com/200251/50822219-6fb57900-1331-11e9-81c4-127d4a0dca13.png)

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/2427
