### ISSUE TITLE
Network list search misaligned

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#877]
The network list search form is misaligned and off:

<img width="283" alt="screen shot 2018-10-31 at 3 17 22 pm" src="https://user-images.githubusercontent.com/4040039/47816120-386a9080-dd20-11e8-857c-5554e70018f7.png">

**Comment by mrfelton** [comment]
@JimmyMow this is fixed in mater already so I'm going to close this.
