### ISSUE TITLE
Testnet string misaligned next to logo

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#878]
The testnet string next to the logo in the top left got misaligned:

<img width="183" alt="screen shot 2018-10-31 at 3 17 24 pm" src="https://user-images.githubusercontent.com/4040039/47816143-4f10e780-dd20-11e8-8e45-4bb9eabb74af.png">

**Comment by mrfelton** [comment]
Looks like this is fixed in mater too @JimmyMow so going to close
<img width="660" alt="screenshot 2018-11-05 22 57 45" src="https://user-images.githubusercontent.com/200251/48029331-3c4a4880-e14e-11e8-9a1f-ee2ff276def2.png">
