### ISSUE TITLE
Missing resources/bin/linux/lnd

### ISSUE THREAD

**Issue by mbarkhau** [LN-Zap/zap-desktop#88]
```
[0] lnd error: Error: spawn /home/user/zap-desktop/resources/bin/linux/lnd ENOENT
[0] lnd shutting down -2
```

It's not that this should be in the repository, but it should be part of the build process right?

**Comment by JimmyMow** [comment]
yes, plan on updating this soon. thanks for creating an issue!

**Comment by JimmyMow** [comment]
@mbarkhau updated the `README` to install `lnd` and put a copy of the `lnd` binary into zap. or you can run `lnd` from the command line and zap will pick it up. 

gonna close this. feel free to reopen if you feel the instructions are good enough

**Comment by mbarkhau** [comment]
It was clear enough yes. Thank you!
