### ISSUE TITLE
Slack link is expired

### ISSUE THREAD

**Issue by PierreRochard** [LN-Zap/zap-desktop#90]
Getting "This invite link is no longer active." from the link in the readme

**Comment by JimmyMow** [comment]
Shoot. The ability to create invite links has disappeared for me 🙁 

For the time being I can invite you via email while I find a better solution. Email you want me to send a link to @PierreRochard?

**Comment by PierreRochard** [comment]
pierre@rochard.org please, thank you @JimmyMow !

**Comment by JimmyMow** [comment]
@PierreRochard sure thing. sent. 

gonna keep this issue open till I figure out a better invitation solution

**Comment by PierreRochard** [comment]
Thank you!

**Comment by funyug** [comment]
There are two links to slack in the readme file. The first one works. The second one under the todo section is expired.

**Comment by JimmyMow** [comment]
Yup. Closing this issue since https://github.com/LN-Zap/zap-desktop/pull/94 is merged
