### ISSUE TITLE
Properly categorise funding and closing transactions in the activity list

### ISSUE THREAD

**Issue by hosiawak** [LN-Zap/zap-desktop#902]
## Description

All my channel closing txs resulted in "Sent 0 BTC" being showin in both "All" and "Sent" tabs. It is confusing because I didn't actually send any BTC to anyone.

## Expected Behavior

Either don't show these transactions at all or show them as "Received on chain"

## Your Environment

- Zap Desktop version: 0.2.2-beta.4225
- Operating System and version: OS X 10.14

**Comment by mrfelton** [comment]
Closed via https://github.com/LN-Zap/zap-desktop/pull/1640
