### ISSUE TITLE
Synch problem

### ISSUE THREAD

**Issue by wdey** [LN-Zap/zap-desktop#903]
ZAP connecting to testnet; problem: synching hangs at 99%
MS Windows 10 Pro
Version 10.0.17134 Build 17134
Zap Desktop 0.2.2 Beta
99%
Block 1.443.563 of 1.443.587
Commitment Filter 1.443.563 of 1.443.587

**Comment by mrfelton** [comment]
@wdey our bitcoin nodes were slightly out of sync but have been update since. Could you verify if this is still a problem please? Thanks.

**Comment by wdey** [comment]
Perfect ! I started from scratch ! Problem solved ! Thanks
