### ISSUE TITLE
ZAP -> LN Desktop not working

### ISSUE THREAD

**Issue by wdey** [LN-Zap/zap-desktop#909]
## Steps to Reproduce

- 1.
- 2.
- 3.
- 4.

## Your Environment

- Zap Desktop version:
- Operating System and version:

**Comment by wdey** [comment]
I have ZAP, LN Desktop and HTLC.me on same Windows 10 Laptop. All versions are up to date.
ZAP <=> HTLC.me working ok
LN Desktop <=> HTLC.me working ok
ZAP => LN Desktop working ok
However, LN =/ > ZAP doesn't work.

ERROR: Lightning payment failed!
lnd: 2018-11-19 10:43:44.045 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters

Is this a known feature ?

**Comment by JimmyMow** [comment]
@wdey when you say LN Desktop do you mean the Lightning App? Also the error log you posted above is irrelevant. I assume the route failed because of capacity issues would be my guess. More logs would be helpful

**Comment by wdey** [comment]
Yes, you are of course right: LN App ! After a upgrade of LN App, everything is now working ! Thanks
