### ISSUE TITLE
Scrollable activity list is visible in pay form

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#910]
## Description
When clicking a `lightning:` link online, it opens my Zap app and the pay form contains the scrollable sidebar from the activity list
## Expected Behavior
There should be no visible sidebar on the payform

## Actual Behavior
The sidebar is visible on the payform

## Steps to Reproduce
Click `lightning:` link

<img width="1020" alt="screen shot 2018-11-20 at 7 47 07 pm" src="https://user-images.githubusercontent.com/4040039/48814274-d211d600-ecff-11e8-8a54-15f5b51dad14.png">

**Comment by mrfelton** [comment]
@JimmyMow I can't seem to reproduce this. I open up my wallet which has lots of network connections and a scroll bar in the network list.

Then I try opening a `lightning:` link from my browser, eg:

`lightning: lnbc3450n1pdl69vvpp5kvn7wyekf58w7y0clpwze6e0cumzadv2h345xsjz0582xcpysv6qdzz2pshjmt9de6zqen0wgsrxdp4ypcxj7r9d3ejqct5ypekzar0wd5xjuewwpkxzcm99cxqzjccqp2xddghhvkmwv926xrujtfa3zdkndwrdv7k6jmwwaaauqtw88uycd34fhu57y0859dn04nmp7vxtqxzt5ryczk9w4ry9f0ztxge6t9g3qp45sfxh`

And it switches back to Zap and opens the invoice. I don't see scroll bars like in your screenshot.

Can you provide some more detailed steps to reproduce? Or upload a video or something? Thanks.

**Comment by mrfelton** [comment]
Is this still an issue for you @JimmyMow ?

**Comment by mrfelton** [comment]
This was fixed via #1044
