### ISSUE TITLE
Activity list only shows up to 100 invoices (no pagination) 

### ISSUE THREAD

**Issue by bumi** [LN-Zap/zap-desktop#911]
If a node has more than 100 invoices only the first/oldest 100 invoices are shown. New invoices will not be get listed.

## Description

By default the [listInvoices](https://api.lightning.community/#listinvoices) gRPC call to lnd returns 100 invoices. If the node has more than 100 invoices those seem to miss in the invoices/activity list. 

## Expected Behavior

All invoices are visible in the list with the newest first.

## Actual Behavior

The latest invoices are missing.  
Only the first/oldest 100 invoices seem to be visible.

## Possible Fix

We should either increase this limit by providing a `num_max_invoice` parameter when [calling ListInvoices](https://github.com/LN-Zap/zap-desktop/blob/master/app/lib/lnd/methods/invoicesController.js#L29) 

or introduce pagination for the invoices. 

## Steps to Reproduce

- make sure your node has more than 100 invoices
- create a new invoice (through the app or through the lncli)
- invoice will not be visible in the list

## Your Environment

- Zap Desktop version: master
- Operating System and version: Arch Linux 4.18.6-arch1-1-ARCH
- node version: v10.10.0
- lnd versin: 0.5.0-beta commit=v0.5-beta-141-g6b19df162a161079ab794162b45e8f4c7bb8beec

**Comment by seanyesmunt** [comment]
Maybe this is a bug with lightning? The docs say it should return the latest invoices 
https://api.lightning.community/#listinvoices
> ... If none of the parameters are
> # specified, then the last 100 invoices will be returned.
> # For example: if you have 200 invoices, "lncli listinvoices" will return
> # the last 100 created. If you wish to retrieve the previous 100, the
> # first_offset_index of the response can be used as the index_offset of
> # the next listinvoices request.
