### ISSUE TITLE
0 shown at the bottom of the network view, not suggested nodes

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#943]
After syncing a fresh new wallet there is a 0 string at the bottom of the network view instead of the suggested nodes list.

## Expected Behavior

No `0` shown, instead suggested nodes are shown

## Steps to Reproduce

- 1. Sync new wallet
- 2. Check network tab

## Your Environment

Next branch

**Comment by mrfelton** [comment]
@JimmyMow this issue exists in master too. Retagging.
