### ISSUE TITLE
Integrate Travis

### ISSUE THREAD

**Issue by JimmyMow** [LN-Zap/zap-desktop#95]
https://github.com/LN-Zap/zap-desktop/pull/85#issuecomment-350393176

@torkelrogstad here is the issue to set up continuous integration for the project

**Comment by JimmyMow** [comment]
@torkelrogstad

**Comment by torkelrogstad** [comment]
Nice
@JimmyMow I see that there's already a `.travis.yml` file in the repo. That's the file Travis uses for config purposes. Was Travis set up for this project previously?

**Comment by JimmyMow** [comment]
I didn't personally, I assume it came with the boilerplate I used @torkelrogstad

**Comment by auldsyababua** [comment]
I can try to take a stab at this next week if wanted. How do I get in on the slack channel?

**Comment by JimmyMow** [comment]
@auldsyababua slack link should be in the README

**Comment by NahomAgidew** [comment]
@JimmyMow Since there's already the config file, you just go to https://travis-ci.org/ and enable Travis for the project.

**Comment by Empact** [comment]
First ever CI-checked PR 🤘 https://github.com/LN-Zap/zap-desktop/pull/140

**Comment by JimmyMow** [comment]
Ayyyyy. Just don't wanna close this cause it took Travis 20 minutes to clear lol. Must be doing something wrong

**Comment by Empact** [comment]
@JimmyMow propose we close this and improve the CI over time

**Comment by JimmyMow** [comment]
@Empact agree. closing
