### ISSUE TITLE
Migrate from the `grpc` package to `@grpc/grpc-js`.

### ISSUE THREAD

**Issue by nicolasnoble** [LN-Zap/zap-desktop#951]
## Detailed Description
The grpc package contains native code, and causes grief and difficulty of usage for the end user. Switching to the @grpc/grpc-js package, a pure javascript implementation, would simplify greatly the installation story for the end users. See #760 for instance, but also a few more issues that got created here in the past.

## Context
Since electron 3, it became possible to use the pure javascript version of grpc, since the necessary http2 module became available there. Also, a quick glance shows that zap-desktop doesn't use any feature that's currently not implemented in this version.

See https://github.com/grpc/grpc-node/blob/master/PACKAGE-COMPARISON.md for more details.

## Possible Implementation
Remove the dependency from `grpc` to `@grpc/grpc-js`, and change the import to `'@grpc/grpc-js'`. Nothing else should have to change.

**Comment by mrfelton** [comment]
Thanks for creating this @nicolasnoble .

There is just one issue that is preventing us from being able to merge a PR that makers these changes - See https://github.com/grpc/grpc-node/pull/665
